### PR TITLE
Truncate long package names

### LINKED ISSUE #6436: Long name files break layout
image

### PR DESCRIPTION
**Pull request by bgeuken**
Shorten long package names.

Fixes #6436

Before:
screenshot_2019-03-06 show home admin aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

After
screenshot_2019-03-06 file bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb of package aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
screenshot_2019-03-06 show home admin aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa - open build service
screenshot_2019-03-06 show home admin aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa - open build service 1
screenshot_2019-03-06 upload file to aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### CODE REVIEW

**Comment by bgeuken** [comment]
Why would you want to show the full filename in the browser title and breadcrumb when the file name is excessively long?

**Comment by dmarcoux** [comment]
The class is [text-word-break-all](https://github.com/openSUSE/open-build-service/blob/d032a712d834b0124f7b541fe8aebca84fdae72a/src/api/app/assets/stylesheets/webui2/texts.scss#L17-L19)

**Comment by dmarcoux** [comment]
Updates for this?

**Comment by bgeuken** [comment]
> Because it might be excessively long for a reason? It might be beside another excessively-long-for-a-reason package. Etc.

We already show the name of the package, project, ... in the title field of the card. For the breadcrumbs I don't really see a point to show the full text if it's excessive. It's just noise. But I changed it now.

I left the truncation of the title shown in the browser since a word break wouldn't work there anyway.

**Comment by dmarcoux** [comment]
I would also prefer to truncate.

**Comment by bgeuken** [comment]
So we show full package / file / ... name in the title of the overview card and truncate them in the breadcrumbs? Is that fine with everyone?
It might still look ugly for very long names, but it's an edge case anyway.

**Comment by dmarcoux** [comment]
@bgeuken Fine for me.

**Comment by bgeuken** [comment]
Well, I wish they had never allowed such a long string for object names ><

**Comment by hennevogel** [comment]
> Well, I wish they had never allowed such a long string for object names

Well even seemingly  normal strings like `openSUSE:infrastructure:hackweek` overflow in some parts. I don't think you can avoid this.

screenshot from 2019-03-06 14-48-30

**Comment by bgeuken** [comment]
I know. I am not saying that we have this problem in general. But we would not have these extreme cases like seen in my screenshots.

**Pull request merged**
