### PR TITLE
Use custom forms with package/show in webui2

### PR DESCRIPTION
**Pull request by hellcp**
They look nicer on more devices, blend better with current theme (and with any theme in the future).

### CODE REVIEW

**Comment by dmarcoux** [comment]
There seems to be some issue with the changes. The checkbox is weird, here's an example:

pr

**Comment by DavidKang** [comment]
@hellcp, thanks for your contribution :smile_cat:

**Comment by hellcp** [comment]
@dmarcoux whoops, one class is incorrectly assigned

**Comment by DavidKang** [comment]
screenshot_2018-09-14 show home admin perl-citrix - open build service

:heart:

**Comment by DavidKang** [comment]
@hellcp , looks very good, thanks :smile_cat: 

screenshot_2018-09-14 show home admin perl-citrix - open build service 1

**Comment by dmarcoux** [comment]
Please, squash the commits. It's all good to go then :+1:

**Comment by DavidKang** [comment]
@dmarcoux, right!

**Comment by dmarcoux** [comment]
We don't use labels anymore in the commit messages. It's not a big deal though.

**Comment by mdeniz** [comment]
Can you rebase on master to get rid of the flickering test that are failing?

BTW, nice job @hellcp :+1:

**Comment by hellcp** [comment]
@mdeniz tests hate me :P

**Comment by mdeniz** [comment]
Don't worry too much @hellcp we are having some flickering tests that happen when some animation runs and capybara tries to click on a moving element... @DavidKang is trying to fix it in another PR. Whenever is done I will ping you back to rebase again and retry :+1:

**Comment by hellcp** [comment]
@bgeuken if you could, thanks

**Comment by bgeuken** [comment]
@hellcp merged:tada:
I also added an entry to [our pattern library](https://obs-patterns.netlify.com/): https://github.com/openSUSE/obs-patterns/pull/22

If you have any feedback regarding the pattern library or components we use, please let us know. This would be more than welcome:smile:

**Pull request merged**
