### PR TITLE
Migrate Subprojects to Bootstrap

### PR DESCRIPTION
**Pull request by ChrisBr**
subprojects-2

subprojects-1

subprojects-modal

### CODE REVIEW

**Comment by ChrisBr** [comment]
[Subprojects](https://trello.com/c/KmRfcZwj/971-subprojects)

**Comment by dmarcoux** [comment]
@openSUSE/obs-frontend Please have a look

**Comment by ChrisBr** [comment]
@dmarcoux & @vpereira thanks for finishing, this LGTM. Unfortunately I can not approve because I created the PR but you have my formal approval :+1:

**Comment by dmarcoux** [comment]
@vpereira and I are not so happy with the form, especially the part where we check the namespace, but this will have to be changed in another PR, possibly when we tackle the project index page (the form is also used in that context)

**Comment by dmarcoux** [comment]
I'm fixing the specs

**Comment by vpereira** [comment]
> @vpereira and I are not so happy with the form, especially the part where we check the namespace, but this will have to be changed in another PR, possibly when we tackle the project index page (the form is also used in that context)

the whole ```subprojects.html.haml```, should be reworked, the actions extracted from the ```ProjectController``` to brand new CRUD controllers.. I'm afraid we are trying to fit everything in a single sprint and compromising the code quality.. something to be discussed tomorrow in our retrospective :/

**Comment by vpereira** [comment]
> @vpereira and I are not so happy with the form, especially the part where we check the namespace, but this will have to be changed in another PR, possibly when we tackle the project index page (the form is also used in that context)

the whole ```subprojects.html.haml```, should be reworked, the actions extracted from the ```ProjectController``` to brand new CRUD controllers.. I'm afraid we are trying to fit everything in a single sprint and compromising the code quality.. something to be discussed tomorrow in our retrospective :/

**Comment by vpereira** [comment]
> @vpereira and I are not so happy with the form, especially the part where we check the namespace, but this will have to be changed in another PR, possibly when we tackle the project index page (the form is also used in that context)

the whole ```subprojects.html.haml```, should be reworked, the actions extracted from the ```ProjectController``` to brand new CRUD controllers.. I'm afraid we are trying to fit everything in a single sprint and compromising the code quality.. something to be discussed tomorrow in our retrospective :/

**Comment by dmarcoux** [comment]
Removed some duplicated comments (probably due to issues from GitHub right now)

**Comment by dmarcoux** [comment]
coveralls is catching up... probably in some hours or tomorrow, so merging now

**Pull request merged**
