### PR TITLE
[ci] Enable Style/UnneededInterpolation rubocop cop

### PR DESCRIPTION
**Pull request by DavidKang**

### CODE REVIEW

**Comment by marcus-h** [comment]
Hmm some of these new .to_s calls can be omitted:

- src/api/app/mixins/build_log_support.rb
- src/api/app/models/branch_package.rb
- src/api/test/functional/branch_publish_flag_test.rb
- "def cleanup_empty_projects_helper" in
  src/api/test/functional/request_controller_test.rb

(this list is probably incomplete/I haven't checked the others...)

**Comment by DavidKang** [comment]
right 😞

**Comment by eduardoj** [comment]
Please merge this pull request after #2884 got merged.

**Comment by Ana06** [comment]
please rebase!

**Comment by DavidKang** [comment]
I'm working on it

**Pull request merged**
