### PR TITLE
[dist] Add OBS Worker for Systemd

### PR DESCRIPTION
**Pull request by leemgs**
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
* after this PR:

```
root@mytizen:~# systemctl start obsworker@1.service
root@mytizen:~# systemctl status obsworker@1.service
● obsworker@1.service - OBS worker for 1
   Loaded: loaded (/lib/systemd/system/obsworker@.service; disabled; vendor preset: enabled)
   Active: active (running) since 화 2017-04-18 19:32:50 KST; 4s ago
  Process: 9683 ExecStartPre=/bin/chmod 755 /var/cache/build/state_%i (code=exited, status=0/SUCCESS)
  Process: 9680 ExecStartPre=/bin/chmod 755 /var/cache/build/root_%i (code=exited, status=0/SUCCESS)
  Process: 9676 ExecStartPre=/bin/mkdir -p /var/cache/build/state_%i (code=exited, status=0/SUCCESS)
  Process: 9673 ExecStartPre=/bin/mkdir -p /var/cache/build/root_%i (code=exited, status=0/SUCCESS)
 Main PID: 9686 (bs_worker)
   CGroup: /system.slice/system-obsworker.slice/obsworker@1.service
           └─9686 /usr/bin/perl -w /usr/lib/obs/server/bs_worker --hardstatus --root /var/cache/build/root_1 --statedir /var/cache/build/state_1 --id --reposerver http://10.113.62.177:5252 --jobs &

 4월 18 19:32:50 mytizen systemd[1]: Starting OBS worker for 1...
 4월 18 19:32:50 mytizen systemd[1]: Started OBS worker for 1.
 4월 18 19:32:50 mytizen bs_worker[9686]: Name "Build::Kiwi::urlmapper" used only once: possible typo at /usr/lib/obs/server/bs_worker line 2491.
 4월 18 19:32:50 mytizen bs_worker[9686]: starting worker 1983bacee23e8b3312c2c4d859ffe3f3 build 3b2de27b58e7fc943bc20a25fc75f99b
root@mytizen:~# 
root@mytizen:~# 

```

**Comment by leemgs** [comment]
This PR is to fix https://github.com/openSUSE/open-build-service/issues/2997.

**Comment by bgeuken** [comment]
LGTM from what I can say. @openSUSE/open-build-service guys?

**Comment by lethliel** [comment]
Yes. LGTM too. 👍

**Pull request merged**
