### PR TITLE
[ci] Remove codeclimate testcoverage reporter

### PR DESCRIPTION
**Pull request by ChrisBr**
turned out to be also not reliable.

@bgeuken feel free to merge when you enabled codecov again.

### CODE REVIEW

**Comment by coolo** [comment]
perhaps you remove it from required earlier this time? :)

**Comment by ChrisBr** [comment]
> perhaps you remove it from required earlier this time? :)

Hm, yeah! I will remove it when codecov is in place or we merged this PR. Or should we already disable it as it is anyway not really reliable? cc @hennevogel @bgeuken

**Comment by ChrisBr** [comment]
(review app label is for testing the review app :smile:)

**Comment by bgeuken** [comment]
I don't see the point of removing it now when we just agreed to re-add codecov.

**Comment by ChrisBr** [comment]
> I don't see the point of removing it now when we just agreed to re-add codecov.

Removing what? From circle ci or from the protected branches?

**Comment by bgeuken** [comment]
Nevermind, I thought there are some dependencies between the coverage setups.

**Comment by hennevogel** [comment]
So what now? Are we measuring coverage with codeclimate of with codecov? :-)

**Pull request merged**
