### PR TITLE
2.6

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by ChrisBr** [comment]
Tested it on my local machine. The action for the user_icon was wrong. But I really wonder why this worked before because the only change I did in my previous commit was:
https://github.com/ChrisBr/open-build-service/commit/0efcc1dd5a15c36de0e001e9cfd32d06a2cae45a

So the action was already wrong before and the tests should have failed before! Any idea @adrianschroeter ?

**Comment by hennevogel** [comment]
Why do you need to include f84d7eed25e360c39c6854731a12d2448b9c0e3b?

**Comment by ChrisBr** [comment]
Otherwise 
``src/api/test/unit/webui/webui_helper_test.rb#test_format_projectname`` fails

Still wondering why 2.6.6 worked ...

**Comment by ChrisBr** [comment]
Now handled in  #1333

**Pull request closed without merging**
