### PR TITLE
Handle Stage Request manually accepted

### PR DESCRIPTION
**Pull request by DavidKang**

### CODE REVIEW

**Comment by vpereira** [comment]
@coolo Any idea if we should do something similar for other final states, like revoked?

**Comment by coolo** [comment]
And about your question: revoked requests *usually* get a request superseding it, so we keep them in the staging project for a while - the staging project will be unacceptable in this case.

**Comment by vpereira** [comment]
> So this is the opposite of the agreement in #7376, right?

hey @coolo ,

Reading through the comments, the only agreed thing was that it should be handled. Otherwise there was some discussion going on where none of the developers were involved, right? We will revisit what was proposed there, but in the meantime, any disadvantage on this PR approach?

**Comment by coolo** [comment]
You implemented *the other* option from https://github.com/openSUSE/open-build-service/issues/7376#issuecomment-559467756 - it's not so bad, but the downside is that you unselect without doing all the actions that the client would do on unselect.

**Comment by vpereira** [comment]
From the linked issue, I read the following:

```
Well, the options are:

auto-unselecting on accept
require manual unselect to make it force acceptable
Basically: we require force accept on backlog and on normal accept on ready - but we don't require force accept on staged requests, because you can always put them back into the backlog first. And it's the smaller mess IMO
```

which we understood as "auto-unselecting" was actually the first option and the less intrusive. 

> You implemented _the other_ option from [#7376 (comment)](https://github.com/openSUSE/open-build-service/issues/7376#issuecomment-559467756) - it's not so bad, but the downside is that you unselect without doing all the actions that the client would do on unselect.

Any other action from the client that comes to your mind that we should implement here?

**Comment by coolo** [comment]
atm this is mainly limited to removing adi projects if they become empty. I don't think that should be done on the API level. And it's optional. 

But you don't know what will happen in the future, that's why I proposed to block accepting (in 2 comments before the one you quoted). The options were only listed to show Dimstar what the alternative is.

**Pull request merged**
