### PR TITLE
 Replace bento views by bootstrap views for groups

### PR DESCRIPTION
**Pull request by DavidKang**

### CODE REVIEW

**Comment by dmarcoux** [comment]
Some specs are failing due to a wrong path.

**Comment by DavidKang** [comment]
@dmarcoux, could you review it again? please :smile_cat:

**Comment by dmarcoux** [comment]
I have 2 questions:

- The shared views under `src/api/app/views/webui2/shared/user_or_groups_roles` are going to be moved when we move the users controller?
- It's not possible to delete a group? Try it here: https://obs-reviewlab.opensuse.org/davidkang-bootstrapmerge-groups/groups

Everything else looks good.

**Comment by DavidKang** [comment]
> The shared views under src/api/app/views/webui2/shared/user_or_groups_roles are going to be moved when we move the users controller?

These views are already moved to `/webui/shared`. We have a card for remove the `webui2/webui/shared` directory when we finish to move all the controllers and views.

> It's not possible to delete a group? Try it here: https://obs-reviewlab.opensuse.org/davidkang-bootstrapmerge-groups/groups

I looked in the bento UI, and at least via webui we can't delete or change the name of the group.

**Pull request merged**
