### PR TITLE
[dist] Add a simple DJ queue stat script

### PR DESCRIPTION
**Pull request by hennevogel**
```
$ rails runner script/delayed_job_stats.rb
-------------DJ-STATS-------------
There are currently 606 jobs in the queues
-----------Jobs by type-----------
CleanupNotifications           3
EventNotifyBackendJob          198
IssueTrackerUpdateIssuesJob    4
PackageUpdateIfDirtyJob        219
ProjectLogRotateJob            1
StatusHistoryRescalerJob       2
UpdatePackagesIfDirtyJob       3
-----------Jobs by queue----------
quick                          3
issuetracking                  4
default                        598
project_log_rotate             1

### CODE REVIEW

**Comment by hennevogel** [comment]
Before you ask. I was having problems with `ApplicationJob.subclasses` when doing this as rake task. I guess eager loading of the environment or what not...

**Comment by evanrolfe** [comment]
Some rubocop errors, otherwise LGTM

**Comment by hennevogel** [comment]
@evanrolfe can you give it a pass then? :-)

**Comment by hennevogel** [comment]
@evanrolfe?

**Pull request merged**
