### PR TITLE
Introduces User.mark_as_spammer!

### PR DESCRIPTION
**Pull request by hennevogel**
Just a little helper method to deal with spam accounts.

1. Enable admin rights for your user with
  ```
   run_in_api rake user:toggle_admin_rights YOUR_LOGIN
  ```
2. Delete the account in the rails console
  ```
  User.find_by(login: 'YOUR_LOGIN').run_as { User.find_by(login: 'SPAMMER_LOGIN').mark_as_spammer! }
  ```
3. Remove admin rights for your user again with
  ```
  run_in_api rake user:toggle_admin_rights YOUR_LOGIN
  ```

### CODE REVIEW

**Comment by danidoni** [comment]
Why not using a rake task wrapped with the `user:toggle_admin_rights` instead of a method? That way you don't have to spawn the rails console, just run a task.

**Comment by hennevogel** [comment]
> That way you don't have to spawn the rails console, just run a task.

Does that matter?

**Comment by danidoni** [comment]
> Does that matter?

I think so. Now you need to remember this syntax `User.find_by(login: 'YOUR_LOGIN').run_as { User.find_by(login: 'SPAMMER_LOGIN').mark_as_spammer! }`. And remember to have admin right before and release them after. With a task you don't need to remember to acquire and release the right nor the syntax. You need to remember only the name of the task, and if you don't, you have `rake -T`.

**Comment by hennevogel** [comment]
> With a task you don't need to remember to acquire and release the right nor the syntax

You will have to remember the syntax of the task as it would require *two* arguments...

**Review by danidoni — APPROVED** [review]

**Pull request merged**
