### PR TITLE
Rubocop 0.57.1

### PR DESCRIPTION
**Pull request by Ana06**

### CODE REVIEW

**Comment by Ana06** [comment]
@openSUSE/open-build-service as already said in https://github.com/openSUSE/open-build-service/pull/5097 and https://github.com/openSUSE/open-build-service/pull/5103, any concerns? :smile:

**Comment by DavidKang** [comment]
@Ana06, LGTM

**Comment by hennevogel** [comment]
@Ana06  you have to package the dependency before merging

**Comment by Ana06** [comment]
@hennevogel 

> @Ana06 you have to package the dependency before merging

didn't the bot already did it?

https://github.com/openSUSE/open-build-service/pull/5097#issuecomment-395337938

**Comment by ChrisBr** [comment]
> wait... did he package the wrong version? confused

The factory auto bot updates all gems as soon as they are released (running every hour). The depfu bot comments on all depfu pull requests (branch starting with ``depfu``). So the packages should be up to date but you need to double check! To avoid that in the future, I recommend to not close the depfu PR (to keep the comments) and push directly to this branch!

**Comment by Ana06** [comment]
@ChrisBr 

> I recommend to not close the depfu PR (to keep the comments) and push directly to this branch!

And how do I do this? :thinking:

**Comment by ChrisBr** [comment]
```
There is no submit request for jaro_winkler (1.5.1). If you recently accepted a submit request, the repository is probably not yet published!
Package rubocop is already up to date in d:l:r:e (0.57.1), update link reference with osc setlinkrev OBS:Server:Unstable rubygem-rubocop.
```

c&p from the other PR

jaro_winkler is not updated because it is a new package. factory auto bot only updates packages but does not create new ones!

**Comment by ChrisBr** [comment]
@Ana06 check out the branch locally, e.g. ```depfu/update/srcapi/rubocop-rspec-1.26.0``` (it is in the opensuse/open-build-service repository). Change it locally and push it back into opensuse/open-build-service  (you should have permissions).

BTW: If you open a new PR, there is now also by default checked that maintainer can change the PR. So you can basically push into every pull request, you just need to check it out locally and push back into the fork :smile:

**Comment by Ana06** [comment]
https://github.com/openSUSE/open-build-service/pull/5098 also updated rubocop, I added my changes there. Closing...

**Pull request closed without merging**
