### PR TITLE
Replace sass-rails with sassc-rails

### PR DESCRIPTION
**Pull request by coolo**
ruby sass is dead, partly fixing #6263

### CODE REVIEW

**Comment by dmarcoux** [comment]
Just to be extra safe, I'll put the review app label. Just in case

**Comment by coolo** [comment]
@ChrisBr good thing we implemented the OBS Package Build check, no? :)

**Comment by ChrisBr** [comment]
> good thing we implemented the OBS Package Build check, no? :)

it was not the first time good :+1:

**Comment by ChrisBr** [comment]
Means we need to require libsass?

**Comment by ChrisBr** [comment]
But still wondering that the review app works and does not crash :thinking:

**Comment by coolo** [comment]
the review is pretty much independent of the test suite IMO, so dismissing it isn't necessary

**Comment by coolo** [comment]
I filed an issue upstream and added a workaround

**Comment by coolo** [comment]
looks like it's working

**Comment by ChrisBr** [comment]
> looks like it's working

Thanks for taking care. But could you please add some more details 7988e41e7d9131ea63de38414f0053aecd87249b and maybe even link to the issue. Thanks :heart:

**Comment by coolo** [comment]
you mean URL within the spec file?

**Comment by ChrisBr** [comment]
> you mean URL within the spec file?

No, in your commit message :smile:

**Comment by coolo** [comment]
I know - but I dislike how github spams the other issue then, so I wanted to avoid that. :)

**Comment by ChrisBr** [comment]
> I know - but I dislike how github spams the other issue then, so I wanted to avoid that. :)

But then at least add a description and write the repository to look for in the commit message :thinking:

**Comment by ChrisBr** [comment]
LGTM, thanks @coolo

**Pull request merged**
