### PR TITLE
[api] fix editing of issue tracker entries

### PR DESCRIPTION
**Pull request by adrianschroeter**
eg. via

` # osc api -e /issue_trackers/$tracker
`
we need to backport in case 2.10 is also affected.

Also all other places in test suite where "put ...., params: $body_data"
is used needs to be checked if we broke the api there as well.
needs to become raw_put again...

### CODE REVIEW

**Comment by hennevogel** [comment]
Maybe you can explain what the problem actually is that you are fixing?

**Comment by adrianschroeter** [comment]
that it isn't working basically and all changes get ignored when use as described in the api. Just run the adapted test suite without the fix to see that (sending it as www encoded params was never intended in the api).

**Comment by hennevogel** [comment]
So you do want to get rid of the (partial) json API?

**Comment by hennevogel** [comment]
How about this?

**Comment by hennevogel** [comment]
@vpereira please have another look

**Comment by hennevogel** [comment]
@adrianschroeter this changes the API now, see the included chunk for `api.txt`. I think it makes sense, are you okay with that?

**Comment by adrianschroeter** [comment]
@hennevogel seems you forgot to commit the chunk for api.txt?

If it is just about the drop of .json, I am fine with it (it seems to not usable anyway so far at least for writing).

**Comment by hennevogel** [comment]
Indeed I have. pushed now

**Pull request merged**
