### PR TITLE
WIP: [frontend] fixed source_controller#show_project

### PR DESCRIPTION
**Pull request by vpereira**
I fixed some broken routes, which lead me to the question if it was dead code or was just broken

the routes:

https://build.opensuse.org/source/openSUSE:Factory?view=verboseproductlist
https://build.opensuse.org/source/openSUSE:Factory?view=issues
https://build.opensuse.org/source/openSUSE:Factory?view=productlist

are broken. In this commit I fix them. If they are necessary, I would like to get some ideas how to test it. the line ```it { expect(Xmlhash.parse(response.body)['count']).to eq(project.packages.count) }``` should work however it didn't, and to test all conditions I have to initialize better the objects, i.e Product and make sure that a Project has packages and etc.

So my first question:

is it dead code and can be deleted or should it be fixed?

### CODE REVIEW

**Comment by adrianschroeter** [comment]
they are definitive not dead, but critical in our real life setup. You mixed the webui host name with api routes, but I think this is just mistake in the example.

They are tested in the product_test.rb with some example data.

**Comment by adrianschroeter** [comment]
it would be important to test with opensuse and sle sp style product setups in case you want to re-do the test.

**Comment by vpereira** [comment]
Hi @adrianschroeter ok, I see, I'm able to access them via ```osc api '/source/openSUSE:Factory?view=verboseproductlist'``` , etc, even though it doesn't looks like right to get errors 500 while accessing this endpoint via "webui", maybe a 404 would be more appropriate?

**Comment by adrianschroeter** [comment]
On Montag, 21. Mai 2018, 22:55:01 CEST wrote Victor Pereira:
> Hi @adrianschroeter ok, I see, I'm able to access them via ```osc api '/source/openSUSE:Factory?view=verboseproductlist'``` , etc, even though it doesn't looks like right to get errors 500 while accessing this endpoint via "webui", maybe a 404 would be more appropriate? 

yes, 500 is not good. IMHO it should be 400 since the project object exists, but the view does not.
However, the exact error code is not so important in webui.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by vpereira** [comment]
i will close it for now

**Pull request closed without merging**
