### PR TITLE
Convert ERB templates to HAML for Configuration and Groups

### PR DESCRIPTION
**Pull request by mdeniz**
This was done automatically with https://rubygems.org/gems/html2haml (see https://github.com/haml/html2haml for how to). Some issues were fixed by hand.

### CODE REVIEW

**Comment by bgeuken** [comment]
There is a small difference in the Haml version:

html
before

haml
after

Rest LGTM

**Comment by mdeniz** [comment]
How can be? I mean, the HAML didn't change the content of the textarea... So strange!
😱

**Comment by bgeuken** [comment]
No idea. Maybe I didn't do a ctrl-R ... but I tried it in both directions 😕

**Comment by mdeniz** [comment]
@openSUSE/open-build-service can you have a look at this? beside @bgeuken's comment...

**Comment by bgeuken** [comment]
@mdeniz not sure what you mean, because the rest is fine for me as well... Did you checkout the ui on your machine? Does it happen there as well? If not maybe it's not such a big deal

**Comment by mdeniz** [comment]
Just wanted to know if other people have other issues beside that...

I see the same with master... so looks like this is not related to HAML

**Comment by eduardoj** [comment]
I only notice a little difference: the spaces in the first line of the content of the text area are gone:

Before:

screenshot from 2017-02-16 17-02-07

After the proposed changes:

screenshot from 2017-02-16 17-02-31

For me the changes are fine.

**Comment by mdeniz** [comment]
@bgeuken, @eduardoj looks like is a HAML bug (https://github.com/haml/haml/issues/643#issuecomment-256283660). So I added the fix inside an initializer.

Thanks @DavidKang for pointing me to the solution.

**Pull request merged**
