### PR TITLE
Verify that the files we try to link to exist

### LINKED ISSUE #15834: [production][request#request_action] No route matches {:action=>"show", :controller=>"webui/packages/files", :expand=>1, :filename=>"q...
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/65f96aa984bf4608f8818c59)
# No route matches {:action=&gt;&quot;show&quot;, :controller=&gt;&quot;webui/packages/files&quot;, :expand=&gt;1, :filename=&gt;&quot;qtwebchannel-everywhere-src-6.6.2.tar.xz/.QT-ENTERPRISE-LICENSE-AGREEMENT&quot;, :format=&gt;&quot;html&quot;, :id=&gt;&quot;3123440&quot;, :number=&gt;&quot;1157849&quot;, :package=&gt;&quot;qt6-webchannel&quot;, :package_name=&gt;&quot;qt6-webchannel&quot;, :project=&gt;&quot;KDE:Qt6&quot;, :project_name=&gt;&quot;KDE:Qt6&quot;, :rev=&gt;&quot;36e1aa971aabd612cf971d9ed98ebcc1&quot;}, possible unmatched constraints: [:filename]
Did you mean?  project_package_file_url
               project_package_files_url #
### URL ###
[https://build.opensuse.org/request/1157849/request_action/3123440?index=0](https://build.opensuse.org/request/1157849/request_action/3123440?index=0)"
### Where ###
request#request_action

### Occured ###
Mar 19 10:36am

### Similar ###
4

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;request_action&quot;,
  &quot;controller&quot; =&gt; &quot;webui/request&quot;,
  &quot;id&quot; =&gt; &quot;3123440&quot;,
  &quot;index&quot; =&gt; &quot;0&quot;,
  &quot;number&quot; =&gt; &quot;1157849&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;zNOzNJoaQqlktNi_xiqQXO1mNdQrOG5hPcY6d2VeXbc&quot;,
  &quot;session_id&quot; =&gt; &quot;8c23d104ffaefac8b69c32174cf36e0d&quot;
}
~~~

## Backtrace ##
~~~
44:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/journey/formatter.rb -> **path**
824:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb -> **url_for**
271:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb -> **call**
327:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb -> **block in define_url_helper**
24:  app/components/sourcediff_tab_component.rb -> **file_view_path**
37:  app/components/sourcediff_tab_component.html.haml -> **block (2 levels) in call**
35:  app/components/sourcediff_tab_component.html.haml -> **each**
35:  app/components/sourcediff_tab_component.html.haml -> **each_with_index**
35:  app/components/sourcediff_tab_component.html.haml -> **block in call**
17:  app/components/sourcediff_tab_component.html.haml -> **each**
17:  app/components/sourcediff_tab_component.html.haml -> **call**
126:  /GEM_ROOT/gems/view_component-3.11.0/lib/view_component/compiler.rb -> **render_template_for**
334:  /GEM_ROOT/gems/view_component-3.11.0/lib/view_component/base.rb -> **safe_render_template_for**
109:  /GEM_ROOT/gems/view_component-3.11.0/lib/view_component/base.rb -> **render_in**
42:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/helpers/rendering_helper.rb -> **render**
1:  app/views/webui/request/request_action.js.erb -> **_app_views_webui_request_request_action_js_erb__2834133764405812259_114960**
244:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/base.rb -> **public_send**
244:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/base.rb -> **_run**
157:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/template.rb -> **block in render**
208:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/notifications.rb -> **instrument**
361:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/template.rb -> **instrument_render_template**
155:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/template.rb -> **render**
65:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
206:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/notifications.rb -> **instrument**
60:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
79:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
59:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/rendering.rb -> **block in _render_template**
270:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/rendering.rb -> **_render_template**
216:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/rendering.rb -> **render_to_body**
158:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/rendering.rb -> **render_to_body**
141:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/renderers.rb -> **render_to_body**
27:  /GEM_ROOT/gems/actionpack-7.0.8/lib/abstract_controller/rendering.rb -> **render**
139:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/rendering.rb -> **render**
22:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/core_ext/benchmark.rb -> **ms**
22:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb -> **block in render**
91:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-7.0.8/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
21:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb -> **render**
35:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/implicit_render.rb -> **default_render**
7:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
215:  /GEM_ROOT/gems/actionpack-7.0.8/lib/abstract_controller/base.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/rendering.rb -> **process_action**
234:  /GEM_ROOT/gems/actionpack-7.0.8/lib/abstract_controller/callbacks.rb -> **block in process_action**
107:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/callbacks.rb -> **run_callbacks**
233:  /GEM_ROOT/gems/actionpack-7.0.8/lib/abstract_controller/callbacks.rb -> **process_action**
23:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/rescue.rb -> **process_action**
67:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
206:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/notifications.rb -> **instrument**
66:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/instrumentation.rb -> **process_action**
259:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-7.0.8/lib/active_record/railties/controller_runtime.rb -> **process_action**
151:  /GEM_ROOT/gems/actionpack-7.0.8/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-7.0.8/lib/action_view/rendering.rb -> **process**
188:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal.rb -> **dispatch**
251:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_controller/metal.rb -> **dispatch**
49:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb -> **dispatch**
32:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb -> **serve**
18:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
48:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/journey/router.rb -> **serve**
852:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/routing/route_set.rb -> **call**
87:  /GEM_ROOT/gems/flipper-1.2.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
45:  /GEM_ROOT/gems/flipper-1.2.2/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/head.rb -> **call**
38:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/http/permissions_policy.rb -> **call**
36:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/session/abstract/id.rb -> **call**
704:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/callbacks.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
28:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
25:  /GEM_ROOT/gems/railties-7.0.8/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/railties-7.0.8/lib/rails/rack/logger.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/remote_ip.rb -> **call**
93:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.6.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-7.0.8/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/sendfile.rb -> **call**
131:  /GEM_ROOT/gems/actionpack-7.0.8/lib/action_dispatch/middleware/host_authorization.rb -> **call**
530:  /GEM_ROOT/gems/railties-7.0.8/lib/rails/engine.rb -> **call**
226:  /GEM_ROOT/gems/railties-7.0.8/lib/rails/railtie.rb -> **public_send**
226:  /GEM_ROOT/gems/railties-7.0.8/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.8.1/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 |

### PR DESCRIPTION
**Pull request by hellcp-work**
The backend diff provides us with filenames for files that can't be viewed in the frontend, since they contain a `/` in their name. This verifies that we can actually link to them, by asking the backend if the file exists.

Fixes #15834

### CODE REVIEW

**Review by danidoni — APPROVED** [review]

**Review by hennevogel — CHANGES_REQUESTED** [review]
How did this slip through the spec?

**Review by eduardoj — CHANGES_REQUESTED** [review]
Changes in the cassette file `src/api/spec/cassettes/MaintenanceWorkflow/maintenance_workflow.yml` are not needed.

**Comment by hennevogel** [comment]
> There is simply no spec that tests binary file changes from the backend, which is what triggered the issue in the first place

Guess this is on your TODO list then...

**Comment by eduardoj** [comment]
I added a commit to restore the `src/api/spec/cassettes/MaintenanceWorkflow/maintenance_workflow.yml` to its original state. Feature tests should pass.

Feel free to merge the commit into yours, if it finally works.

**Review by eduardoj — APPROVED** [review]

**Pull request merged**
