### PR TITLE
OpenAPI specifications for project's attributes

### PR DESCRIPTION
**Pull request by rubhanazeem**
Specifications for `GET,POST,DELETE source/:project/_attribute/(:attribute) `

### CODE REVIEW

**Comment by rubhanazeem** [comment]
[Sources - Projects (L)](https://trello.com/c/MSXY9t4w/1986-sources-projects-l)

**Review by danidoni — DISMISSED** [review]

**Comment by danidoni** [comment]
I'm getting a 200 response with
```
<attributes/>
```
instead of a 200 response with
```
<attributes>
	<attribute name="MaintenanceProject" namespace="OBS">
	</attribute>
</attributes>
```
When adding the `OBS:MaintenanceProject` attribute to a `home:Admin` project....

**Comment by rubhanazeem** [comment]
> home:Admin

It's because `home:Admin` doesn't have `MaintenanceProject` in `OBS` name space

**Comment by danidoni** [comment]
> > home:Admin
> 
> It's because `home:Admin` doesn't have `MaintenanceProject` in `OBS` name space

Hmmm strange, I believe I added the attribute before... Anyway, I tried again and now it returns the correct response.

**Review by danidoni — APPROVED** [review]

**Pull request merged**
