### PR TITLE
[webui][api] Move comment authorization check to policy

### LINKED ISSUE #2357: Allow maintainers to remove comments
Comments sections tend to be used by users as an alternative to "send mail to maintainer". For example, packaging questions or comments about new versions are not uncommon. Unfortunately only owners of these comments or administrators seem to be able to remove them. This allows many years out-of-date comments to persist.

Please allow maintainers of packages and projects to remove these zombie comments.

### PR DESCRIPTION
**Pull request by ChrisBr**
fixes #2357.

### CODE REVIEW

**Comment by ChrisBr** [comment]
When #2348 is merged we can also merge the three different policies into one! I don't mind if we wait till #2348 is merged and I rebase and adapt this one or the other way around.

**Comment by ChrisBr** [comment]
@Ana06 ^^

**Comment by hennevogel** [comment]
@ChrisBr please rebase as #2348 is merged

**Comment by ChrisBr** [comment]
As this is some bigger task and not planned in the current sprint I will close this one and add a card to the backlog!

**Pull request closed without merging**
