### PR TITLE
Fix the API docs involving the directory schema

### PR DESCRIPTION
**Pull request by dcermak**
- The directory element can contain the `vrev` attribute
- The example for the `/source/<project>/<package>` route is a `_meta` and not the list of files as would be expected.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
Thanks, but you introduced new directory_filelist.xml without new schema file. This is the reason for the testcase failure. 

We could either extend current directory.xml or we introduce an additional schema. directory_source_listing might be a good name here.

**Comment by dcermak** [comment]
> Thanks, but you introduced new directory_filelist.xml without new schema file. This is the reason for the testcase failure.
> 
> We could either extend current directory.xml or we introduce an additional schema. directory_source_listing might be a good name here.

Not sure if introducing another schema makes sense here, as the `directory.xsd` **is** the correct schema already, the example is just plain wrong.

**Comment by adrianschroeter** [comment]
On Dienstag, 14. Januar 2020, 09:24:55 CET Dan Čermák wrote:
> > Thanks, but you introduced new directory_filelist.xml without new schema file. This is the reason for the testcase failure.
> > 
> > We could either extend current directory.xml or we introduce an additional schema. directory_source_listing might be a good name here.
> 
> Not sure if introducing another schema makes sense here, as the `directory.xsd` **is** the correct schema already, the example is just plain wrong.

The example is complete valid for a different route (/source/$project).

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dcermak** [comment]
Adrian Schröter <notifications@github.com> writes:

> On Dienstag, 14. Januar 2020, 09:24:55 CET Dan Čermák wrote:
>> > Thanks, but you introduced new directory_filelist.xml without new schema file. This is the reason for the testcase failure.
>> > 
>> > We could either extend current directory.xml or we introduce an additional schema. directory_source_listing might be a good name here.
>> 
>> Not sure if introducing another schema makes sense here, as the `directory.xsd` **is** the correct schema already, the example is just plain wrong.
>
> The example is complete valid for a different route (/source/$project).
>

Would a symlink work for the schema? Then at least the two directory.xsd
schemas couldn't diverge.

**Comment by dcermak** [comment]
Adrian Schröter <notifications@github.com> writes:

> On Dienstag, 14. Januar 2020, 09:24:55 CET Dan Čermák wrote:
>> Not sure if introducing another schema makes sense here, as the `directory.xsd` **is** the correct schema already, the example is just plain wrong.
>
> The example is complete valid for a different route (/source/$project).

Oh and the example is also invalid for that route, /source/$project
gives you the list of packages in $project, but the example is a
package's _meta. That doesn't even conform to the directory.xsd schema.

**Comment by dcermak** [comment]
@adrianschroeter How should we proceed here?

**Comment by adrianschroeter** [comment]
Just extend the existing one, because it is used for all routes.

Or split it into multiple, and create a special one for source directory listings, but that needs also code updates or the test suite will continue to fail.

**Comment by hennevogel** [comment]
@dcermak whats the status here?

**Comment by dcermak** [comment]
> @dcermak whats the status here?

I honestly don't know how to fix the test failures: the current example for the source listing is the wrong one and extending it won't work (the example is a package _meta file which cannot obey the directory.xsd schema).

**Comment by hennevogel** [comment]
> I honestly don't know how to fix the test failures

Just say so, @openSUSE/obs-frontend  are here to help :-)

**Comment by dcermak** [comment]
Hm, no idea what the issue is here. @openSUSE/obs-frontend help?

**Pull request merged**
