### PR TITLE
Since 1/9/2021, github won't accept unauthenticated git

### PR DESCRIPTION
**Pull request by vpereira**
More details: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

### CODE REVIEW

**Review by krauselukas — COMMENTED** [review]
I would just fix the indentation and maybe rename the commit description, you describe what happend not what your commit is doing

**Comment by krauselukas** [comment]
is the codeclimate failure related to the changes, seem it cannot fetch the code anymore

**Comment by vpereira** [comment]
> is the codeclimate failure related to the changes, seems it cannot fetch the code anymore

it is probably trying to fetch information from master and github is blocking it

**Comment by vpereira** [comment]
> I would just fix the indentation and maybe rename the commit description, you describe what happend not what your commit is doing

updated!

**Review by eduardoj — APPROVED** [review]
Tabs have changed to two spaces. It should not be an issue.

**Pull request merged**
