### PR TITLE
Fix cicount schema and add documentation to link.rng

### LINKED ISSUE #11067: link.xml in docs/api/api/ is invalid
The example `_link` file:
https://github.com/openSUSE/open-build-service/blob/65901a1d979c2665b21c8f643edf25ad1cc47757/docs/api/api/link.xml#L2

is invalid provided that I understand the backend code correctly:
https://github.com/openSUSE/open-build-service/blob/65901a1d979c2665b21c8f643edf25ad1cc47757/src/backend/BSSrcServer/Link.pm#L556

So `cicount` should be either `add`, `copy`, `local` or not present at all, but not a number.

### PR DESCRIPTION
**Pull request by dcermak**
Fixes #11067

### CODE REVIEW

**Comment by hennevogel** [comment]
Awesome @dcermak :bouquet:

**Comment by dmarcoux** [comment]
@adrianschroeter Please have a look at this PR. I added you as a reviewer since you commented in the issue linked in the PR's description.

**Comment by dcermak** [comment]
Bump?

**Comment by dcermak** [comment]
@adrianschroeter Bump?

**Comment by Smarre** [comment]
Strange that this ticket is only place to get proper documentation about _link...

**Comment by dmarcoux** [comment]
Thank you @dcermak for submitting this PR.

**Pull request merged**
