### PR TITLE
[ci] Fix flaky DoD test

### PR DESCRIPTION
**Pull request by coolo**
Wait for the repository container to appear before checking
things within it

### CODE REVIEW

**Comment by ChrisBr** [comment]
Thanks @coolo :heart:

**Comment by coolo** [comment]
it became less flaky and the error message changed, but I needed to run around 30 runs to trigger:

```
 expected to find visible css ".repository-container" but there were no matches
```

And the test.log shows that the POST wasn't even done.

**Comment by coolo** [comment]
After sudo zypper in xorg-x11-fonts-core xorg-x11-fonts:

screenshot_2018-06-24-07-56-31 333

So looks all good

**Comment by ChrisBr** [comment]
> Perhaps you put some fonts in the frontend container, so that screenshots are somewhat debuggable :)

Lol! Added the ``xorg-x11-fonts-core xorg-x11-fonts`` package to the base containers.

**Comment by adrianschroeter** [comment]
On Sonntag, 24. Juni 2018, 14:04:12 CEST wrote Christian Bruckmayer:
> > Perhaps you put some fonts in the frontend container, so that screenshots are somewhat debuggable :)
> 
> Lol! Added the ``xorg-x11-fonts-core xorg-x11-fonts`` package to the base containers.

Should these be Requires of some package, eg. obs-devel ?

(we should not maintain development dependencies in every development enviroment...)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Pull request merged**
