### PR TITLE
Add support for hostlabel based job filtering for workers

### PR DESCRIPTION
**Pull request by trhd**
Add support for configuring workers such that they will only get jobs that meet the their hostlabel requirements. Previously it has only been possible to set hostlabels for jobs so that the jobs will be run on workers that have the same hostlabels but it has not been possible to filter jobs from the worker's point of view.

This change implements two filtering modes for the hostlabels. The "and" mode requires that an incoming job has all the same hostlabels as the worker and the "or" mode requires the incoming jobs to have at least on of the worker's hostlabels.

The first commit removes some dead code that was found during this' development (pay attention to the lines 1363 and 1364).

### CODE REVIEW

**Comment by adrianschroeter** [comment]
So the dependency from the _constraints file is suddenly also something what a worker can check for?

IMHO we shouldn't mix this, but I would need to know about the use case you have. Are you sure that you couldn't solve your usecase with some lines of perl code in BSConfig.pm "our $dispatch_constraint" on your server in a more convenient way?

**Comment by trhd** [comment]
> So the dependency from the _constraints file is suddenly also something what a worker can check for?

Yes and no. It is a configurable option for the worker but in reality, the worker passes this filtering requirement to the server/dispatcher.


Use case no. 1: 

I want to investigate something specific about a job while it is running (not necessarily a job that I have created myself, but perhaps some jobs have misbehaved in some manner for example). I set up a worker (e.g. on my own computer) and join the worker pool of our server. Now without this kind of a configuration option the worker I just set up might accept any jobs from the server. By configuring this kind of a filtering I can ensure that only the jobs I want to investigate will get dispatched to my special worker.


Use case no. 2:

I have jobs with special requirements (e.g. extra long run, requires a ton of HD, requires special permissions, etc.) and I've prepared some workers just for this purpose. I then want only the jobs with the special requirement to be dispatched to these servers (to avoid bottlenecks, security threats, special workers might be more expensive).


It might be possible to achieve the same effect with the use of dispatch_constraint but I don't see the benefit of it. Perhaps I'm missing something?

The key thing here, is that I'm able to configure a worker (perhaps even just temporarily), that accepts only some special earmarked jobs without needing to modify the OBS server itself.

**Comment by adrianschroeter** [comment]
For Usecase No. 1 we should add on option to bs_worker where you can specify a (local?) jobfile to build exactly that. Could also be combined with --test so it does not block it for other workers.

Usecase No. 2: I see the risk that the not portable labels get used too much. Means you won't have them on another OBS installation. Wouldn't it be better to transport some concrete requirement, to the dispatcher? ("I build only jobs with requirement of XXXGB disk space", "Only build jobs which require 99 CPU cores").

**Comment by trhd** [comment]
> For Usecase No. 1 we should add on option to bs_worker where you can specify a (local?) jobfile to build exactly that. Could also be combined with --test so it does not block it for other workers.

Sounds reasonable.

> Usecase No. 2: I see the risk that the not portable labels get used too much. Means you won't have them on another OBS installation. Wouldn't it be better to transport some concrete requirement, to the dispatcher? ("I build only jobs with requirement of XXXGB disk space", "Only build jobs which require 99 CPU cores").

For those two cases a concrete requirement could do, but I imagine people could have very exotic uses for this in which case free-from requirements would be needed.

I don't see the non-portability of the labels as a problem. I would imagine these hostlabels end up being so context dependent that the risk of mixing which labels are used on which server would be small. I also have hard time imagining people using that many different OBS servers side by side in the first place.

In any case, its completely fine to close these PRs of mine if the offered functionality doesn't interest you...

**Comment by mlschroe** [comment]
Restricting workers to specific jobs seems worthwhile to me. But I'd prefer some more generic way, e.g. to have the worker also specify constraints that are used as minimal set that the job must have. So the worker can say "I'm only taking jobs that need at least 1 Gig of mem" or such.

Currently there would be no way to specify your and/or flag. Is that something you need in your obs instance?

Also note that the "dead code" you removed is also about limiting the worker to jobs. It's some feature of our old autobuild system, a constraint can be met to some percentage which means that the job would build ok but the worker doesn't fit very well. Thus a worker that has a lot of mem can also build small jobs but only if no other worker builds them for some time.

**Comment by trhd** [comment]
The and/or option is given to the worker via sysconfig.

**Pull request closed without merging**
