### PR TITLE
Bootstrap/package user groups

### PR DESCRIPTION
**Pull request by mdeniz**
Migrate the Users tab of the Package, now look like this:

image

This is for adding a user, now is in a modal dialog:

image

Removing the user roles is also a modal dialog for confirmation:

image

This is for adding a group now is in a modal dialog:

image

Removing the group roles is also a modal dialog for confirmation:

image

When clicking in the checkboxes a spinner appears next to the clicked checkbox:

roles_click

### CODE REVIEW

**Comment by mdeniz** [comment]
> For the other search box (on the users tab) I found a strange behavior which is:
> Enter 'Group' or 'Admin' and it filters the tables as expected. Enter 'Super' and nothing happens.

:smile: 

That's the normal behavior... if you write a text that every single row has then all stay... like `Super` and `OBS Instance Superuser (Admin)` both have **Super** on it so, nothing changes
And if you write something like **obs** then just the first one will be there

**Comment by mdeniz** [comment]
>There two things I found:
>    The 'Users' label is missing in the breadcrumb

Will do!

>    In the user / group dialog, I added 'Super' in the search field and hit enter. This closes the dialog
>    and cancels the action. I would expect that this either triggers the search or confirms the input

For the search you don't need to hit enter.
Pressing enter is closing the dialog, and every other dialog we have... I will add it to the card of issues and take a look if have time :+1:

**Comment by dmarcoux** [comment]
We must not forget to add the autocomplete to OBS patterns.

**Comment by bgeuken** [comment]
Hm, I am somewhat sure that previously the user search was also filtering the groups table:thinking:
Anyway, I can't reproducing it anymore.


> For the search you don't need to hit enter as this is an autocomplete field.
Pressing enter is closing the dialog, and every other dialog we have... I will add it to the card of issues and take a look if have time 👍

I don't this is obvious or intuitive for users.  Quite sure that most of the times they will enter some text and then hit enter to search for it.
We could fetch some users and see how this works for them.

So for the search field I would not trigger any action when hitting enter. And for the dialogs in general (out of scope for this PR) I would close (as in cancel) them when Esc key was pressed and trigger an accept when enter was hit and the focus is on the Ok (or at least not on the Cancel button).

**Comment by mdeniz** [comment]
> I don't this is obvious or intuitive for users. Quite sure that most of the times they will enter some text > and then hit enter to search for it.

I agree

> We could fetch some users and see how this works for them.

That sounds like our beta program, I think there is no need to do it for this little thing. I agree with that hitting enter is quite common and we need a solution.

> So for the search field I would not trigger any action when hitting enter. And for the dialogs in general > (out of scope for this PR) I would close (as in cancel) them when Esc key was pressed and trigger an > accept when enter was hit and the focus is on the Ok (or at least not on the Cancel button).

This is happening in every single dialog we have (that have an input field). I don't want to fix everything here is not the purpose of this PR. I already added the issue to the card in our board.

Do you think that anything else needs to be fixed/changed in the PR?

**Comment by mdeniz** [comment]
I created the issue to fix the problem https://github.com/openSUSE/open-build-service/issues/5959

**Comment by bgeuken** [comment]
> > We could fetch some users and see how this works for them.

> That sounds like our beta program, I think there is no need to do it for this little thing. I agree with that hitting enter is quite common and we need a solution.

Not really. The beta program is about feedback in general. I was talking about testing some specific workflow (adding users to a package) with a smaller group of people.

IMO we should do that for workflows we are not sure how users perceive them. Not sure if that applies here

**Comment by bgeuken** [comment]
> This is happening in every single dialog we have (that have an input field). I don't want to fix everything here is not the purpose of this PR. I already added the issue to the card in our board.

Alright, if you are saying you are going to fix this bug in another PR I am fine with that. My point is just that having a bug elsewhere is not a good reason to have it here as well.

**Comment by mdeniz** [comment]
> Alright, if you are saying you are going to fix this bug in another PR I am fine with that. My point is just that having a bug elsewhere is not a good reason to have it here as well.

Yes, I'm going to fix all the issues in the same PR, better to have an homogeneous solution for all. Just merge this one if you are ok with the rest and I will change it after, there is no need to change this PR in the meanwhile.

**Pull request merged**
