### PR TITLE
Allow to specify commit messages when changing files

### PR DESCRIPTION
**Pull request by vpereira**
Backport from PR #7813 from master to branch 2.10

### CODE REVIEW

**Comment by DavidKang** [comment]
For me it's fine, because we are "backporting" to the 2.10-beta

**Comment by saraycp** [comment]
I'm ok with backporting it :+1:

**Comment by hennevogel** [comment]
We are backporting everything until we released 2.10

**Comment by DavidKang** [comment]
superseded by PR#[7845](https://github.com/openSUSE/open-build-service/pull/7845)

**Pull request closed without merging**
