### PR TITLE
Set the responsive_ux layout as the default layout

### PR DESCRIPTION
**Pull request by dmarcoux**
The responsive_ux layout was renamed to webui and the "old" webui layout has thus been overwritten, it's now gone.

*Note: Views from the "old" webui layout will be removed in following PRs. I try to keep PRs small for easy reviews.*

### CODE REVIEW

**Comment by dmarcoux** [comment]
I'm hitting the issue #10170... I'll look into why it's happening.

**Comment by dmarcoux** [comment]
[Remove responsive_ux feature flag after the rollout](https://trello.com/c/KlHFqSGS/1626-remove-responsiveux-feature-flag-after-the-rollout)

**Comment by dmarcoux** [comment]
We're going to tackle this more towards the end since it's just too big to start with. Too many specs are failing.

**Comment by dmarcoux** [comment]
After looking more into this, not having the layout is going to be a blocker so we need to handle this now.

**Comment by dmarcoux** [comment]
Sorry for the somewhat big PR... it's difficult to make this smaller since it's a all or nothing approach when switching the layout.

**Review by eduardoj — APPROVED** [review]

**Pull request merged**
