### PR TITLE
Improve copyproject API

### PR DESCRIPTION
**Pull request by tuminoid**
Copy more missing files from source project when using copyproject API. This prevents more cases where rebuilding occurs after copy and also fixes viewing of logs etc.

### CODE REVIEW

**Comment by tuminoid** [comment]
@kkeil would you check these as they improve your previous copyproject patches?

**Comment by adrianschroeter** [comment]
it should be possible to implement this without to extend BSXML and scheduler parts, but filter during preperation of the import job in repserver's copybuild function directly.

**Comment by kulmesa** [comment]
> it should be possible to implement this without to extend BSXML and scheduler parts ...

Probably those BSXML changes are not necessary, but I think some scheduler changes are needed (I don't think scheduler would otherwise copy the :lastcheck file to target reporoot).

:lastcheck file is important to copy, because in some cases when build-compare has been used in the source project, it would cause unnecessary rebuilds in target project. In these cases scheduler would detect meta changes incorrectly in checkpackage function, because :lastcheck is missing.

>  ... but filter during preperation of the import job in repserver's copybuild function directly.

Do you mean uploadbuild job? (repserver doesn't create import job in copybuild function)

**Comment by adrianschroeter** [comment]
copybuild is creating a job in Line 2176 in git master. (haven't checked 2.6 branch, but this change is to big for 2.6 anyway IMHO)

**Comment by kulmesa** [comment]
Ok, I though you were talking about import event. Anyway, the main idea of this patch is just to copy :lastcheck and preinstallimage files, because in those parts the copyproject doesn't work correctly in 2.6 branch.

I just noticed that it is enough to copy .preinstallimage file to jobdir in reposerver and then the update_dst_full function in scheduler will take care of the rest. So in that part it wouldn't require any changes to scheduler code.

**Comment by adrianschroeter** [comment]
:lastcheck is a cache and should not be needed to avoid build-compare builds, if the meta files got copied.

**Comment by kulmesa** [comment]
Even though meta files were copied, we still had some issues in a following case:
- source project contains three packages (e.g. packageA, packageB and packageC)
- packageB depends on (BuildRequires) packageA, and packageC depends on packageB _and_ packageA.
- there is a source change in packageA, which also causes packageB and packageC to be rebuild
- build-compare doesn't detect any changes in packageB and packageC:
  (build log: Retried build at ... returned same result, skipped)
- at this point source project packageC metafiles would look something like this:

`$ grep packageA /srv/obs/build/<src_proj>/<repo>/<arch>/packageC/.meta.success`
`e00479c5a6c6e66bbc8470841cb3b4ee  packageA`
`$ grep packageA /srv/obs/build/<src_proj>/<repo>/<arch>/:meta/packageC
40b0c17ee975ccfaabefaa7efada9cc8  packageA`
`e00479c5a6c6e66bbc8470841cb3b4ee  packageB/packageA`

- notice that source project packageC/.meta.success contains older version of packageA (i.e. version of packageA when build-compare detected change)
- however :meta/packageC contains latest version of packageA and also version of packageA what was used when packageB was build
- if source project would be copied now, destination project packageC would be rebuild, because scheduler would think that packageA meta is changed

Copying source project :lastcheck seemed to solve this issue with build-compare rebuilds.

**Comment by mlschroe** [comment]
Maybe lastcheck copying suppressed the rebuild, but it is definitely the wrong thing to do. It basically disables the scheduler looking at the package, you might as well disable building for the project.

From your description it seems like we're copying the wrong meta file, we should copy the file in :meta and not the .meta.success file. I'll try to fix this.

**Comment by kulmesa** [comment]
not sure if it is enough to copy the :meta file (it is changed in the pull request). When I was testing that case which I mentioned earlier, scheduler seemed to trigger rebuild in packageC even though :meta file was copied. It seemed that the scheduler wasn't able to recalculate the same packageA dependencies in destination packageC what was in the source package :meta file. It's quite odd that souce :meta file contained two versions of packageA.

**Comment by adrianschroeter** [comment]
I have adapted the test case for git master branch here:

  https://github.com/adrianschroeter/open-build-service/tree/test_copy_project

One issue was that the source project got no clean setup (no injected builds) for x86_64. After fixing that the test succeeds on git master for me.

Does it still look like the situation you want to test? 
If yes, it means one of the fixes for this from git master did not went to your code branch yet ....

**Comment by kulmesa** [comment]
> Does it still look like the situation you want to test? 

I think it is good to have, because I don't think there is a test case for copyproject which checks that the binaries are really copied to destination project.

> If yes, it means one of the fixes for this from git master did not went to your code branch yet ....

What fix are you referring to?

BTW, have you checked about the rebuild issue which I mentioned few comments ago? I noticed that Michael did some fixes to master, but I don't know if those help with that rebuild issue. We are still using the lastcheck file there, since I don't know any better solution for that case.

**Comment by adrianschroeter** [comment]
Right, we will merge the test case in any case. Thanks a lot for your ground work here!

Next step is to backport the modified version again to see if we lack fixes in older branches, since the test case succeeds without further modifications in git master. I just wanted to check back with you that we do still test the same scenario.

**Comment by kkeil** [comment]
Hi all,

I did verify that the master (appliance from today) pass this:

- source project contains three packages (e.g. packageA, packageB and
packageC)
- packageB depends on (BuildRequires) packageA, and packageC depends on
packageB and packageA.
 - there is a source change in packageA, which also causes packageB and
packageC to be rebuild
 - build-compare doesn't detect any changes in packageB and packageC:
(build log: Retried build at ... returned same result, skipped)


Here are no rebuilds in this case.

@Esa, please verify that my test setup is correct for this, the packages
are on
https://github.com/b1-systems/obsdemo_packages

Here are 3 test packages, demotest1...3 each with only a _service file
in the OBS packages:
demotest1:
<services>
  <service name="tar_scm" mode="serveronly">
    <param name="version">0.6.1</param>
    <param name="revision">a0.6.1</param>
    <param
name="url">http://github.com/b1-systems/obsdemo_packages.git</param>
    <param name="scm">git</param>
  </service>
  <service name="extract_file">
    <param name="files">*/dist/demotest1.spec</param>
    <param name="outfilename">demotest1.spec</param>
    <param name="archive">*.tar</param>
  </service>
  <service name="recompress">
    <param name="compression">xz</param>
    <param name="file">*.tar</param>
  </service>
  <service name="set_version">
  </service>
</services>

demotest2:

<services>
  <service name="tar_scm" mode="serveronly">
    <param name="version">0.2.1</param>
    <param name="revision">b0.2.1</param>
    <param
name="url">http://github.com/b1-systems/obsdemo_packages.git</param>
    <param name="scm">git</param>
  </service>
  <service name="extract_file">
    <param name="files">*/dist/demotest2.spec</param>
    <param name="outfilename">demotest2.spec</param>
    <param name="archive">*.tar</param>
  </service>
  <service name="recompress">
    <param name="compression">xz</param>
    <param name="file">*.tar</param>
  </service>
  <service name="set_version">
  </service>
</services>

demotest3:

<services>
  <service name="tar_scm" mode="serveronly">
    <param name="version">0.1.0</param>
    <param name="revision">c0.1.0</param>
    <param
name="url">http://github.com/b1-systems/obsdemo_packages.git</param>
    <param name="scm">git</param>
  </service>
  <service name="extract_file">
    <param name="files">*/dist/demotest3.spec</param>
    <param name="outfilename">demotest3.spec</param>
    <param name="archive">*.tar</param>
  </service>
  <service name="recompress">
    <param name="compression">xz</param>
    <param name="file">*.tar</param>
  </service>
  <service name="set_version">
  </service>
</services>

Using these _service files for the first build.
After building try a project copy, should always work fine (master and
backport).

Then modify demotest1 _service file to use version 0.6.2 and tag a0.6.2
(Only a change in README.md). This results in
a rebuild of all 3 package, but 2 and 3 are retried only.

Now the projectcopy works with master, but not yet with the current
backport without rebuilding.

**Comment by kulmesa** [comment]
> @Esa, please verify that my test setup is correct for this, the packages are on

Yes, this is the correct test setup.

**Comment by adrianschroeter** [comment]
merged the new test case and the fixes from kkeil into my branch. Pull request 1896 . So we can close this one.

**Pull request closed without merging**
