### PR TITLE
Autocorrect some RuboCop offenses (III)

### PR DESCRIPTION
**Pull request by eduardoj**

### CODE REVIEW

**Comment by danidoni** [comment]
Can we do something about the issues CodeClimate is complaining about?

**Comment by eduardoj** [comment]
> Can we do something about the issues CodeClimate is complaining about?

codeclimate reports 9 issues fixed and 2 new issues to fix. Those 2 new issues have poped up after refactoring the code. I would say they are in fact the same.

**Review by danidoni — APPROVED** [review]

**Comment by eduardoj** [comment]
@danidoni, I need to rebase on master.

After that, new `Lint/RedundantCopDisableDirective` appeared. I added a commit to fix them.

I also added the las commit, to improve the definition of migration for the "Isolated Migrations" GitHub action.

Please take a look again.

**Review by danidoni — APPROVED** [review]

**Comment by eduardoj** [comment]
I approved the two codeclime issues. Merging.

**Pull request merged**
