### PR TITLE
[webui] Fix replace_jquery_meta_characters

### LINKED ISSUE #1986: save repository does not work for some repos
save remote repos over interconnect

### PR DESCRIPTION
**Pull request by ChrisBr**
supersedes 3815422644b4e176b905e8d26708c9fa5ab23914.
Finally fixes #1986.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Once again I learned how awesome tests are ... :cry:

**Comment by hennevogel** [comment]
@adrianschroeter I guess you want to hotfix this...

**Comment by adrianschroeter** [comment]
@hennevogel  ChrisBr and me agreed to hotfix it together with the pre-selection bugfix.

**Comment by adrianschroeter** [comment]
okay, the part is applied ...

@ChrisBr while you are over it, can you also add some commit message for the changes?
That way the single commits may make sense in the history. You can do so by calling this before save/store:

project.commit_opts = { comment: "Adding $repository_name" }

**Comment by hennevogel** [comment]
@adrianschroeter the pre-selection is a feature, it never worked for remote projects... ;-)

**Comment by adrianschroeter** [comment]
@hennevogel test again with an OBS before webui merge;) Okay, it did not broke with repository_controller commit then...

@ChrisBr in case you want to test the history entry, you can request it via

 "/source/$PROJECT/_history?meta=1"

call, JFYI

**Comment by ChrisBr** [comment]
@adrianschroeter added the suggested comments.

**Pull request merged**
