### PR TITLE
Revert "[ci][api] Update tests for calls to /status/history"

### PR DESCRIPTION
**Pull request by bgeuken**
This reverts commit 7d818bd83b7cadfc241547134820ae002bd89271.

This is just a test!

### CODE REVIEW

**Comment by bgeuken** [comment]
No need to review. I just want to test the coverage...

**Comment by bgeuken** [comment]
@hennevogel @adrianschroeter @ChrisBr @mdeniz Anyone of you has an idea why the reverted test decreases the test coverage by 20%?
And do we consider that to be bad or not... IIRC Henne recently mentioned that our real coverage should be around 60%...

**Comment by bgeuken** [comment]
hm, maybe it's the Timecop call

**Comment by hennevogel** [comment]
I've played around with the problems/solutions mentioned in a [blog post](https://www.stormconsultancy.co.uk/blog/development/ruby-on-rails/getting-accurate-code-coverage-metrics-from-simplecov-rails-project/) about accurate code coverage metrics. This had nothing to do with Timecop...

**Comment by hennevogel** [comment]
The [test run in the PR](https://coveralls.io/builds/3851239) didn't decrease but all test runs afterward did. WTF is going on...

**Comment by bgeuken** [comment]
@hennevogel After adding the Timecop freeze in 1facf33 coverage went down again to 64...

**Comment by hennevogel** [comment]
Try a `Timecop.return`

**Comment by hennevogel** [comment]
Or 
```ruby
Timecop.freeze(something) do
  something
end
```

**Comment by bgeuken** [comment]
Yep. Just doing in #1267

**Comment by bgeuken** [comment]
There are quite some cases of Timecop.freeze calls without return or block in our tests. We might need to clean them up.

**Comment by bgeuken** [comment]
#1267 passed and increased coverage back to 87%. I am opening an issue for the remaining Timecop calls.

=> closed

**Pull request closed without merging**
