### PR TITLE
Change top navigation menu

### PR DESCRIPTION
**Pull request by DavidKang**
We limited the max-width of the top navigation and also changed the menus on the top navigation.

Screenshot_2020-02-17 Open Build Service(2)

### CODE REVIEW

**Comment by dmarcoux** [comment]
Whenever there is room available, so on most devices except smaller ones like phones, I suggest that we display all items directly in the top navigation bar. So if I want to logout, I could directly click `Logout` instead of having to click on my avatar, then on `Logout`.

**Comment by DavidKang** [comment]
@dmarcoux, something like this:

Screenshot_2020-02-17 Open Build Service

Honestly, I don't like to have the logout at this level.

**Comment by dmarcoux** [comment]
I like it!

I'm fine with having the `Logout` on this level, but completely on the right side. If not, where should we put it? As before in a menu under the avatar, together with `Profile`?

**Comment by DavidKang** [comment]
> where should we put it? As before in a menu under the avatar, together with Profile?

@dmarcoux, I don't have a clear solution for that. For now, I can live with the logout at the end.

**Comment by danidoni** [comment]
> > where should we put it? As before in a menu under the avatar, together with Profile?
> 
> @dmarcoux, I don't have a clear solution for that. For now, I can live with the `logout` at the right.

What about hiding the buttons under something that slides left when you move the mouse over, like for example, the profile. Then you have a one-click solution and is not "polluting" the top bar. The downside is that maybe its not super evident, but maybe with an arrow/left-chevrons suggesting something can be pulled off...

**Comment by dmarcoux** [comment]
I don't agree that it's "polluting" the top bar to have the buttons there. I understand that we need to think about different strategies on devices with smaller viewports, but on desktop, displaying a small amount of icons is fine.

**Comment by hennevogel** [comment]
I dont like it either. It's too cramped and gives logout a weight that it does not deserve.

Especially as the off canvas menu provides the possibility to extend the navigation beyond this...

**Comment by danidoni** [comment]
> I don't agree that it's "polluting" the top bar to have the buttons there. I understand that we need to think about different strategies on devices with smaller viewports, but on desktop, displaying a small amount of icons is fine.

Okay!

**Comment by vpereira** [comment]
Screenshot_2020-02-19_23-10-49

I don't like to use the "GH does like that" joker but my point is more like, it's doable, we use GH daily and it's really not a problem to have it there 

Gitlab does the same:

Screenshot_2020-02-19_23-14-15

Trello, Basecamp, Gmail, you name it.. all of them do it as we do, so it's pretty much a standard to have it as we have now.

**Comment by DavidKang** [comment]
@vpereira, after the planning meeting this PR is no valid anymore. So I will close it.

**Pull request closed without merging**
