### PR TITLE
[backend] call-service-in-docker.sh - docker image now configurable

### PR DESCRIPTION
**Pull request by M0ses**

### CODE REVIEW

**Comment by mmohring** [comment]
Hi, I have seen src/backend/call-service-in-lxc.sh got deleted. And I could not find out how to configure LXC vs. Docker in the Backend nor where to find the docker images needed. Please enlight us.

**Comment by M0ses** [comment]
@mmohring : unfortunately we don`t have prepared docker image ATM for non-technical reasons. I readd the lxc script in this PR https://github.com/openSUSE/open-build-service/pull/2313

Once we are ready with the docker image, we will also provide a HowTo (in Admin Guide or BestPractice) or a script to automate the docker setup

Sorry for inconvenience

**Comment by mmohring** [comment]
No Problem. I just saw that the LXC script was deleted in the git repo and got curious how it works and gets configured. A comment in BSConfig.pm would help already how to setup the source service in the backend. Is it true that the source service does not use LXC nor Docker by default at the moment ? And that the config got moved to the config file via config api ?

**Comment by M0ses** [comment]
In our appliance nor docker neither lxc is used by default. 

AFAIK: 
* there is no documentation how to setup lxc or docker. 
* lxc is no longer supported by newer releases of SLES/openSUSE

docker will be the new way to run services in containers. Please feel free to open an issue for documentation, to get more visibility.

I did not got your point about the config. As you can see in

https://github.com/openSUSE/open-build-service/commit/911de7bac46d31af8482238297380e880af3478b

obs_admin got a new feature to query for configuration options. It uses BSConfiguration which is able to give back configuration values from configuration.xml (which can be modified by the api) or from BSConfig.pm. For us it is also a good point to set default values instead of doing in the daemons directly as defaults in the daemons can not be queried from the outside.

I hope this answers your questions.

**Comment by mmohring** [comment]
My question was which field in the configuration.xml is setting this variable.

**Comment by M0ses** [comment]
You can add a variable called $service_wrapper to BSConfig.pm. But I would not recommend to try it without an detailed howto as it will not work out of the box.

Please open an issue requesting documentation and if we fixed the docker container issue, we may provide information about how to configure (it`s up to @adrianschroeter to  prioritize later on).

**Pull request merged**
