### PR TITLE
Change type of `report_bug_url` field from `text` to `string`

### PR DESCRIPTION
**Pull request by eduardoj**
A limit of `65_535` is a bit excesive for a URL.

### CODE REVIEW

**Comment by hennevogel** [comment]
> A limit of 65_535 is a bit excesive for a URL.

Why? What do we gain from limiting this?

**Comment by eduardoj** [comment]
> > A limit of 65_535 is a bit excesive for a URL.
> 
> Why? What do we gain from limiting this?

Two reasons:

1) A sane setting of an URL. To me it doesn't make much sense that a user could enter a generic URL bigger than 2000 characters. I proposed to twice this number. More than that seems unnecessary big, or simly wrong.

2) Dabatase wise, changing from `:text` to `:string` would make the field change from type `text` to `varchar`. This has its benefits. From the [reference documentation](https://mariadb.com/kb/en/text/#difference-between-varcharvarchar-and-text):

_Using TEXT or [BLOB](https://mariadb.com/kb/en/blob/) in a [SELECT](https://mariadb.com/kb/en/select/) query that uses temporary tables for storing intermediate results will force the temporary table to be disk based (using the [Aria storage engine](https://mariadb.com/kb/en/aria-storage-engine/) instead of the [memory storage engine](https://mariadb.com/kb/en/memory-storage-engine/), which is a bit slower. This is not that bad as the [Aria storage engine](https://mariadb.com/kb/en/aria-storage-engine/) caches the rows in memory. To get the benefit of this, one should ensure that the [aria_pagecache_buffer_size](https://mariadb.com/kb/en/aria-system-variables/#aria_pagecache_buffer_size) variable is big enough to hold most of the row and index data for temporary tables._

**Comment by hennevogel** [comment]
> To me it doesn't make much sense that a user could enter a generic URL bigger than 2000 characters.

To you maybe not but that isn't really what the world adheres to right? 😜  AFAIR HTTP/2 says something like 8K characters.

> Using TEXT or [BLOB](https://mariadb.com/kb/en/blob/) in a [SELECT](https://mariadb.com/kb/en/select/) query that uses temporary tables for storing intermediate results will force the temporary table to be disk based

I very much doubt that we'll use the content of this field in queries...

**Comment by eduardoj** [comment]
> > To me it doesn't make much sense that a user could enter a generic URL bigger than 2000 characters.
> 
> To you maybe not but that isn't really what the world adheres to right? 😜 AFAIR HTTP/2 says something like 8K characters.

Fair point. I changed the proposed limit to 8192.

**Review by hennevogel — APPROVED** [review]

**Pull request merged**
