### PR TITLE
Improve admin check

### PR DESCRIPTION
**Pull request by adrianschroeter**
Working on making backend and api xml rendering more similar.

### CODE REVIEW

**Comment by mdeniz** [comment]
I think I'm missing something... why do we need an Admin helper?
Helpers are not for random code that not belongs to views (please check what they are for here http://mixandgo.com/blog/the-beginner-s-guide-to-rails-helpers). 
I mean, if you need a place for having method that run in background or inside tests for sure they don't have to be in a helper. Helper's methods are visible in ALL the views, so you can run them by error in a view.

**Comment by hennevogel** [comment]
And please don't put it into `app/helpers`. This will expose it to all controllers and views!

**Comment by adrianschroeter** [comment]
I will turn it into a job class, okay?

**Comment by mdeniz** [comment]
Yes, that's ok :+1:  :smile:

**Pull request merged**
