### PR TITLE
Maintenance incidents

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
can squash the last two commits together? the intermediate state confused me quite a lot :)

**Comment by bgeuken** [comment]
Oups, sorry.

**Comment by bgeuken** [comment]
@adrianschroeter updated

**Comment by adrianschroeter** [comment]
hm, shouldn't we also squash the remaining two? The first commit alone would just lead to broken runtime, right?

Yes, more a style then a real code question ...

**Comment by bgeuken** [comment]
Thanks for the review. I was experiencing with using scopes and obviously did not clean this up properly before sending the pull request.

**Comment by ChrisBr** [comment]
LGTM :+1:

**Pull request merged**
