### PR TITLE
Silence deprecation warnings in production

### PR DESCRIPTION
**Pull request by hennevogel**
They have no value in production, the admin can't do anything
about them.

### CODE REVIEW

**Comment by hennevogel** [comment]
I have the **unfounded** suspicion that this is the base of some of the sync problems we're seeing...

**Comment by hennevogel** [comment]
The problem currently is #9617 which happens **every** time we render a model to XML...

**Comment by vpereira** [comment]
> The problem currently is #9617 which happens **every** time we render a model to XML...

it should fix it https://github.com/openSUSE/open-build-service/issues/9617#issuecomment-636117615 (untested code :))

**Comment by saraycp** [comment]
> it should fix it [#9617 (comment)](https://github.com/openSUSE/open-build-service/issues/9617#issuecomment-636117615) (untested code :))

Even if there is a possible solution for #9617 and this PR is a temporary solution, I'm going to merge it to avoid handling monkey patches in production. These days we are deploying frequently and this make things easier.

PR #9617 is still open, so we can do follow-up there.

**Pull request merged**
