### PR TITLE
Some fixes to make the tests work with chromedriver (and poltergeist for now)

### PR DESCRIPTION
**Pull request by coolo**
This makes reviewing the chrome changes easier later, but remember:

### CODE REVIEW

**Comment by ChrisBr** [comment]
@coolo are these changes supposed to be backward compatible?

**Comment by coolo** [comment]
backward? you mean towards poltergeist? :)

Yes, as written in the PR summary. rspec test suite passes

**Comment by ChrisBr** [comment]
> backward? you mean towards poltergeist? :)

Jup

> Yes, as written in the PR summary. rspec test suite passes

I only  see a comic in your PR description :smile:

**Comment by coolo** [comment]
You could help by elimating the required circleci: backend test :)

**Comment by ChrisBr** [comment]
> You could help by elimating the required circleci: backend test :)

removed :+1: Thanks! Haven't thought about that we need to remove it from the protected branches ...

**Pull request merged**
