### PR TITLE
[backend] renamed BSDispatch/ to BSDispatcher/

### PR DESCRIPTION
**Pull request by lethliel**
renamed BSDisptach/ --> BSDispatcher/

because of naming conflicts between BSDispatch.pm (which is the request dispatcher) and the subdirectory BSDispatch/ (which is the job dispatcher module subdirectory) 

@mlschroe @M0ses please review

### CODE REVIEW

**Comment by adrianschroeter** [comment]
we have this "conflict" also at other places, eg. Build.pm and build in build script. Why is this a problem here? (more are curious question then a complain ;)

**Comment by lethliel** [comment]
just to be prepared for the future. The dispatcher will be getting even more refactored during the new worker / constraint queries and then i can name the main module BSDispatcher.pm :)

**Comment by lethliel** [comment]
added the unit tests for the Constraint Module

**Comment by mlschroe** [comment]
LGTM +1

**Comment by marcus-h** [comment]
If you're bored, you could also change
```
+BSDispatch::Constraints - function to check and calculate constraints
```
to BSDispatcher::Constraints in BSDispatcher/Constraints.pm

**Comment by lethliel** [comment]
done

**Pull request merged**
