### PR TITLE
Cherry pick some fixes

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
now circleci also stops reporting status? :)

**Comment by coolo** [comment]
I have a theory what happened: there were PRs merged between checkout and run of the rspec job. And the checksum it expects no longer matched.

**Comment by hennevogel** [comment]
I'm beginning to suspect that this is a better solution:

```
diff --git a/src/api/app/mixins/has_attributes.rb b/src/api/app/mixins/has_attributes.rb
index f487e51b2..1ea2c0de7 100644
--- a/src/api/app/mixins/has_attributes.rb
+++ b/src/api/app/mixins/has_attributes.rb
@@ -13,9 +13,9 @@ module HasAttributes
     return unless CONFIG['global_write_through']
     project_name = is_a?(Project) ? name : project.name
     if is_a?(Package)
-      Backend::Api::Sources::Package.write_attributes(project_name, name, User.current.login, render_attribute_axml)
+      Backend::Api::Sources::Package.write_attributes(project_name, name, User.current_login, render_attribute_axml)
     else
-      Backend::Api::Sources::Project.write_attributes(project_name, User.current.login, render_attribute_axml)
+      Backend::Api::Sources::Project.write_attributes(project_name, User.current_login, render_attribute_axml)
     end
   rescue ActiveXML::Transport::Error => e
     raise AttributeSaveError, e.summary

```

**Comment by coolo** [comment]
I was thinking about it back then - but nobody really shouldn't write attributes. If it does, it's hiding bugs. And you know: no code changes to please the test suite

**Pull request merged**
