### PR TITLE
Unescape carriage return char in nokogiri xml output

### LINKED ISSUE #10272: 0x13 characters in Edit description of a package via webinterface
When changing the description of a package via "Edit description" in the webinterface the resulting XML contains` &#13;`. This wastes space and looks ugly. Please strip these characters.

Workflow:
* Open Edit description
* Open spec file in another tab
* Copy text from spec file description to package description

### PR DESCRIPTION
**Pull request by krauselukas**
The carriage return character '\r' gets escaped by
nokogiri/libxml which causes the character to be
rendered in the xml output.

https://github.com/sparklemotion/nokogiri/issues/1356

Since this is a valid xml char we can workaround this problem
by unescaping it again.

Fixes #10272

### CODE REVIEW

**Review by dmarcoux — APPROVED** [review]
It would be nice to have a spec covering this.

**Review by eduardoj — APPROVED** [review]

**Comment by krauselukas** [comment]
@dmarcoux I added a little test, its only checking at one point, but I think other tests at least covering that it doesn't brake things and the new one checks for a regression

**Review by dmarcoux — APPROVED** [review]

**Comment by stoecker** [comment]
I would have simply deleted it as it serves no purpose...

**Comment by eduardoj** [comment]
> I would have simply deleted it as it serves no purpose...

@stoecker , could you elaborate? With 'it', are you referring to carriage return characters '\r'?

**Comment by stoecker** [comment]
> @stoecker , could you elaborate? With 'it', are you referring to carriage return characters '\r'?

Yes. The XML is perfectly valid without \r and dropping them saves space.

**Comment by eduardoj** [comment]
> Yes. The XML is perfectly valid without \r and dropping them saves space.

I agree that the XML is perfectly valid without \r, and dropping the will save also space. But dropping the \r characters will make what now is shown like this:

Screenshot from 2020-10-14 14-10-37

... to be shown like this:

Screenshot from 2020-10-14 14-14-15

So, preserving the \r characters has sense for some descriptions. Am I missing something else?

**Comment by stoecker** [comment]
Do you mix \r and \n? \r serves no purpose, the \n is used for text flow.

**Pull request merged**
