### PR TITLE
[webui] Add link to upstream homepage on package page

### PR DESCRIPTION
**Pull request by hiberis**
Fixes: https://github.com/openSUSE/open-build-service/issues/801

### CODE REVIEW

**Comment by hennevogel** [comment]
Hmm this is not really the place. All the other links here are indicating that you have to do something. Why not simply link the title to the *url* if it's present? :-)

**Comment by hiberis** [comment]
Hmm, I do not think that linking a title is good UI design. I think it would not be very intuitive for a user.

The other links also contain information on the package, like that it is a devel package, that there are derived packages and that the package links to an other package.

**Comment by hennevogel** [comment]
Well... how about a subtitle then? :-) Something like

```
<h2>Package Title<br><small>http://example.com</small></h2>
```

**Comment by hiberis** [comment]
Like this?

**Comment by hennevogel** [comment]
Cool. Thanks :-)

**Pull request merged**
