### PR TITLE
Fun with flags

### PR DESCRIPTION
**Pull request by bgeuken**
Some flag related refactoring I did a while ago.

### CODE REVIEW

**Comment by mmohring** [comment]
@bgeuken  I will look into this because I think there is currently a problem with flags updating when you use `osc meta prj` and `osc meta pkg` with xml files containing flags. I will check this and your patch.

**Comment by bgeuken** [comment]
@mmohring That's cool. Thank you! Just be aware that tests are failing right now and I might have to update code.

**Comment by ChrisBr** [comment]
@bgeuken btw, nice name for the PR :clap: 

Fun with flags

**Comment by bgeuken** [comment]
Thanks:D

**Comment by hennevogel** [comment]
giphy

That scope LGTM!

**Pull request merged**
