### PR TITLE
Drop /checks from end of route

### PR DESCRIPTION
**Pull request by ChrisBr**
because appearently it was discussed as this with the stakeholder.

### CODE REVIEW

**Comment by ChrisBr** [comment]
> I am not very convinced with this reason. why was it discussed as this? I guess there is a reason for the stakeholder to want it like that.

It is personal preference :thinking: I can add this to the message but I'm not sure you will like that either :thinking: :smile:

**Comment by ChrisBr** [comment]
> still not convinced... eyes

Me neither ...

**Comment by Ana06** [comment]
@ChrisBr 

> It is personal preference thinking I can add this to the message but I'm not sure you will like that either thinking smile

At least that is a reason :rofl: I would add it because then at least is clear that there was not reason for this change when reading this commit in one year. :thinking:

**Comment by ChrisBr** [comment]
@Ana06 updated!

**Comment by ChrisBr** [comment]
@hennevogel please take care to update the documentation PR, thanks :heart:

**Comment by mlschroe** [comment]
Check out the "Relationship between URL and HTTP methods" sections in the wiki entry about REST: https://en.wikipedia.org/wiki/Representational_state_transfer. You do a POST if you want to modify an existing resource, you do a PUT if you want to create/replace a resource. A PIT to `.../checks` means you create/replace the resource named `checks`.

**Comment by ChrisBr** [comment]
> A PUT to .../checks means you create/replace the resource named checks

This is what we actually do :+1:

**Comment by mlschroe** [comment]
That's why I asked if a `GET .../checks` is a meaningful operation or not...

**Comment by ChrisBr** [comment]
> That's why I asked if a GET .../checks is a meaningful operation or not...

It could be a meaningful collection, yes. But @coolo said he is not particular interested of the state of a single check. Therefore there is ``GET .../reports`` which shows you one report instead (with all the checks which belong to this particular report)

**Pull request merged**
