### PR TITLE
[ci] Update rspec-rails to 3.4.2

### PR DESCRIPTION
**Pull request by ChrisBr**
to fix Undefined Method  in Tests.
See https://github.com/rspec/rspec-rails/issues/1532.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Encountered while developing tests for PackageController#remove_file action.

**Comment by hennevogel** [comment]
Have you packaged it?

**Comment by ChrisBr** [comment]
@hennevogel not yet but I can do it!

**Comment by ChrisBr** [comment]
@hennevogel what is the usual workflow: first merging and then packaging or the other way around (or it doesn't matter)

**Comment by ChrisBr** [comment]
@hennevogel package updated in Unstable
https://build.opensuse.org/package/show/OBS:Server:Unstable/rubygem-rspec-rails

**Comment by ChrisBr** [comment]
Superseded by #2060

**Pull request closed without merging**
