### PR TITLE
Update project routes

### PR DESCRIPTION
**Pull request by bgeuken**
This would update main project routes and the routes for tabs visible on the project page from:
* project/subprojects/:project to project/:project/subprojects/
* project/show/:project to project/:project
...

### CODE REVIEW

**Comment by bgeuken** [comment]
I was working on this to get an idea if and how we could simplify our routes and maybe make them more RESTful. Obviously this is just touching a small part of our routes. Though I wanted to get your opinion on this first before continuing with it.

**Comment by coolo** [comment]
the advantage of project/monitor/home:Iggy over your project/home:Iggy/monitor is that I can change the end of the URL to go to subproject or parent project

**Comment by bgeuken** [comment]
And you can not change the middle of the url?

**Comment by hennevogel** [comment]
Hm, why don't you use resourceful routing?

**Comment by bgeuken** [comment]
@hennevogel Mainly because I didn't go further without asking feedback. Using resourceful routing would have required additional testing and probably more changes in the code. 

Also there are plenty of sub -resources nested in the project scope. It might make sense to clean that up first.

If you all are fine with the change, I would continue this in a couple of smaller PRs. Actually that would be my long term goal.

**Comment by adrianschroeter** [comment]
On Tuesday 19 January 2016, 09:40:48 wrote Henne Vogelsang:
> Hm, why don't you use resourceful routing? 

because only selected views should become accessable via /public

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by coolo** [comment]
I can change something in the middle, but that's not how URL completion works in browsers.

**Comment by hennevogel** [comment]
And I guess this only makes sense if you also change the package routes

**Comment by hennevogel** [comment]
BTW I just remembered that I also have [a branch](https://github.com/hennevogel/open-build-service/tree/refactoring_project_controller_routing) with this ;-) Although hopelessly outdated...

**Comment by bgeuken** [comment]
@hennevogel Yup, as said I didn't want to spend to much time before asking you guys for your opinion.

**Comment by bgeuken** [comment]
I am closing this for now and continue on updating our routes.

**Pull request closed without merging**
