### PR TITLE
Speed up migration

### PR DESCRIPTION
**Pull request by adrianschroeter**
We need this for production deploy or we will be done for a longer time

### CODE REVIEW

**Comment by evanrolfe** [comment]
I don't know why I didn't think of that...
LGTM

For the record `find_each` finds the repos in batches of 1000 and I tested this migration against production data locally and it ran in a matter of seconds. But this is still an improvement.

**Comment by coolo** [comment]
the repository.save! still is a single update, no?

**Comment by mdeniz** [comment]
@coolo `find_each` is running that update in batches of 1000 rows by default... See http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_each

**Comment by coolo** [comment]
Of course - I'm just saying that the save within the loop is *not* done in batches

**Pull request merged**
