### PR TITLE
Enable Bootstrap project show to all beta users

### PR DESCRIPTION
**Pull request by dmarcoux**

### CODE REVIEW

**Comment by vpereira** [comment]
@dmarcoux  thats is repeated https://github.com/openSUSE/open-build-service/pull/6499 no?

**Comment by dmarcoux** [comment]
This is for the project controller. The other PR is for the repositories controller.

**Comment by hennevogel** [comment]
It's kind of the same as  #6502

**Comment by coolo** [comment]
> It's kind of the same as #6502

just that this one has the nicer PR description? :)

**Comment by dmarcoux** [comment]
I didn't see that the other PR was there. I'm closing this one.

**Pull request closed without merging**
