### PR TITLE
[api] fix getting package _meta with view=blame or given revision

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by hennevogel** [comment]
please rebase

**Comment by mdeniz** [comment]
@adrianschroeter Rebase! 😄

**Comment by adrianschroeter** [comment]
Did you figured out that this IMHO wrong params: $body should really stay?

**Comment by bgeuken** [comment]
@mdeniz @hennevogel @adrianschroeter ping

**Comment by hennevogel** [comment]
we have not talked about this no, doesn't really matter for this PR right?

**Comment by bgeuken** [comment]
Okay, then let's merge this.

**Pull request merged**
