### PR TITLE
[webui] Fix redirect after registering as new user

### PR DESCRIPTION
**Pull request by bgeuken**
The workaround for users without home project should get removed as soon
as issue#1090 get's fixed.

### CODE REVIEW

**Comment by mdeniz** [comment]
LGTM

**Comment by bgeuken** [comment]
Somehow I suspected that there are 20 additional sub-cases. I'll have a look and also add an additional test

**Comment by bgeuken** [comment]
I've rebased the commit with the suggestions from Adrian. Please review again.

**Comment by bgeuken** [comment]
@adrianschroeter I've rebased the commit with your suggestions. Please review again.

**Comment by bgeuken** [comment]
@adrianschroeter As discussed I reverted the change for the configuration setting. One last review?

**Comment by hennevogel** [comment]
:fire: :hankey:

**Pull request merged**
