### PR TITLE
Update user fake pw creation

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by marcus-h** [comment]
> diff --git a/src/api/spec/models/user_spec.rb b/src/api/spec/models/user_spec.rb
> index 6eb5436..edb4a13 100644
> --- a/src/api/spec/models/user_spec.rb
> +++ b/src/api/spec/models/user_spec.rb
> @@ -273,6 +273,10 @@
>        let(:user) { User.create_user_with_fake_pw!({ login: 'tux', email: 'some@email.com' }) }
>  
>        it 'creates a user with a fake password' do
> +        expect(user.password).not_to eq(User.create_user_with_fake_pw!({ login: 'tux2', email: 'some@email.com' }))

Hmm aren't you comparing user.password with a user object?

(Btw., why is it important that the "fake passwords" differ?)

**Comment by bgeuken** [comment]
ouch, you are rightXD

**Comment by bgeuken** [comment]
> marcus-h commented an hour ago
> (Btw., why is it important that the "fake passwords" differ?)

@marcus-h So that the passwords are at least not identical. In case that someone manage to decrypt one of them he would just have access to one account, not all.

But testing this is indeed a bit fuzzy.

**Comment by bgeuken** [comment]
Fixed the test @ChrisBr mind to have a second look?

**Pull request merged**
