### PR TITLE
[doc] Add SUPPORT file

### PR DESCRIPTION
**Pull request by Ana06**
Linked when creating the first PR in Github. :bowtie: :green_heart: 

Closes https://github.com/openSUSE/open-build-service/issues/4486.

### CODE REVIEW

**Comment by Ana06** [comment]
@openSUSE/open-build-service does someone come up with something else we should add here? :thinking:

**Comment by adrianschroeter** [comment]
Hm, could you just point to our official page for this? It includes also commercial consulting option...

http://openbuildservice.org/support/

**Comment by bgeuken** [comment]
This is just shown when someone opens his first PR. I don't think we have to link to consultants or our docu from there.

**Comment by adrianschroeter** [comment]
On Freitag, 23. Februar 2018, 17:26:12 CET wrote Björn Geuken:
> This is just shown when someone opens his first PR. I don't think we have to link to consultants or our docu from there.

true, but isn't too late to ask for development support then?

(no strong opinion here though)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by marcus-h** [comment]
On 2018-02-23 08:04:10 -0800, Ana María Martínez Gómez wrote:
> Linked when creating the first PR in Github. :bowtie: :green_heart: 
> 
> Closes https://github.com/openSUSE/open-build-service/issues/4486.
> You can view, comment on, or merge this pull request online at:
> 

> diff --git a/SUPPORT.md b/SUPPORT.md
> new file mode 100644
> index 0000000000..41adc9f7e3
> --- /dev/null
> +++ b/SUPPORT.md
> @@ -0,0 +1,18 @@
> +# Do you need help?
> +
> +If you find something that doesn't work properly, you can
> +[open an issue](https://github.com/openSUSE/open-build-service/issues/new)
> +to let us now.
> +

Hmm I'm not sure if this is really helpful (exaggeration: in the worst
case this "discourages" the potential contributor and she files an issue
instead of the PR). Additionally, if someone is going to create a PR,
we can assume (IMHO) the she knows where to file an issue. Instead, add
something "motivating" along these lines:

Thanks a lot for your contribution. We will try to review your
patch ASAP. In case of further questions, feel free to contact us
at...

(Just an idea...)

**Comment by Ana06** [comment]
@marcus-h 

> Thanks a lot for your contribution. We will try to review your
patch ASAP. In case of further questions, feel free to contact us
at...

I think that `Thanks a lot for your contribution` doesn't apply, as they will read this before contributing. But I think I get your point about adding something more motivating. Please re review it :wink:

**Comment by marcus-h** [comment]
On 2018-03-05 02:00:20 -0800, Ana María Martínez Gómez wrote:
> > Thanks a lot for your contribution. We will try to review your
> patch ASAP. In case of further questions, feel free to contact us
> at...
> 
> I think that `Thanks a lot for your contribution` doesn't apply, as they will read this before contributing. But I think I get your point about adding something more motivating. Please re review it :wink: 
> 
Nice! Some minor, minor remarks

> +You can also contact every of us directly. 

each of us? (Btw., almost all sentences in this paragraph start with
"You can" (but feel free to leave it as it is).)

> +If you find something that doesn't work properly, you can also

For consistency, we should avoid the contraction ("does not" instead of
"doesn't").

> +[open an issue](https://github.com/openSUSE/open-build-service/issues/new)
> +to let us now.

know

**Comment by Ana06** [comment]
@marcus-h changes made! Thanks for the review :bouquet:

**Comment by marcus-h** [comment]
On 2018-03-06 09:39:57 +0000, Ana María Martínez Gómez wrote:
> @marcus-h changes made! Thanks for the review :bouquet: 
> 
Perfect!

**Pull request merged**
