### PR TITLE
[api] add index to events sent_mail

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
@Ana06 we need it for debugging our speed problems on build.o.o (the 0.0 send us to the wrong direction friday evening)

**Comment by adrianschroeter** [comment]
erm, sorry, I spoke about the problems not having ActiveRecord times (solved in the package).

I applied this because mls noticed this to be a bottleneck and we need to see if it helps in production with our problems.

**Comment by bgeuken** [comment]
Shall we wait with merging this until it's verified that it solves the issue?

**Comment by adrianschroeter** [comment]
well, it solves the slow select problem for sure, just it might cause others ;) (like slowing down adding new events).
But that will pop up in the logs again

**Pull request merged**
