### PR TITLE
Avoid using brace expansion since the feature is not always available.

### PR DESCRIPTION
**Pull request by jberry-suse**
Breaks our CI on travis: openSUSE/openSUSE-release-tools#1639.

https://github.com/openSUSE/open-build-service/commit/6e4627680be065311a409b494010ae4e896f3a20#diff-52c976fc38ed2b4e3b1192f8a8e24cffL10

From what I understand brace expansion is not supported in sh, but in a variety of other shells like bash. On openSUSE systems `sh = bash`, but not so everywhere like travis.

I verified this works on travis by cloning the source branch for this PR in our CI. It would be nice if the OBS CI was expanded to exercise this docker bit as it seems to break on travis now and again.

Feel free to come up with a way to require/verify bash/expansion, but this seemed the most straight forward.

### CODE REVIEW

**Comment by jberry-suse** [comment]
Preferably merge sooner rather than later, otherwise I'll have to merge a temporary workaround to clone my branch instead of master.

**Comment by jberry-suse** [comment]
Mention original author in case he has some input. @dmarcoux

**Comment by ChrisBr** [comment]
@jberry-suse out of curiosity: Why are you running OBS in Travis?

**Comment by jberry-suse** [comment]
@ChrisBr our tools are heavily integrated with it's API and it is far more effective to load a running version and run the tools against it in a simulated workflow than rewriting OBS in mocks.

**Pull request merged**
