### PR TITLE
[api] move project meta actions to its own controller and make it REST

### PR DESCRIPTION
**Pull request by vpereira**
third iteration of source_controller refactoring. Now I moved the "project meta" related code from ```source_project_controller``` to its own controller ```source_project_meta_controller```. 
minispec and rspec suites were updated too.

### CODE REVIEW

**Comment by vpereira** [comment]
looks like travis pipeline is broken?

**Comment by vpereira** [comment]
thank you!

**Comment by coolo** [comment]
I think codeclimate wants you to enhance the refactoring by extracting functions. And there are indeed quite some low hanging fruits :)

**Comment by vpereira** [comment]
@coolo yes indeed, however I want now to change less code as possible, but break it in smaller controllers, add some controller specs,  make the routes resourceful and after that refactor the code. I hope that's ok!

**Comment by coolo** [comment]
Talk to codeclimate, I'm just telling you what she thinks :)

**Pull request merged**
