### PR TITLE
Disable IRC 'notifications' from travis

### PR DESCRIPTION
**Pull request by coolo**
They are just spam on the IRC channel

### CODE REVIEW

**Comment by hennevogel** [comment]
**require** is a strong word but I like them. Why do you think this is spam?

**Comment by coolo** [comment]
Well, I would *like* to have notifications if master or PRs failed, but this is creating notifications for every broken branch of every fork:

```
20:22 -!- rber [~raphael@139.82.178.78] has joined #opensuse-buildservice
20:23 -!- einar77_work is now known as einar77
20:23 -!- travis-ci [~travis-ci@ec2-54-225-1-141.compute-1.amazonaws.com] has joined #opensuse-buildservice
20:23 < travis-ci> coolo/open-build-service#1861 (timing_with_vcr - 6857fcd : Stephan Kulow): The build has errored.
20:23 < travis-ci> Change view : https://github.com/coolo/open-build-service/commit/6857fcd99068
20:23 < travis-ci> Build details : https://travis-ci.org/coolo/open-build-service/builds/409971786
20:23 -!- travis-ci [~travis-ci@ec2-54-225-1-141.compute-1.amazonaws.com] has left #opensuse-buildservice []
20:26 -!- travis-ci [~travis-ci@ec2-54-87-70-219.compute-1.amazonaws.com] has joined #opensuse-buildservice
20:26 < travis-ci> coolo/open-build-service#1860 (timing_without_vcr - 20e5941 : Stephan Kulow): The build has errored.
20:26 < travis-ci> Change view : https://github.com/coolo/open-build-service/compare/353c01bc8146^...20e59411d129
20:26 < travis-ci> Build details : https://travis-ci.org/coolo/open-build-service/builds/409971565
20:26 -!- travis-ci [~travis-ci@ec2-54-87-70-219.compute-1.amazonaws.com] has left #opensuse-buildservice []
20:29 -!- ^OvO^ [~SpAmBot@2409:4061:690:421e:1979:1c4e:2b8:9165] has quit [Quit: weed finish]
20:32 -!- bugfinder [~Thunderbi@p200300EDEF0DB100DE5360FFFE09A376.dip0.t-ipconnect.de] has joined #opensuse-buildservice
20:34 -!- travis-ci [~travis-ci@ec2-54-211-183-233.compute-1.amazonaws.com] has joined #opensuse-buildservice
20:34 < travis-ci> coolo/open-build-service#1862 (timing_with_vcr - a7a335b : Stephan Kulow): The build passed.
20:34 < travis-ci> Change view : https://github.com/coolo/open-build-service/compare/6857fcd99068...a7a335b64069
20:34 < travis-ci> Build details : https://travis-ci.org/coolo/open-build-service/builds/409972211
20:34 -!- travis-ci [~travis-ci@ec2-54-211-183-233.compute-1.amazonaws.com] has left #opensuse-buildservice []
20:45 -!- adrianS [~adrian@ipbcc3dd71.dynamic.kabel-deutschland.de] has joined #opensuse-buildservice
20:45 -!- adrianS [~adrian@ipbcc3dd71.dynamic.kabel-deutschland.de] has quit [Changing host]
20:45 -!- adrianS [~adrian@opensuse/member/AdrianSuSE] has joined #opensuse-buildservice
20:46 -!- bugfinder [~Thunderbi@p200300EDEF0DB100DE5360FFFE09A376.dip0.t-ipconnect.de] has quit [Quit: bugfinder]
20:48 -!- travis-ci [~travis-ci@ec2-54-87-70-219.compute-1.amazonaws.com] has joined #opensuse-buildservice
20:48 < travis-ci> bgeuken/open-build-service#2735 (cleanup_staging_controller - a92a8c2 : Björn Geuken): The build was fixed.
20:48 < travis-ci> Change view : https://github.com/bgeuken/open-build-service/compare/7f4a46ba31bf...a92a8c205348
20:48 < travis-ci> Build details : https://travis-ci.org/bgeuken/open-build-service/builds/409982164
20:48 -!- travis-ci [~travis-ci@ec2-54-87-70-219.compute-1.amazonaws.com] has left #opensuse-buildservice []
20:48 -!- jimklimov [~jimklimov@ip-86-49-244-239.net.upcbroadband.cz] has joined #opensuse-buildservice
20:49 -!- niiko [~stOrymake@2409:4061:690:421e:d5e4:cd42:ed81:da77] has joined #opensuse-buildservice
20:51 -!- travis-ci [~travis-ci@ec2-54-87-70-219.compute-1.amazonaws.com] has joined #opensuse-buildservice
20:51 < travis-ci> coolo/open-build-service#1863 (timing_without_vcr - f5cf21e : Stephan Kulow): The build has errored.
20:51 < travis-ci> Change view : https://github.com/coolo/open-build-service/compare/20e59411d129...f5cf21e7826e
20:51 < travis-ci> Build details : https://travis-ci.org/coolo/open-build-service/builds/409972459
20:51 -!- travis-ci [~travis-ci@ec2-54-87-70-219.compute-1.amazonaws.com] has left #opensuse-buildservice []
20:52 -!- Son_Goku [~King_InuY@fedora/ngompa] has quit [Quit: My MacBook has gone to sleep. ZZZzzz…]
20:52 -!- jimklimov [~jimklimov@ip-86-49-244-239.net.upcbroadband.cz] has quit [Read error: Connection reset by peer]
20:54 -!- jimklimov [~jimklimov@ip-86-49-244-239.net.upcbroadband.cz] has joined #opensuse-buildservice
20:56 -!- Son_Goku [~King_InuY@fedora/ngompa] has joined #opensuse-buildservice

**Comment by vpereira** [comment]
fine with me too.

**Comment by hennevogel** [comment]
fair enough

**Comment by dmarcoux** [comment]
@openSUSE/obs-frontend 

Should we also do the same for CircleCI? I would disable it because sometimes CircleCI fails with the error `Unable to connect to #opensuse-buildservice` before even starting to run specs/linters.

I would send a PR, but it's done in the web UI at https://circleci.com/gh/openSUSE/open-build-service/edit#hooks. 

Please vote on my comments with :+1: or :-1:

**Pull request merged**
