### PR TITLE
proxy_auth_mode testing

### PR DESCRIPTION
**Pull request by hennevogel**
This might be an option to test proxy mode. Let's discuss!

### CODE REVIEW

**Comment by hennevogel** [comment]
Hm if we want to be fair to travis we shouldn't create a whole TEST_SUITE for this...

**Comment by ChrisBr** [comment]
@hennevogel how long takes the additional suite?

**Comment by hennevogel** [comment]
@ChrisBr it's 2 tests + starting everything up again after the config change. The last run was around a minute...

**Comment by hennevogel** [comment]
Hey @openSUSE/open-build-service no opinions?

**Comment by mdeniz** [comment]
LGTM

**Pull request merged**
