### PR TITLE
Use update project on request delegation

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
I doubt the failures are caused by this commit, but something became flaky in minitest lately .... will try to repeat the local runs and see if I can trigger it ...

**Comment by hennevogel** [comment]
I restarted the build. Both test still fail in the same way.

**Comment by hennevogel** [comment]
I guess this is the relevant part of the test.log

[01c2706c-f4b4-46e1-9335-e60ab5aa35cd.log](https://github.com/openSUSE/open-build-service/files/5208323/01c2706c-f4b4-46e1-9335-e60ab5aa35cd.log)

**Comment by adrianschroeter** [comment]
rebased the commit and including the testsuite reliability fixes

**Review by hennevogel — APPROVED** [review]

**Pull request merged**
