### PR TITLE
Migrate Image Template to Bootstrap

### PR DESCRIPTION
**Pull request by DavidKang**
We migrate Image Template view to Bootstrap

#### Before
Screenshot_2019-05-16 Open Build Service(1)

#### After
Screenshot_2019-05-16 Open Build Service(3)

### CODE REVIEW

**Comment by hennevogel** [comment]
why the old icons?

**Comment by DavidKang** [comment]
Because they are coming from a file

**Comment by bgeuken** [comment]
There seems to be a problem when the appliance icons are not available:



It looks similar for the old UI, except that the text in the icon field does not overflow. That's why I didn't block the PR. But it would be nice if we could catch the not found errors and render a default image instead.
IIRC we do something like that for the comments already.

**Comment by DavidKang** [comment]
@bgeuken, could you review it again :smile_cat:

**Pull request merged**
