### PR TITLE
Create a default subscription for Decision-related events

### PR DESCRIPTION
**Pull request by danidoni**
We need to have everyone subscribed automatically to FavoredDecision and ClearedDecision events.

### CODE REVIEW

**Review by krauselukas — DISMISSED** [review]

**Review by krauselukas — CHANGES_REQUESTED** [review]
@danidoni I think you forgot to commit the timestamp change in the `schema.rb` file

**Review by saraycp — CHANGES_REQUESTED** [review]
Nobody is subscribed to Event::CreateReport in production right now.
I think we should do that in this data migration as well.
I double-checked if an admin can do it through the UI but they can't yet (Configuration > Notification).

**Comment by danidoni** [comment]
> @danidoni I think you forgot to commit the timestamp change in the `schema.rb` file

Yeah, I completely forgot!

**Comment by danidoni** [comment]
Depends on #15007

**Comment by danidoni** [comment]
> > @danidoni I think you forgot to commit the timestamp change in the `schema.rb` file
> 
> Yeah, I completely forgot!

Schema file updated. Please take a look again.

**Review by krauselukas — APPROVED** [review]

**Pull request merged**
