### PR TITLE
[webui] Use new DataTable class for user reviews

### PR DESCRIPTION
**Pull request by ChrisBr**
This is a leftover from #2680.

### CODE REVIEW

**Comment by ChrisBr** [comment]
@evanrolfe may have a look?

**Comment by evanrolfe** [comment]
LGTM (when travis passes)

**Comment by hennevogel** [comment]
@ChrisBr travis does not pass...

you shall not pass

**Comment by evanrolfe** [comment]
LGTM again (when travis passes)

**Pull request merged**
