### PR TITLE
[webui] Fixes to display of binary sources

### PR DESCRIPTION
**Pull request by LelCP**
Fixes to CSS as per #4525

### CODE REVIEW

**Comment by GitCop** [comment]
There are some things that can be improved in your commit messages :wink:

 * Commit: 3dd95bf68874762ce2df0819cb61f77ab8cebcbe
  * Commits must be in the following format: **%{type}%{description}**

Read about how we write commits at https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-write-proper-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by hennevogel** [comment]
@LelCP this is not about the title of the pull request on github but about the commit message. You can rewrite that by calling `git commit --amend` for instance...

**Comment by bgeuken** [comment]
@LelCP Sorry for the noise. You can ignore the GitCop messages for now. We are just testing this plugin :blush:

**Comment by LelCP** [comment]
Nah, I will fix that, I also thought I could just edit with Github's interface, not such luck ;)

**Comment by hennevogel** [comment]
@LelCP usually when we are doing interface changes we attach a screenshot to the PR. Can you do that? :-)

**Comment by LelCP** [comment]
Yes, of course, here you go:
Screenshot

**Comment by bgeuken** [comment]
Let's ship it :ship: And thanks again:-)

**Comment by coolo** [comment]
@Ana06 puedes tener tu regla de vuelta. Gracias por la solución alternativa :heart_decoration:

**Pull request merged**
