### PR TITLE
Stop using chunkypng and sprite-factory

### PR DESCRIPTION
**Pull request by dmarcoux**
In order to test this locally, add the `sponsors` to your `development` environment in `src/api/config/options.yml`. It would be something like this, which I took from our production environment:

```
development:
  <<: *default
  (other keys... )
  sponsors:
  - name: SUSE
    description: Enterprise Linux you can rely on.
    icon: sponsor_suse
    url: http://www.suse.com
  - name: AMD
    description: Enabling today. Inspiring tomorrow.
    icon: sponsor_amd
    url: http://www.amd.com/
  - name: B1 Systems
    description: Linux / Open Source Consulting, Training, Development & Support
    icon: sponsor_b1-systems
    url: http://www.b1-systems.de/en/homepage/
  - name: Heinlein Support
    description: We provide Knowledge and Experience
    icon: sponsor_heinlein
    url: https://www.heinlein-support.de/
  - name: applied micro
    description: Build the future of ARMv8 on Applied Micro
    icon: sponsor_apm
    url: https://www.apm.com
```

### CODE REVIEW

**Comment by dmarcoux** [comment]
I will remove chunkypng and sprite-factory in the following PR.

**Comment by vpereira** [comment]
[nitpick] I would prefer if I didn't have to see sponsor ads in the development environment

**Comment by dmarcoux** [comment]
> [nitpick] I would prefer if I didn't have to see sponsor ads in the development environment

I've done nothing regarding this in this PR and I won't in the following PR removing chunkypng and sprite-factory.

I'll probably send this in a separate PR so we can discuss about this.

**Comment by dmarcoux** [comment]
@saraycp Please have another look.

**Comment by danidoni** [comment]
:ship:it!

**Pull request merged**
