### PR TITLE
Allow changing repositories for package maintainer

### LINKED ISSUE #8110: Changing repositories not possible if not project maintainer
# Issue Description
I can't enable/disable builds anymore at the Repositories page of packages, e.g. https://build.opensuse.org/repositories/devel:languages:python/python-Cerberus
Clicking on the icons has no result.
In the browser's javascript console I see:
14:17:56.517 SyntaxError: An invalid or illegal string was specified commandline_frame.js:15463
    listenForCounters perf.ts:167
    ts commandline_frame.ts:379
    Webpack 3

Expected Result
============
it works

How to Reproduce
===============
1. Go to a package you are allowed to edit
2. Click on Repositories
3. Click any icon to enable/disable builds

### PR DESCRIPTION
**Pull request by eduardoj**
Allow a user to enable or disable the repositories of a package he or she is mantainer of.

Fixes #8110.

### CODE REVIEW

**Comment by eduardoj** [comment]
> specs?

I'm working on it.

**Comment by eduardoj** [comment]
@hennevogel, I had a look, and tried to use the policy of a repository, but it didn't work because there isn't any relationship between a repository and a package.

We can refactor this change and add tests later on.

**Comment by vpereira** [comment]
> @hennevogel, I had a look, and tried to use the policy of a repository, but it didn't work because there isn't any relationship between a repository and a package.
> 
> We can refactor this change and add tests later on.

please open an issue for that, that we don't forge it, and then we can approve this PR.

**Comment by eduardoj** [comment]
> please open an issue for that, that we don't forge it, and then we can approve this PR.

Created: #8186.

**Pull request merged**
