### PR TITLE
[doc] typo in comment

### PR DESCRIPTION
**Pull request by jnweiger**
[doc] spelling ...

### CODE REVIEW

**Comment by ChrisBr** [comment]
Please fix the commit message error:

```
Commit Subject Prefix Error. Use: /\A(?!\s)(?:Merge|Revert|Update|Upgrade|\[api\]|\[backend\]|\[ci\]|\[dist\]|\[doc\]|\[frontend\]|\[webui\])+ \S+/.
```

**Comment by jnweiger** [comment]
Is there plain english instructions for the syntax of the subject line? I deciphered the regexp and added a '[doc] ' in front. But it does not help.

**Comment by marcus-h** [comment]
On 2017-10-18 16:13:33 +0000, Jürgen Weigert wrote:
> Is there plain english instructions for the syntax of the subject line? I deciphered the regexp and added a '[doc] ' in front. But it does not help.
> 
Hmm this check is about the summary line of your commit, which
is currently "spelling...". I think you just adjusted the
title/summary/whatever it is called of this PR itself.

**Comment by eduardoj** [comment]
> Is  there plain english instructions for the syntax of the subject line? I deciphered the regexp and added a '[doc] ' in front. But it does not help.

There is a section in the contributing guide for that: https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-write-proper-commit-messages

Thanks for your contribution!

**Comment by eduardoj** [comment]
Hm... Changing the comment of the pull request to `[doc] typo in comment` is not enough. You have to change the comment of your commit message to `[doc] spelling...`.

**Comment by jnweiger** [comment]
Seems the trivial things are becoming harder and harder. I have no clue what to do. Found another pencil in the gui and added another [doc] -- hoping for the best.

**Comment by marcus-h** [comment]
On 2017-10-20 17:40:47 +0000, Jürgen Weigert wrote:
> Seems the trivial things are becoming harder and harder. I have no clue what to do. Found another pencil in the gui and added another [doc] -- hoping for the best.
> 
The commit message itself need to be adjusted:
- cd <your checkout>
- git commit --amend
  # add the [doc] prefix
- git push --force <your remote etc.>

This should do the trick.

**Comment by jnweiger** [comment]
added the {doc] thing with amend, It autoclosed. and I the reopen button is greyed out.

**Pull request closed without merging**
