### PR TITLE
[docu] Remove command from readme that is handled by package spec file

### PR DESCRIPTION
**Pull request by bgeuken**
The obs-api package is already setting correct ownership

### CODE REVIEW

**Comment by hennevogel** [comment]
Please also adopt the headline then

**Comment by bgeuken** [comment]
done

**Comment by hennevogel** [comment]
Sorry for not being clear. The headline of the section in the readme you change...

**Comment by bgeuken** [comment]
Ahh, I completely overlooked this. Thanks

**Comment by hennevogel** [comment]
:+1:

**Pull request merged**
