### PR TITLE
Release targets ng continue

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
IMHO the pull request is fine. Just noticed again that the webui assumes that only one patchinfo is inside of an incident. Maybe we should add a test case with two patchinfos just to ensure that we do not crash. Or showing some warning that this is not supported by the webui.

**Comment by bgeuken** [comment]
Ja, there are some inconsistencies around patchinfos, like what you mentioned or that parts of the code assume patchinfos are always named '_patchinfo'. I am thinking about changing the Patchinfo class a bit. Splitting backend and frontend related code.

**Comment by adrianschroeter** [comment]
'_patchinfo' is a correct assumption, the backend is only building patchinfos from this file. This file is also classifing the build type as patchinfo. But the package container name can be chosen. "patchinfo" is just often used.

**Comment by bgeuken** [comment]
@openSUSE/open-build-service please review

**Comment by ChrisBr** [comment]
Except my comments, LGTM :+1:

**Comment by adrianschroeter** [comment]
do we need to take the travis error serious?

**Comment by bgeuken** [comment]
Yes, I am in the middle of rebasing.Just got interrupted by some other stuff. Give me a minute

**Pull request merged**
