### PR TITLE
Prevent crashes for access-protected projects/packages

### LINKED ISSUE #13636: [production][delayed_job#SendEventEmailsJob] Project not found: openSUSE:Factory:openh264
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/63b5742784bf466767ed5574)
# Project not found: openSUSE:Factory:openh264 #
### Where ###
delayed_job#SendEventEmailsJob

### Occured ###
Jan 04 12:42pm

### Similar ###
500

## Params ##
~~~
{
  &quot;active_job&quot; =&gt; {
    &quot;arguments&quot; =&gt; [],
    &quot;enqueued_at&quot; =&gt; &quot;2023-01-04T12:42:09Z&quot;,
    &quot;exception_executions&quot; =&gt; {},
    &quot;executions&quot; =&gt; 0,
    &quot;job_class&quot; =&gt; &quot;SendEventEmailsJob&quot;,
    &quot;job_id&quot; =&gt; &quot;cc254b65-3e37-4061-aeb7-50cd7035c78b&quot;,
    &quot;locale&quot; =&gt; &quot;en&quot;,
    &quot;priority&quot; =&gt; nil,
    &quot;provider_job_id&quot; =&gt; nil,
    &quot;queue_name&quot; =&gt; &quot;mailers&quot;,
    &quot;timezone&quot; =&gt; &quot;UTC&quot;
  },
  &quot;attempts&quot; =&gt; 0,
  &quot;failed_at&quot; =&gt; nil,
  &quot;handler&quot; =&gt; &quot;--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: SendEventEmailsJob\n  job_id: cc254b65-3e37-4061-aeb7-50cd7035c78b\n  provider_job_id: \n  queue_name: mailers\n  priority: \n  arguments: []\n  executions: 0\n  exception_executions: {}\n  locale: en\n  timezone: UTC\n  enqueued_at: &#39;2023-01-04T12:42:09Z&#39;\n&quot;,
  &quot;id&quot; =&gt; 989764442,
  &quot;last_error&quot; =&gt; nil,
  &quot;locked_at&quot; =&gt; &quot;2023-01-04T12:42:14.000Z&quot;,
  &quot;locked_by&quot; =&gt; &quot;delayed_job.1020 host:api pid:4596&quot;,
  &quot;priority&quot; =&gt; 0,
  &quot;queue&quot; =&gt; &quot;mailers&quot;,
  &quot;run_at&quot; =&gt; &quot;2023-01-04T12:42:09.000Z&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
234:  app/models/project.rb -> **get_by_name**
147:  app/models/package.rb -> **internal_get_project**
164:  app/models/package.rb -> **get_by_project_and_name**
23:  app/models/event/relationship.rb -> **notifiable_id**
8:  app/models/event/relationship.rb -> **parameters_for_notification**
56:  app/services/notification_service/notifier.rb -> **notifiable_exists?**
48:  app/services/notification_service/notifier.rb -> **create_notification?**
41:  app/services/notification_service/notifier.rb -> **create_notification_per_subscription**
33:  app/services/notification_service/notifier.rb -> **block (2 levels) in call**
32:  app/services/notification_service/notifier.rb -> **each**
32:  app/services/notification_service/notifier.rb -> **block in call**
31:  app/services/notification_service/notifier.rb -> **each**
31:  app/services/notification_service/notifier.rb -> **call**
13:  app/jobs/send_event_emails_job.rb -> **block in perform**
88:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/relation/delegation.rb -> **each**
88:  /GEM_ROOT/gems/activerecord-7.0.4/lib/active_record/relation/delegation.rb -> **each**
7:  app/jobs/send_event_emails_job.rb -> **perform**
59:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/execution.rb -> **block in _perform_job**
118:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **block in run_callbacks**
322:  /GEM_ROOT/gems/i18n-1.12.0/lib/i18n.rb -> **with_locale**
9:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/translation.rb -> **block (2 levels) in &lt;module:Translation&gt;**
127:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **instance_exec**
127:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **block in run_callbacks**
66:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/core_ext/time/zones.rb -> **use_zone**
9:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/timezones.rb -> **block (2 levels) in &lt;module:Timezones&gt;**
127:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **instance_exec**
127:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **block in run_callbacks**
138:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
58:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/execution.rb -> **_perform_job**
20:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/instrumentation.rb -> **_perform_job**
46:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/execution.rb -> **perform_now**
14:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/instrumentation.rb -> **block in perform_now**
25:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/instrumentation.rb -> **block in instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
206:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/notifications.rb -> **instrument**
35:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/instrumentation.rb -> **instrument**
14:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/instrumentation.rb -> **perform_now**
18:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/logging.rb -> **block in perform_now**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb -> **tagged**
25:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/logging.rb -> **tag_logger**
18:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/logging.rb -> **perform_now**
24:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/execution.rb -> **block in execute**
118:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **block in run_callbacks**
54:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/railtie.rb -> **block (4 levels) in &lt;class:Railtie&gt;**
92:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb -> **wrap**
72:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/reloader.rb -> **block in wrap**
92:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb -> **wrap**
71:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/reloader.rb -> **wrap**
53:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/railtie.rb -> **block (3 levels) in &lt;class:Railtie&gt;**
127:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **instance_exec**
127:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **block in run_callbacks**
138:  /GEM_ROOT/gems/activesupport-7.0.4/lib/active_support/callbacks.rb -> **run_callbacks**
22:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/execution.rb -> **execute**
47:  /GEM_ROOT/gems/activejob-7.0.4/lib/active_job/queue_adapters/delayed_job_adapter.rb -> **perform**
81:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb -> **block in invoke_job**
10:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/delayed_job.rb -> **block (2 levels) in &lt;class:Airbrake&gt;**
79:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block (2 levels) in add**
61:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block in initialize**
79:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block in add**
66:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **run_callbacks**
78:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb -> **invoke_job**
231:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block (2 levels) in run**
189:  /GEM_ROOT/gems/timeout-0.3.1/lib/timeout.rb -> **block in timeout**
196:  /GEM_ROOT/gems/timeout-0.3.1/lib/timeout.rb -> **timeout**
231:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block in run**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
230:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **run**
313:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block in reserve_and_run_one_job**
61:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block in initialize**
66:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **run_callbacks**
313:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **reserve_and_run_one_job**
214:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block in work_off**
213:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **times**
213:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **work_off**
176:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block (4 levels) in start**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
175:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block (3 levels) in start**
61:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block in initialize**
66:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **run_callbacks**
174:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block (2 levels) in start**
173:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **loop**
173:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **block in start**
7:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/plugins/clear_locks.rb -> **block (2 levels) in &lt;class:ClearLocks&gt;**
79:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block (2 levels) in add**
61:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block in initialize**
79:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **block in add**
66:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb -> **run_callbacks**
172:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/worker.rb -> **start**
137:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/command.rb -> **run**
125:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/command.rb -> **block in run_process**
277:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **block in start_proc**
84:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/daemonize.rb -> **call_as_daemon**
281:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **start_proc**
307:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **start**
56:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/controller.rb -> **run**
199:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons.rb -> **block in run_proc**
124:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/cmdline.rb -> **catch_exceptions**
198:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons.rb -> **run_proc**
123:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/command.rb -> **run_process**
98:  /GEM_ROOT/gems/delayed_job-4.1.11/lib/delayed/command.rb -> **daemonize**
5:  script/delayed_job.api.rb -> **&lt;top (required)&gt;**
58:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **load**
58:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **kernel_load**
23:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **run**
486:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **exec**
27:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb -> **run**
127:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb -> **invoke_command**
392:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb -> **dispatch**
31:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **dispatch**
485:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb -> **start**
25:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **start**
48:  /usr/lib64/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle -> **block in &lt;top (required)&gt;**
120:  /usr/lib64/ruby/3.1.0/bundler/friendly_errors.rb -> **with_friendly_errors**
36:  /usr/lib64/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle -> **&lt;top (required)&gt;**
25:  /usr/bin/bundle.ruby3.1 -> **load**
25:  /usr/bin/bundle.ruby3.1 -> **&lt;main&gt;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | delayed_job.1020 |
| HTTP_USER_AGENT |  |

### PR DESCRIPTION
**Pull request by dmarcoux**
Fixes #13636

Co-authored-by: Dany Marcoux <dmarcoux@suse.com>
Co-authored-by: Lukas Krause <lkrause@suse.de>

### CODE REVIEW

**Comment by hennevogel** [comment]
Some form of test case would be nice I guess?

**Comment by dmarcoux** [comment]
We forgot to consider these lines which rely on a user session:

https://github.com/openSUSE/open-build-service/blob/51acec8a4e1ec15291767da23cfe68e79b36183b/src/api/app/models/project.rb#L219-L223

In a delayed job when this code is called, we don't have a user session. So this implies refactoring this `Project#check_access?` method to pass the user. The method is used in a few areas of the code. We need to investigate further...

**Comment by dmarcoux** [comment]
Another attempt at fixing the issue by changing `NotificationService::Notifier#create_notification_per_subscription` with `User#run_as` like this:

```ruby
    def create_notification_per_subscription(subscription, channel)
      subscription.subscriber.run_as do
        return unless create_notification?(subscription.subscriber, channel)

        ALLOWED_CHANNELS[channel].new(subscription, @event).call
      end
    end
```

This doesn't work since the subscriber can sometimes be a group, so we would need to loop through all group members. This is quickly getting messy and inefficient.

**Comment by dmarcoux** [comment]
So the remaining solution is to avoid sending notifications for access-protected projects/packages. Notifications weren't sent for them, since this is obviously broken, so this isn't like we remove some functionality.

**Review by saraycp — APPROVED** [review]

**Pull request merged**
