### PR TITLE
Adding alternative port for rsync staging server

### PR DESCRIPTION
**Pull request by doccaz**
This patch allows one to specify a different TCP port for the RSYNCD server used for the publisher. This was done in order to circumvent a firewall restriction on a local OBS installation for a customer.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
couldn't you just specify the port in the url?
`
 our $stageserver = 'rsync://127.0.0.1:873/put-repos-main`

**Comment by doccaz** [comment]
Rsync expects the port to be passed via --port parameter. It didn't accept the port in the URL, I tried that.  It confuses the port with part of the share name (which begins with ::).

**Comment by hennevogel** [comment]
@doccaz please prefix your commit with the label, not the title of the pull request in github

**Comment by doccaz** [comment]
Adrian,
If I use the rsync://mystageserver:443 format in the $stageserver variable, bs_publish executes this:

>  rsync -ar0 --include=*.rpm --include=*.deb --include=*.pkg.tar.gz --include=*.pkg.tar.xz --include=*/ --exclude=* --timeout 7200 --files-from=- /srv/obs/repos mystageserver:443::reposync

... which in turn calls this:
> ssh mystageserver rsync --server -logDtprRe.iLsC --timeout=7200 . 443::reposync

Whereas with the --port parameter it'd execute:
> rsync -ar0 --include=*.rpm --include=*.deb --include=*.pkg.tar.gz --include=*.pkg.tar.xz --include=*/ --exclude=* --timeout 7200 --port=443 --files-from=- /srv/obs/repos mystageserver::reposync

I agree that rsync://mystageserver:443 should work, but the extra ":" is hardcoded on the qsystem() call.

**Comment by doccaz** [comment]
The failing check doesn't appear to be related to my changes. Do I need to do anything else?

**Comment by doccaz** [comment]
Superseded by #4627 .

**Pull request closed without merging**
