### PR TITLE
Fix smoke tests

### PR DESCRIPTION
**Pull request by M0ses**
Without this patch only a part of the string 'openSUSE.org:openSUSE:Tools'
gets passed to the backend, which quits with a 404 from the remote side.

This behavior is non-determenistic.

SEE ALSO:
teamcapybara/capybara#1890

Fix taken from here:

teamcapybara/capybara#1890 (comment)

This patch

* adds a sleep after clicking "Branch existing project" before entering the strings
  to give jQuery the time to complete the animation
* sends the strings char by char to avoid race conditions with autocompletion

### CODE REVIEW

**Comment by coolo** [comment]
don't go this route. Disable animations and wait for popups to appear instead

**Comment by eduardoj** [comment]
> don't go this route. Disable animations and wait for popups to appear instead

Yes, something like [this](https://github.com/openSUSE/open-build-service/blob/master/src/api/spec/features/webui/search_spec.rb#L27).

**Comment by M0ses** [comment]
Working on your suggestions - needs to be squashed when done

**Comment by M0ses** [comment]
commits squashed, ready to merge from my POV

**Pull request merged**
