### PR TITLE
ruby31 fixes

### PR DESCRIPTION
**Pull request by hennevogel**
See https://github.com/ruby/uri/commit/61c6a47ebf1f2726b60a2bbd70964d64e14b1f98

### CODE REVIEW

**Review by vpereira — CHANGES_REQUESTED** [review]
Please squash the commits before merging it

**Comment by vpereira** [comment]
@hennevogel you just ignored my change request and merged it?

**Comment by dmarcoux** [comment]
The commits were merged into this other PR, so it's still up to review: https://github.com/openSUSE/open-build-service/pull/12302

**Comment by hennevogel** [comment]
No I pushed to another branch. You saw this is for ruby31 right? :)

**Pull request merged**
