### PR TITLE
[WIP] Remove bento icons except the sponsors ones

### PR DESCRIPTION
**Pull request by saraycp**
Remove most of the icons inside _assets/icons_ that were used by bento. Only keep an updated license file and the sponsor's logos.

Move _assets/icons/_ to _/assets/images/icons._

Modify the task _lib/tasks/sprites.rake_ and use it to re-generate _icons_sprite.png_ and its corresponding CSS file (_icons.scss_). They are created from the icons inside _assets/icons._

Before, the _icons_sprite.png_ contained all the bento icons:

icons_sprite

Now, the _icons_sprite.png_ only contains the sponsor's logos:

icons_sprite

The list of sponsors we want to show is set in _config/options.yml_ > _sponsors:_.

Is it time to update the list of sponsor's logos?  I checked in production and we are not showing the _IP-Exchange_ ones anymore. Should I remove them from _icons_sprite.png_?

### CODE REVIEW

**Comment by saraycp** [comment]
> Is it time to update the list of sponsor's logos? I checked in production and we are not showing the _IP-Exchange_ ones anymore. Should I remove them from _icons_sprite.png_?

@hennevogel

**Comment by hennevogel** [comment]
> Is it time to update the list of sponsor's logos?

No, this whole feature is a bit strange. Don't invest too much time into it.

**Comment by saraycp** [comment]
> > Is it time to update the list of sponsor's logos?
> 
> No, this whole feature is a bit strange. Don't invest too much time into it.

Ok! :+1:

**Comment by saraycp** [comment]
I'll open a new PR keeping minimal bento for obs_factory (old UI for Staging dashboard).
Sponsor's and a few more icons have to stay in the stripe image and its corresponding CSS.

**Pull request closed without merging**
