### PR TITLE
Add jshint rules

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@openSUSE/open-build-service Please review

**Comment by ChrisBr** [comment]
@bgeuken could you please add some description what jshint is?
- How do we see that we violate it?
- Is it included in travis?
- How can I run it locally?

**Comment by Ana06** [comment]
@ChrisBr 

> @bgeuken could you please add some description what jshint is?
> 
> - How do we see that we violate it?
> - Is it included in travis?
> - How can I run it locally?

we are using jshint since some months... it  runs already in Travis

**Comment by Ana06** [comment]
@bgeuken something is wrong, Travis is failling :sob:

**Comment by bgeuken** [comment]
> ChrisBr commented a day ago 
>
> @bgeuken could you please add some description what jshint is?
>
> * How do we see that we violate it?

Our test suite will fail.
> * Is it included in travis?

Yes. It's actually there since [November 2016](2a198209745ee2a426f027ad57a885ba73f85431). 
But given that we suddenly see jshint errors that were not enabled in this commit, I assume that jshint requires a .jshintrc file to work. Which seems weird, but...

btw the default .jshintrc [is here](https://github.com/jshint/jshint/blob/master/examples/.jshintrc]. Though this is not an official community style guide or such.
> * How can I run it locally?

Via ` jshint $file_or_directory ` or ` rake dev:lint `, but that runs all our linters

We probably should document all this. I am going to add something to our wiki.

**Pull request merged**
