### PR TITLE
[webui] Fix format_projectname for home:foo

### PR DESCRIPTION
**Pull request by andreas-schwab**
Abbreviate home:foo as ~foo instead of ~foo:foo.

### CODE REVIEW

**Comment by coolo** [comment]
unit tests to the rescue!

**Comment by andreas-schwab** [comment]
I don't know how to create a test case.

**Comment by bgeuken** [comment]
No problem. I'll add a test for it.

Thanks much for the patch

**Comment by bgeuken** [comment]
That's the test: 3766c7e

**Pull request merged**
