### PR TITLE
Show user state on user's page, only for admin users

### PR DESCRIPTION
**Pull request by eduardoj**
Before:

Screenshot from 2024-01-29 14-19-06

After:

Screenshot from 2024-01-29 14-18-42

### CODE REVIEW

**Comment by danidoni** [comment]
What about using [badges](https://getbootstrap.com/docs/5.3/components/badge/) for the user state?

**Comment by eduardoj** [comment]
> What about using [badges](https://getbootstrap.com/docs/5.3/components/badge/) for the user state?

I thought they could be mistaken with the user roles. So I didn't use them.

**Comment by danidoni** [comment]
> I thought they could be mistaken with the user roles. So I didn't use them.

But it says "State: " so it's kind of very clear what this is about, so I think it won't be confusing...

**Comment by eduardoj** [comment]
> But it says "State: " so it's kind of very clear what this is about, so I think it won't be confusing...

I particularly don't find any special benefit from using a badge for showing the value of a field when this field will have only one value. Badges could be used to show one value, but tend to be used to show multiple values. The page will also look more loaded, without that being need. This will be also a field that only administrators will see.

I still see more reasons against using a badge than in favor of using it. I hope I convinced you...

**Comment by danidoni** [comment]
> I still see more reasons against using a badge than in favor of using it. I hope I convinced you...

Alright, let it be like it is now and we can improve it later

**Review by danidoni — APPROVED** [review]

**Pull request merged**
