### PR TITLE
Test obs factory controllers (Distribution and Staging Project)

### PR DESCRIPTION
**Pull request by DavidKang**
We added some tests to cover the OBS Factory controllers

### CODE REVIEW

**Comment by DavidKang** [comment]
@hennevogel, @Ana06, @bgeuken and @coolo, please review it

**Comment by coolo** [comment]
I have no problem with it

**Comment by Ana06** [comment]
@Ana06

> @DavidKang aren't you too much author?? :rofl: :rofl: 
> 
image

Ouch! It was not @DavidKang, but @mdeniz :rofl:

**Comment by Ana06** [comment]
@DavidKang 

> @hennevogel, @Ana06, @bgeuken and @coolo, please review it

why do we need that many people reviewing this? :confused:

**Comment by Ana06** [comment]
@bgeuken @hennevogel more concerns? :smile:

**Pull request merged**
