### PR TITLE
Rename Leap DVD from openSUSE to Leap

### LINKED ISSUE #8608: staging dashboard timeout
https://build.opensuse.org/project/dashboard/openSUSE:Leap:15.2 times out always

### PR DESCRIPTION
**Pull request by lnussel**
https://progress.opensuse.org/issues/50465

closes #8608

### CODE REVIEW

**Comment by coolo** [comment]
As you make the strategy 15.2 specific by this, please also adopt src/api/app/models/obs_factory/distribution.rb#L203

**Comment by lnussel** [comment]
In order to make the dashboard work for 15.1 still? Sure could be done but there's no gain as the dashboard for 15.1 isn't needed anymore. The ports will do the rename as well.

**Comment by coolo** [comment]
No, just to avoid the same timeouts happening if someone (google bots are eager to be that someone) visits the 15.1 dashboard. She should get a 404 instead

**Comment by lnussel** [comment]
With that requirement my copy&paste ruby skills hit its limits

**Comment by coolo** [comment]
https://www.codecademy.com/learn/learn-ruby ? :smiling_imp:

**Comment by coolo** [comment]
Let me fix up the test suite

**Comment by coolo** [comment]
pushed the fixes into your branch

**Comment by lnussel** [comment]
thanks! just hit road blocks on product converter and libzypp side. holding back for now

**Pull request closed without merging**
