### PR TITLE
Authorize move_path

### PR DESCRIPTION
**Pull request by dmarcoux**
Additionally turn the after_action around and maintain a whitelist instead of a blacklist. This requires new methods authorized by default.

new_package and its dialog are just informal authorizations, so people do not even try to do this.

Co-authored-by: Henne Vogelsang <hvogel@opensuse.org>
Co-authored-by: Saray Cabrera Padrón <scabrerapadron@suse.de>
Co-authored-by: David Kang <dkang@suse.com>

### CODE REVIEW

**Comment by dmarcoux** [comment]
Debugging this is tricky... I cannot run the Docker setup on the 2.9 branch. I rebuilt the frontend Docker image, but it still doesn't work. I might need to rebuild the frontend-base too... It just takes a while.

**Comment by dmarcoux** [comment]
In the end, I had to clone the repository and start from scratch (so removing all Docker images/containers). It now works.

**Comment by vpereira** [comment]
@dmarcoux looks like one rspec is broken (restarted the job to check if it wasn't flickering), looks like its giving a 500 error

**Comment by dmarcoux** [comment]
@vpereira I know it's broken, I've been trying to fix this for 2 days now... I cannot reproduce it locally.

**Pull request merged**
