### PR TITLE
Preparing for Release for 2.7.3

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by ChrisBr** [comment]
@adrianschroeter please review!

**Comment by bgeuken** [comment]
@ChrisBr please fix the broken tests, and rubocop;-)

**Comment by adrianschroeter** [comment]
there are some more bugs fixed:

Changes:

* Compability with OBS 2.8 remote instances

Bugfixes:

* api: project meta data was corrupted after undelete
* api: raising access and sourceaccess permissions as admin is working again
* backend: Download on demand sync fixes
* webui: fixed revert to a specified source revision

**Comment by ChrisBr** [comment]
@hennevogel please review!

@adrianschroeter needed to cherry-pick also 7bad561, otherwise tests introduced in 7d2f8cb9d72c472a2516ec1f4788b10381de2b84 would fail!

**Comment by adrianschroeter** [comment]
ChrisBr: please don't pick 7bad561 , it is a behaviour change.

7d2f8cb needs a different backport then... I can have a look ...

**Comment by ChrisBr** [comment]
@adrianschroeter please do! These lines fail
```
post "/request/#{id4}?cmd=setincident&incident=#{incidentProject.gsub(/.*:/, '')}"
assert_response :success
```

line 563 in channel maintenance test. Problem is that the result is a ``403`` because maintenance project gets locked in ``create_post_permissions_hook``. But I have to less insights to decide if changing to 403 is fine or not ...

**Comment by adrianschroeter** [comment]
just drop this post command and the next one from the test case in 2.7. This is a non issue there.

**Comment by ChrisBr** [comment]
@adrianschroeter ok!

**Comment by ChrisBr** [comment]
@adrianschroeter done!

**Comment by hennevogel** [comment]
LGTM

**Pull request merged**
