### PR TITLE
Request#show: merge comments, history and reviews

### PR DESCRIPTION
**Pull request by coolo**
The current request#show has several problems and I'm trying to tackle the most obvious one here:
the reviews, their history and the comments aren't in a logic order in the page.

So I'm merging request history, review history, open reviews and comments in one list - so users understand what's going on and reviewers add their review comments where they see the question.

*Before*
screencapture-localhost-3000-request-show-2-2019-05-18-09_23_18

*After*
screencapture-localhost-3000-request-show-2-2019-05-18-09_21_53

This is a revival of the ideas I tried in #6225 and I'm not yet done, because I still need to add the superseded requests to the history and readd the box that has accept/decline/comment at the end.

But I wanted to create the draft pull request to discuss the idea (and secondarly the code)

### CODE REVIEW

**Comment by DimStar77** [comment]
> This is a revival of the ideas I tried in #6225 and I'm not yet done, because I still need to add the superseded requests to the history and readd the box that has accept/decline/comment at the end.

With this, it might go in the right direction. My first thought when seeing the new screenshot was

* oh now, now I have to find the various accept/decline boxes somewhere in the middle of a long comment - like - looking page.

This looks very much like the 'comments section'. Are comments / history interleaved together (I don't think the current screenshot shows comments)?

**Comment by coolo** [comment]
> > This is a revival of the ideas I tried in #6225 and I'm not yet done, because I still need to add the superseded requests to the history and readd the box that has accept/decline/comment at the end.
> 
> With this, it might go in the right direction. My first thought when seeing the new screenshot was
> 
> * oh now, now I have to find the various accept/decline boxes somewhere in the middle of a long comment - like - looking page.
> 
> This looks very much like the 'comments section'. Are comments / history interleaved together (I don't think the current screenshot shows comments)?

user_1 and user_2 are just commenting.

**Comment by coolo** [comment]
Well, if you have just one role in the request it's easy - there will only be one set of buttons.

And that bots abuse comments is something that needs to be fixed - and there plans for it already.

**Comment by vpereira** [comment]
@coolo  does it still make sense?

**Comment by coolo** [comment]
well, what makes sense in this world :)

It's an on-off-on project of mine, I will get back to it

**Comment by coolo** [comment]
Just for a little motivation why I want to work on this page - need to press 13 times page down to get to the approve button

screencapture-build-opensuse-org-request-show-726391-2019-08-28-19_08_42

**Comment by dmarcoux** [comment]
You could also press once on the `End` button.

**Comment by vpereira** [comment]
@coolo  does it still make sense?

**Comment by coolo** [comment]
yes

**Comment by vpereira** [comment]
> yes
@coolo ,

but you will have to adapt it to the master, since the whole webui2 code is gone, and you are still referencing to it (probably that's why there is no conflict). How do you want to tackle it?

**Comment by vpereira** [comment]
I'm closing this PR @coolo but to don't loose what you did already, I linked it to our backlog https://trello.com/c/hWWRRjoQ/5-collaboration-bsrequest-workflow-redesign

**Pull request closed without merging**
