### PR TITLE
[ci] Split up test_submit_request into seperate methods to make tests less error prone

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@adrianschroeter that fixes the last failing test when packaging OBS

**Comment by hennevogel** [comment]
Can you explain how this makes it less error prone? Timing?

**Comment by bgeuken** [comment]
Timing. But also by not having those scenarios depend on each other. We probably could also have re-visited the page after testing the clientside form validation. But having seperate tests for each funtionality seems to be the saner approach.

Packages built from this branch can be found here:
https://build.opensuse.org/package/show/home:bgeuken:branches:OBS:Server:Unstable/obs-server

**Comment by adrianschroeter** [comment]
problem is that this test case tries to create a project for a user which has already a home project in the fixtures. couldn't we do this with some new user or some which has not yet a home project?

**Comment by adrianschroeter** [comment]
merging since we have no building packages atm

**Comment by bgeuken** [comment]
@adrianschroeter The test with the problem with the home project we talked about earlier was fixed here: 14b0da541edb3b4e24e7b9a7d1c18e89c0a2ddc3

**Pull request merged**
