### PR TITLE
[webui][api] EventMailer views use local variables

### PR DESCRIPTION
**Pull request by evanrolfe**
... so that they can be re-used by other mailers (this is needed for the daily digest email).

### CODE REVIEW

**Comment by mdeniz** [comment]
AH!!!!!! stay! 3 Times in a row, don't merge more PRs that are conflicting with the RSS PLEASEEEEEE!!!!

**Comment by evanrolfe** [comment]
@mdeniz this is what github conflict resolution is for. there are only 3 conflicts and they are very simple to resolve:

https://github.com/openSUSE/open-build-service/pull/3248/conflicts

**Comment by evanrolfe** [comment]
This is also why its a good idea to keep PRs small. Your rss notifications pr contains lots of refactorings that could have already been merged by now. For example the `Token` stuff and the `Notification` changes - I am also waiting for the polymorphic notifications stuff to be merged barbecue I need it merged before I can complete the daily email stuff.

**Comment by mdeniz** [comment]
Don't worry that much is just a complain to myself 😈

**Pull request merged**
