### PR TITLE
Get rid of Webui::LoadBuildresults and ProjectController#package_buildresult

### PR DESCRIPTION
**Pull request by Ana06**
:bowtie:

### CODE REVIEW

**Comment by coolo** [comment]
It's even covered - even if unused :)

```
spec/controllers/webui/project_controller_spec.rb:          get :package_buildresult, params: { project: user.home_project }, xhr: true

**Comment by Ana06** [comment]
@coolo 

> It's even covered - even if unused :)

100% percent coverage of unsed code :stuck_out_tongue_winking_eye:

**Comment by coolo** [comment]
Coverage increased (+0.007%) to 90.749%

**Comment by Ana06** [comment]
@coolo 

> Coverage increased (+0.007%) to 90.749%

Covarage increased? :confused:

**Pull request merged**
