### PR TITLE
Avoid mismatching with different issue trackers

### PR DESCRIPTION
**Pull request by saraycp**
Having a `x.changes` file that contains a text like `- Fixes gh#cli/cli#1 issue.`, the only issue tracker that should match is the `gh` one, but not the `i` issue tracker.

The code is wrongly assuming that `i#1` coming from _gh#cli/cl**i#1**_ is an issue referenced in the `x.changes` file, but it shouldn't.
 
By setting word boundaries on the regular expression, we want to prevent the mismatches.

- `gh#cli/cli#1`
- `bcn#123445/boo#98487`

Closes https://github.com/openSUSE/open-build-service/issues/12031

### CODE REVIEW

**Comment by krauselukas** [comment]
@adrianschroeter @bugfinder I dont know how this is setup for the backend in production, I think you need to adjust the config/xml file that contains the issue_tracker regular expression for the backend in order to make this work https://github.com/openSUSE/open-build-service/blob/0723856ff7913d81bce7d6075451e0b8c8a6c5e5/src/backend/bs_srcserver#L3204

**Comment by dmarcoux** [comment]
It seems like the regex should always start and finish with `\b`. We should enforce this with a validation on the `IssueTracker` model.

**Comment by hennevogel** [comment]
And why do we do this in the regex column instead where we use that regex?

**Comment by krauselukas** [comment]
@hennevogel I can't only adapt the code to use the word boundary since the frontend is sending the issue tracker informations to the backend in a delay job https://github.com/openSUSE/open-build-service/blob/28b5bdf5f55269c2cc2db9631c35bf0169010b78/src/api/app/jobs/issue_tracker_write_to_backend_job.rb#L3 since the backend is creating the issues we have to send the correct regular expressions. Thats why we have to update the database... also just figured this out
@dmarcoux I added a validation to the issue tracker model to check for the word boundary in the future, please have a look :)

**Comment by krauselukas** [comment]
> @adrianschroeter @bugfinder I dont know how this is setup for the backend in production, I think you need to adjust the config/xml file on our production instances that contains the issue_tracker regular expression for the backend in order to make this work
> 
> https://github.com/openSUSE/open-build-service/blob/0723856ff7913d81bce7d6075451e0b8c8a6c5e5/src/backend/bs_srcserver#L3204

Overlooked that there is a delayed job to update the backend side, so no action required

**Comment by krauselukas** [comment]
I see have to adapt a couple of specs and minitest

**Comment by adrianschroeter** [comment]
it does not make much sense to enforce that the config must contain \b in start and end. If we want this, we should adapt the parser instead.

**Comment by adrianschroeter** [comment]
Not sure if we want to change this behaviour though, because it would also change the results of past changelog entries. Why should we support the writing of combining issues using slashes now?

**Comment by krauselukas** [comment]
> Not sure if we want to change this behaviour though, because it would also change the results of past changelog entries. Why should we support the writing of combining issues using slashes now?

Do you mean by combining issues something like this `foo#123/foo#456` ? This would currently result in two issues, so its already supported, the word boundary doesn't change this if I understand you correctly.

@adrianschroeter Since the parsing of the text is happening on the backend, can I pass this on to you to fix the issue?

**Comment by krauselukas** [comment]
@adrianschroeter just to be clear, what I want to prevent is that something like `gh#cli/cli#1` results in the creation of `gh#cli/cli#1`
and `i#1`

**Comment by krauselukas** [comment]
Closing this since it should be fixed on the parser on the backend

**Pull request closed without merging**
