### PR TITLE
[webui] show link information for a branched package with no update

### LINKED ISSUE #4916: webui may not show any hint that a package is a link/branch
Issue/Feature description
====================

webui is not showing package link information (links to on top right of package show page), if target is not existing target project.

This is the case when the package is not available at all or only available indirectly. This is the case for every branch from a stable distribution as long as no maintenance update has been shipped and therefore relative grave (Links to :Update, but source exists only via project link).

Expected result
============

We should always show the link information if it is defined in the source.

We may not want to make it a link if the target does not exist direct.

We may want to show additional information if target is not reachable at all.

How to Reproduce
===============
Branch any package from a stable distro where no maintenance update has been released. eg.  openSUSE:Leap:42.3:Update hello

Further information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

### PR DESCRIPTION
**Pull request by vpereira**
Fixes #4916

please @adrianschroeter  could you check it?

Co-authored-by: Ana María Martínez Gómez <ammartinez@suse.de>

### CODE REVIEW

**Comment by ChrisBr** [comment]
@vpereira could you please check the broken tests?

**Comment by Ana06** [comment]
@ChrisBr 

> @vpereira could you please check the broken tests?

All of them are `Timeout::Error` and taking into account that Travis does pass, it seems to me some configuration problem with CircleCI.

**Comment by Ana06** [comment]
@adrianschroeter any concern with this solution? :thinking:

**Comment by ChrisBr** [comment]
> All of them are Timeout::Error and taking into account that Travis does pass, it seems to me some configuration problem with CircleCI.

Would be anyway nice if sb could investigate as we plan to switch to Circle CI very soon!

**Comment by vpereira** [comment]
I ran it with SSH enabled and the backend server is dying. The last time it ran successfully was https://circleci.com/gh/openSUSE/open-build-service/429

**Comment by Ana06** [comment]
@ChrisBr 

> Would be anyway nice if sb could investigate as we plan to switch to Circle CI very soon!

I agree, but this is not related with the PR. @openSUSE/open-build-service it would be nice if someone review this PR :pray:

**Comment by coolo** [comment]
I guess it would help if travis wouldn't ignore the failures in rspec

**Comment by bgeuken** [comment]
> ChrisBr commented 6 hours ago
> All of them are Timeout::Error and taking into account that Travis does pass, it seems to me some configuration problem with CircleCI.Would be anyway nice if sb could investigate as we plan to switch to Circle CI very soon!

@ChrisBr @Ana06 I had a similar issue in my PR. It looks like in Circle CI the order of how the tests run (probably per test file) is different than in Travis.

**Comment by coolo** [comment]
I don't get what you're discussing - travis fails with the same errors. And so I assume do local tests.

**Comment by bgeuken** [comment]
Right, just noticed.

@vpereira You probably have to refresh the cassettes. If your tests rely on the backend you need to have [this switch](https://github.com/openSUSE/open-build-service/blob/master/src/api/spec/models/branch_package_spec.rb#L3) enabled while running the test.

@ChrisBr Looks like the recent Circle CI changes broke the travis test suite

**Comment by ChrisBr** [comment]
> Looks like the recent Circle CI changes broke the travis test suite

Huh?
I did not change anything regarding Travis
https://github.com/openSUSE/open-build-service/pull/5139/files

**Comment by ChrisBr** [comment]
Argh, this broke it:
https://github.com/openSUSE/open-build-service/pull/5144

Last command is now the rm which succeeds :/ Before the last command was of course the test command :cry:

**Comment by vpereira** [comment]
@ChrisBr maybe save the return from rspec (after run it save the $?) and then after the cleanup with mkdir, return the $? saved previously..

**Comment by ChrisBr** [comment]
https://github.com/openSUSE/open-build-service/pull/5151

I only remove it now outside of CI but your solution is maybe better

**Comment by ChrisBr** [comment]
@vpereira please rebase on master to see if Travis also fails now :+1:

**Comment by vpereira** [comment]
I rebased the master into this branch to make sure that travis fails!

There are two problems here:

a) rspec VCR ninjutsu (missing to regenerate some cassetes)
b) minitests fails, but some tests that I looked into are simply massaging the API and test the wrong "use case scenario" exactly what we fixed with this PR.  

we actually tested it manually branching package in different scenarios, via webui and osc and it was working as it should. I would like to wait for @adrianschroeter and talk with him about the minitests cases. Until there the "a" problem should be already solved :)

**Comment by vpereira** [comment]
analysing it further, the change would break the link between branched package and the update project. 
Closing it for now

**Pull request closed without merging**
