### PR TITLE
[RFC] [dist] Ubuntu Service Support

### PR DESCRIPTION
**Pull request by myungjoo**
I have been running OBS in my Ubuntu 14.04 machine and I wanted to share the service scripts (just slightly modified from the current scripts for the compatibility). Right now, OBS servers that were essential for my deployment are included.

Ubuntu /etc/init.d/ service files for OBS.
Tested and running at Ubuntu 14.04 / x86_64.

Signed-off-by: MyungJoo Ham myungjoo.ham@samsung.com

### CODE REVIEW

**Comment by hennevogel** [comment]
[[2] Merge PullRequest #1997](https://trello.com/c/p7rzO9wx/15-2-merge-pullrequest-1997)

**Comment by leemgs** [comment]
I have evaluated this PR on my own Ubuntu 16.04 X64 LTS in order to run all obs services automatically at boot time. This PR will be helpful for developers to run 'open-build-service'  services on Debian & Ubuntu distribution.

**Comment by leemgs** [comment]
The packaging project to build open-build-service packages for Debian/Ubuntu distribution was started  by debian community guys since Sep-17-2016. 
* Source Package: open-build-service (2.7.1-1)
  https://packages.debian.org/en/source/experimental/open-build-service

**Comment by adrianschroeter** [comment]
I am not really a fan of duplicating all init scripts. Since we want to move them to systemd services anyway we should maybe do this and verify that it works on SUSE and Debian together? What do you think about this?

**Comment by leemgs** [comment]
It is reasonable that obs have to move from init-sysv(run-level style) to systemd (target style) because most of the Linux distributions have already moved to systemd as a default init daemon. So, It will be best way that we append compatible systemd-style  services  running both openSUSE and Debian/Ubuntu ASAP.

**Comment by leemgs** [comment]
\CC: @sai-divvela @jerrynoid, Please take a look at this.

**Comment by adrianschroeter** [comment]
we just merged systemd init files. Have a look in dist/systemd/ for them.

I hope they work for you, since they should work on debian already.

**Comment by leemgs** [comment]
@adrianschroeter , Thanks a million.

**Pull request closed without merging**
