### PR TITLE
[api] fix release tracking special case

### PR DESCRIPTION
**Pull request by adrianschroeter**
when rpms are published into some repo where they also get published
as part of a rpm venv

If you haven't done so already, please read the CONTRIBUTING.md file to learn how we work and what we expect from all contributors.

https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by coolo** [comment]
you're based on some outdated master

**Comment by adrianschroeter** [comment]
Do I need to disable Layout/AlignHash check to allow align'd variable assignment? (it is really not readable without ...)

**Comment by coolo** [comment]
you can disable it for the block, yes

**Comment by coolo** [comment]
I don't think there is a way to change the options for a cop per code comment - because that would be the preferred solution here (as AlignHash can also align hashes as you prefer)

**Comment by hennevogel** [comment]
Can you just align the hash and be done with it? If we want to change this rule we can talk about it somewhere else.

**Comment by hennevogel** [comment]
@adrianschroeter ping

**Comment by adrianschroeter** [comment]
got merged into this pull request:

https://github.com/openSUSE/open-build-service/pull/7562

**Pull request closed without merging**
