### PR TITLE
[ci] update capybara and poltergeist

### PR DESCRIPTION
**Pull request by hennevogel**
As travis is getting more busy all the time, the occurance of
Capybara::Poltergeist::TimeoutError increased. Let's see if
an update of the test clickers works...

### CODE REVIEW

**Comment by Ana06** [comment]
It seems that it is still failing :disappointed:

**Comment by adrianschroeter** [comment]
seems not to help ;) Maybe increasing it way more and we trigger rspec test suite several times?

It may also be a random dead lock reported that way ....

**Comment by hennevogel** [comment]
Yeah I will investigate this further...

**Comment by hennevogel** [comment]
Updating seems to make this better. I've already updated the packages in `:Unstable` too.

**Comment by hennevogel** [comment]
[Fixing the flickering rspec test suite](https://trello.com/c/XBKqBiuV/85-fixing-the-flickering-rspec-test-suite)

**Pull request merged**
