### PR TITLE
Correct Rubocop Style/RegexpLiteral offences

### PR DESCRIPTION
**Pull request by saraycp**

### CODE REVIEW

**Comment by dmarcoux** [comment]
Could you split this up in smaller PRs? I think 2 PRs would already make this much easier to review. :slightly_smiling_face:

**Comment by saraycp** [comment]
> Could you split this up in smaller PRs? I think 2 PRs would already make this much easier to review. slightly_smiling_face

Sure!

**Comment by saraycp** [comment]
@dmarcoux, superseded by:

https://github.com/openSUSE/open-build-service/pull/10055
https://github.com/openSUSE/open-build-service/pull/10056
https://github.com/openSUSE/open-build-service/pull/10057
https://github.com/openSUSE/open-build-service/pull/10058

**Comment by dmarcoux** [comment]
Thank you @saraycp!

**Pull request closed without merging**
