### PR TITLE
Enable WordArray Rubocop cop

### PR DESCRIPTION
**Pull request by Ana06**
This cop can check for array literals made up of word-like strings, that are not using the `%w()` syntax. :bowtie:

### CODE REVIEW

**Comment by bgeuken** [comment]
What's wrong with using the array syntax, ["a", "b"]? At least for symbols it should be fine.

**Comment by Ana06** [comment]
@bgeuken 

> What's wrong with using the array syntax, ["a", "b"]? At least for symbols it should be fine.

for symbols? That is only affecting strings... :confused: 

And there is nothing wrong with the other syntax, it is a matter of consistency. And if we are going to be consistent in our application, why not choosing the default and being consistent with other projects as well? https://github.com/bbatsov/ruby-style-guide#percent-w

**Comment by evanrolfe** [comment]
I agree with Ana lets pick one way of writing arrays and stick with it so we can have some consistency here. 

As for whether we use '["a", "b"]' or '%w[a b]` I don't really care, just as long as we just pick one.

**Comment by bgeuken** [comment]
I am also all for using one way.

My remark to the symbols was came from a discussion we had because I was [asked](https://github.com/openSUSE/open-build-service/pull/3995) to already apply this cop.

That said, I prefer ["a", "b"], [1, 2], [:a, :b]

**Comment by Ana06** [comment]
@bgeuken 

> My remark to the symbols was came from a discussion we had because I was asked to already apply this cop.

What is discussed there doesn't make any sense :rofl: That's only for strings.

Ok, now that you now it is only for strings, can we take the default here?

**Comment by bgeuken** [comment]
>  Ana06 commented
>
> Ok, now that you now it is only for strings, can we take the default here?

No, see my previous [comment](https://github.com/openSUSE/open-build-service/pull/4004#issuecomment-336156504):-) I still like ["a"] better. And if we keep using the "Array" variant for anything else than strings, why wouldn't we allow it (having ["some_string"]) for strings?

**Comment by Ana06** [comment]
@bgeuken 

> No, see my previous comment:-) I still like ["a"] better. And if we keep using the "Array" variant for anything else than strings, why wouldn't we allow it (having ["some_string"]) for strings?

Because it is the default and we need consistency. Also, [Ruby style guide](https://github.com/bbatsov/ruby-style-guide#percent-w) is a community driven guide. If you don't like the rules, you should raise your concerns there. It would we great that instead of always discussing about Rubocop rules in OBS, all this discussions were moved to the Style Guide or Rubocop. It will save as plenty of time. And at the end the important thing is to have a default.


As we can keep the discussion for ever, @bgeuken are you fine with asking everybody else and take the one more people prefer?

So, @openSUSE/open-build-service what do you prefer the Rubocop default `%(a, b)` or `['a', 'b']`?

**Comment by DavidKang** [comment]
>   Rubocop default %(a, b) or ['a', 'b']?

This is not the same, I think you wanted to say `%w(a, b)`, but I don't have a strong opinion, just pick one.

**Comment by DavidKang** [comment]
@Ana06, please rebase 😸

**Comment by Ana06** [comment]
@DavidKang 

> This is not the same, I think you wanted to say %w(a, b), but I don't have a strong opinion, just pick one.

Yes, I just edited.

> @Ana06, please rebase 

When we agree on something, now, it makes no sense.

**Comment by DavidKang** [comment]
@ Ana06, but if you want a point of view I will prefer the default from rubocop.

**Comment by mdeniz** [comment]
If I have to choose then the ['a', 'b'] way. The % way I don't like it because there are too many possibilities with that notation that I don't have it clear what's going on at first sight (http://www.chrisrolle.com/blog/ruby-percentage-notations).

**Comment by eduardoj** [comment]
I prefer the Rubocop default `%(a, b)`. And from now on I would also prefer to follow Rubocop default rules.

**Comment by evanrolfe** [comment]
Maybe we need to take a vote on this? Also @Ana06 in this PR you are not using `%w()` syntax, you are using `%w[]`..

**Comment by evanrolfe** [comment]
I prefer `%w()` for no other reason than that it is whats in the ruby styleguide..

**Comment by Ana06** [comment]
@evanrolfe 

> Maybe we need to take a vote on this? Also @Ana06 in this PR you are not using %w() syntax, you are using %w[]..

Yes, sorry I wrote if wrong, corrected in my comment!

**Comment by Ana06** [comment]
@mdeniz 

> If I have to choose then the ['a', 'b'] way. The % way I don't like it because there are too many possibilities with that notation that I don't have it clear what's going on at first sight (http://www.chrisrolle.com/blog/ruby-percentage-notations).

Maybe you should raise this concerns in the **community** style guide/rubocop. :wink:

**Comment by ChrisBr** [comment]
I personally like ``['a'...]`` better but I don't have a strong opinion about that. I'm fine either way. If ``w%()`` is the recommend way by the community, maybe we should follow this recommendation. But as said, I don't really care :smile:

**Comment by Ana06** [comment]
and the winner is....

`%w[a, b]`: **5** (I am counting @ChrisBr and I am not pretty sure reading his comment)

`['a', 'b']`: **2**

And reading the comments I think it is clear that most people one to enable one of them to have an style rule here. So @bgeuken can you live with enabling the default? If we enable the other one, more people would be unhappy.. and we will end no enabling anything.... :sob:

**Comment by mdeniz** [comment]
@Ana06 I'm not going to talk to that comunity... I'm talking to our comunitiy... I don't like that. Why it should be prohibited? 

BTW, If I need to do something like this.. ['hello my' , 'world !'] with the %w notation... then I will need to do %w[hello\my world\ !] ...is that more readable?

**Comment by mdeniz** [comment]
BTW 

>I personally like ['a'...] better but I don't have a strong opinion about that. I'm fine either way. If w%() is the recommend way by the community, maybe we should follow this recommendation. But as said, I don't really care 😄

Doesn't mean he is in for the %w notation... he prefers the other, please don't pervert you own statistics 😈

**Comment by mdeniz** [comment]
Also, David's

> This is not the same, I think you wanted to say %w(a, b), but I don't have a strong opinion, just pick one.

He don't really care, so, don't count him

**Comment by mdeniz** [comment]
So, my statistics to the rescue 😸 :

@Ana06 %w
@bgeuken ['a'] 
@mdeniz ['a'] 
@evanrolfe %w
@ChrisBr ['a']
@eduardoj %w
@DavidKang ['a']

So, %w 3 votes, ['a'] 4 votes 🗡

**Comment by Ana06** [comment]
@mdeniz 

@DavidKang's last comment:
> @ Ana06, but if you want a point of view, I will prefer the default from rubocop.

and @ChrisBr 

> If ``w%()`` is the recommend way by the community, maybe we should follow this recommendation


@mdeniz  would have been nice that you ask me before you close this... :rage: 

So at the end we don't enable anything, and we don't have any style rule at all.  We have just partially rules enabled, which we don't disable but we also can not agree to enable. This is not the way.... We should at least agree on disabling it, currently it is still enabled but with offenses. Any way, this is the last Rubocop rule I try to enable in this project.. I fell wasting my time. @openSUSE/open-build-service maybe we should remove rubocop at all from the project...

And @bgeuken and @mdeniz we work in open source... If our language has a community driven style you don't agree with you should raise your concerns there...

**Comment by eduardoj** [comment]
> BTW,  If I need to do something like this.. `['hello my' , 'world !']` with the %w notation... then I will need to do `%w[hello\ my world\ !]` ...is that more readable?

You can do `%w[hello\ my world\ !]`, but you are not forced to. The cop only works with arrays of words, each element of the array is only one word. So if we enable the WordArray cop it will not prevent you from using `['hello my' , 'world !']`.

I hope that this can make you change your opion, @mdeniz.

**Comment by bgeuken** [comment]
\*back from being sick \*

> Ana06 commented 4 days ago
> @mdeniz
>
> If I have to choose then the ['a', 'b'] way. The % way I don't like it because there are too many possibilities with that notation that I don't have it clear what's going on at first sight (http://www.chrisrolle.com/blog/ruby-percentage-notations).
Maybe you should raise this concerns in the community style guide/rubocop. :wink:

So you ask people to choose one of the options here and the moment they do that you tell them to complain somewhere else? ;-)

**Comment by bgeuken** [comment]
Give me some time to contemplate about this one (will be on a conference next week).

My general opinion on such things is: We, the OBS team / community, is working on this and we should feel comfortable doing so. That includes getting agreement on such massive changes like changing the style guide.

It might be that the majority is okay with a certain change, or at least doesn't mind, but as soon as there is someone having hard feelings about a proposed change, we should listen and consider this. Even if it means that we can not enable that cop, or implementing that change (since this isn't limited to linter rules).

**Comment by bgeuken** [comment]
> Ana06 commented
>
> And @bgeuken and @mdeniz we work in open source... If our language has a community driven style you don't agree with you should raise your concerns there...

"we work in open source..." is a good reminder to work on things collaboratively instead of forcing things through:-)

**Comment by mdeniz** [comment]
@Ana06 💋 

>So at the end we don't enable anything, and we don't have any style rule at all. 

I don't agree with you, enabling and disabling cops here means to me agreeing in our own style guide. 

>We have just partially rules enabled, which we don't disable but we also can not agree to enable. This is not the way.... We should at least agree on disabling it, currently it is still enabled but with offenses. 

If the status of this code is unaceptable then either disabled it or enable it without offenses.

From my side I want to disable it and remove the offenses too. I don't want to be forced to have special cases of Arrays that must be written differently (and hardly to remember what it means) because other people agreed on it.

>Any way, this is the last Rubocop rule I try to enable in this project.. I fell wasting my time. @openSUSE/open-build-service maybe we should remove rubocop at all from the project...

I like your hard work with the Rubocop, don't get me wrong. If you feel wasting the time, then don't invest it in that for a while... agreeing is sometimes hard. Removing Rubocop at all is not an option for me to get better.

>And @bgeuken and @mdeniz we work in open source... If our language has a community driven style you don't agree with you should raise your concerns there...

The history have shown many examples of "community driven" big failures over the years... don't just follow the mass without your own opinion sometimes you can point to another direction.

**Comment by Ana06** [comment]
@bgeuken 

> So you ask people to choose one of the options here and the moment they do that you tell them to complain somewhere else? ;-)

if you don't agree with a community developed guide of course you should raise your concern there. It is **our** guide.

> Give me some time to contemplate about this one (will be on a conference next week).
> 
> My general opinion on such things is: We, the OBS team / community, is working on this and we should feel comfortable doing so. That includes getting agreement on such massive changes like changing the style guide.
>
> It might be that the majority is okay with a certain change, or at least doesn't mind, but as soon as there is someone having hard feelings about a proposed change, we should listen and consider this. Even if it means that we can not enable that cop, or implementing that change (since this isn't limited to linter rules).
> 
> "we work in open source..." is a good reminder to work on things collaboratively instead of forcing things through:-)

We already chose to have Rubocop. Rubocop is supposed to save us time, as there is already an style convention. Our configuration that differs to rubocop should be in `.rubocop.yml`. What is in `.rubocop_todo.yml` is what is already enabled but where we couldn't enabled the offenses. So, many of the cop you don't agree to enable, **are already enabled**. This is not the way to work with rubocop. 

And I also don't fell confortable working in a project with doesn't have style conventions and the ones it has are incoherent. I am not trying to force that we enable the rule, I was just trying to tell you, that maybe there is more people uncomfortable with not having a style rule, that the one which is uncomfortable with enabling it. @bgeuken why that you are uncomfortable with having the rule is more important that I fell uncomfortable with no having a style rule?

Anyway, we have the same discussion with every single cop. I really consider this important but I just fell wasting my time, I give up. I'll close this. But someone should either remove Rubocop from the project or add a proper configuration for it.

**Comment by bgeuken** [comment]
I actually was in favor of having a style guide early on, when I joined this team. We just never managed to properly talk this through for once and then apply it.

And one of the nice things of rubocop is that it allows to configure the cops, or even disable them in case that a project doesn't agree to one of them.

Why you constantly try to corner people that have a different opinion is beyond my understanding.

**Comment by Ana06** [comment]
@mdeniz 

> I don't agree with you, enabling and disabling cops here means to me agreeing in our own style guide. 

But you are still missing the point that this cop is already enabled, as it is in the todo file and not in the config file... so we didn't agree on anything, also not on disabling it... It is something like partially enabled...

> The history have shown many examples of "community driven" big failures over the years... don't just follow the mass without your own opinion sometimes you can point to another direction.

That is a really sad comment, and more when we work on an open source project... :cry:  It is not following the mass without your own opinion, is telling the community your opinion, if not they can not know that you disagree. And specially in Rubocop, where everybody opinion is taking into account... :disappointed: 

@bgeuken 

> I actually was in favor of having a style guide early on, when I joined this team. 

You are the one that is always against enabling most of the cops since I joined this team... :unamused:

> We just never managed to properly talk this through for once and then apply it.And one of the nice things of rubocop is that it allows to configure the cops, or even disable them in case that a project doesn't agree to one of them.

The problem is that it is done **wrong**: what is in the **todo file is already enabled**.  We are just solving some of the missing offenses. If you want to modify the default configuration, you should do it in the config file not in the todo file.

I am against modifying the default configuration because of many reasons, for example that the people working on the project may change.  But if you want to modify the config and we can agree on something, I am fine with it, better to have a custom style than not having style at all. But lets do it properly.

> Why you constantly try to corner people that have a different opinion is beyond my understanding.

I would really appreciate that you didn't write this kind of comments. You may hurt someone feelings... :unamused:

**Comment by bgeuken** [comment]
> Ana06 commented 2 days ago
>
> You are the one that is always against enabling most of the cops since I joined this team... :unamused:

I am the one who probably enabled most of the cops and who reviews a fair bit of code. Might be that I once in a while disagree with certain changes. No shame in that.

> The problem is that it is done wrong: what is in the todo file is already enabled. We are just solving some of the missing offenses. If you want to modify the default configuration, you should do it in the config file not in the todo file.

That seems to be two different things. Whether we do something wrong with the way we handle  the rubocop config seems independent from the question which cops (and with which settings) we want to have enabled, aka. what ruby style do we agree on.

>> bgeuken commented 
>>
> > Why you constantly try to corner people that have a different opinion is beyond my understanding.
>
> I would really appreciate that you didn't write this kind of comments. You may hurt someone feelings... :unamused:

So I tell you how I feel, seeing your kind of comments, and you just ignore it and accuse me of hurting someones feelings... :unamused: :broken_heart:

**Pull request closed without merging**
