### PR TITLE
Show notification toolbar for missed notification types

### LINKED ISSUE #17012: The notification toolbar is not shown anymore
# Issue Description
The notification toolbar is now shown anymore

Expected Result
============
When you click on a notification, it should send you to the subject of the notification and a notification toolbar should appear at the top of the page, allowing you to mark that notification as read, or go back to the notifications listing.

How to Reproduce
===============
1. Go to [any of your notifications](https://build.opensuse.org/my/notifications)
2. Click on any of them
3. See no notification toolbar at the top of the page

### PR DESCRIPTION
**Pull request by eduardoj**
The missed notification types are:
- Build Failures
- Workflow Runs
- Appealed Decisions

~Solves most of~ Fixes #17012.

### CODE REVIEW

**Review by ncounter — APPROVED** [review]

**Review by danidoni — CHANGES_REQUESTED** [review]
Requests do not show the notification bar when clicking on them.

**Comment by ncounter** [comment]
> Requests do not show the notification bar when clicking on them.

https://obs-reviewlab.opensuse.org/eduardoj-fixissue_17012_3/requests/16?notification_id=38
image

**Comment by eduardoj** [comment]
> Requests do not show the notification bar when clicking on them.

How that can be related to the changes of this pull request?

**Comment by danidoni** [comment]
> > Requests do not show the notification bar when clicking on them.
> 
> How that can be related to the changes of this pull request?

IDK, I didn't see the notification for requests when I tested it. Looks like the latest push fixed it because now it works...

**Review by danidoni — APPROVED** [review]

**Pull request merged**
