### PR TITLE
[api][webui] Switch from coveralls to codecov

### PR DESCRIPTION
**Pull request by hennevogel**
coveralls stopped merging results, try out a new service....

### CODE REVIEW

**Comment by hennevogel** [comment]
Please do not merge, only review. This needs gem packages to be prepared...

**Comment by hennevogel** [comment]
You can see how this would look and feel here: https://codecov.io/gh/hennevogel/open-build-service/branch/feature_codecov

**Comment by mdeniz** [comment]
I like it, nice look of the dashboard, I feel it clearer than the Coveralls one. The only remaining thing is to add the summary result to the PR after it finish 👍

**Comment by hennevogel** [comment]
@mdeniz yeah that we can only do after merging :-)

**Comment by hennevogel** [comment]
There is (OBS#482267)[https://build.opensuse.org/request/show/482267] and [OBS#482266](https://build.opensuse.org/request/show/482266) now. Please review too

**Comment by mdeniz** [comment]
@hennevogel  I'm not a maintainer of [devel:languages:ruby:extensions](https://build.opensuse.org/project/users/devel:languages:ruby:extensions), maybe @bgeuken can do it 😄

**Comment by bgeuken** [comment]
Looks nice. Is it also possible to distinguish between coverage of rspec, api and webui?

**Comment by hennevogel** [comment]
@bgeuken nope everything is merged

**Comment by coolo** [comment]
@bgeuken you can have fun with flags: https://docs.codecov.io/v4.3.0/docs/flags

**Comment by bgeuken** [comment]
Nice! :+1:

**Pull request merged**
