### PR TITLE
Adjust fontsize and gravatar in request history box

### PR DESCRIPTION
**Pull request by krauselukas**
The fontsize was too small. Now it's consistent with
the other content of the page

Co-authored-by: Saray Cabrera Padrón <scabrerapadron@suse.de>

Before:
Screenshot-2019-8-7 Request 4 (review)(2)

After:
Screenshot-2019-8-7 Request 4 (review)(1)

### CODE REVIEW

**Comment by saraycp** [comment]
> What about the color?

We decided not to touch the color now but when we tackle the "Wave" card. In fact, we haven't agreed on a color palette yet.

**Comment by dmarcoux** [comment]
I would remove the `.text-muted` from the request history. It can be the plain color for now and it would be already much better.

**Comment by krauselukas** [comment]
> I would remove the `.text-muted` from the request history. It can be the plain color for now and it would be already much better.

@dmarcoux done

Screenshot-2019-8-8 Request 1 (review)

**Comment by saraycp** [comment]
[Request: Review font classes / tags and line length](https://trello.com/c/gAEO50ru/1206-request-review-font-classes-tags-and-line-length)

**Pull request merged**
