### PR TITLE
Revert "Merge pull request #3167 from bgeuken/remove_custom_structure…

### PR DESCRIPTION
**Pull request by bgeuken**
…_dump"

This reverts commit aa9d0a6e78bb947a452c6d3db5542844914b2f75, reversing
changes made to 4377556551f8157b286bb35f730a39ea8fbbb2e7.

In our package builds we run a db structure dump comparison (script/api_test_in_spec.sh)
that fails now because timestamps and alike don't match with the
expected structure.sql.
We have to first change / remove this script.

=========

[  348s] ERROR: Migration is producing a different structure.sql
[  348s] --- db/structure.sql	2017-06-01 13:16:34.064000000 +0000
[  348s] +++ db/structure.sql.git	2017-06-01 13:16:19.536000000 +0000
[  348s] @@ -1,8 +1,8 @@
[  348s] --- MySQL dump 10.15  Distrib 10.0.27-MariaDB, for Linux (x86_64)
[  349s] +-- MySQL dump 10.15  Distrib 10.0.29-MariaDB, for Linux (x86_64)
[  349s]  --
[  349s] --- Host: localhost    Database: api_25
[  349s] +-- Host: localhost    Database: localhost
[  349s]  -- ------------------------------------------------------
[  349s] --- Server version	10.0.27-MariaDB
[  349s] +-- Server version	10.0.29-MariaDB
[  349s]
[  349s]  /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
[  349s]  /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
[  349s] @@ -1820,7 +1820,7 @@
[  349s]  /*!40101 SET character_set_client = @saved_cs_client */;
[  349s]
[  349s]  --
[  349s] --- Dumping routines for database 'api_25'
[  349s] +-- Dumping routines for database 'api_development'
[  349s]  --
[  349s]  /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
[  349s]
[  349s] @@ -1832,7 +1832,7 @@
[  349s]  /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
[  349s]  /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
[  349s]
[  349s] --- Dump completed on 2017-06-01 13:16:34
[  349s] +-- Dump completed on 2017-05-31 16:16:33
[  349s]  INSERT INTO schema_migrations (version) VALUES
[  349s]  ('1'),
[  349s]  ('20140210114542'),
[  349s] Makefile:65: recipe for target 'test_unit' failed
[  349s] make: *** [test_unit] Error 1
[  349s] make: Leaving directory '/home/abuild/rpmbuild/BUILD/open-build-service-2.8.51.git20170601.71c89f5/src/api'

### CODE REVIEW

**Comment by bgeuken** [comment]
Only in OBS... ><

**Comment by bgeuken** [comment]
I am voting for dropping the custom 'migration test'

**Comment by evanrolfe** [comment]
+1 for dropping this check in `script/api_test_in_spec.sh`. Also if we move from structure.sql to schema.rb then we should be able to re-implement this check using schema.rb since schema.rb won't have timestamps and other stuff like that.

**Comment by hennevogel** [comment]
Anyway, for now we should have building packages...

**Comment by mmohring** [comment]
Still an error :(

[  234s] Dropped database 'api_25'
[  234s] ERROR: Migration is producing a different structure.sql
[  234s] --- db/structure.sql   2017-06-01 15:52:28.688547518 +0000
[  234s] +++ db/structure.sql.git       2017-06-01 15:52:18.700547513 +0000
[  234s] @@ -1229,4 +1229,3 @@
[  234s]  ('20170511120355'),
[  234s]  ('20170516140442');
[  234s]  
[  234s] -
[  234s] Makefile:65: recipe for target 'test_unit' failed

**Pull request merged**
