### PR TITLE
Pick less offensive colours for staged requests

### PR DESCRIPTION
**Pull request by coolo**
screencapture-f102-suse-de-3000-staging-workflows-136-2019-11-29-12_02_09

### CODE REVIEW

**Comment by coolo** [comment]
Oh? There is a discussion forum 'with the development team' other than here where the development happens?

**Comment by coolo** [comment]
btw, if you sticked to your colour patterns, we might not have this discussion. Part of the problem is that you mix bootstrap background colours with your own foreground colours.

**Comment by vpereira** [comment]
> btw, if you sticked to your colour patterns, we might not have this discussion. Part of the problem is that you mix bootstrap background colours with your own foreground colours.

that's why it's import to talk with the development team. We had a sprint about colors x usability, involving customers with some level of vision impairment and we used the tool https://wave.webaim.org/, to guide us through the process.

**Comment by coolo** [comment]
I doubt that sprint involved the staging dashboard's colours.

**Comment by coolo** [comment]
the review app bot is broken :(

**Comment by eduardoj** [comment]
@coolo:

> the review app bot is broken :(

Fixed!

**Comment by vpereira** [comment]
@coolo could you please validate this PR with WAVE (https://wave.webaim.org) ?

**Comment by coolo** [comment]
I fixed the review apps to have a proper staging workflow by default, resulting in:

https://wave.webaim.org/report#/https://obs-reviewlab.opensuse.org/coolo-fix_colours/staging_workflows/openSUSE:Factory

Warnings about low contrast.

**Comment by coolo** [comment]
It should be noted that this is not a regression as the master dashboard has white on orange. But I'll try to adopt.

**Comment by coolo** [comment]
I picked more boring colours - and there are no more complaints.

**Comment by vpereira** [comment]
yes, no issues at WAVE and the colours are ok.

**Pull request merged**
