### PR TITLE
Disallow branch filters for tag push event

### LINKED ISSUE #13206: SCM/CI integration, OBS can't download `.obs/workflows.yml` on `tag_push` from a github repository
# Issue Description
I am trying to trigger services of a package when a tag is pushed to the related github repository. For some reason it always fails and it looks like OBS tries to use the tag sha against the github API and it doesn't seam to be supported.

In OBS workflow run reports I can see this error:

```
<status code="non_existent_workflows_file">
  <summary>.obs/workflows.yml could not be downloaded from the SCM branch/commit 0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f: GET https://api.github.com/repos/rancher/elemental-cli/contents//.obs/workflows.yml?ref=0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f: 404 - No commit found for the ref 0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f // See: https://docs.github.com/v3/repos/contents/</summary>
</status>
```

From a cloned repo I can see:
```
$ git show-ref --tags
....
0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f refs/tags/v0.1.0
```

So OBS uses the tag hash to download the workflow against github API, but this doesn't seam to work. [1] does not work, but [2] seams to work fine.

[1] https://api.github.com/repos/rancher/elemental-cli/contents//.obs/workflows.yml?ref=0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f

[2] https://api.github.com/repos/rancher/elemental-cli/contents//.obs/workflows.yml?ref=v0.1.0

Expected Result
============
The workflow run should not fail, it should be capable to find `.obs/workflows.yml` in a github repository from an tag_push` event.

How to Reproduce
===============
Set a workflow in some github repository as:
```yaml
tag_workflow:                                                                                                                                                                                                                                  
  steps:                                                                                                                                                                                                                                           
    - trigger_services:                                                                                                                                                                                                                            
        project: <my_prj>
        package: <my_pkg>
  filters:                                                                                                                                                                                                                                         
    event: tag_push
```

Set a webhook to make use of an OBS workflow token on `branch or tag creation` and `pushes` events.

Finally push a new tag to the repository and the triggered workflow will fail to fetch `.obs/workflow` from the repository.

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

### PR DESCRIPTION
**Pull request by krauselukas**
We cannot filter branches for a tag push event, since the tag is referring to a certain commit and has no reference to a branch. Therefore the webhook does not contain the information about the branch.

Fixes #13206

I will add a note to the docs

### CODE REVIEW

**Comment by krauselukas** [comment]
[Fix workflows for tag_push event once and for all (L)](https://trello.com/c/ZilUAhlG/2110-fix-workflows-for-tagpush-event-once-and-for-all-l)

**Comment by dmarcoux** [comment]
Please add a spec for this.

**Comment by krauselukas** [comment]
@dmarcoux added a test case for that

**Comment by krauselukas** [comment]
Added a PR to update the documentation regarding this https://github.com/openSUSE/obs-docu/pull/269

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
