### PR TITLE
[ci] Add launchy gem

### PR DESCRIPTION
**Pull request by ChrisBr**
to fire up a browser in feature tests.
https://github.com/copiousfreetime/launchy

### CODE REVIEW

**Comment by ChrisBr** [comment]
@adrianschroeter @bgeuken @hennevogel @mdeniz what do you think about launchy? Than we can use ``save_and_open_page`` for debugging purpose in our feature / rspec tests ...

**Comment by ChrisBr** [comment]
See https://build.opensuse.org/request/show/363701

**Comment by adrianschroeter** [comment]
fine

**Comment by ChrisBr** [comment]
as @adrianschroeter agreed and it's already in our Unstable repository, merging ...

**Pull request merged**
