### PR TITLE
[backend] Add support for cleaning up worker chroot

### PR DESCRIPTION
**Pull request by tuminoid**
Add a configuration option to cleanup chroot/lxc buildroots from workers after build has finished.

### CODE REVIEW

**Comment by mmohring** [comment]
Hi, I would allow this option also for virtual machine builds.

**Comment by tuminoid** [comment]
@mmohring There is already undocumented `OBS_VM_DISK_CLEAN="yes"` for VMs.

**Comment by Conan-Kudo** [comment]
@tuminoid I would suggest ensuring that it only does the cleanup on success. Failures might warrant actual investigation.

**Comment by adrianschroeter** [comment]
@Conan-Kudo The cleanup should happen in any case, since this is about to free resources. You can do local builds for debugging.

I like to have only one variable to configure it, independend of chroot/kvm. Will take care about that ...

**Comment by adrianschroeter** [comment]
hm, vmdisk-clean is something different ... so let's just take this.

**Pull request merged**
