### PR TITLE
Remove unused code from user_login

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by mdeniz** [comment]
LGTM

**Comment by ChrisBr** [comment]
Hakiri fails because #1233 isn't merged yet! We should first merge #1233 and than I'll rebase this one which should resolve the hakiri issue!

**Comment by mdeniz** [comment]
I have merged #1233, Rebase it ;)

**Comment by ChrisBr** [comment]
@mdeniz thx!

**Pull request merged**
