### PR TITLE
[api] tell which attribute blocked an operation

### PR DESCRIPTION
**Pull request by adrianschroeter**
tried to reproduce https://github.com/openSUSE/open-build-service/issues/2782

### CODE REVIEW

**Comment by adrianschroeter** [comment]
Not able to reproduce the problem from https://github.com/openSUSE/open-build-service/issues/2782 here. But it shows that we changed the api incompatible by changing the status code errors

**Comment by adrianschroeter** [comment]
this contains now a reproducer for issue #2782

**Comment by adrianschroeter** [comment]
This pull request is known to fail atm. It is more a bugreport and intended to discuss how we can provide the status code errors using pundit, since this will bite us also in other places where it is more critical then here.

**Comment by hennevogel** [comment]
@adrianschroeter now has been handled in 9c62713da565dbf92857c2b3363c4909fdaf2282

**Pull request closed without merging**
