### PR TITLE
Backport LDAP local user feature to 2.9 branch

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
the database changes (cloud_azure related) seems to be too much here?

**Comment by bgeuken** [comment]
I forgot to drop the db and re-setup a 2.9 db before running the migration

**Comment by bgeuken** [comment]
@adrianschroeter I removed them now

**Comment by adrianschroeter** [comment]
great, please proceed

**Pull request merged**
