### PR TITLE
Add repository status to Monitor page columns

### LINKED ISSUE #6567: monitor page looses the icons in front of repository name
Those icons e.g. tell me things like

- "repository not created yet"
- "publishing"
- "published"

All this is lost after the migration to bootstrap.

Before:
example

Now:
now

### PR DESCRIPTION
**Pull request by ChrisBr**
Fix #6567

### CODE REVIEW

**Comment by coolo** [comment]
I prefer small

**Comment by ChrisBr** [comment]
I also prefer small, updated!

**Comment by ChrisBr** [comment]
> small doesn't work here. You want fa-xs. Otherwise it looks like this

Hm, in chrome it worked for me :thinking: :cry: But thanks, changed...

**Comment by ChrisBr** [comment]
selection_017

Added also a margin now.

**Pull request merged**
