### PR TITLE
Upgrade rack to 2.2.8.1

### PR DESCRIPTION
**Pull request by danidoni**
See #15688

### CODE REVIEW

**Comment by danidoni** [comment]
The OBS checks are going to fail because we to remove the rack dependency on 2.2.6.4, which is what this PR is trying to do.

**Review by krauselukas — COMMENTED** [review]
@danidoni shouldn't this happen together with the version bump in the Gemfile? (so basically the depfu PR)

**Comment by danidoni** [comment]
> @danidoni shouldn't this happen together with the version bump in the Gemfile (so basically the Depfu PR)? Or is there a reason to do this separate?

I need this to make OBS builds to succeed, then I can go back to the referenced PR and rerun everything green.

**Comment by danidoni** [comment]
Closing in favor of doing this step in the referenced PR

**Pull request closed without merging**
