### PR TITLE
Update yajl-ruby gem to version 1.3.1

### PR DESCRIPTION
**Pull request by mschnitzer**

### CODE REVIEW

**Comment by mschnitzer** [comment]
@hennevogel please re-review

**Comment by hennevogel** [comment]
@mschnitzer please rebase

**Comment by mschnitzer** [comment]
@hennevogel rebased

**Comment by mschnitzer** [comment]
@hennevogel ping

**Comment by mschnitzer** [comment]
@hennevogel ping ;-)

**Pull request merged**
