### PR TITLE
Send scheduler metrics first

### PR DESCRIPTION
**Pull request by eduardoj**
"jobs building" metrics could be a thousand metrics, while the rest sent by the WorkerMeasurementsJob could hardly reach a hundred metrics.

By switching the order the metrics are sent leaving the "jobs building" metrics at the end, the scheduler metrics are guaranteed to be parsed.

Monkey Patched in production, until scheduler metrics can be seen in Grafana.

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Comment by dmarcoux** [comment]
This has been monkey-patched in production for 2 days, what is the reason for the `DO NOT MERGE` label?

**Comment by vpereira** [comment]
> This has been monkey-patched in production for 2 days, what is the reason for the `DO NOT MERGE` label?

I don't see why we have to test it in production if we have a AHM development environment: https://github.com/openSUSE/open-build-service/wiki/Site-Reliability#development-environment

**Comment by eduardoj** [comment]
> This has been monkey-patched in production for 2 days, what is the reason for the `DO NOT MERGE` label?

This patch was a way of testing that the problem was not related to sending scheduler metrics.

Even now, that scheduler metrics are correctly shown in Grafana, this patch doesn't provide a full fix for the problem. "jobs building" metrics are not all shown. There seems to be a problem sending so many metrics at once.

**Comment by eduardoj** [comment]
> > This has been monkey-patched in production for 2 days, what is the reason for the `DO NOT MERGE` label?
> 
> I don't see why we have to test it in production if we have a AHM development environment: https://github.com/openSUSE/open-build-service/wiki/Site-Reliability#development-environment

Using the AHM development environment would have required setting up fake "job building" results - not a straightforward task. And even after that, there was no guarantee that the error could have been reproduced.

**Comment by vpereira** [comment]
> Using the AHM development environment would have required setting up fake "job building" results - not a straightforward task. And even after that, there was no guarantee that the problem could have been reproduced.

the AHM development environment is just a development environment + Grafana + Influxdb. If you build a package it will be built as usual.. Or you enter in a rails console (while running the development environment) and schedule some jobs manually, or even you setup an appliance with Grafana and Influxdb and run your tests there.. IMO production is definitely not the place to do these tests

**Comment by eduardoj** [comment]
After #11392 got merged and deployed, this monkey patch is no longer needed.

**Pull request closed without merging**
