### PR TITLE
[api] fix change time in reviews (when attriute)

### PR DESCRIPTION
**Pull request by adrianschroeter**
It was never updated which made the information in most
cases identical to request creation time always.

The attribute is supposed same as the when attriute
of the request itself, where it is the last time the
request changed.

### CODE REVIEW

**Comment by hennevogel** [comment]
Not sure this does what you want it to do. `Review.updated_at` will change every time that the record changes. No matter if this is for a `state` change or not. Let's say because we delete a `Group` and `Review.group_id` gets nullified.

In the model we look up `history_element`s to decide when it was accepted/declined. Maybe we should add a new field?

**Comment by adrianschroeter** [comment]
On Dienstag, 28. Juli 2020, 17:32:28 CEST wrote Henne Vogelsang:
> Not sure this does what you want it to do. `Review.updated_at` will change every time that the record changes. No matter if this is for a `state` change or not. Let's say because we delete a `Group` and `Review.group_id` gets nullified.

deleting a group must indeed not touch the timestamp, but it is also only
stored as text string therefore to be independend. If there is another vector
causing this we need to solve this indeed.

IMHO we should get rid of the belongs_to :group there.

(on the other hand, removing a group could maybe seen as very seldom special case no worth 
 to be taken care off....)

> In the model we look up `history_element`s to decide when it was accepted/declined. Maybe we should add a new field?

I like to avoid that if possible...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by hennevogel** [comment]
>> Maybe we should add a new field?

> I like to avoid that if possible...

Because?

**Comment by hennevogel** [comment]
Let me show you what I mean. Commit incoming...

**Comment by adrianschroeter** [comment]
fine with me (even though we could drop update_at now since we have no usage for it anymore)

**Comment by adrianschroeter** [comment]
hm, and what is with old requests where the data was still valid? 
Maybe we need a migration to rescue the data from update_at that otherwise we also break the data on the older requests now...

**Comment by hennevogel** [comment]
> hm, and what is with old requests where the data was still valid?

In the data migration we copy over the date from `updated_at`. Until this data migration is run we cover this in the reader of the new attribute. It does `changed_state_at || updated_at`.

**Comment by eduardoj** [comment]
I rebased on master.

**Review by hennevogel — APPROVED** [review]

**Pull request merged**
