### PR TITLE
[api] Never return nil as current user, but nobody

### PR DESCRIPTION
**Pull request by Ana06**
Return the `nobody` user instead of nil if there is not current user, similarly as it is done with `current_login`. :bowtie: 

With this we could actually always set the current user to nil in the code, and then everything related to the `nobody user` could be inside the User model. We could even make the `find_nobody!` method private.

Fixes https://github.com/openSUSE/open-build-service/issues/4746

### CODE REVIEW

**Comment by ChrisBr** [comment]
It is not that easy ...
I already tried something similar here 131cec33079c7ef41d5c90bde452157662337867

Problem is that you will change the logic on many places, you don't even know which side effects this will have. I would prefer to life with the occasional exceptions instead of breaking even more stuff and logic ...

Thanks anyway for looking into it! I'm fine with closing the original issue!

**Comment by Ana06** [comment]
@ChrisBr 

> It is not that easy ...

It is also not impossible. As you see in the second commit already it will simplify the code in general a lot. We always have problems with this nobody users, it would be nice to try to get all the user logic in the User model and not everywhere in the code.


> I would prefer to life with the occasional exceptions instead of breaking even more stuff and logic ...

Fixing it doesn't imply that we break everything. We can put some extra effort in trying and review it. :thinking: 

@openSUSE/open-build-service what do you think?

**Comment by ChrisBr** [comment]
I'm strongly against it as can not oversee which sideeffects this will have! According to errbit there are also no more of these errors as they were mostly coming from BsRequestActionWebuiInfosJob which we fixed in: 462938c85b146eb211f7ecfe42e3d0b345a6ea02

**Comment by Ana06** [comment]
@ChrisBr 

> I'm strongly against it as can not oversee which sideeffects this will have! According to errbit there are also no more of these errors as they were mostly coming from BsRequestActionWebuiInfosJob which we fixed in: 462938c

it is not the first time we have problems with the nobody users, and I think it won't be the last one neither. Maybe it is worthwhile to improve this code.... :thinking:

**Comment by ChrisBr** [comment]
> it is not the first time we have problems with the nobody users, and I think it won't be the last one neither. Maybe it is worthwhile to improve this code....

But currently there are no problems :thinking: So I would prefer to focus on fixing other problems instead of this. As this will require quite some effort to get it right. Effort I would prefer to put into other issues ....

**Comment by ChrisBr** [comment]
I canceled the CircleCI job because it takes forever because of _MANY_ failing tests which get retried three times... (maybe it makes sense to also kill Travis)

Anyway, as you see: 
* Spider broken
* rspec broken (with a lot of tests)
* minitest broken (with a few)
...

Of course it is not impossible to fix these tests. The question is just: it buys us currently not much if we fix it...

**Comment by bgeuken** [comment]
I would be in favor of such a change since it would simplify our code.

Like @ChrisBr said this potentially breaks at various places. And that'S the tricky part. @Ana06 If you want to do this you will have to properly test this and review the OBS code to ensure that nothing breaks (well minimize the possibility it:wink:).

**Comment by ChrisBr** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

Travis already did it for you ...

**Comment by eduardoj** [comment]
@Ana06 

> Fixing it doesn't imply that we break everything. We can put some extra effort in trying and review it. :thinking:
> 
> @openSUSE/open-build-service what do you think?

I was trying to find a proper answer, and then:

@bgeuken 

> I would be in favor of such a change since it would simplify our code.
> 
> Like @ChrisBr said this potentially breaks at various places. And that'S the tricky part. @Ana06 If you want to do this you will have to properly test this and review the OBS code to ensure that nothing breaks (well minimize the possibility it :wink:).

I fully agree. :+1:

**Pull request closed without merging**
