### PR TITLE
Fix issue 1259

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
For the Activerecord::RecordNotFound fix I am not 100% sure if this actually should fail hard and end in a 500 error. Your call;-)

**Comment by bgeuken** [comment]
Ignore the branch name, this patch is for issue 1259;-)

**Comment by adrianschroeter** [comment]
hm, not sure if we should make this error silent. It is in the end a mis-configuration by the Admin user. IMHO we should keep the error 500 for now, but report the error to the admin-messages once we have such a mechanism.

**Comment by bgeuken** [comment]
True, I should also fix the chackboxes.
But in any way we shouldn't show a 500 to users, unless it's really an unexpected error. Having a repo already added (selected) doesn't seem like such a case.

**Comment by adrianschroeter** [comment]
Right, having a repo already added is exactly what should get fixed.

But I read your changes more in the direction that you fixed the invalid data from the invalid configured remote instance (RecordNotFound). 

Is the ActiveRecord::RecordInvalid case the double add situation? So, commit 7714bea is fine then, just it is not the problem in heroku link ;)

**Comment by adrianschroeter** [comment]
in short, I would skip commit 272c87b for now

**Comment by bgeuken** [comment]
@adrianschroeter Rebased without the commit in question. I am going to fix the distribution checkboxes in a separate PR, if that's okay with you

**Comment by bgeuken** [comment]
@adrianschroeter Mind to have a last look?

**Pull request merged**
