### PR TITLE
WIP Convert action navigation into a sidebar 

### PR DESCRIPTION
**Pull request by DavidKang**
We made the action navigation bar always visible for xl and xxl breakpoints. With this change, the actions are always visible and available.

Screenshot_2020-03-17 home Admin

### CODE REVIEW

**Comment by hennevogel** [comment]
I like it, but I'm not sure we should change it right now. We haven't even "tested" the menus on the top right for a while with people.

**Comment by hennevogel** [comment]
I have the feeling for those viewport sizes we should have a full menu on the left. What do you think?

**Comment by danidoni** [comment]
> I have the feeling for those viewport sizes we should have a full menu on the left. What do you think?

That's a good idea

**Comment by DavidKang** [comment]
> I have the feeling for those viewport sizes we should have a full menu on the left. What do you think?

The idea behind this PR, is to move into this direction, having a menu on the left. I started with actions because it was something that I felt was needed. 

So, having a full menu sounds good :smile_cat:

**Comment by DavidKang** [comment]
For the moment, we are not going to this direction. I will close this PR for now.

**Pull request closed without merging**
