### PR TITLE
Add Saray, Victor and Dany to .gitmessage

### PR DESCRIPTION
**Pull request by eduardoj**
Also fix Moisés tildes.

### CODE REVIEW

**Comment by eduardoj** [comment]
@Ana06 

> Well, more than belonging somewhere is that they don't send code anymore... should we maybe add @coolo ? :rofl:

@coolo, are you fine with this?

**Comment by eduardoj** [comment]
@Ana06:

> you forgot @vpereira! :sob:

Added.

**Comment by coolo** [comment]
I'm a solo dancer - https://i.gifer.com/IG6Z.gif

**Comment by bgeuken** [comment]
Now I have an [Ohrwurm](https://www.youtube.com/watch?v=3ij_pUtJJrw&feature=youtu.be&t=24)

**Pull request merged**
