### PR TITLE
Drop cassette rewinder

### PR DESCRIPTION
**Pull request by hennevogel**
No one is using this anymore...

### CODE REVIEW

**Comment by danidoni** [comment]
> No one is using this anymore...

I didn't know about this! It is not useful then to clean unused cassettes?

**Review by eduardoj — APPROVED** [review]

**Comment by dmarcoux** [comment]
> I didn't know about this! Isn't it useful then to clean up unused cassettes?

Same thought from me.

**Comment by hennevogel** [comment]
> Isn't it useful then to clean up unused cassettes?

Things are only useful if they are used :)

**Comment by dmarcoux** [comment]
> > Isn't it useful then to clean up unused cassettes?
> 
> Things are only useful if they are used :)

Wise words, we didn't use this. I don't think this will change even if we now know that this script exists.

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
