### PR TITLE
[api][webui] Copy the rebuild strategy

### PR DESCRIPTION
**Pull request by Ana06**
Copy the rebuild strategy from the template when branching a image template.

### CODE REVIEW

**Comment by Ana06** [comment]
[(3) Branching image templates (ui)](https://trello.com/c/Rlh3QEWC/132-3-branching-image-templates-ui)

**Comment by adrianschroeter** [comment]
Please document the new "copy" argument in docs/docs/api.txt . A testcase for the api branching would also be nice. Apart from that :+1:

**Comment by Ana06** [comment]
@adrianschroeter 

> Please document the new "copy" argument in docs/docs/api.txt

I think you mean **docs/api/api/api.txt**

**Comment by adrianschroeter** [comment]
LGTM :+1:

**Comment by ChrisBr** [comment]
LGTM :+1:

**Pull request merged**
