### PR TITLE
Set pagingType and Language as in our DataTables default

### PR DESCRIPTION
**Pull request by vpereira**
Set our default datatables options for PagingType and Language to improve the datatables experience in smaller screens

### CODE REVIEW

**Comment by vpereira** [comment]
The `StateDuration` on this datatable instance are 2 days. Our default is "forever". Should we sync both together @hennevogel  ?

**Comment by vpereira** [comment]
Any reason why this file is kept as `erb` @openSUSE/open-build-service ?

**Comment by vpereira** [comment]
[DataTables](https://trello.com/c/F7kZJucA/1330-datatables)

**Comment by dmarcoux** [comment]
> Any reason why this file is kept as `erb` @openSUSE/open-build-service ?

I don't really see why it's `erb`.

**Comment by vpereira** [comment]
> I don't really see why it's `erb`.

I will look into that.. I couldn't find any ruby interpolation being done there.

**Comment by dmarcoux** [comment]
> > I don't really see why it's `erb`.
> 
> I will look into that.. I couldn't find any ruby interpolation being done there.

I got to the same conclusion.

**Comment by hennevogel** [comment]
> Our default is "forever". Should we sync both together?

Sure thing, forever.

**Comment by vpereira** [comment]
> I got to the same conclusion.

renamed

**Comment by vpereira** [comment]
> Sure thing, forever.

done

**Pull request merged**
