### PR TITLE
[backend] Pass result file path as argument to clouduploader

### PR DESCRIPTION
**Pull request by ChrisBr**
We used the wrong directory to store the result file. Now the backend will pass the path of the result file as an argument so we also don't need to parse the ID out of the filename.

### CODE REVIEW

**Comment by ChrisBr** [comment]
@DavidKang please also approve after the test was successfully :+1:

**Comment by bgeuken** [comment]
@ChrisBr @DavidKang Please review again:-) I would like to get new 2.9 packages soon. That's why I push :smile:

**Comment by ChrisBr** [comment]
@bgeuken we need to wait till we can deploy this again to test!

**Comment by ChrisBr** [comment]
Ok, this is deployed now! Waiting for feedback from @DavidKang

**Comment by DavidKang** [comment]
@ChrisBr, works!

screenshot from 2018-02-27 17-27-54

**Pull request merged**
