### PR TITLE
[api] Remove format parameter in public controller

### PR DESCRIPTION
**Pull request by ChrisBr**
before passing to backend. Otherwise you will receive an unknown parameter error from backend.
Requested by @digitaltom to make use of public actions in the browser.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Please with merging, @adrianschroeter will check in the backend, maybe we will fix it there then ...

**Comment by hennevogel** [comment]
@adrianschroeter any news on this?

**Comment by bgeuken** [comment]
Removed the 'Do not merge' per discussion with Adrian

**Comment by hennevogel** [comment]
[[2] Merge PullRequest #1997](https://trello.com/c/p7rzO9wx/15-2-merge-pullrequest-1997)

**Comment by hennevogel** [comment]
Superseded by #1997

**Comment by mschnitzer** [comment]
@hennevogel I think you meant "Superseded by # 2184" and not # 1997, right? I changed it. Correct me, if I'm wrong.

**Pull request closed without merging**
