### PR TITLE
Introduces a Terms (of Service) link

### PR DESCRIPTION
**Pull request by hennevogel**
## Before
Screenshot from 2021-07-22 14-13-34

## After
Screenshot from 2021-07-22 14-10-18

### CODE REVIEW

**Comment by dmarcoux** [comment]
Could you submit the commit 885a176 in another PR? It's completely unrelated to the other changes. Same for almost all changes of 6e6c2eb. I'm fine with keeping those changes if 885a176 is taken out.

**Comment by hennevogel** [comment]
> It's completely unrelated to the other changes.

Not really, happens when you run `db:migrate`. So all you will create, is two PRs with a dependency :)

**Comment by dmarcoux** [comment]
> > It's completely unrelated to the other changes.
> 
> Not really, happens when you run `db:migrate`. So all you will create, is two PRs with a dependency :)

It's a lot of noise among the Terms of Service changes. Running `bundle exec rake db:migrate` on `master` is also generating the changes which are creating that noise. It just makes reviewing harder.

**Comment by vpereira** [comment]
the other PR is merged @hennevogel

**Review by rubhanazeem — APPROVED** [review]

**Comment by hennevogel** [comment]
Hm looks like our `Configuration` mockery doesn't return nil for an empty column?

**Comment by hennevogel** [comment]
@rubhanazeem turned the logic [here](https://github.com/openSUSE/open-build-service/pull/11415/commits/0d0576de3cd3375e0d08f282d95d6e2e9d2d6e3a#diff-ec7c5f73cd00d2a91b2b8d71b09932e0cc1ec94fba29016416bbffcaf81cd072R31) around, please have another look.

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
