### PR TITLE
Enable Haml-Lint idNames

### PR DESCRIPTION
**Pull request by DavidKang**

### CODE REVIEW

**Comment by bgeuken** [comment]
LGTM

**Comment by Ana06** [comment]
@DavidKang did you correct this manually? 😱

**Comment by DavidKang** [comment]
@Ana06, yes, I hope nothing breaks :sweat_smile:

**Comment by bgeuken** [comment]
It might be worth to briefly check the views in OBS to have a sanity check

**Comment by bgeuken** [comment]
> bgeuken commented 5 hours ago
> It might be worth to briefly check the views in OBS to have a sanity check

Just did that. Seems all fine.

**Pull request merged**
