### PR TITLE
Add wrapper for can modify methods

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2018-06-28 08:54:17 +0000, Björn Geuken wrote:
> diff --git a/src/api/app/models/user.rb b/src/api/app/models/user.rb
> index a99081fe1a..1488f1410f 100644
> --- a/src/api/app/models/user.rb
> +++ b/src/api/app/models/user.rb
> @@ -423,6 +423,17 @@ def has_global_permission?(perm_string)
>      end
>    end
>  
> +  def can_modify?(object)
> +    case object
> +    when Project
> +      can_modify_project?(object)
> +    when Package
> +      can_modify_package?(object)
> +    else
> +      raise ArgumentError, "Wrong type of object: '#{object.class}' instead of Project or Package."
> +    end
> +  end

Hmm won't this break for a remote package?
At least according to the comment in User.can_modify_package?,
object might be nil:

def can_modify_package?(package, ignore_lock = nil)
  return false if package.nil? # happens with remote packages easily

If package is nil, can_modify? raises an ArgumentError.

**Comment by hennevogel** [comment]
Hm, why don't you move this into a `Project`/`Package` policy?

**Comment by bgeuken** [comment]
> @marcus-h commented
> Hmm won't this break for a remote package?
> At least according to the comment in User.can_modify_package?,
> object might be nil:
> 
> def can_modify_package?(package, ignore_lock = nil)
>   return false if package.nil? # happens with remote packages easily
> 
> If package is nil, can_modify? raises an ArgumentError.

That sucks. I will have a look

**Comment by bgeuken** [comment]
> @hennevogel commented
> Hm, why don't you move this into a Project/Package policy?

I didn't plan to rewrite all of our authentication code with this PR.
btw right now our policies currently rely on the can_modify helpers.

**Comment by bgeuken** [comment]
Closing since I have to figure out how to handle remote projects / packages

**Comment by bgeuken** [comment]
This was easier solved than expected. Since I can not re-open this PR after rebasing my branch. I opened a new PR: #5247

The only change I did was that can_modily?(x) returns false when x is nil

**Pull request closed without merging**
