### PR TITLE
[webui]Update show.html.erb

### PR DESCRIPTION
**Pull request by alllexandr**
Added revision to submit package

### CODE REVIEW

**Comment by mdeniz** [comment]
Hey @alllexandr, beside the failing tests... we tag the commits with [webui] in your case.

**Comment by hennevogel** [comment]
@alllexandr this is about the commit message, not the title of the pull-request :-)

**Comment by alllexandr** [comment]
I must close request? and create new with right comment?

**Comment by coolo** [comment]
actually you can git commit --amend and git push -f

**Pull request closed without merging**
