### PR TITLE
[api] fix project wide manual release in maintenance scheme

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by mdeniz** [comment]
Is there any issue that this PR fixes?

**Comment by mdeniz** [comment]
BTW, can you add a test for this change too?

**Comment by adrianschroeter** [comment]
the issue is that a package get released in a different (wrong) way when you release it alone or as entire project.

Agreed that it needs a test case, but not anymore today (fixing the data caused by the surprising behaviour took too much time ;).

**Comment by hennevogel** [comment]
@adrianschroeter how about today? This week? Next week? :-)

**Comment by mdeniz** [comment]
Ping! :smile:

**Comment by hennevogel** [comment]
Another month passed without any reaction...

**Comment by bgeuken** [comment]
@adrianschroeter JFYI I've picked up your commit and added some tests in #5023

**Comment by bgeuken** [comment]
Moved to #5023

**Pull request closed without merging**
