### PR TITLE
[rake] Drop custom rake task for creating a db structure dump

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
I've compared the structure.sql files created by the rails db structure dump and our custom one. The differences I could spot are:

a.) "DROP TABLE IF EXISTS" entries get created for each table
b.) "AUTO_INCREMENT=14" entries get created for each table of the db the dump is taken from that contain table entries
c.) /*!40101 SET @saved_cs_client     = @@character_set_client */; entries get added before and after  each 'CREATE TABLE' section

====

a.) seems to be fine for me
b.) expected behaviour. Depending on the usage of the dev instance the number of existing tables differ. However this means that everytime we update the structure.sql in our git repo, the chances are high that a couple of unrelated AUTO_INCREMENT entries will change.

Only solution I found so far is to extend the rake task with 2 lines of code.

c.) This is just setting and re-setting some values for the time the CREATE TABLE call gets executed. I don't see any harm here.

**Comment by evanrolfe** [comment]
The AUTO_INCREMENT thing is a bit annoying.. Here is another option to solve the problem:

Use the ruby format for schema dumps insead of SQL.

http://guides.rubyonrails.org/v3.2.8/migrations.html#types-of-schema-dumps

The only problem is if we have any mysql specific stuff that can't be expressed in active record? AFAIK we don't. One thing is that the docs say that using ruby for structure.rb means that it can't handle foreign key constraints but I believe that isn't 100% true and the foreign key constraints should work for us using ruby instead of SQL. Perhaps worth some investigation?

**Comment by coolo** [comment]
when we switched to SQL, it didn't support foreign key constraints for sure - claiming that rails already handles that and you wouldn't need SQL constraints.

**Comment by bgeuken** [comment]
> The AUTO_INCREMENT thing is a bit annoying..

yep

> There is a good post here about the difference between structure.sql and structure.rb:
> https://stackoverflow.com/questions/34394823/what-is-the-difference-between-rails-structure-sql-and-schema-rb

I know the difference. What I did not know is what we want to achieve with that scrum story. It only says we want to get rid of the custom rake task. That doesn't seem to be a big deal. But then it's rated with a 5 which indicates there is more to do.

Does everyone agree to move to the schema.rb?

**Pull request closed without merging**
