### PR TITLE
 [webui] Fix highlighting of headers in nested tabs

### PR DESCRIPTION
**Pull request by Ana06**
It partially solves the broken JavaScript for multi requests (#4719). :bowtie: 

This is affecting code in other places and not only in multiple request. But I would say it is more likely that I fix with it something somewhere else as that I break it. :rofl: I checked the UI and I didn't find anything broken, but it would be great if someone can double check it. :smile:

### CODE REVIEW

**Comment by ChrisBr** [comment]
Hm, I'm not sure if this makes sense. Why should the code in groups.js responsible for adding/removing the selected class? I would prefer to have this generic somewhere else.

**Comment by Ana06** [comment]
@ChrisBr 

> Hm, I'm not sure if this makes sense. Why should the code in groups.js responsible for adding/removing the selected class? I would prefer to have this generic somewhere else.

I thought it was the generic code for the tabs... isn't it? it is used like that. Although it is not really generic and then we need to patch it all around the code. :unamused: 

What would you like to do instead? :thinking:

**Comment by Ana06** [comment]
@ChrisBr 

> If it is generic, I wonder why it is in a file called group.js, doesn't make sense, right?
> 
> I would like to get this code then into a place where it makes sense (e.g. application.js ?). Anyway, I would never look into groups. js if the JS is broken on the request page, right?

The tabs as a group? :thinking: :rofl: 

It is required in the application.js file, so you will finding it when looking there :wink: 

I was thinking about sending a refactoring PR, because this is used **by accident** in other places. What about renaming that file in that other PR to something like `tabs`? This is not really related with the broken javascript.  :thinking:

**Comment by ChrisBr** [comment]
> It is required in the application.js file, so you will finding it when looking there wink

Sure I would find it. But looking at the groups.js file it is clearly about groups in OBS! And it just worked by accident. So that is the whole point about fixing this issue, right? So why not just moving the code which is responsible to for adding / removing the selected group to some other place where it makes more sense, shouldn't be much work I hope :smiley:

**Comment by Ana06** [comment]
@ChrisBr 

> Sure I would find it. But looking at the groups.js file it is clearly about groups in OBS! And it just worked by accident. So that is the whole point about fixing this issue, right? So why not just moving the code which is responsible to for adding / removing the selected group to some other place where it makes more sense, shouldn't be much work I hope

I just didn't want to make big PRs.. but ok, I'll add it here :wink:

**Comment by Ana06** [comment]
The problem of the reload buttons which don't work is also in how the javascript of `buildresult_box` is implemented. But I would suggest to fix that part in another PR once this is merged, to avoid a huge PR. :wink:

**Comment by Ana06** [comment]
[P5: JavaScript for multi requests completely broken](https://trello.com/c/0BUIqLCS/729-p5-javascript-for-multi-requests-completely-broken)

**Comment by ChrisBr** [comment]
Review app is available here: http://10.86.0.147/ana06-javascript/package/show/home:Admin/obs-service-kiwi_import

**Comment by eduardoj** [comment]
Only two typos, in commit messages:
- In the 4th: s/seting/setting/
- In the 5th: s/undertand/understand/

**Comment by eduardoj** [comment]
Another typo in the last commit message: s/Addapt/Adapt/

**Comment by Ana06** [comment]
@eduardoj 

> In the 4th: s/seting/setting/

the commit number is more practical than the number/order of the commits. The order can change and the number is also linked by Github. Just for next time. :wink:

**Comment by coolo** [comment]
indeed

**Comment by eduardoj** [comment]
Another typo in the commit message? s/Makes/Make/ b3fc0ec55c3473617e8ac0365973e1a85eb57f8a

**Comment by Ana06** [comment]
@ChrisBr re-review please! :pray:

**Pull request merged**
