### PR TITLE
Replace FactoryGirlRails with FactoryBotRails

### PR DESCRIPTION
**Pull request by DavidKang**
`factory_girl_rails` project has renamed it to `factory_bot_rails`. So we replaced the gem and all the references to `factory_girl_rails`

### CODE REVIEW

**Comment by DavidKang** [comment]
DO NOT MERGE until the gems are linked to OBS:Unstable

**Comment by hennevogel** [comment]
@DavidKang what about the packages?

**Comment by DavidKang** [comment]
@hennevogel, need to make some changes to the packages.

Submit Requests: 
Factory_bot: https://build.opensuse.org/request/show/538754
Factory_bot_rails: https://build.opensuse.org/request/show/538753

**Comment by hennevogel** [comment]
@DavidKang so when are you going to push for the review? :-)

**Comment by DavidKang** [comment]
@hennevogel, @bgeuken and me we still working on it, yesterday we made some changes to the packages. We hope could merge it soon 😸

**Pull request merged**
