### PR TITLE
[webui] Use can_create_project? in the project policy

### PR DESCRIPTION
**Pull request by hennevogel**
:fire: :fire: :fire:  DO NOT MERGE THIS :fire: :fire: :fire:

I'm just testing my new codeclimate integration :-)

:fire: :fire: :fire:  DO NOT MERGE THIS :fire: :fire: :fire:

### CODE REVIEW

**Comment by bgeuken** [comment]
That's already covered in #1298. See https://github.com/openSUSE/open-build-service/pull/1298/files#diff-370f75ee05a28de50bb17d630cb7aea0R4

**Comment by bgeuken** [comment]
And you replaced the @record with @user again;-)

**Comment by hennevogel** [comment]
Sorry, I'm just testing my new codeclimate integration ;-)

**Comment by hennevogel** [comment]
:fire: :fire: :fire:  DO NOT MERGE THIS :fire: :fire: :fire:

**Comment by adrianschroeter** [comment]
it will actually come with my pull request ...

**Pull request closed without merging**
