### PR TITLE
[webui][api] Use authenticate only in the controllers where it's needed

### PR DESCRIPTION
**Pull request by mdeniz**
Use webui_controller.rb#reset_activexml and #authenticate only in the controllers where it's needed

### CODE REVIEW

**Comment by mdeniz** [comment]
@hennevogel, @bgeuken, @ChrisBr: please review. 
Also think about what to do with the Patchinfo#save method... I think that's unused.

**Comment by hennevogel** [comment]
Can you merge in https://github.com/hennevogel/open-build-service/commit/3436dd777d36acd8d2c4f036ccc299d1f3bb840e

**Comment by mdeniz** [comment]
@bgeuken, I think that's unused, but to be sure I wanted you to review it

**Comment by hennevogel** [comment]
We should fix this up. No need to leave this hanging here...

**Pull request closed without merging**
