### PR TITLE
[api][webui] move Project#cleanup_before_destroy to a service class

### PR DESCRIPTION
**Pull request by evanrolfe**

### CODE REVIEW

**Comment by DavidKang** [comment]
nice work!  👍

**Comment by hennevogel** [comment]
@evanrolfe are you going to address the test suite failures?

**Comment by evanrolfe** [comment]
@hennevogel yes I will when there is time at towards the end of this sprint. Do you prefer that I close this PR and keep the branch locally until I have time to fix the failures?

**Comment by hennevogel** [comment]
Yeah that sounds like a plan...

**Pull request closed without merging**
