### PR TITLE
Move the rest of beta tests out from beta

### PR DESCRIPTION
**Pull request by eduardoj**
Migrate all tests from `spec/features/beta/` that already are tested in `spec/features/`.

The remaining tests left in `spec/features/beta/` are not moved because they are testing the current beta features: "notifications_redesign" and "user_profile_redesign".

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Review by dmarcoux — APPROVED** [review]

**Comment by eduardoj** [comment]
@dmarcoux, I revisited the tests, and the calls to `skip_on_mobile` in `users/admin_configuration_spec.rb` were not needed, so I removed them. I also added back the `users/profile_spec.rb` in beta. Please review it again.

**Comment by dmarcoux** [comment]
@eduardoj What is the reason for putting `users/profile_spec.rb` back in the beta folder? Looking at the spec, it's not testing anything related to a feature flag. It's only testing the elements to join/leave the beta program.

**Comment by eduardoj** [comment]
@dmarcoux:

> @eduardoj What is the reason for putting `users/profile_spec.rb` back in the beta folder? Looking at the spec, it's not testing anything related to a feature flag. It's only testing the elements to join/leave the beta program.

I added it because it tests elements inside the user profile page, so it is related to the "user_profile_redesign" feature flag. Currently we are not testing the "user_profile_redesign" flag in beta, but I wanted to prevent the back and forth of removing the file now and adding it again in a following pull request that adds the user_profile_redesign" flag to beta.

**Comment by dmarcoux** [comment]
I'm kind of divided on this. You are right, we need to test this with and without the feature flag `user_profile_redesign`. I would prefer to not copy the file if possible.

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
