### PR TITLE
[webui] redirect logins from /user/do_login to :home

### LINKED ISSUE #1557: OBS 2.6.8: login from /user/do_login page redirects to 404 page
Reproducible with OBS appliance (obs-server.x86_64-2.6.8-Build1.10.install.iso).

Steps to reproduce:

1. click on login button at top-right of webui
2. try to login with the wrong password
3. you are redirected to the /user/do_login page
4. try to login with the correct password
5. get 404 page

Problem introduced in commit f6c9a14e6370596daaabc82bde3a119a06d81f22

### PR DESCRIPTION
**Pull request by cschneemann**
Logins from /user/do_login page redirects to th 404 page because a get route for /user/do_login is missing, redirecting into :home to fix that.

this commit fixes #1557

### CODE REVIEW

**Comment by bgeuken** [comment]
I think the right way to fix this would be to always redirect to the user's home, if login was successful.
That would be here: https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/user_controller.rb#L39

**Comment by cschneemann** [comment]
Yes, that's 'a bit' nicer, so I will adapt the pull request together with the test case

The route was called with get, because that was what have been done by the code. Björn pointed to the right place for a better fix without touching routes.

**Comment by adrianschroeter** [comment]
@bgeuken we just fixed a bug where people complained that they do no stay on their visited page after login. An enforced redirect to home sounds wrong to me therefore.

**Comment by cschneemann** [comment]
The user should just be redirected to home if he was on the /user/do_login page directly, because of a mistyped password in the dropdown.
If he logs in from that page he will be logged in, but sees the login-form again in master, in the 2.6.8 code he is not allowed to load that page and the 404 is shown. So simply redirecting to home would be good for the 2.6.8.

**Comment by bgeuken** [comment]
@adrianschroeter @cschneemann  Ah, I had this page in mind https://build.opensuse.org/user/login Didn't think the ui widget would be involved. Sorry for misleading you.

But introducing a new route sounds like a workaround. I would think there is some broken redirect. So you say /user/do_login is accessible in 2.6 via browser?

**Comment by cschneemann** [comment]
@bgeuken /user/do/login is not accessible directly (with a get from a browser), but it seems that you will be redirected there with a POST to try again when you passed wrong login data to the dropdown/widget. After that you are redirected to the last page you came from and this time it is /user/do_login. In 2.6.8 this page is not accessible by a GET, therefor the quick fix with the additinal route, in current master you are logged in, but see the /user/do_login page.

Reproduce:
go to obs
- click "login"
- enter wrong credentials in dropdown/widget
- enter correct credentials on the form you are redirected to

I try to put that into a testcase, but that's new to me ;)

**Comment by bgeuken** [comment]
And our tests are not exactly easy to read;-)

Took me a while, but what seems to work is this, in the do_login action:
```ruby
    if request.referer.end_with?("/user/login")
      redirect_to home_path
    else
      redirect_back_or_to root_path
    end
```

Most likely that would also work in 2.6

**Comment by cschneemann** [comment]
@bgeuken tested with 2.6, works there. So decline my pull request and take yours? ;)

**Comment by adrianschroeter** [comment]
@cschneemann we still want a test documenting this changed behaviour. Can you provide this together with the changed code proposal from @bgeuken ?

**Comment by cschneemann** [comment]
OK, see pull requst #1618, code from @bgeuken and a testcase for this.

**Pull request closed without merging**
