### PR TITLE
BuildResult

### PR DESCRIPTION
**Pull request by DavidKang**

### CODE REVIEW

**Comment by dmarcoux** [comment]
Refreshing the build results is making the collapsed repositories to flicker.

flicker

**Comment by DavidKang** [comment]
@dmarcoux, no, is not on purpose

**Comment by DavidKang** [comment]
@dmarcoux, this is happening with Chrome, I will have a look

**Comment by dmarcoux** [comment]
With Firefox too

**Comment by DavidKang** [comment]
@dmarcoux, could you review it again please? :smile_cat:

**Comment by DavidKang** [comment]
@dmarcoux, sure :+1:

**Comment by DavidKang** [comment]
First I need to talk with @dmarcoux, I will reopen it if I continue working on it.

**Comment by dmarcoux** [comment]
Oh I completely forgot about this.

**Pull request closed without merging**
