### PR TITLE
Revert "[webui][api] Backend files classes"

### PR DESCRIPTION
**Pull request by mdeniz**
Reverts openSUSE/open-build-service#1184

### CODE REVIEW

**Comment by bgeuken** [comment]
@mdeniz What's the reason for reverting it? It's not mentioned in the commit messge

**Comment by mdeniz** [comment]
@bgeuken I broke master. That's all. 14 days waiting to be merged... but was wrong. I prefer to revert and let master be ok. When I finish the fixing I will resend the PR.

**Comment by bgeuken** [comment]
I see. Next time please add the reason for reverts to the commit message:-)

**Comment by mdeniz** [comment]
Ok. I will.

**Pull request merged**
