### PR TITLE
[ci] Fix project_spec to work on fresh backend

### PR DESCRIPTION
**Pull request by coolo**
The original author of the test had the test running on a backend
with multiple runs of delete/undelete on the same backend and
recorded this into a VCR. Making it impossible to run the test
on a fresh backend to regenerate the cassette

### CODE REVIEW

**Comment by coolo** [comment]
The funny part of this is: the cassette is just a year old.

62daff32c7ad133b8a463212d76a8cb44b492b6e added some 404 to the cassette, which have noting to do with the test if run on any backend and are just consequence of running cassettes on changed . 

So if team members tell me, they always regenerate cassettes that change...


These stale VCRs really do nothing but hiding bugs and need go *GO*

**Comment by hennevogel** [comment]
> These stale VCRs really do nothing but hiding bugs and need go GO

Of people do the right thing and people review the right thing :-)

**Comment by hennevogel** [comment]
codecov hangs... merging.

**Comment by coolo** [comment]
@ChrisBr and me just found out the reason for codecov hangs: if you only have commits with [ci] prefix, codecov does not bother commenting

**Pull request merged**
