### PR TITLE
[ci] Split the test suite again

### PR DESCRIPTION
**Pull request by hennevogel**
* Split of the spider test and remove it from test coverage

### CODE REVIEW

**Comment by hennevogel** [comment]
This also means that it won't run locally with `rake test:webui` anymore...

**Comment by adrianschroeter** [comment]
can you also adapt the spec file this please?

**Comment by hennevogel** [comment]
@adrianschroeter the one in dist or the one in the project?

**Comment by adrianschroeter** [comment]
the one in dist/ directory is used inside of the project.

**Comment by hennevogel** [comment]
@adrianschroeter done

**Comment by bgeuken** [comment]
LGTM

**Comment by mdeniz** [comment]
LGTM :+1:

**Pull request merged**
