### PR TITLE
Revert package webui fix 2.6

### LINKED ISSUE #1438: "Revert to revision" ignores revision
https://build.opensuse.org/package/submit_request_dialog/project/package?revision=42&target_project=project will submit the latest version which completely defeats the purpose of reverting.

### PR DESCRIPTION
**Pull request by tuminoid**
Fixes #1438 for 2.6.

### CODE REVIEW

**Comment by hennevogel** [comment]
@adrianschroeter do you want to fix this in 2.6?

**Comment by adrianschroeter** [comment]
it is fine to merge it into 2.6 if tested in master. We won't release a now 2.6 release though.

And we should merge it also in 2.7 if we take it for 2.6.

**Comment by adrianschroeter** [comment]
JFYI, pull request for 2.7 is here: https://github.com/openSUSE/open-build-service/pull/2291

**Comment by bgeuken** [comment]
Alright, I've merged #2291 and cherry-picked the commit into 2.6 as well

**Pull request merged**
