### PR TITLE
Rename exeption objects to e

### PR DESCRIPTION
**Pull request by coolo**
This is a new default rubocop introduced with 0.67.2 and I agree with it

You can find details at https://rubocop.readthedocs.io/en/latest/cops_naming/#namingrescuedexceptionsvariablename

Please vote @openSUSE/obs-frontend

### CODE REVIEW

**Comment by eduardoj** [comment]
> Please vote @openSUSE/obs-frontend

I agree.

**Comment by hennevogel** [comment]
And why is there no cop configuration?

**Comment by coolo** [comment]
It's default - once rubocop releases a fixed version containing this cop, 0.67.2 was rejected due to 2 bugs, but the cop is real. We can have fixes for cops not yet released, no? :)

**Comment by coolo** [comment]
It claims to support it - and also prints out Cs during progress, but doesn't change the code :)

And depfu sent a PR, that I closed due to a bug in that rubocop version

**Comment by coolo** [comment]
I only cherry picked the fixes

**Pull request merged**
