### PR TITLE
Improve UX of new request#show

### PR DESCRIPTION
**Pull request by dmarcoux**
For reviewers, see https://obs-reviewlab.opensuse.org/dmarcoux-request-multiple-actions-hint/request/show/9

Before:
before

After:
after

### CODE REVIEW

**Comment by dmarcoux** [comment]
[Request action dropdown improvements (L)](https://trello.com/c/usNPBwRc/2097-request-action-dropdown-improvements-l)

**Comment by danidoni** [comment]
I think the dropdown should display the index of the action, otherwise telling the user is looking at action number 12 without any other reference leaves the user to count the actions from the top. For requests with a couple of actions there is no problem, but with actions with more than 10 actions it can be disorienting...

**Comment by dmarcoux** [comment]
@hellcp-work @danidoni I pushed changes to address the issues you mentioned in your comments. Here's a preview of the changes. Once with some revision comments and once without:

changes
changes-2

**Comment by dmarcoux** [comment]
> Revision looks missing in those

It's because the revisions aren't there. I faked it in the other screenshot. I guess removing the `Revision` header could be a solution, but it involves checking all details of every action...

**Review by danidoni — APPROVED** [review]

**Pull request merged**
