### PR TITLE
[frontend] Adopt FullTextSearch to thinking sphinx changes

### LINKED ISSUE #3727: [production][delayed_job#Delayed::PerformableMethod] undefined local variable or method `logger' for #<FullTextSearch:0x0000000712ca30 @result=nil>
delayed_job#Delayed::PerformableMethod threw this 0 times
<pre>
undefined local variable or method `logger&#39; for #&lt;FullTextSearch:0x0000000712ca30 @result=nil&gt;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a7ebe56180760006d01f0d)

### LINKED ISSUE #3737: [production][delayed_job#Delayed::PerformableMethod] undefined method `index' for #<ThinkingSphinx::RakeInterface:0x00000005d03a90>
delayed_job#Delayed::PerformableMethod threw this 160 times
<pre>
undefined method `index&#39; for #&lt;ThinkingSphinx::RakeInterface:0x000000062ff430&gt;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a836306180760014d02073)

### PR DESCRIPTION
**Pull request by hennevogel**
Thinking sphinx split it's rake tasks between realtime indexes and sql indexes. See https://github.com/pat/thinking-sphinx/releases/tag/v3.4.0

Fixes #3727 
Fixes #3737

### CODE REVIEW

**Comment by hennevogel** [comment]
@eduardoj please re-review

**Comment by eduardoj** [comment]
I shouldn't remove the `begin rescue` block for `interface.sql.index`. It could be that for some reason the thinking-sphinx daemon is down and the `interface.daemon.start` line is not reached.

I would only remove the line of the retry.

**Comment by hennevogel** [comment]
Well then we should switch this around...

**Comment by hennevogel** [comment]
Fixed in #3741

**Pull request closed without merging**
