### PR TITLE
Track syntax changes in db/structure.sql

### PR DESCRIPTION
**Pull request by dmarcoux**
When I ran the last migrations with `bundle exec rake db:migrate`, those changes happened.

### CODE REVIEW

**Comment by hennevogel** [comment]
ran where?

**Comment by dmarcoux** [comment]
> ran where?

In my local development environment with Docker.

**Comment by hennevogel** [comment]
> In my local development environment with Docker.

Which is different to what we CI/use in production and those syntax changes are mariadb version dependent....

**Comment by hennevogel** [comment]
It's also why the test fails :smile:

**Pull request closed without merging**
