### PR TITLE
Navigation through bs requests via keyboard shortcuts

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
First test balloon. There are a couple of other places were we could have this. Though if we go for it, we should provide some cheatsheet, and / or make the shortcuts visible

**Comment by ChrisBr** [comment]
Nice :+1:

**Comment by hennevogel** [comment]
Have you packaged the gems?

**Comment by bgeuken** [comment]
They are packaged in d:l:r:e. We'll just have to link them

**Comment by hennevogel** [comment]
Please rebase, link packages and merge 👍 :-)

**Pull request merged**
