### PR TITLE
Skip callbacks on IssueTracker.issues_updated

### PR DESCRIPTION
**Pull request by hennevogel**

### CODE REVIEW

**Comment by ChrisBr** [comment]
The _WHY_ would be interesting :smile: Please also add it to the commit message!

**Comment by hennevogel** [comment]
@ChrisBr better?

**Comment by ChrisBr** [comment]
To avoid the after_save callbacks     
```
after_save :delayed_write_to_backend
after_save :update_package_meta
```

**Comment by ChrisBr** [comment]
LGTM

**Pull request merged**
