### PR TITLE
Fix live build log

### LINKED ISSUE #4625: live build log repeats logs instead of appending linearly
Issue/Feature description
====================
Live build log, when updating appends parts of logs, that were already displayed. This makes the web page grow rapidly.

Expected result
============
Live build log should be updated linearly.

How to Reproduce
===============
Watch any live build log on build.opensuse.org

### PR DESCRIPTION
**Pull request by mdeniz**
Before the last part of the log was being added over and over again to the live log instead of showing it linearly without duplicating any part of it.

It fixes #4625

### CODE REVIEW

**Comment by hennevogel** [comment]
What I don't understand, how did this break?

**Comment by Ana06** [comment]
@hennevogel 

> What I don't understand, how did this break?

It seems it has been always broken :no_mouth:

**Comment by coolo** [comment]
No, it works fine on e.g. https://pmbs.links2linux.de/monitor

**Comment by Conan-Kudo** [comment]
@coolo pmbs and other OBS 2.8 systems are fine. OBS 2.9 ones are busted on the live build logs...

**Comment by coolo** [comment]
wow, as this is deployed on IBS now I have to tell you: this made live logs much worse (or something else but I doubt it). Now if I go into a live log the log is fetched 2K per second or so until it reaches the end. It used to start 2K from the end and then fetch more. Now it takes a minute until I'm seeing the end.

**Comment by coolo** [comment]
Also OBS is deployed, so it's easier to share links there.

Go to a long running build of e.g. https://build.opensuse.org/package/live_build_log/multimedia:libs/pulseaudio/openSUSE_Factory_ARM/armv7l (as of writing it runs for 14 days, so I assume it will run some more :)

The live log starts from the beginning and builds up piece by piece - and I'm sure it will kill my browser at some point.

**Comment by mdeniz** [comment]
Late that you see it... can you please open an issue and label it properly :smile: 

> Now if I go into a live log the log is fetched 2K per second or so until it reaches the end

No is not, see that the max size of the data fetched is 64K... could be that the log is written at 2k/s and you saw it that way but the code is loading the last 32K/s (64K every 2 secs) if there are enough data to fill that, if not only what is there available. See https://github.com/openSUSE/open-build-service/pull/4663/files#diff-40ffe899764c55c2f7bf66c7f24f4942R820

> The live log starts from the beginning and builds up piece by piece 

It starts from the beginning if is not finished... can you point to this in the issue?

**Comment by coolo** [comment]
32K/s *is* within '2K/s or so' :)

**Comment by coolo** [comment]
It's 7K here - but you have https://github.com/openSUSE/open-build-service/issues/4708 now

**Pull request merged**
