### PR TITLE
project_monitor.js: sort unfinished status codes before finished codes

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by dmarcoux** [comment]
Hey @andreas-schwab,

Thank you for submitting this PR. Could you explain why this is needed? Could you also add screenshots to preview what this changes?

**Comment by andreas-schwab** [comment]
It doesn't make sense having to scroll through hundreds of empty rows.

**Comment by hennevogel** [comment]
>  empty rows

Hm, when do you run into a project that has hundreds of packages that don't have a build status code?

**Comment by andreas-schwab** [comment]
You see it in any larger project.

**Comment by hennevogel** [comment]
> You see it in any larger project.

I don't think this does what you think it does. If a package has no build results for any repo/arch (if it's build disabled) it's not shown on the monitor page at all. If a package has a result for any repo/arch, the whole row is shown. So there are no empty rows, rows always contain something.

If you sort a **column**, empty cells are at the bottom (with or without your change). 

So what is it you actually try to achieve? :)

**Comment by andreas-schwab** [comment]
> So there are no empty rows, rows always contain something.

Nope.

> If you sort a column, empty cells are at the bottom (with or without your change).

Nope.

**Pull request closed without merging**
