### PR TITLE
Fix several file upload issues

### PR DESCRIPTION
**Pull request by ChrisBr**
* Fix package add file validations  (#5980)
* Hide overflow of long filenames (#5979)

### CODE REVIEW

**Comment by mdeniz** [comment]
What about screenshots?

**Comment by ChrisBr** [comment]
> What about screenshots?

image


The validation issue is functional so you have to try it, I can't provide a screenshot :smile: Maybe @bgeuken wants to have a look as he reported it.

**Comment by mdeniz** [comment]
> The validation issue is functional so you have to try it, I can't provide a screenshot smile Maybe @bgeuken wants to have a look as he reported it.

Sure, you can use a gif if you think is better :smile:

**Comment by ChrisBr** [comment]
> Sure, you can use a gif if you think is better smile

Hm, not really because it is a very weird behavior which only occurs if you write & remove something to two different input fields. I think creating a gif will be more work as just trying it quickly on the review app :thinking:

**Pull request merged**
