### PR TITLE
[api] harmonize Repository.find_by name with other models

### PR DESCRIPTION
**Pull request by adrianschroeter**
find_by_project_and_repo_name => find_by_project_and_name

### CODE REVIEW

**Comment by hennevogel** [comment]
# Rubocoped!

h20e7396d

**Comment by mdeniz** [comment]
NICE!!

**Comment by bgeuken** [comment]
LGTM, though you need to rebase on master to get the travis tests fixed.

**Comment by hennevogel** [comment]
And why don't you send separate pull-requests for separate features next time? :-)

**Comment by bgeuken** [comment]
@hennevogel Probably for the same reason you add separate changes in one commit;-)

**Pull request merged**
