### PR TITLE
[api] Add migration of BsRequestAction

### PR DESCRIPTION
**Pull request by DavidKang**
We add again the indexes that were removed in the following PR
https://github.com/openSUSE/open-build-service/pull/3212

### CODE REVIEW

**Comment by bgeuken** [comment]
Was that slowing down the bs request related pages?

**Comment by ChrisBr** [comment]
@bgeuken What do you mean with
```
Was that slowing down the bs request related pages?
```

**Comment by bgeuken** [comment]
IIRC you were mentioning last Friday that loading times got worse. So I wondered if that might be related. But seems it's not.

**Comment by ChrisBr** [comment]
Grml, just tested it on my machine and it has a big impact on User#incoming_requests, from <100 ms now to more than 2 seconds... 
Please don't merge migrations before we tested it :cry: 

@DavidKang @bgeuken

**Pull request merged**
