### PR TITLE
[backend] Remove publishing penalty for good

### LINKED ISSUE #3776: Publisher penalty too cruel
We have a OBS instance here that basically builds a single repository with tons of ISOs - let's call them SLE. 

Most of the day the publisher has nothing to do but syncing these ISOs somewhere else. But it refuses to do so and just says 'not yet'. This is hurting our dead lines massively and is pretty nonsense too as there is no other publish event to worry about in that time waiting.

### PR DESCRIPTION
**Pull request by coolo**
Fixes #3776

### CODE REVIEW

**Comment by adrianschroeter** [comment]
We don't shortcut the fuse, just because it always reacts to your hairdryer under water ...

Seriously, we don't return to the problem that maintenance updates could get blocked for days due to factory builds.

**Comment by coolo** [comment]
You seriously misunderstand how queues work. Let's take your maintenance update example:

If it takes an hour to publish the kernel update and then notice that the kernel has a broken dependeny and try to add a little thing to the repo, you have to wait 5 hours before the publisher will look at it again *even if there is nothing else to do*.

Factory builds are not involved there. If you have important and unimportant publish events, then implement a priorization queue instead of adding sleeps in a FIFO. This sleep is harmful and nothing else.

**Comment by mlschroe** [comment]
Closing.

**Comment by hennevogel** [comment]
*grabs* 🍿

**Pull request closed without merging**
