### PR TITLE
Add back removed files after rebase of staging-workflow

### PR DESCRIPTION
**Pull request by dmarcoux**
This was removed by mistake in the rebase on master.

### CODE REVIEW

**Comment by dmarcoux** [comment]
Hum... I don't see the connection with the failing specs and these partials.

**Comment by DavidKang** [comment]
Now everything makes sense after the rebase :smile_cat:

**Comment by vpereira** [comment]
@dmarcoux your name appears in all commits now https://github.com/openSUSE/open-build-service/commits/staging-workflow :see_no_evil:

**Comment by dmarcoux** [comment]
I don't know what's up with CircleCI, but if you look at the checks tab, it passed. Somehow, it's not updated in the pull request overview (so the conversation tab)

**Comment by coolo** [comment]
if it's running as app, it only creates a check and reports 'test_all' as status. This branch requires the outdated ones.

**Pull request merged**
