### PR TITLE
[webui] Show outdated icon when the build result is dirty.

### PR DESCRIPTION
**Pull request by evanrolfe**
Fixes https://github.com/openSUSE/open-build-service/issues/3386

### CODE REVIEW

**Comment by evanrolfe** [comment]
@coolo this is what the build result looks like when you trigger a rebuild of the package:
screenshot from 2017-09-06 13-38-37

**Comment by evanrolfe** [comment]
[(3) P1: Dirty flag not shown on project/show](https://trello.com/c/ljEfmdvk/526-3-p1-dirty-flag-not-shown-on-project-show)

**Comment by coolo** [comment]
(review from screenshot) good :)

**Comment by ChrisBr** [comment]
@evanrolfe please rebase!

**Pull request merged**
