### PR TITLE
[ci] Migrate CSRF test to RSpec

### PR DESCRIPTION
**Pull request by mdeniz**
Migrate CSRF test to RSpec

### CODE REVIEW

**Comment by hennevogel** [comment]
I don't get the travis failure. Do you need to rebase?

**Comment by mdeniz** [comment]
No. I'm updated... I will try just rerunning the webui suite

**Comment by mdeniz** [comment]
You see.. Travis Flickering... :smiley:

**Comment by hennevogel** [comment]
Looks good to me! :ship: this :hankey: !

**Pull request merged**
