### PR TITLE
Fix issue #8516. Build state failed link should remain the same color…

### PR DESCRIPTION
**Pull request by AshNaz87**
… on hover

### CODE REVIEW

**Comment by DavidKang** [comment]
Hi @AshNaz87, thanks for your contribution :smile_cat:.

Just a few things, I think your branch is not updated with master. That the reason why the linters are complaining. Regarding the title of the commit, please doesn't add the issue number, instead of that you could add it at the end of the commit description like `fix #XXXX`. And if is possible when you made visual changes, it will be good if you provide some screenshots.

**Comment by coolo** [comment]
I don't think the index has anything to do with the hover

**Comment by saraycp** [comment]
> I don't think the index has anything to do with the hover

True! we wrote the wrong issue number. :+1:

**Comment by DavidKang** [comment]
@AshNaz87, do you need help? :smile_cat:

**Comment by AshNaz87** [comment]
@DavidKang Are the steps straightforward in terms of setting up?

Thing the task itself is not so bad

**Comment by hennevogel** [comment]
move to #9132 

sorry this took so long :disappointed:

**Pull request closed without merging**
