### PR TITLE
Refactor ldap mock

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@evanrolfe Please review

**Comment by bgeuken** [comment]
The linter is currently failing because it does not allow commit messages starting with "Revert". I am creating another PR fixing this.

**Comment by evanrolfe** [comment]
@bgeuken how do you know this will fix travis? Since before all the changes to UserLdapStrategy spec passed travis in the PR but failed once merged to master.. I propose that we just delete this spec for now and refactor UserLdapStrategy so it doesn't use class variables as "pseudo instance variables".

**Comment by bgeuken** [comment]
@evanrolfe I ran the whole spec in master (before the revert) and it failed with one of these failures. I ran the whole spec in this PR and it worked.

And if it turns out that it fails after merging regardless, we have fix the test suite. Dropping it is no option:-)

**Comment by bgeuken** [comment]
And it seems we still have these errors. At least they appear in some of the current PRs. And for some I know for sure that they have the test removal commit.

**Pull request merged**
