### PR TITLE
[api] Fix branch_remote_repositories not to rely on cache

### LINKED ISSUE #5319: Buggy test: Project#branch_remote_repositories
c0a3edadf1 from @Ana06 added the test and following comment:

```
# WARNING: If you need to make a Backend call uncomment the following line
# CONFIG['global_write_through'] = true
```

If I uncomment this, I get failures - the problem seems to be masked by just not calling the functions deleting the repository as they return without global_write_through.

I have no idea what the purpose of the test is

````
Project
  #branch_remote_repositories
    normal project
      keeps original repository
        should be empty (FAILED - 1)
        should be empty (FAILED - 2)
        should eq #<Repository id: 7, db_project_id: 5, name: "xUbuntu_14.04", remote_project_name: "", rebuild: nil, block: nil, linkedbuild: nil, hostsystem_id: nil> (FAILED - 3)

Failures:

  1) Project#branch_remote_repositories normal project keeps original repository should be empty
     Failure/Error: it { expect(old_repository.architectures).to be_empty }
       expected `#<ActiveRecord::Associations::CollectionProxy [#<Architecture id: 35, name: "x86_64", available: true>]>.empty?` to return true, got false
     # ./spec/models/project_spec.rb:157:in `block (5 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

  2) Project#branch_remote_repositories normal project keeps original repository should be empty
     Failure/Error: it { expect(old_repository.path_elements).to be_empty }
       expected `#<ActiveRecord::Associations::CollectionProxy [#<PathElement id: 2, parent_id: 5, repository_id: 6, position: 1>]>.empty?` to return true, got false
     # ./spec/models/project_spec.rb:158:in `block (5 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

  3) Project#branch_remote_repositories normal project keeps original repository should eq #<Repository id: 7, db_project_id: 5, name: "xUbuntu_14.04", remote_project_name: "", rebuild: nil, block: nil, linkedbuild: nil, hostsystem_id: nil>
     Failure/Error: it { expect(old_repository).to eq(repository) }
     
       expected: #<Repository id: 7, db_project_id: 5, name: "xUbuntu_14.04", remote_project_name: "", rebuild: nil, block: nil, linkedbuild: nil, hostsystem_id: nil>
            got: #<Repository id: 8, db_project_id: 5, name: "openSUSE_42.2", remote_project_name: "", rebuild: nil, block: nil, linkedbuild: nil, hostsystem_id: nil>
     
       (compared using ==)
     
       Diff:
       
       @@ -1,7 +1,7 @@
       -#<Repository:0x0000000008920560
       - id: 7,
       +#<Repository:0x00000000081e9990
       + id: 8,
         db_project_id: 5,
       - name: "xUbuntu_14.04",
       + name: "openSUSE_42.2",
         remote_project_name: "",
         rebuild: nil,
         block: nil,
       
     # ./spec/models/project_spec.rb:156:in `block (5 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

Finished in 4.93 seconds (files took 4.27 seconds to load)
3 examples, 3 failures

Failed examples:

rspec ./spec/models/project_spec.rb:157 # Project#branch_remote_repositories normal project keeps original repository should be empty
rspec ./spec/models/project_spec.rb:158 # Project#branch_remote_repositories normal project keeps original repository should be empty
rspec ./spec/models/project_spec.rb:156 # Project#branch_remote_repositories normal project keeps original repository should eq #<Repository id: 7, db_project_id: 5, name: "xUbuntu_14.04", remote_project_name: "", rebuild: nil, block: nil, linkedbuild: nil, hostsystem_id: nil>

Randomized with seed 6403

### PR DESCRIPTION
**Pull request by coolo**
to_axml reads from Rails.cache but as the function mungles
the XML on a raw base, better use the direct XML not the
cached one.

This avoids races a little better - and fixes #5319

### CODE REVIEW

**Comment by coolo** [comment]
@Ana06 - it's your test, please review

**Comment by coolo** [comment]
As @Ana06 is on vacation now, could someone else review this?

**Comment by coolo** [comment]
it's been a week...

**Comment by hennevogel** [comment]
> it's been a week...

That's whats happening if you limit the bus factor to :one:

**Pull request merged**
