### PR TITLE
[dist] Fetch up-to-date user agents config file before each package build

### PR DESCRIPTION
**Pull request by bgeuken**
That config file contains all known crawler bots and is used by voight-kampff gem
to identify and lock out spiders (as we call them in OBS).

Config file get's fetched by an OBS service from
  https://github.com//monperrus/crawler-user-agents/blob/master/crawler-user-agents.json

### CODE REVIEW

**Comment by bgeuken** [comment]
This makes sure that our obs-server packages come with the most recent version of crawler-user-agents.json. That config will also be used in the test suite of our package builds.

The file won't be part of our git repo so that we don't have to track and manually update that file. Instead the conf that comes with the voight_kamff gem will be used.

Everyone fine with this? @openSUSE/open-build-service

**Comment by hennevogel** [comment]
LGTM

**Comment by hennevogel** [comment]
Hm and where is this file coming from then?

**Comment by bgeuken** [comment]
@hennevogel from https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json

I've updated the _service for our packages to fetch that file before each build

**Pull request merged**
