### PR TITLE
Introduces Rubocop

### PR DESCRIPTION
**Pull request by hennevogel**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
It looks like the robocop test would only run on travis but nowhere else by default?

doesn't it make sense to make it an own test part of unit/code_quality test?

**Comment by bgeuken** [comment]
I would propose to
  - Merge this one
  - Do a follow up commit to integrate this into our local tests
  - Discuss what other conventions we want to add and if we should use the new SUSE styleguide.

**Comment by bgeuken** [comment]
Or maybe better: We discuss this today, all together, and adjust the rubocop file acordingly.

**Comment by ChrisBr** [comment]
+1

Would also suggest to discuss this today and adjust the rubocop file together

**Comment by hennevogel** [comment]
I would like to discuss this when @adrianschroeter is around, he isn't in the next 2 days...

**Pull request merged**
