### PR TITLE
Move leftover bootstrap feature tests to the main feature tests

### PR DESCRIPTION
**Pull request by krauselukas**
While removing the bento ui, a few feature test haven't
been moved from the seperate bootstrap folder to the main's
feature test folder.

### CODE REVIEW

**Comment by hennevogel** [comment]
We don't use `MonitorPage` anymore?

**Comment by krauselukas** [comment]
> We don't use `MonitorPage` anymore?

@hennevogel I couldn't find a place where its used, let's see, if its used the test's should fail right :D

**Comment by krauselukas** [comment]
@hennevogel but yeah, its strange that it is not used anymore, so I will double check if a feature test got accidentally removed :)

**Comment by krauselukas** [comment]
@hennevogel I created a seperate commit for removing the unused support module

**Pull request merged**
