### PR TITLE
Enable SymbolProc Rubocop cop

### PR DESCRIPTION
**Pull request by Ana06**
Enable `SymbolProc` Rubocop cop and automatically solve the the offenses. :bowtie:

### CODE REVIEW

**Comment by Ana06** [comment]
[Enable Style/SymbolProc Rubocop cop](https://trello.com/c/kHHItoGt/244-enable-style-symbolproc-rubocop-cop)

**Comment by bgeuken** [comment]
The 2 commits belong together, don't they?

**Comment by Ana06** [comment]
@bgeuken 
> The 2 commits belong together, don't they? Why did you split them?

Because we agreed here to split them: https://github.com/openSUSE/open-build-service/pull/2328  :slightly_smiling_face: 

I would prefer to put it 1 commit but we should be consistent.

**Comment by bgeuken** [comment]
@Ana06 Hm, na gut.

**Pull request merged**
