### PR TITLE
Fixes and tracking extension for media

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by coolo** [comment]
could you rebase on the submodule update?

**Comment by DavidKang** [comment]
@adrianschroeter, what's the state of this PR?

**Comment by DavidKang** [comment]
Circle-CI passed: https://circleci.com/workflow-run/2cd4c9a3-f165-4349-88c4-256ea98937d2

**Comment by adrianschroeter** [comment]
On Dienstag, 2. Juni 2020, 12:54:17 CEST wrote David Kang:
> @adrianschroeter, what's the state of this PR?

dunno, but in production since several month

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by hennevogel** [comment]
coveralls hangs. codecov is fine. merging!

**Pull request merged**
