### PR TITLE
Adapt rails generator to create primary keys as unsigned int by default

### PR DESCRIPTION
**Pull request by vpereira**
Rails since version 5.1 has all primary keys being created as `Bigint` by default.  We changed it [back in the days](https://github.com/openSUSE/open-build-service/pull/3809), rolling it back to `integer` and forcing it in our [generators](https://github.com/openSUSE/open-build-service/pull/5610). We should however be doing it using [unsigned int instead of int](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html).

How to test it:

- Pull the branch
- `rails g model foo name:string`
- `rails db:migrate`
- check your `schema.db`

```
# schema.rb

+  create_table "foos", id: :integer, unsigned: true, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
+    t.string "name"
+    t.datetime "created_at", precision: 6, null: false
+    t.datetime "updated_at", precision: 6, null: false
+  end
+
```

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [x] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Comment by vpereira** [comment]
[Do research about using another data type for notification id](https://trello.com/c/t1vrsI1o/1607-do-research-about-using-another-data-type-for-notification-id)

**Comment by coolo** [comment]
going bigint is still the correct thing to do. The worry back then was that you can't create foreign keys towards int if `integer` is bigint - which is true. But the primary key id can still be bigint and foreign keys can be `t.bigint`

You actually have the same problem with what you're proposing. If the primary key default is unsigned int, then every new foreign key needs to specify this and plain `integer` wouldn't do any longer.

**Comment by vpereira** [comment]
> going bigint is still the correct thing to do. The worry back then was that you can't create foreign keys towards int if `integer` is bigint - which is true. But the primary key id can still be bigint and foreign keys can be `t.bigint`
> 
> You actually have the same problem with what you're proposing. If the primary key default is unsigned int, then every new foreign key needs to specify this and plain `integer` wouldn't do any longer.

Hi @coolo 

Hm interesting. After some initial tests, I couldn't spot any issues (I'm able to get notifications and display it in the UI) in the branch https://github.com/openSUSE/open-build-service/pull/10715. I think after ruby 2.4, where `BigNum` and `FixNum` got merged into `Integer` maybe even the old issue was gone too?

**Comment by coolo** [comment]
How ruby names the types doesn't matter to mariadb.

**Comment by coolo** [comment]
What's most important is the foreign key and the primary key it refers to have the same range. So if something fails for int vs bigint, it will fail also with int vs unsigned int. If something works for int vs unsigned int, it will also work for int vs bigint.

Now the problem is, I don't *really* understand what the problem with bigint back then was. New tables using bigint can't be the problem (which was reverted), I assume it's rather adding new foreign keys to existing tables. But even in `t.references` you use `type: :integer` or `type: :bigint` (any idea how to give unsigned int there?). Possibly that option was given in later rails versions?

**Comment by vpereira** [comment]
> How ruby names the types doesn't matter to mariadb.

Yes sure, 

> How ruby names the types doesn't matter to mariadb.

I thought you are talking about the rails association, sure, in the DB that's no way to overcomeit

**Comment by vpereira** [comment]
> Possibly that option was given in later rails versions?

Yes. its new. Back in the days, there was no way to do it.

**Comment by vpereira** [comment]
> Yes. its new. Back in the days, there was no way to do it. You will probably to pass `:unsigned_integer`

**Comment by vpereira** [comment]
@coolo https://github.com/rails/rails/blob/main/activerecord/lib/active_record/type/unsigned_integer.rb

**Comment by vpereira** [comment]
> Now the problem is, I don't _really_ understand what the problem with bigint back then was.

I think the problem happens when you have foreign key constraints.

**Comment by vpereira** [comment]
I will close this PR, let's see what the future holds for us :pray:

**Pull request closed without merging**
