### PR TITLE
docs: Replace status.xsd with status.rng

### PR DESCRIPTION
**Pull request by dmach**
Also extend the <data> element with missing attributes:
- sourceproject
- sourcepackage
- targetpackage

### CODE REVIEW

**Comment by dmach** [comment]
For the record, I kept a reference to `status.xsd` in `docs/api/Makefile`
That file contains several xsd files that do not seem to exist already.

**Comment by hennevogel** [comment]
There are also tons of references to it in the old and the new API docu

**Comment by dmach** [comment]
> There are also tons of references to it in the old and the new API docu

My bad, I forgot to attach those changed files. Thanks!
Force-pushed with added `<empty/>` nodes to the schema, hoping that it's going to fix the failing tests.

**Comment by dmach** [comment]
Schema needed another fix - I wrote part of it incorrectly.

**Comment by eduardoj** [comment]
> For the record, I kept a reference to status.xsd in docs/api/Makefile
> That file contains several xsd files that do not seem to exist already.

I'm for removing the  reference to `status.xsd` in `docs/api/Makefile` in this pull request. We could remove the references to the other non-existent `.xsd` files in another pull request.

**Comment by eduardoj** [comment]
> We could remove the references to the other non-existent `.xsd` files in another pull request.

I created #15620.

**Comment by dmach** [comment]
> > For the record, I kept a reference to status.xsd in docs/api/Makefile
> > That file contains several xsd files that do not seem to exist already.
> 
> I'm for removing the reference to `status.xsd` in `docs/api/Makefile` in this pull request. We could remove the references to the other non-existent `.xsd` files in another pull request.

Rebased and removed `status.xsd` from `docs/api/Makefile`

**Review by hennevogel — APPROVED** [review]

**Pull request merged**
