### PR TITLE
Further cleanup BsRequest#webui_infos

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by coolo** [comment]
btw, for a moment I wondered what a "Fürther Cleanup" is. I have some theories...

**Comment by bgeuken** [comment]
*rebased on master*

**Comment by dmarcoux** [comment]
Any news here?

**Comment by bgeuken** [comment]
Closing, this is outdated. I gone have to rebase this on current master and update the code again. Not sure when I find the time for that.

**Pull request closed without merging**
