### PR TITLE
[webui] backport LDAP authentication support to 2.8

### PR DESCRIPTION
**Pull request by evanrolfe**
Part of this card:
https://trello.com/c/9kDKaI22/465-8-p1-improve-tests-for-ldap

### CODE REVIEW

**Comment by evanrolfe** [comment]
I've added DO NOT MERGE, because I want to do a bit more manual testing with this to make sure ldap works as expected in 2.8.

**Comment by evanrolfe** [comment]
This has been tested. Ready for review please team

**Comment by bgeuken** [comment]
Please also update the release notes. If you rebase with the 2.8 branch you find some for 2.8.3 now.

**Comment by evanrolfe** [comment]
@bgeuken I've rebased with 2.8 and update the release notes

**Comment by evanrolfe** [comment]
[(8) P1: Improve tests for LDAP](https://trello.com/c/9kDKaI22/465-8-p1-improve-tests-for-ldap)

**Pull request merged**
