### PR TITLE
Attrib validators

### PR DESCRIPTION
**Pull request by bgeuken**
Cleaning up after 1a7f17d4e06203869a1dc95c7b6b0150c56b49b4

### CODE REVIEW

**Comment by hennevogel** [comment]
Why? :-)

**Comment by bgeuken** [comment]
Sad that I have to explain that, but you can read that [here](https://github.com/bgeuken/open-build-service/commit/eae6ed792d7642d6fff165635f4b4f24075ba1aa):P

Of course I am totally guessing what you mean with your question;-)

**Comment by hennevogel** [comment]
I'm asking because I don't know of a preference for custom validators to be in methods not in classes...

**Comment by hennevogel** [comment]
So you're saying that validatiors have to be generic to be a ActiveModel::Validator? Sounds reasonable :-) 

:+1:

**Pull request merged**
