### PR TITLE
[webui] Fix P1: toggle_sliced_text called with nil

### LINKED ISSUE #2607: Bug in webui post last 'maintenance' update
```
10:06 < DimStar> adrianS: is 'maintenance' over yet? Then we might have an issue: https://build.opensuse.org/request/show/452555 => returns ERROR 500
10:08 < coolo> DimStar: don't worry. the obs team is spammed with the error report every 2 minutes :)
10:08 < coolo> there are some routes that hurt more if broken than others :)
10:09 < coolo> mdeniz1 will fix it quickly I'm sure :)
10:09 < coolo> https://github.com/openSUSE/open-build-service/pull/2594/files#diff-d6b551dedaaae6cce3a56f2afb75ef6fR416 is the crashing line as text is nil
10:16 < henne> DimStar: just open a bugreport. like always
10:18 < henne> DimStar: monkey patched :-)
```

so - there you go

### PR DESCRIPTION
**Pull request by mdeniz**
Fixes #2607

### CODE REVIEW

**Comment by hennevogel** [comment]
LGTM

**Comment by DavidKang** [comment]
LGTM

**Comment by hennevogel** [comment]
`text` will still be nil if it's nil

**Comment by mdeniz** [comment]
Sure, now it should be fixed 😄

**Comment by hennevogel** [comment]
Please also test the nil condition as it quit frequently happens

**Comment by mdeniz** [comment]
Done 😄

**Pull request merged**
