### PR TITLE
Fix version comparison

### PR DESCRIPTION
**Pull request by hiberis**
Fixes: https://github.com/openSUSE/open-build-service/issues/887

### CODE REVIEW

**Comment by adrianschroeter** [comment]
hm, much rpm specific code for just a message? 

IMHO such package format specific things should belong to backend / build parsers. But we need to think about an api and what the webui needs...

**Comment by coolo** [comment]
the mean thing is that this is comparing the package version with the upstream version - which may or may not might be more correct with rpm than with gems. But perl versions will stay wrong. So I don't really see the point

**Comment by adrianschroeter** [comment]
okay, let's close this. Sorry, Hiberis. If you think we miss the point or do not understand the importance you may want to discuss on our mailinglist.

**Comment by jspanjers** [comment]
Closing this is fine by me.

Rethinking this, I conclude that the version comparison method the we should use varies among upstream packages. It might be a nice feature to give a packager the option to specify the specific version comparison method for his upstream. But in the absence of such feature, the best thing the build service can do is chose a sane default version comparison method. The current version comparison method using Gem::Version is such a sane default. The version comparison method using the version comparison logic from RPM that I implemented is also a sane default, but not really better of worse than the current one.

**Comment by hiberis** [comment]
Closing this is fine by me.

Rethinking this, I conclude that the version comparison method that we should use varies among upstream packages. It might be a nice feature to give a packager the option to specify the specific version comparison method for his upstream. But in the absence of such feature, the best thing the build service can do is chose a sane default version comparison method. The current version comparison method using Gem::Version is such a sane default. The version comparison method using the version comparison logic from RPM that I implemented is also a sane default, but not really better of worse than the current one.

**Pull request closed without merging**
