### PR TITLE
[webui] Update _news.html.erb

### PR DESCRIPTION
**Pull request by vpereira**
use the comment_body helper to avoid XSS issues.

### CODE REVIEW

**Comment by hennevogel** [comment]
Not really an issue because this is only do-able by admins who can do way more evil stuff, but okay... :-)

**Comment by mdeniz** [comment]
Avoiding XSS at the news created by the admin... but in the other hand `comment_body` adds markdown processing to the already posted news... Do we want to do that? Is better or worse?

**Comment by adrianschroeter** [comment]
Having a way to create links to pages with more explementation is a good thing. markdown is welcome therefore from my POV.

**Comment by mdeniz** [comment]
Ok, so let's merge it

**Comment by vpereira** [comment]
@hennevogel that's normally how it becomes a problem. Tomorrow we change the logic and create a new "editor" role and the problem is relevant. Unless we have it automated with our test-suite, IMO we should keep (even for admins) the whitelist approach.

**Pull request merged**
