### PR TITLE
obsworker: use proxy only if it is enabled

### PR DESCRIPTION
**Pull request by cschneemann**
Use configured proxy only if it is also enabled to be used.

### CODE REVIEW

**Comment by cschneemann** [comment]
> That seems to be the wrong logic. libproxy at least checks if PROXY_ENABLED is set to "no". It uses the proxy settings if PROXY_ENABLED is not set or has some different value.

So what should be changed here? It seems libproxy is not used in curl: https://github.com/curl/curl/pull/977

**Comment by mlschroe** [comment]
It should be:
```
if [ "$PROXY_ENABLED" != "no" ]; then
```

**Comment by cschneemann** [comment]
> It should be:
> 
> ```
> if [ "$PROXY_ENABLED" != "no" ]; then
> ```

true...

changed

**Comment by coolo** [comment]
please squash these commits

**Pull request merged**
