### PR TITLE
[CI] Try with docker build OBS images

### PR DESCRIPTION
**Pull request by ChrisBr**
I built the docker images now with native docker and used the bundle gems service. Let's see if CI works.

https://build.opensuse.org/project/show/home:cbruckmayer:containers

### CODE REVIEW

**Comment by ChrisBr** [comment]
@hennevogel now I remember what the problem was with the user:

In the kiwi build we set the frontend user
https://build.opensuse.org/package/view_file/OBS:Server:Unstable:container:SLE12:SP3/frontend-base/config.kiwi?expand=1
which is fine for CI because we want to run the tests as frontend user. However, for development we need to set the root user as we need to do the user id mapping. 

Solution would be that we set root user in the frontend-base image and need to switch the user in the CI run to frontend.

**Comment by hennevogel** [comment]
> Solution would be that we set root user in the frontend-base image and need to switch the user in the CI run to frontend.

Or the other way around like we did in [Dockerfile](https://github.com/openSUSE/open-build-service/blob/master/src/api/docker-files/Dockerfile) and [Dockerfile.frontend-base](https://github.com/openSUSE/open-build-service/blob/master/src/api/Dockerfile.frontend-base):
```
root frontend root -> root frontend
```

**Comment by ChrisBr** [comment]
I tested the images and they seem to work. They're still in my home directory but I will move them over to the O:S:U subproject now. As soon as they finished building, our CI most likely will start to fail. Not 100% sure if we can already merge this PR before.

**Comment by hennevogel** [comment]
> Not 100% sure if we can already merge this PR before.

Because?

**Comment by coolo** [comment]
the circleci complaint is about the rename, so go ahead :)

**Pull request merged**
