### PR TITLE
Yellow state for booting schedulers

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by mschnitzer** [comment]
@adrianschroeter can you please explain what the yellow state is (in the description of the PR maybe?)

**Comment by adrianschroeter** [comment]
On Freitag, 9. Dezember 2016, 01:55:01 CET wrote Manuel Schnitzer:
> @adrianschroeter can you please explain what the yellow state is (in the description of the PR maybe?)

well, when the scheduler is in "booting" state, thought that is a bit obvious in the code.

We could add a tooltip hint there though:

 Red: "Not running, admin needs to fix it"
 Yellow: "Cold start, does not response atm, but will be fine without any action required"

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Graham Norton, HRB 21284 (AG N�rnberg) 
 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany

**Comment by mlschroe** [comment]
You should use the scheduler info file ("$bsdir/info/schedulerinfo.$arch") instead of creating a new file.

**Comment by adrianschroeter** [comment]
no, they or not document afaik. IMHO independent of this change though.

**Comment by adrianschroeter** [comment]
@mlschroe isn't it a bit too expensive to parse all the scheduler info files quite frequently? (it is don't by the monitor backgroud job)

**Comment by adrianschroeter** [comment]
@mlschroe is it better that way?

**Comment by bgeuken** [comment]
LGTM for the frontend part. Didn't realize before that the yellow state was already there.

**Comment by adrianschroeter** [comment]
reviewed together with michael, just waiting for test suite

**Pull request merged**
