### PR TITLE
Add ossf-scorecard action

### PR DESCRIPTION
**Pull request by hennevogel**
Scans for software security best practices.

https://github.com/ossf/scorecard & https://securityscorecards.dev/

### CODE REVIEW

**Comment by dmarcoux** [comment]
So once this was executed, where would I see this on GitHub?

**Comment by hennevogel** [comment]
> So once this was executed, where would I see this on GitHub?

Screenshot from 2022-09-01 16-50-52

**Comment by hennevogel** [comment]
Checks are documented here: https://github.com/ossf/scorecard/blob/main/docs/checks.md

**Review by eduardoj — APPROVED** [review]

**Comment by hennevogel** [comment]
Here goes nothing...

**Pull request merged**
