### PR TITLE
[ci] Enable artifact upload on travis

### PR DESCRIPTION
**Pull request by hennevogel**

### CODE REVIEW

**Comment by ChrisBr** [comment]
Cool! LGTM :+1:

**Comment by hennevogel** [comment]
It might look cool but nothing happens... ;-)

**Comment by mdeniz** [comment]
LGTM :+1:

**Comment by bgeuken** [comment]
@hennevogel So, is this having any effect now? Or did I understand you wrong?

**Comment by ChrisBr** [comment]
@bgeuken Travis will upload the logs & capybara screenshots to our Amazon S3 instance. This will help debugging failing tests!

**Pull request merged**
