### PR TITLE
[api][webui] Fix sending broken event over and over again

### PR DESCRIPTION
**Pull request by ChrisBr**
When an event from the backend is broken (e.g. invalid character like emjoi in commit message),
this job tries to create the event over and over again in an infinite loop.
The problem was that the rescue was outside of the loop.
This commit moved the rescue again inside the loop and partially reverts commit
2bee297917a01ece4f00804a1b581b9e04e563f9.

### CODE REVIEW

**Comment by hennevogel** [comment]
This is also a strong candidate for 2.8 backporting...

**Comment by ChrisBr** [comment]
@hennevogel please have a look at the Airbreak syntax!
Also removed the return in the second rescue as it would also trigger to create the event over and over again.

**Comment by ChrisBr** [comment]
[Make it possible to search for package #3512](https://trello.com/c/NSXJ0C6j/489-make-it-possible-to-search-for-package-3512)

**Comment by ChrisBr** [comment]
@hennevogel any idea why the codecov dropped?

**Comment by hennevogel** [comment]
@ChrisBr the `.01%` are because you have one line more... :-)

**Pull request merged**
