### PR TITLE
[api] increase size limit for binary_releases table

### PR DESCRIPTION
**Pull request by adrianschroeter**
We reached the integer limit meanwhile, going from int to bigint for index

### CODE REVIEW

**Comment by saraycp** [comment]
I believe we should deploy this change on a maintenance window. I add a DO NOT MERGE label to merge on Wednesday and deploy on Thursday morning.

**Comment by saraycp** [comment]
I pushed two little changes:

- Added annotations on the model
- Changed the version from 6.1 to 7.0 (`ActiveRecord::Migration[7.0]`)

**Review by eduardoj — APPROVED** [review]

**Comment by adrianschroeter** [comment]
This seems not to be enough, the database changes to bigint, but activemodel is still using 32bit limits. However, it works in console, but not in background job for some reason.

Trying to set it manualy to the right type now and see ...

However, this is not urgent for build.opensuse.org, we are far away of the limit there, so we can take our time here...

**Comment by adrianschroeter** [comment]
Failures were caused by "repository.binary_releases.create" via belongs_to: ... it seems the activemodel is not taking care of the 64bit limit in this situation.
Workarounded that now and it seems to work.

**Comment by saraycp** [comment]
@adrianschroeter are we save to merge this now and deploy tomorrow?

**Review by saraycp — APPROVED** [review]

**Comment by adrianschroeter** [comment]
@saraycp you could, but there seems still to be a problem somewhere (or old code running). I see that new entries exceeding with 32bit integer get created so it works in general, but still some failures appear in my inbox.

I have no time for it atm, in doubt just wait as build.o.o is not in trouble yet anyway.

**Comment by saraycp** [comment]
> @saraycp you could, but there seems still to be a problem somewhere (or old code running). I see that new entries exceeding with 32bit integer get created so it works in general, but still some failures appear in my inbox.
> 
> I have no time for it atm, in doubt just wait as build.o.o is not in trouble yet anyway.

No rush then. As you said, it's not an issue in build.o.o yet. I'm going to move it to draft.

**Comment by adrianschroeter** [comment]
This code is supposed to be fine now.

Could be merged at any time now, but it is not urgent for any external instance.

**Comment by saraycp** [comment]
@adrianschroeter are we save to merge this now and deploy tomorrow?

> This code is supposed to be fine now.
> 
> Could be merged at any time now, but it is not urgent for any external instance.

Thanks for the heads-up. We'll merge tomorrow and deploy on Thursday's maintenance window.

**Review by saraycp — APPROVED** [review]

**Pull request merged**
