### PR TITLE
[ci] Use a single password for our test users

### PR DESCRIPTION
**Pull request by bgeuken**
Password is 'buildservice'. Admin user king is still 'sunflower'.

### CODE REVIEW

**Comment by ChrisBr** [comment]
+1 :+1: 
But can we document it somewhere?

**Comment by mdeniz** [comment]
LGTM :+1: and +1 to document it too

**Comment by bgeuken** [comment]
True. We should. Maybe we can note it in the OBS readme

**Comment by bgeuken** [comment]
@ChrisBr @mdeniz Added a note to the vagrant section at the bottom. Here is how it looks like: https://github.com/bgeuken/open-build-service/blob/e5ae047d91e77f292e106f1a338d6febd9e6c4be/README.md

**Comment by hennevogel** [comment]
:heart:  it :kissing:

**Comment by mdeniz** [comment]
:+1:

**Comment by ChrisBr** [comment]
:+1:

**Pull request merged**
