### PR TITLE
Remove the peek gem

### PR DESCRIPTION
**Pull request by danidoni**
This PR removes the Peek gem.

### CODE REVIEW

**Comment by danidoni** [comment]
[Search and destroy js left-overs from the bento UI](https://trello.com/c/Rmo8RkzQ/1423-search-and-destroy-js-left-overs-from-the-bento-ui)

**Comment by dmarcoux** [comment]
Should this be in the release notes for 2.11? I guess it doesn't, but just to be sure.

**Comment by hennevogel** [comment]
> Should this be in the release notes for 2.11?

Nah, release notes are for admins. This is a developer thing.

**Comment by dmarcoux** [comment]
@danidoni @hennevogel I removed the submodule update.

**Pull request merged**
