### PR TITLE
[ci] project controller spec: Cleanup it blocks to make their descriptions more speaking

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by mdeniz** [comment]
Hey! I did that way from the very beginning, then @hennevogel said me "why having a 'before' block for only one 'it'?" So,... what we should do?

**Comment by bgeuken** [comment]
My thought process was that "it 'without nextstatus param' do" and alike should be changed in a way that the sentence makes sense.

Options that came to my mind were something like "it 'should succeed without nextstatus param' do" or "context 'with nextstatus param' do ...etc.".
I guess both versions have it's rights. Depending on the situation. Maybe something worth to discuss in the review meeting we plan to do soon.

**Comment by mdeniz** [comment]
If you want to change it like you did is ok for me, was my first implementation. And you are right, we should talk about this (if a before block should exist if only one 'it' block will be there) :smile:

**Comment by bgeuken** [comment]
Yep, though in any case the text entries should always make sense;-)

**Comment by mdeniz** [comment]
LGTM :+1:

**Pull request merged**
