### PR TITLE
[api] fix view=blame for attributes

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
On Montag, 14. Mai 2018, 16:47:38 CEST wrote Ana María Martínez Gómez:
> Ana06 requested changes on this pull request.
> 
> What is this about? :confounded: I would really thank a description :pray: 

?? what else should I write about that? The api is not delivering what it is supposed
to do. Just compare the output with the output from the backend.

it is our standard blame view what we deliver for any file, just it did not work
for the _attribute one due to special routing since some time.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by bgeuken** [comment]
> ?? what else should I write about that? The api is not delivering what it is supposed
to do. Just compare the output with the output from the backend.
 adrianschroeter commented 17 hours ago
>
> it is our standard blame view what we deliver for any file, just it did not work
for the _attribute one due to special routing since some time.

That's what you could write in the commit message:wink:

It might be obvious to you, but it's not to others:-) And it might even be less obvious to you in half a year when you stumble over this code while debugging something. 
So please add a description of the issue and the reason why you solve it the way you do.

**Comment by ChrisBr** [comment]
Since there was no update since almost one month, I took the liberty and edited the commit message. I mostly took it from @adrianschroeter comment.

@bgeuken & @Ana06 please review if you're fine with the new commit message. Thanks!

**Comment by Ana06** [comment]
@ChrisBr 

> Since there was no update since almost one month, I took the liberty and edited the commit message.

Thanks! :heart_eyes: 

BTW... rubocop is complaining...

**Pull request merged**
