### PR TITLE
Update rails to 5.0.1

### PR DESCRIPTION
**Pull request by Ana06**

### CODE REVIEW

**Comment by Ana06** [comment]
[(3) Update rails to 5.0.1](https://trello.com/c/lXMszJle/157-3-update-rails-to-5-0-1)

**Comment by bgeuken** [comment]
LGTM, you tested the ui a bit for regressions, right?

Before merging please ensure that OBS:Server:Unstable provides the new gem versions.
And maybe coordinate with @adrianschroeter . Could imagine that he wants to deploy before updating rails.

**Comment by adrianschroeter** [comment]
just merge it and we will fix OBS:Server:Unstable afterwards. It is okay when there are unresolvable errors temporary.

**Comment by bgeuken** [comment]
Ok. And there is nothing left for the review that could be blocked by broken packages -> merging

**Pull request merged**
