### PR TITLE
[webui] Add markdown support in project and package description

### PR DESCRIPTION
**Pull request by mdeniz**
This closes issue #1812

### CODE REVIEW

**Comment by hennevogel** [comment]
Are you sure about the intersection of markdown and XML? :-)

**Comment by mdeniz** [comment]
No, never.
That's why I'm not rendering the markdown at the builders for xml... I think that in the comments is that way too, isn't it?

**Comment by mdeniz** [comment]
Or you mean without rendering the markdown?

**Comment by hennevogel** [comment]
I have no idea I just think that people will start using markdown in the description and then it will get rendered to the XML in the backend or in the command line client etc. That might not be what people expect :-)

**Comment by mdeniz** [comment]
And if we just render de markdown as html inside xml? is worst?

**Comment by hennevogel** [comment]
As HTML is some kind of XML *cough* this would be even worse yes. That's why I asked if you have thought about the intersection between those two :-)

**Comment by mdeniz** [comment]
Yes. But I don't have a good answer to that... If this can be really a mess then better to close the PR.
What do you think @openSUSE/open-build-service?

**Comment by mdeniz** [comment]
Ok. Nobody said something in favor of this PR, so close it.

**Pull request closed without merging**
