### PR TITLE
[backend] drop privs before touching .exit/.restart files

### PR DESCRIPTION
**Pull request by M0ses**
This is needed to give the daemon the possiblity
to remove the action files from the

### CODE REVIEW

**Comment by M0ses** [comment]
@adrianschroeter : Please review
@mlschroe : Please comment after return

**Comment by M0ses** [comment]
as discussed with @adrianschroeter I merged this commit and will send an e-mail to @mlschroe

**Comment by mmohring** [comment]
@M0ses  Now the testsuite fails for the backend:

[  426s] Test Summary Report
[  426s] -------------------
[  426s] t/0170-BSSched-BuildJob-Package.t         (Wstat: 512 Tests: 7 Failed: 0)
[  426s]   Non-zero exit status: 2
[  426s]   Parse errors: Bad plan.  You planned 9 tests but ran 7.

**Comment by marcus-h** [comment]
Hmm why is this needed? Since rundir is/should be owned by
bsuser:bsgroup, it should be possible remove the *.restart and
*.exit files (regardless of their owner:group). Or is there some
mount option/whatever that forbids this (default?) behavior?

**Comment by M0ses** [comment]
@mmohring - I doubt that this commit was responsible for the problems

This commit was the cause:

https://github.com/openSUSE/open-build-service/pull/2040/files

and here I fixed it:

https://github.com/openSUSE/open-build-service/commit/c504d6151107ab7083be12112896fbea23afbe39

**Comment by M0ses** [comment]
@marcus-h - Right, but (IMHO) it`s "cleaner" to drop privs before writing state files. I have to discuss this point anyway with @mlschroe after vacation, because ATM we running into problems with bs_service and docker. When running services inside docker, bs_service needs to run under docker group to be able to interact with containers (e.g. start new containers).

My workaround is to use "setfacl" to give obsservicerun permissions to /srv/obs/run

But as stated above, I will discuss this with @mlschroe

**Pull request merged**
