### PR TITLE
Update colors for obs_green, bootstrap-info and bootstrap-success

### PR DESCRIPTION
**Pull request by krauselukas**
The colors had a bad contrast in many areas of the OBS
webui

**Before**
Screenshot-2019-8-12 ctris(1)

**After**
Screenshot-2019-8-12 ctris(2)

### CODE REVIEW

**Comment by dmarcoux** [comment]
I like it. I wonder if we need multiple greens, like we have `primary` and `success` which are the same now. I don't have an issue with this. However, we still have `$green` which is another green we use sometimes. Should we remove it along with all the other non-obs colors?

Let's gather some more feedback. @openSUSE/obs-frontend, what do you think?

**Comment by hennevogel** [comment]
I think it also works better with the darker header/footer.

**Comment by dmarcoux** [comment]
@krauselukas and I removed the different tones of green. It created inconsistencies since sometimes we used `$obs_green` and in other cases, we used `$green`. We now define `$green` and use it everywhere (for `$primary` and whenever needed in our CSS). Same thing for the other colors like `$obs_blue`, `$obs_yellow` and the rest.

**Comment by krauselukas** [comment]
[Address Wave Recommendations Regarding Contrast/Colors](https://trello.com/c/iZGln7WX/1200-address-wave-recommendations-regarding-contrast-colors)

**Comment by dmarcoux** [comment]
Coveralls is still running after one hour... and changes to stylesheets won't affect OBS Package Build, so I'm merging this.

**Pull request merged**
