### PR TITLE
[ci] Cleanup VCR cassetes

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@hennevogel Please review

**Comment by hennevogel** [comment]
You shouldn't remove User_with_confirmation.yml IMHO

**Comment by bgeuken** [comment]
@hennevogel It doesn't seem to be used by our current tests. Maybe a relict from a test that never made it to master

**Comment by hennevogel** [comment]
I rather have the feeling that _workerstatus might get called sometimes and sometimes not :-/

**Comment by bgeuken** [comment]
Then it might be better to remove it and debug this once a test pulls this in again. Or once travis fails because of the missing cassete

**Comment by hennevogel** [comment]
Alright let's try :-)

**Pull request merged**
