### PR TITLE
first version of osc based testing

### PR DESCRIPTION
**Pull request by M0ses**

### CODE REVIEW

**Comment by mlschroe** [comment]
LGTM (except the commit message)

**Comment by hennevogel** [comment]
Erm shouldn't you do this in [osc](https://github.com/openSUSE/osc)? :-)

**Comment by M0ses** [comment]
no - the tests are used to ensure that the backend is working correctly

**Comment by hennevogel** [comment]
You are so far away from the backend and there is so much stuff in between I really don't see how you can tell that the backend does what it's supposed to do :-) Between your osc and the backend is the frontend. So if osc is broken your test will fail. If the frontend is broken, your tests will fail etc. 

I don't get why you have to do this here...

**Comment by M0ses** [comment]
I correct myself - this tests are integration tests

**Pull request merged**
