### PR TITLE
Make StatusController methods private & remove routes

### PR DESCRIPTION
**Pull request by Ana06**
Make the `_from_cache` & `find_relationships_for_packages` methods private and remove the public routes. They are methods not actions.

### CODE REVIEW

**Comment by Ana06** [comment]
[P8: Refactor StatusController](https://trello.com/c/UymZd1py/841-p8-refactor-statuscontroller)

**Comment by Ana06** [comment]
@bgeuken 

> IIRC Rails is taking care of caching the queries that are done in the *_from_cache methods. You probably can drop them.

Why? :thinking: According to the [Rails guide](https://guides.rubyonrails.org/caching_with_rails.html#sql-caching):

> it's important to note that query caches are created at the start of an action and destroyed at the end of that action and thus persist only for the duration of the action. If you'd like to store query results in a more persistent fashion, you can with low level caching.

**Comment by coolo** [comment]
It's (interstingly enough) the only action that maps Role ids to titles - so moving it to models only makes them fat without much gain

**Comment by Ana06** [comment]
@vpereira

> good job! There was a note move to models which is gone. Which leaves the question open: There was no opportunity to move some code away to the models @Ana06 ?

Why did you merge this if you were not sure if the coment could be removed? :confused: @coolo already explained really nicely why it is not needed though. :wink: 

Also, it would have been nice to wait until @bgeuken rereview this before merging, as what @coolo is explainning is not that obvious. :wink:

**Comment by vpereira** [comment]
> Why did you merge this if you were not sure if the coment could be removed?  @coolo already explained really nicely why it is not needed though. 

Because the card is asking to make it private. However the "move to models" could be a comment to all methods which aren't routable, i.e ```find_relationships_for_packages```, and not just for the methods ```*_from_cache```

**Pull request merged**
