### PR TITLE
[backend ]Udeb publishing support

### PR DESCRIPTION
**Pull request by suihkulokki**
This is a simple way to implement #3268 . We simply create a new debian-installer/ subdir with Packages.gz containing links to the actual udebs. A more complete solution would be to build a complete replica of debian repo structure with dists/ and pool/. But this simpler way should be enough for at least our use case of building custom debian-installer images with a selected packages built with OBS.

### CODE REVIEW

**Comment by DavidKang** [comment]
Thank you for contributing @suihkulokki  :bouquet:

**Comment by mlschroe** [comment]
Thanks! Just one question: currently that debian-installer directory is always created. Should that only be done if there are existing udeb files?

**Comment by suihkulokki** [comment]
I've updated the PR. I've added an rmdir in case debian-installer/Packages was not generated, so debian-installer directory should only exist temporarily while the repo is generated. This should address the consern from @mlschroe . The new commit is fix to make the rmdir work - Packages.new is generated always so the test needed refining.

**Comment by suihkulokki** [comment]
Fixed a mistake where only udeb Release was signed

**Comment by suihkulokki** [comment]
Please take a look.. We have this in use now so if there are errors it would be nice to know before we hit them ;)

**Comment by mlschroe** [comment]
Sorry again that this took so long.

**Pull request merged**
