### PR TITLE
Document published controller integration tests

### PR DESCRIPTION
**Pull request by Ana06**
Explain what is being tested and mark it as FRONTEND, BACKEND or INTEGRATION.

Co-authored-by: Moisés Déniz Alemán <mdeniz@suse.com>
Co-authored-by: Adrian Schröter <adrian@suse.de>

### CODE REVIEW

**Comment by Ana06** [comment]
@openSUSE/open-build-service is there any problem with this? can be merged? please review!

**Comment by coolo** [comment]
you managed to break all test suites

**Comment by Ana06** [comment]
@coolo 

> you managed to break all test suites

ouch! I added files from another branch by accident! :see_no_evil:

**Comment by Ana06** [comment]
@openSUSE/open-build-service please review!

**Pull request merged**
