### PR TITLE
Use bootstrap views instead of bento views in apidocs

### PR DESCRIPTION
**Pull request by DavidKang**

### CODE REVIEW

**Comment by dmarcoux** [comment]
I'm trying to test this locally by building the API docs... but it's not working somehow. I followed the [wiki](https://github.com/openSUSE/open-build-service/wiki/OBS-API#enabling-api-doc-locally)

I keep getting `Unable to load API documentation.` when trying to access http://localhost:3000/apidocs

How did you do it @danidoni and @eduardoj ?

**Comment by DavidKang** [comment]
@dmarcoux, did you made this step: https://github.com/openSUSE/open-build-service/wiki/OBS-API#building-the-api-docu

**Comment by dmarcoux** [comment]
Yes, but it looks like it somehow failed.... The schemas are missing: https://paste.opensuse.org/96717115

**Comment by dmarcoux** [comment]
Oh crap, I found why it didn't work. It's not the missing schemas (some XML files don't have one, others do). I forgot to restart the server after changing `config/options.yml`. :see_no_evil:

**Pull request merged**
