### PR TITLE
Fix #3018: Allow simple emails to be used as logins to OBS

### LINKED ISSUE #3018: Allow logins with @ character in them
Issue/Feature description
====================
Allow logins to be created using the @ symbol, so that simple emails may be used as usernames

Steps to Reproduce
===============
1. Attempt to create a username with @ in the name, say foo@bar.baz

Actual Result
===========
Account create fails.

Expected result
============
Account create succeeds.

Further information
===============
Name: obs-server
Version: 2.7.2-2.3

Background
==========
My employer uses LDAP to implement single signon, and I was "it" when it came to hooking up OBS.  
We have a somewhat non-standard situation where we are sharing infrastructure across business units.  Two of the units are large enough to have users with identical usernames.  Rather than change the usernames, we have migrated all our services to use email addresses as logins, as these business units have different domains.

Well, after enabling debug logging, it became clear that the validators were too strict.  I experimentally tracked down the validators in src/api/app/models (user.rb and project.rb), and adding @ to the regexes seemed to do the trick rather well; I was able to make the user and was submitting/building packages in less than a minute, so it doesn't appear? to be particularly harmful.

### PR DESCRIPTION
**Pull request by teodesian**
Do so by relaxing the validator to accept the @ character.

### CODE REVIEW

**Comment by estrabd** [comment]
Idk how to vote for this, but it'd help us out, too!

**Comment by adrianschroeter** [comment]
Hm, the problem with that is that we couldn't detect anymore automatically if a string is an email or an account name...

**Comment by teodesian** [comment]
I suspected something like this would be a possibility -- that a translation layer in the API authentication mechanisms might be needed further down the line to ensure consistency.  I haven't personally encountered any issues yet, but that doesn't mean they aren't lurking somewhere.

If a mechanism were made where the user's email could be used as an alias for the username, that would probably be 'good enough' for our purposes; however the LDAP routines would also need to be extended to search against the right attribute (I think).

I would be glad to pursue such a patch, if you think the above sounds sensible.  I don't know the procedure for updating your documentation, but I'm sure whatever patch is involved with this feature will likely involve such a change as well.  I'd be glad to help with that as I can.

I would appreciate any clarification as to what these duplicate records might cause trouble with down the line as well; it will make writing the patch a bit of an easier sell :)

**Comment by hennevogel** [comment]
Usually this is a configuration option of the application so the admin can allow different `authentication keys`. And then the authentication library (`authentication_keys` in our case)  tries to find users through those keys. 

This however requires that they keys are uniqe. We only ensure uniqueness for `User.login` so far. So as soon as you add this you also need to make sure that people can migrate existing data if they enable this.

**Comment by teodesian** [comment]
Hmm, I'm still not 100% sure I follow; how does allowing emails as usernames prevent them from remaining unique?  Is there something further down the line comparing it versus, say the email field, and that it must be different from said field for some reason? 

@adrianschroeter suggested there is perhaps some piece of code which has to deal with uncertain inputs, and that attempts to infer whether it is an email or a username.  Any hints as to what specifically is doing this? If I more fully understand the problem I can adjust the pull request accordingly.

A quick `git grep -i 'email'` in the repo didn't make any situation obvious where login==email would be a problem.

@hennevogel where might I configure authentication_keys?  I didn't see any obvious config data, and `git grep -i` returns no results.  It sounds like configuring the login to consult say, the email field instead would do the job for me, if I only knew how such a thing might be accomplished.  None of the doc seems to clarify the situation either.

I am not sure how this will violate uniqueness of the 'login' field, why would this require user migration to a new data model?

**Comment by hennevogel** [comment]
@teodesian what I am saying is that adding a configuration option for which keys `Authenticator` is looking is how this *feature* should be implemented instead allowing `@` in logins.

**Comment by hennevogel** [comment]
@teodesian closing this, sorry but this is simply not how we should do this. If you need help with implementing this feature in `Authenticator` or have any other question please let us know.

**Comment by teodesian** [comment]
That makes more sense.  I suspected that was where you were going, but getting clarity is quite difficult without extended discussion.  I believe I can adjust the patch to consider the email field rather than the login field in find_by_login, it doesn't look too difficult to do.

I still would like a clearer explanation as to what specifically is going to be confused by these @ characters in the 'login' database field down the line so that my next patch doesn't run afoul of the same concerns that I don't fully understand.  I suppose I can take you guys' word for it though.

**Comment by hennevogel** [comment]
@teodesian allowing `@` in login names except that it's very confusing. The username is also frequently used as part of an url (where `@` has a special meaning) or in emails etc. etc. It's just so confusing that this will probably lead to mistakes being made down the road...

**Comment by teodesian** [comment]
It certainly would be a big change in assumptions -- the likelyhood of escaping problems cropping up in the future definitely goes up, and may complicate regexes, especially in client interfaces.

I should have time to take a look at this friday going into the weekend.  Adding code that 1) considers emails as a login alias and 2) is controllable via the configuration file doesn't look especially complicated, so hopefully I will have something next week.

**Comment by hennevogel** [comment]
@teodesian awesome. thank you in advance :-)

**Pull request closed without merging**
