### PR TITLE
[WIP] Remove images that are not used in the new UI

### PR DESCRIPTION
**Pull request by saraycp**
Remove all the images that are not in use in the new UI. This includes svg favicons and some sponsors logos inside _/assets/images/sponsors_.

### CODE REVIEW

**Comment by coolo** [comment]
app/assets/images/favicon-danger.svg was just added 2 weeks ago - sure it's not used?

**Comment by saraycp** [comment]
> app/assets/images/favicon-danger.svg was just added 2 weeks ago - sure it's not used?

I only found references in the code to .ico favicon. Maybe I'm missing something... :thinking:

**Comment by saraycp** [comment]
@coolo I have decided to not to remove the favicons, I don't like to block this PR. I'll research a bit more regarding favicon and other images that are still being used in webui2 and they shouldn't. I'll open a new PR soon...

**Comment by hennevogel** [comment]
> Maybe I'm missing something... thinking

The `.svg` files are the source code for the `.ico` icons :smile:

**Comment by saraycp** [comment]
> > Maybe I'm missing something... thinking
> 
> The `.svg` files are the source code for the `.ico` icons smile

Good to know :smile:

**Comment by hellcp** [comment]
It is possible to write a task to handle rendering those svgs into multi-size ico with rmagick, however that's only really useful with very small selection of icons, so I didn't bother.

**Comment by saraycp** [comment]
I close this PR and open a new one where we keep bento images used by obs_factory.

**Pull request closed without merging**
