### PR TITLE
Staging Workflow Configure UX

### PR DESCRIPTION
**Pull request by DavidKang**
We changed a little bit the interface of the `Configuration` page.

Staging page:

Screenshot-2019-3-29 Open Build Service

Manage Staging:

Screenshot_2019-03-26 Open Build Service(1)

### CODE REVIEW

**Comment by hennevogel** [comment]
Why do we need to display the requests on the edit page?

**Comment by DavidKang** [comment]
You are right, I will remove it and make some changes related to it.

**Comment by saraycp** [comment]
I like your proposal :heart:

**Comment by vpereira** [comment]
Screenshot_2019-04-01_08-20-27

Looks like with longer names, it breaks the UI. Maybe truncate the project name?

**Comment by coolo** [comment]
> Looks like with longer names, it breaks the UI. Maybe truncate the project name?

- restrict the allowed names
- make subprojects special in how they are displayed

You guys really need to develop less with 'home:Admin' and 'TestLinux' and more with 
'SUSE:SLE-15:Update:Products:CASP40' - I'd think your solutions would look different.

**Comment by bgeuken** [comment]
>>    Looks like with longer names, it breaks the UI. Maybe truncate the project name?
>
>   restrict the allowed names

Or we wrap the name to the next line

> make subprojects special in how they are displayed

Sounds like a good idea to me.

**Comment by DavidKang** [comment]
> You guys really need to develop less with 'home:Admin' and 'TestLinux' and more with
'SUSE:SLE-15:Update:Products:CASP40' - I'd think your solutions would look different.

@coolo, thanks for your advise :smile_cat:

**Comment by saraycp** [comment]
Now I'm taking charge of this. This PR is superseded by #7308.

**Pull request closed without merging**
