### PR TITLE
[backend] do not publish .packages files anymore

### PR DESCRIPTION
**Pull request by adrianschroeter**
These files are just intermediate files for the .report files.
The .report files get not published either yet, but we should
not confuse users with internal build artefacts.

Better creating something useful in future if needed.

### CODE REVIEW

**Comment by vmoutoussamy** [comment]
Vagrant and JeOS images will appreciate this change : ) We got some report from confused users on these files.

**Comment by dcermak** [comment]
Thank you @adrianschroeter!

**Comment by bear454** [comment]
This breaks Public Cloud publishing, which relies on .packages for dependency version checks.

**Comment by adrianschroeter** [comment]
On Dienstag, 26. Mai 2020, 17:38:01 CEST wrote James Mason:
> This breaks Public Cloud publishing, which relies on .packages for dependency version checks.

hm, but this is an internal build artefact inside of OBS. It is just
a base for .report files in the end.

However, couldn't you get it via the api? 

I do not really like to see them published to the user, since 
it is not usefull, and is an internal piece where no guarantees
are given...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by aosthof** [comment]
@adrianschroeter While we could adjust to a future solution - e.g. the .report file - our current image publishing automation relies on the .packages files and taking them away just broke our process. As we need to do a general image refresh end of this week the absence of the .package files is not acceptable.

FYI, @bugfinder already reverted the change for the Devel:, home and SUSE: projects in IBS which should give us some breathing room again - thanks!

**Comment by lnussel** [comment]
The bill of materials is valuable information. Who gets confused by that? Please bring it back. See also  #9040

**Comment by rjschwei** [comment]
We have tools and processes that are broken and basically means we will not get openSUSE images published in AWS, Azure and GCE. vs. people that are being confused.

We should find a solution that meets all our needs and revert this change until such a solution is found and all tools can be adjusted accordingly.

**Comment by Vogtinator** [comment]
Yes, I also like to have the .packages files (or an equivalent) available for easy checking.

**Pull request merged**
