### PR TITLE
[webui] avoid a creation of SSL cert on every project show page

### PR DESCRIPTION
**Pull request by adrianschroeter**
Considered to be a temporary solution

### CODE REVIEW

**Comment by bgeuken** [comment]
So we disable the ssl cert feature for now?

**Comment by adrianschroeter** [comment]
yes, as temporary solution. A better proposal was in the other pull requests in my last two comments

**Comment by evanrolfe** [comment]
This commit needs to be reverted in order for the specs to pass: https://github.com/openSUSE/open-build-service/pull/2605/commits/e2aa6bb85fcdb9a19cec142b95f60e0986b73674

**Comment by evanrolfe** [comment]
This is ready for review please

**Comment by ChrisBr** [comment]
This LGTM
However, I don't like reverting abd2cff9d5a92f564f83eb41e33f1270b7b06498 in 72334709e04cc931d05a14906745724cace1602a

**Pull request merged**
