### PR TITLE
Run all feature tests in CircleCI

### PR DESCRIPTION
**Pull request by eduardoj**
Before, only tests under one subdirectory level were tested.

Fix the file pattern used to run the tests, and include all tests, independent of the subdirectory level.

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Review by dmarcoux — APPROVED** [review]
Oh wow, nice catch. Before this change, we were running 159 examples. Now, it's 201 examples. 42 examples were simply ignored... ouch!

**Comment by coolo** [comment]
and these 42 examples didn't cover a single line more - according to codecov. Something doesn't fit :)

**Comment by dmarcoux** [comment]
It's all fine according to coveralls. You can compare https://coveralls.io/builds/37969495 (when #10880 was merged and the coverage decreased by 0.5%)  and https://coveralls.io/builds/38011866 (when we merged this PR and the coverage increased by 0.5%). I don't know for others, but I do sometimes overlook the coverage check. I need to pay more attention to this.

**Comment by coolo** [comment]
0.5% is basically the measuring error of the coverage. But enabling these 42 examples didn't move the coverage outside that.

These are the files missed so far:
```
spec/features/beta/webui/notifications_spec.rb
spec/features/beta/webui/users/notifications_controller_spec.rb
spec/features/beta/webui/users/profile_spec.rb
spec/features/beta/webui/users/user_contributions_spec.rb
spec/features/webui/kiwi/images_spec.rb
spec/features/webui/projects/status_spec.rb
spec/features/webui/requests/submissions_spec.rb
spec/features/webui/users/admin_configuration_spec.rb
spec/features/webui/users/profile_spec.rb
spec/features/webui/users/user_admin_edit_spec.rb
spec/features/webui/users/user_contributions_spec.rb
spec/features/webui/users/user_home_page_spec.rb
```

You would expect the user feature tests to show somewhere in the controller that isn't covered without.

**Comment by dmarcoux** [comment]
> 0.5% is basically the measuring error of the coverage. But enabling these 42 examples didn't move the coverage outside that.

*Basically* the measuring error? What do you mean?

> These are the files missed so far:
> (...)

How did you get to that list?
 
> You would expect the user feature tests to show somewhere in the controller that isn't covered without.

I'm sorry, I don't understand the sentence. *To show somewhere in the controller that isn't covered without....* ???

**Comment by coolo** [comment]
Ah, my mistake. The normal up and down in coverage is 0.05%

**Pull request merged**
