### PR TITLE
[webui] Make PrettyNestedErrors work for n-level associations.

### PR DESCRIPTION
**Pull request by evanrolfe**
Before PrettyNestedErrors only worked for nested associations which are
2 levels deep, now it can work for n-levels deep.

### CODE REVIEW

**Comment by evanrolfe** [comment]
@mschnitzer I've added a spec

**Comment by evanrolfe** [comment]
> In my opinion it's at the wrong place

Why do you think its the wrong place? I think its the right place because PrettyNestedErrors is a concern which could be used in any rails app that uses ActiveRecord, so its not specific to our application and therefore does not go in the /app dir but in /lib.

**Comment by mschnitzer** [comment]
@evanrolfe Hm you're right. This class can be used by other apps as well.

**Comment by hennevogel** [comment]
@evanrolfe why the [DO NOT MERGE] label?

**Comment by evanrolfe** [comment]
Annoyingly, I seem to have overwritten the pretty_nested_errors.rb file using `git commit --amend` and I cant find a way to get it back so I am re-coding the changes to the concern..

**Comment by marcus-h** [comment]
On 2018-02-05 12:25:45 +0000, Evan Rolfe wrote:
> Annoyingly, I seem to have overwritten the pretty_nested_errors.rb file using `git commit --amend` and I cant find a way to get it back so I am re-coding the changes to the concern..
> 
Try "git reflog".

**Comment by evanrolfe** [comment]
@marcus-h that worked! thanks

@mschnitzer please re-review

**Comment by evanrolfe** [comment]
[Make PrettyNestedErrors recursive](https://trello.com/c/KTmjZkLH/611-make-prettynestederrors-recursive)

**Comment by evanrolfe** [comment]
Codecov hangs, I'm going to merge this anyway unless objections? This PR should increase the code coverage of the specs anyway..

**Pull request merged**
