### PR TITLE
[dist] Fix update path to be sequential

### PR DESCRIPTION
**Pull request by hennevogel**
Make more clear that we only support sequential updates.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
we test a direct update from 2.5 in the migration test. So why do you think it does not work?

**Comment by hennevogel** [comment]
Well upgrade from 2.5 would only work if you do all the manual steps for all the sequential versions in this file right? But some might not be needed or even not working anymore. For instance how do I decide if I need to change the [passenger ruby configuration](https://github.com/openSUSE/open-build-service/blob/master/dist/README.UPDATERS#L68)? Or which of the different database migrations I need to run? Which services do I need to enable/start?

I guess this would need more thought than just this [one sentence](https://github.com/openSUSE/open-build-service/blob/master/dist/README.UPDATERS#L4) in this file. So I rather would not support this.

**Comment by adrianschroeter** [comment]
yes, you need to do all steps, this is the reason why we keep all steps in this file.

And all migrations need to run, but that is what we test and what happens anyway when you call the migration. 

So far we have supported skipping releases and I can tell from former experiences that people will try anyway, since it is really a burden to do the updates (including OS) in multiple steps.

**Comment by hennevogel** [comment]
Okay then we need a way to think about how to carry over things you need to do from version to version. I will open another PR for this.

**Pull request closed without merging**
