### PR TITLE
[webui] project monitor page layout changes

### PR DESCRIPTION
**Pull request by kulmesa**
Few layout changes to project page, if project has many repositories:
- fit monitor table to layout boundary
- set packages column visible when vertically scrolling build results

### CODE REVIEW

**Comment by kulmesa** [comment]
before: 
before

after:
after

**Comment by hennevogel** [comment]
This is not really a solution for this problem right? What happens when you build for even more distributions? :-)

**Comment by coolo** [comment]
it's still an improvement I have to admit

**Comment by kulmesa** [comment]
> This is not really a solution for this problem right? What happens when you build for even more distributions? :-)

Monitor wrapper width is bound to width of the table, so it just gets wider if there are more distributions. 
Also the packages column follows the view, if table width is more than the window width. That's quite useful, if you have monitor page like this:
https://build.opensuse.org/project/monitor/Base:System
It's quite difficult to see where the build results belongs to, if you scroll view far to the right.

**Comment by hennevogel** [comment]
@kulmesa I'm not arguing that this is broken. I argue your solution. Why not introduce a second row/table?

**Comment by adrianschroeter** [comment]
well, I would take this as bugfix, since it is fixing the broken layout. That does not mean that we can't improve even more here...

**Comment by hennevogel** [comment]
Please "line-break" the table after @kulmesa. Something like

screenshot from 2016-12-06 15-15-38

If you need help with this let me know

**Pull request closed without merging**
