### PR TITLE
[webui] replace anchor with void in review comment toggle to avoid scrolling

### PR DESCRIPTION
**Pull request by jberry-suse**
Solved #2708.

### CODE REVIEW

**Comment by jberry-suse** [comment]
Ran locally with no failure, assume flaky.
```
  test_spider_anonymously                                         PASS (97.71s)
  test_spider_as_admin                                            PASS (67.15s)
```

**Comment by adrianschroeter** [comment]
thanks, we use the [webui] tag instead of [api] for webui only things, could you change that please?

I will retrigger travis test ...

**Comment by jberry-suse** [comment]
Hopefully it will pass again. :)

**Comment by mdeniz** [comment]
Thanks @jberry-suse  😄 👍

**Pull request merged**
