### PR TITLE
[backend] repserver: also log the build type of finished jobs

### PR DESCRIPTION
**Pull request by mlschroe**

### CODE REVIEW

**Comment by hennevogel** [comment]
Can we also add this to the events?

**Comment by mlschroe** [comment]
Of course! Just add support for a "buildtype" element to the API.

**Comment by hennevogel** [comment]
> Of course! Just add support for a "buildtype" element to the API.

Okay, here or do you want to do it together in another PR?

**Comment by hennevogel** [comment]
If it's in the payload, I think this should be it.

**Comment by hennevogel** [comment]
You saw I pushed a commit right? :-)

**Pull request merged**
