### PR TITLE
Simplify `Distribution.all_as_hash`

### PR DESCRIPTION
**Pull request by DNNX**

### CODE REVIEW

**Comment by mdeniz** [comment]
LGTM +1

**Comment by bgeuken** [comment]
Looks good to me as well. Not that I see that as blocking, but you could write ```map { |d| d.to_hash }``` as ```map(&:to_hash)```:)

**Comment by DNNX** [comment]
Yea, I know. I haven't seen much of this style in the project, so I decided
to go with less magical syntax. Also, performance-wise `map { |x| x.y }` is
a bit faster than `map(&:y)`, so I decided to leave it as is.

**Comment by bgeuken** [comment]
Alright. Thanks again.

**Comment by mdeniz** [comment]
Block is slightly slower than Symbol#to_proc...

https://github.com/JuanitoFatas/fast-ruby#block-vs-symbolto_proc-code

**Comment by DNNX** [comment]
I also tested it. Here are my results:

```
2.2.2 :002 > Benchmark.ips {|x| x.report('&:') { [1,2,3].map(&:to_i)}; x.report('||'){ [1,2,3].map{|x| x.to_i}}; x.compare!}
Calculating -------------------------------------
                  &:    37.395k i/100ms
                  ||    39.115k i/100ms
-------------------------------------------------
                  &:    895.550k (± 2.8%) i/s -      4.487M
                  ||    940.680k (± 2.5%) i/s -      4.733M

Comparison:
                  ||:   940680.0 i/s
                  &::   895550.3 i/s - 1.05x slower
```

**Comment by mdeniz** [comment]
Ok, better let it as is... there is no big difference ;)

**Pull request merged**
