### PR TITLE
[api] fix data inconsistency after package undelete

### PR DESCRIPTION
**Pull request by adrianschroeter**
reparse re-created sources

### CODE REVIEW

**Comment by adrianschroeter** [comment]
regression, should be backported.

**Comment by coolo** [comment]
It's unclear what the problem is, as such it's hard to judge the solution. Can you elaborate?

**Comment by adrianschroeter** [comment]
On Mittwoch, 4. Dezember 2019, 19:22:18 CET Stephan Kulow wrote:
> 
> https://github.com/openSUSE/open-build-service/pull/8836#issuecomment-561775586

the source index get not re-established (no issue and more critical no product indexing in DB).

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by coolo** [comment]
Hakiri wants puma update to be backported to 2.10 branch - not related to this PR

**Pull request merged**
