### PR TITLE
Add Addressable for encoding Backend URIs

### PR DESCRIPTION
**Pull request by mdeniz**
Use the Addressable gem for encoding properly the URI base (not the query part). 

Before it was encoded using `CGI.encode` that created some issues with repositoriy names that have blank spaces inside.

### CODE REVIEW

**Comment by mdeniz** [comment]
Mmm.. ok, is a private method... but anyway

**Comment by mdeniz** [comment]
@evanrolfe please re-review it 👍

**Comment by hennevogel** [comment]
@evanrolfe ping!

**Comment by evanrolfe** [comment]
> Mmm.. ok, is a private method... but anyway

[Nitpick] Maybe it doesnt make sense to have a module which only has private methods? Or to

**Comment by evanrolfe** [comment]
LGTM

**Pull request merged**
