### PR TITLE
Sort staging projects in staging workflow show page

### LINKED ISSUE #8680: Strange sort order in staging workflow list
I can't say what the projects in https://build-test.opensuse.org/staging_workflows/1 are sorted after.

creation time? I have B, adi:5, adi:6, ... adi:223, adi:1, adi:3, adi:4, ..., adi:220

The Factory staging dashboard sorts by state, but I guess sorting by name would be acceptable (as it would allow async loading of the state)

### PR DESCRIPTION
**Pull request by eduardoj**
Use the same sort method that was used before for obs_factory.

Fixes #8680.

Co-authored-by: David Kang <dkang@suse.com>
Co-authored-by: Stephan Kulow <coolo@suse.de>

Screenshot from 2020-01-16 15-12-45

### CODE REVIEW

**Comment by DimStar77** [comment]
Without something like https://github.com/openSUSE/open-build-service/pull/8803 this new sort is quite 'bad'

in Factory I now have a list of all acceptable adi stagings, followed by adi stagings needing reviews in front of all letter stagings.

**Comment by DimStar77** [comment]
on the old obs_factory dashboard this worked as we had two tabs - Letter and adi - so very similar to the new category concept proposed by @coolo

**Comment by nilxam** [comment]
> Without something like #8803 this new sort is quite 'bad'
> 
> in Factory I now have a list of all acceptable adi stagings, followed by adi stagings needing reviews in front of all letter stagings.

I'd argue the same...

**Comment by vpereira** [comment]
@fcrozat could you please tell us how it looks from your side?

**Comment by coolo** [comment]
SLE only has one category of stagings, so the lack of categories doesn't hurt there

**Comment by hennevogel** [comment]
we can certainly talk about something like categories. but not here. I'll approach you peepz for a meeting.

**Comment by vpereira** [comment]
> SLE only has one category of stagings, so the lack of categories doesn't hurt there

sure, but would be good to have a feedback from him too. If the PR didn't make sense for both use cases that we have, we should rething the whole sorting.

**Comment by fcrozat** [comment]
> @fcrozat could you please tell us how it looks from your side?

looks ok.

**Pull request merged**
