### PR TITLE
project_monitor.js: sort unfinished status codes before finished codes

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by vpereira** [comment]
@andreas-schwab would you mind to add a screenshot to your PR to make easier to understand what do you want to achieve?

**Comment by andreas-schwab** [comment]
Screenshot_20191014_162515

**Comment by vpereira** [comment]
hi @andreas-schwab 

if you see on `circle-ci` you have some linter errors:

```
app/assets/javascripts/webui/project_monitor.js: line 12, col 15, Identifier 'code_map' is not in camel case.
app/assets/javascripts/webui/project_monitor.js: line 48, col 31, Identifier 'code_map' is not in camel case.
```

would you mind to rebase with master and fix those?

**Comment by vpereira** [comment]
hey @andreas-schwab did you see this wiki https://github.com/openSUSE/open-build-service/wiki/Build-Results ? We have a different point of view regarding the priorities https://github.com/openSUSE/open-build-service/wiki/Build-Results ? Do you want to discuss  them?

**Comment by vpereira** [comment]
Not valid, since we have a different prioritization for the status codes as defined https://github.com/openSUSE/open-build-service/wiki/Build-Results

**Pull request closed without merging**
