### PR TITLE
refactoring (style, performance and security issues)

### PR DESCRIPTION
**Pull request by vpereira**
Hi,

I did some changes and I did spot some "problems" including (but not limited to):

- Possivel SQL injection on a module
- Performance boost using the any? iterator 
- Improving the coding style, rewriting code using a better "ruby dialect" 

I'm open to discussion and improvements ideas. I was able to test my code, partially (I've got some integrations tests, but I've got them as well before my changes). I ran the rake test:api to test it. 

thanks,

VP

### CODE REVIEW

**Comment by coolo** [comment]
I would prefer if you would squash the commits a bit - there are 2 commits and 6 cleanups. Additionally passing tests would be great.

**Comment by vpereira** [comment]
the problem is that I was having the same failures before and after my changes - running the tests locally -  I will submit each change separately and wait for travis to complete, to see what is broken.

**Comment by adrianschroeter** [comment]
closing this for now, feel free to reopen when the test suite is working

**Comment by vpereira** [comment]
ok! next week i will have time again to take a look into this problem. @adrianschroeter did you push your improved version of the code to your github? would you mind to share it with me?

**Comment by adrianschroeter** [comment]
it is in git master branch, you should spot it on rebase

**Pull request closed without merging**
