### PR TITLE
[webui] Drop ObsRepository as it reimplemented the gem

### PR DESCRIPTION
**Pull request by ChrisBr**
- Fix YAML inheritance, hash merge is not recursive so defaults were not inherited
- After fixing the YAML it was not necessary to merge with defaults in the Repository anymore
- Defaults should be now defined in the defaults production hash in the feature.yml

Now we can use the standard YamlRepository

### CODE REVIEW

**Comment by ChrisBr** [comment]
@hennevogel no, but question is how this should happen as the feature.yml is checked in git?

**Comment by hennevogel** [comment]
@ChrisBr it's in git but marked as [%config(noreplace) ](https://github.com/openSUSE/open-build-service/blob/master/dist/obs-server.spec#L604) in the package.

**Comment by ChrisBr** [comment]
@hennevogel okay fine, didn't know that! However, I fixed the yaml inheritance and one unnecessary line!

cc @eduardoj @mdeniz maybe you can remember why you implemented the additional assignment to data['feature']

**Comment by eduardoj** [comment]
> cc @eduardoj @mdeniz maybe you can remember why you implemented the additional assignment to data['feature']

Having a look at [get_active_features](https://github.com/mgsnova/feature/blob/9e8dd2247892d80826e1b86515fe953388989712/lib/feature/repository/yaml_repository.rb#L65) it seems that the additional assignment to `data['features']` is not needed. I should drop it.

**Comment by ChrisBr** [comment]
@eduardoj already done in this PR

**Comment by ChrisBr** [comment]
@hennevogel please review again!

**Pull request merged**
