### PR TITLE
Update bunny to 2.9.1

### PR DESCRIPTION
**Pull request by ChrisBr**
because depfu is too slow and we already updated it in O:S:U

### CODE REVIEW

**Comment by mschnitzer** [comment]
@ChrisBr I triggered Travis again as it seemed to be hanging in a loop (the job was running for 12h but was - according to the logs - already done).

**Comment by bgeuken** [comment]
blocked for now as we have some issues (#4362) with rabbitmq. This might be caused by the recent update to 2.9.0

**Comment by bgeuken** [comment]
Actually the issue we had is fixed in the new bunny version. We will merge this one as soon as the test suite passed.

**Comment by bgeuken** [comment]
Superseeded by #4366 

@ChrisBr We had to solve some conflicts. So we created a new PR. And while I was it I also updated the commit message and referenced the related issues. Hope that's okay.

**Pull request closed without merging**
