### PR TITLE
[webui] edit user account always finds current user object

### PR DESCRIPTION
**Pull request by kaltsi**

### CODE REVIEW

**Comment by hennevogel** [comment]
This is on purpose. Why do you think this is needed?

**Comment by kaltsi** [comment]
This was a fix to a case when I was in my user's page and another user logged in, if I then clicked the 'edit your account' link, the other user's e-mail address or name could end up in the save dialog that popped up for me.

**Comment by hennevogel** [comment]
This would be a very serious security problem and should not be workarounded. Please open a bugreport if you have a way to reproduce this!

**Comment by kaltsi** [comment]
You sound doubtful that this happened :)

This part in the basic OBS without the proxy authentication that's in use in build.opensuse.org really manifested this problem. It can't be reproduced there because the edit your account link opens to another site. I'm not going to try to reproduce it anymore with the applicance, but it should be reproducible with it.

**Pull request closed without merging**
