### PR TITLE
[backend] introduce $BSConfig::bsserviceuser variable

### PR DESCRIPTION
**Pull request by marcus-h**
$BSConfig::bsserviceuser and $BSConfig::bsservicegroup can be used to
configure the user/group under which "bs_service" is running. The defaults
are $BSConfig::bsuser and $BSConfig::bsgroup.

The new defaults shouldn't break existing installations, because
* the /usr/lib/obs/server/BSConfig.pm file is marked as %config(noreplace)
* bs_service's default $tempdir is set to /var/tmp, which is writable by "obsrun".
  Additionally, I'm not aware of any service that explicitly needs write access to the
  home directory of the user who is executing the service (by default obsrun's
  homedir (/usr/lib/obs) is owned by root).

### CODE REVIEW

**Comment by adrianschroeter** [comment]
I would even go one step further and configure another user (eg obsservicerun) by default. We can create this use in the package on update.

And we can use this user as built-in default when no setting is defined in BSConfig.pm, so we can leave it there just commented out.

**Comment by marcus-h** [comment]
On 2016-03-18 02:05:00 -0700, Adrian Schröter wrote:
> I would even go one step further and configure another user (eg obsservicerun) by default. We can create this use in the package on update.
> 
I just updated the PR:
- obsservicerun is the new default
- the obsservicerun user is created when installing the obs-source_service
  package
- now the obsservice script makes sure that the "rundir" is group writable

> And we can use this user as built-in default when no setting is defined in BSConfig.pm, so we can leave it there just commented out.
> 
Hmm I can change that as well, but this would break some installations during
an update (e.g., all setups where the lxc wrapper script is configured)...

**Comment by adrianschroeter** [comment]
Marcus, thanks for your update, sorry for the late response.

It shouldn't affect updates, since BSConfig.pm is not touch on package update. Just the template file will change. And it is good to haven't it set for new installations.

So, if you don't see a different problem, I would indeed remove the setting in the BSConfig.pm.template file. I try to have as little config settings as needed by default...

**Comment by marcus-h** [comment]
On 2016-04-04 00:30:32 -0700, Adrian Schröter wrote:
> It shouldn't affect updates, since BSConfig.pm is not touch on package update. Just the template file will change. And it is good to haven't it set for new installations.
> 
> So, if you don't see a different problem, I would indeed remove the setting in the BSConfig.pm.template file. I try to have as little config settings as needed by default...
> 
Hmm - if I understand you correctly, you want to comment out the the changes
in BSConfig.pm.template and have something like this in bs_service:

$BSConfig::bsuser = $BSConfig::bssserviceuser || 'obsservicerun';
...

If so, an update would break existing installations where the lxc
service wrapper is configured, because it would be executed as "obsservicerun"
instead of "root".

**Comment by marcus-h** [comment]
Hmm is there still any chance to get this into the 2.7 release?

**Comment by adrianschroeter** [comment]
okay, I can follow you now...

yes, I will merge to master now and backport to 2.7 after a bit more testing.

**Pull request merged**
