### PR TITLE
[ci] Drop minitest based webui test suite

### PR DESCRIPTION
**Pull request by hennevogel**

### CODE REVIEW

**Comment by hennevogel** [comment]
Just testing how this would affect coverage percentage...

**Comment by DavidKang** [comment]
@hennevogel, looks better than we expected 😸

**Comment by hennevogel** [comment]
@openSUSE/open-build-service so this is only 1.09% I'm okay to live with this

**Comment by evanrolfe** [comment]
> so this is only 1.09% I'm okay to live with this

+1 for dropping webui test suite

**Comment by DavidKang** [comment]
+1

**Comment by eduardoj** [comment]
> > so this is only 1.09% I'm okay to live with this

> +1 for dropping webui test suite

Me too!

**Comment by mdeniz** [comment]
Are you f*cking crazy!!! I like it 😄

**Comment by hennevogel** [comment]
Alright, here we go then

**Comment by mdeniz** [comment]
You also need to remove the case from the **dist/ci/travis_script.sh** file.

**Pull request merged**
