### PR TITLE
[frontend] Store comments.body as utf8mb4

### PR DESCRIPTION
**Pull request by coolo**
Reverts openSUSE/open-build-service#5491

### CODE REVIEW

**Comment by hennevogel** [comment]
you stutter...

**Comment by hennevogel** [comment]
please do not merge this as we need to plan the deployment as this requires downtime.

**Comment by coolo** [comment]
Yeah, possibly we change the commit log message :)

**Comment by coolo** [comment]
The details on production shadow:

```
== 20180720082742 SwitchToUtf8mb4: migrating ==================================
-- execute("ALTER DATABASE `api_development` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0003s
-- execute("ALTER TABLE `ar_internal_metadata` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0257s
-- execute("ALTER TABLE `architectures` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0316s
-- execute("ALTER TABLE `architectures_distributions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0260s
-- execute("ALTER TABLE `attrib_allowed_values` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0268s
-- execute("ALTER TABLE `attrib_default_values` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0212s
-- execute("ALTER TABLE `attrib_issues` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0187s
-- execute("ALTER TABLE `attrib_namespace_modifiable_bies` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0785s
-- execute("ALTER TABLE `attrib_namespaces` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0284s
-- execute("ALTER TABLE `attrib_type_modifiable_bies` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0384s
-- execute("ALTER TABLE `attrib_types` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0307s
-- execute("ALTER TABLE `attrib_values` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.3154s
-- execute("ALTER TABLE `attribs` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.3456s
-- execute("ALTER TABLE `backend_infos` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0256s
-- execute("ALTER TABLE `backend_packages` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 5.9144s
-- execute("ALTER TABLE `binary_releases` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 30.5206s
-- execute("ALTER TABLE `bs_request_action_accept_infos` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 6.5024s
-- execute("ALTER TABLE `bs_request_actions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 19.4676s
-- execute("ALTER TABLE `bs_request_counter` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0866s
-- execute("ALTER TABLE `bs_requests` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 14.6904s
-- execute("ALTER TABLE `channel_binaries` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0595s
-- execute("ALTER TABLE `channel_binary_lists` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0595s
-- execute("ALTER TABLE `channel_targets` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0582s
-- execute("ALTER TABLE `channels` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0578s
-- execute("ALTER TABLE `cloud_azure_configurations` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0857s
-- execute("ALTER TABLE `cloud_ec2_configurations` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1034s
-- execute("ALTER TABLE `cloud_user_upload_jobs` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0867s
-- execute("ALTER TABLE `comments` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 4.7321s
-- execute("ALTER TABLE `configurations` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1271s
-- execute("ALTER TABLE `data_migrations` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0763s
-- execute("ALTER TABLE `delayed_jobs` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0579s
-- execute("ALTER TABLE `distribution_icons` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0769s
-- execute("ALTER TABLE `distribution_icons_distributions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0770s
-- execute("ALTER TABLE `distributions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0785s
-- execute("ALTER TABLE `download_repositories` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.9545s
-- execute("ALTER TABLE `event_subscriptions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1654s
-- execute("ALTER TABLE `events` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 11.8427s
-- execute("ALTER TABLE `flags` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 5.6399s
-- execute("ALTER TABLE `group_maintainers` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0927s
-- execute("ALTER TABLE `group_request_requests` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0586s
-- execute("ALTER TABLE `groups` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1319s
-- execute("ALTER TABLE `groups_roles` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0571s
-- execute("ALTER TABLE `groups_users` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0922s
-- execute("ALTER TABLE `history_elements` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 33.6993s
-- execute("ALTER TABLE `incident_counter` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0662s
-- execute("ALTER TABLE `incident_updateinfo_counter_values` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1410s
-- execute("ALTER TABLE `issue_trackers` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0799s
-- execute("ALTER TABLE `issues` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 9.8567s
-- execute("ALTER TABLE `kiwi_descriptions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.3810s
-- execute("ALTER TABLE `kiwi_images` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.3181s
-- execute("ALTER TABLE `kiwi_package_groups` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.2821s
-- execute("ALTER TABLE `kiwi_packages` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 6.4894s
-- execute("ALTER TABLE `kiwi_preferences` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.2217s
-- execute("ALTER TABLE `kiwi_repositories` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1856s
-- execute("ALTER TABLE `linked_projects` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0879s
-- execute("ALTER TABLE `maintained_projects` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1161s
-- execute("ALTER TABLE `maintenance_incidents` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.4603s
-- execute("ALTER TABLE `messages` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0609s
-- execute("ALTER TABLE `notifications` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 3.6505s
-- execute("ALTER TABLE `package_issues` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 40.1354s
-- execute("ALTER TABLE `package_kinds` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 1.2633s
-- execute("ALTER TABLE `packages` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 13.7447s
-- execute("ALTER TABLE `path_elements` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 1.3201s
-- execute("ALTER TABLE `product_channels` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0593s
-- execute("ALTER TABLE `product_media` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0601s
-- execute("ALTER TABLE `product_update_repositories` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0590s
-- execute("ALTER TABLE `products` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0919s
-- execute("ALTER TABLE `project_log_entries` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 69.8946s
-- execute("ALTER TABLE `projects` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 1.7365s
-- execute("ALTER TABLE `ratings` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1754s
-- execute("ALTER TABLE `relationships` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 3.6242s
-- execute("ALTER TABLE `release_targets` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.5314s
-- execute("ALTER TABLE `repositories` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 1.7909s
-- execute("ALTER TABLE `repository_architectures` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 1.8407s
-- execute("ALTER TABLE `reviews` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 30.2300s
-- execute("ALTER TABLE `roles` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0846s
-- execute("ALTER TABLE `roles_static_permissions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0844s
-- execute("ALTER TABLE `roles_users` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1098s
-- execute("ALTER TABLE `schema_migrations` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1338s
-- execute("ALTER TABLE `sessions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0577s
-- execute("ALTER TABLE `static_permissions` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0793s
-- execute("ALTER TABLE `status_histories` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 2.9578s
-- execute("ALTER TABLE `status_messages` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1255s
-- execute("ALTER TABLE `tokens` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1310s
-- execute("ALTER TABLE `updateinfo_counters` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0753s
-- execute("ALTER TABLE `user_registrations` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0877s
-- execute("ALTER TABLE `users` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 2.4155s
-- execute("ALTER TABLE `watched_projects` ROW_FORMAT=DYNAMIC CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.2017s
-- execute("ALTER TABLE `attrib_allowed_values` MODIFY `value` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
   -> 0.1068s
-- execute("ALTER TABLE `attrib_default_values` MODIFY `value` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;")
   -> 0.0965s
-- execute("ALTER TABLE `attrib_values` MODIFY `value` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.3090s
-- execute("ALTER TABLE `backend_packages` MODIFY `error` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 3.8424s
-- execute("ALTER TABLE `bs_requests` MODIFY `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 10.3324s
-- execute("ALTER TABLE `bs_requests` MODIFY `comment` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 9.1580s
-- execute("ALTER TABLE `comments` MODIFY `body` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 1.8810s
-- execute("ALTER TABLE `configurations` MODIFY `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.2826s
-- execute("ALTER TABLE `delayed_jobs` MODIFY `last_error` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1920s
-- execute("ALTER TABLE `events` MODIFY `payload` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 3.6449s
-- execute("ALTER TABLE `history_elements` MODIFY `comment` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 44.5979s
-- execute("ALTER TABLE `messages` MODIFY `text` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0924s
-- execute("ALTER TABLE `notifications` MODIFY `event_payload` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;")
   -> 0.8612s
-- execute("ALTER TABLE `packages` MODIFY `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 9.9472s
-- execute("ALTER TABLE `project_log_entries` MODIFY `additional_info` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 301.9011s
-- execute("ALTER TABLE `projects` MODIFY `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.9716s
-- execute("ALTER TABLE `reviews` MODIFY `reason` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
   -> 45.9296s
-- execute("ALTER TABLE `sessions` MODIFY `data` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
   -> 0.0925s
-- execute("ALTER TABLE `status_messages` MODIFY `message` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1077s
-- execute("ALTER TABLE `users` MODIFY `adminnote` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.9447s
== 20180720082742 SwitchToUtf8mb4: migrated (767.4658s) =======================


warning: db:migrate only migrates your database structure, not the data contained in it.
warning for migrating your data run data:migrate


real    12m51,848s
user    0m3,411s
sys     0m0,852s
```

**Pull request merged**
