### PR TITLE
Make HTTPS communication between services possible

### PR DESCRIPTION
**Pull request by andrewshadura**
When workers and services are located in different networks, we don’t want to send traffic unencrypted and open to anyone to listen to.

This change makes it possible to easily opt in to HTTPS communication by changing the service URLs in BSConfig.

### CODE REVIEW

**Comment by mlschroe** [comment]
I think you must also symlink BSSSL.pm into the `worker` directory.

**Comment by andrewshadura** [comment]
True.

**Comment by andrewshadura** [comment]
Argh. I have accidentally pushed an unrelated branch but then deleted and re-pushed it, but it has closed the pull request.

**Comment by andrewshadura** [comment]
Please see #9189 for a new PR.

**Pull request closed without merging**
