### PR TITLE
Jshint fixes

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by hennevogel** [comment]
What about integrating this into the CI cycle? :-)

**Comment by bgeuken** [comment]
You mean having a jshint test running in travis? I thought about that too.

**Comment by hennevogel** [comment]
Yeah, especially with all the self-made stuff...

**Comment by mdeniz** [comment]
LGTM and :+1: to integrate it into the CI cycle

**Comment by bgeuken** [comment]
Cool. So far I did not fix jshint errors of external js, but started to move that to either jquery gems or vendor/assets. Once this is done we can integrate jshint to travis.

**Comment by hennevogel** [comment]
Created a card in the backlog

**Pull request merged**
