### PR TITLE
[webui] Get rid of error when flags are nil

### LINKED ISSUE #2200: [production][webui/repositories#index] NoMethodError: undefined method `each_with_index' for nil:NilClass
webui/repositories#index threw this 0 times

<pre>
NoMethodError: undefined method `each_with_index&#39; for nil:NilClass
</pre>

[https://build.opensuse.org/repositories/home:cschweingruber](https://build.opensuse.org/repositories/home:cschweingruber)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/57f51e4acd53000006000000)

### PR DESCRIPTION
**Pull request by eduardoj**
Get rid of `undefined method 'each_with_index' for nil:NilClass` error.
"project" or "package" flags could be nil for a certain repository.

This should fix #2200

Mob-programmed with @DavidKang

### CODE REVIEW

**Comment by hennevogel** [comment]
You want to rebase to get 02c6c40516a57cdcfb93ba2775adfbdb02a1cd10

**Comment by eduardoj** [comment]
> You want to rebase to get 02c6c40

Done. Thanks.

**Comment by ChrisBr** [comment]
Aren't we just masking the problem then? 
In which case it is possible that a repository has no flags?

**Comment by eduardoj** [comment]
> Aren't we just masking the problem then?
> In which case it is possible that a repository has no flags?

Probably we have to take a deeper look at [this code](https://github.com/openSUSE/open-build-service/blob/26a5dd50b75dae94df07e88b97b93c484323f554/src/api/app/mixins/get_flags.rb#L2-L4)

Feel free to close this PR.

**Pull request closed without merging**
