### PR TITLE
[ci] Cleanup project controller spec

### PR DESCRIPTION
**Pull request by bgeuken**
* Split preparation of test from actual test
* Ensure that allow_forgery_protection get's set back to false after test run

### CODE REVIEW

**Comment by mdeniz** [comment]
Why?
CSRF is only tested in that "describe" if you change it that way then next "describe" added will be CSRF protected... and this is something unneeded, right?

**Comment by bgeuken** [comment]
> Why?
To make the test more readable and to ensure that allow_forgery_protection is that to false, even in case of test failures or exceptions.

> CSRF is only tested in that "describe" if you change it that way then the next "describe" added will > be CSRF protected... and this is something unneeded, right?
That was also the case before. There is even one advantage now, since one could add the new test inside the 'CSRF protection' describe without having to allow_forgery_protection again.

And who knows what will be added next anyway;-)

**Comment by mdeniz** [comment]
The default behavior is with CSRF disabled... so don't enable it for tests that don't test it...

**Comment by bgeuken** [comment]
Exactly. That's why it get's enabled before the test and disabled afterwards:-)

**Comment by mdeniz** [comment]
I think I didn't explain myself very well!!!

The default behavior IN ALL THE TESTS is having CSRF disabled. So, no need to enable it BEFORE ALL of the specs for Project Controller. Just enable it for this spec and that's all. New spec shouldn't have CSRF protection activated.

**Comment by mdeniz** [comment]
OH! Man! I didn't see that it was inside the describe.... just kill me :cry: !! 

LGTM :+1:

**Pull request merged**
