### PR TITLE
Maintenance factories

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
On my local machine I got an "AttribType::UnknownAttributeTypeError: Attribute Type OBS:MaintenanceProject does not exist" exception. Though it looks like our seeds create this. So might be some flaw in my setup.

**Comment by hennevogel** [comment]
Somehow your factories created projects in the test db

**Comment by eduardoj** [comment]
[(5) Setup factories to be able to test the maintenance workflow](https://trello.com/c/XtVEq3cD/39-5-setup-factories-to-be-able-to-test-the-maintenance-workflow)

**Comment by eduardoj** [comment]
Superseeded by #2368

**Pull request closed without merging**
