### PR TITLE
[webui] Add configurable project filters to project list page

### PR DESCRIPTION
**Pull request by kulmesa**
Projects can be excluded from the main project list easily by clicking checkboxes.
Project filter are configured in options.yml.

### CODE REVIEW

**Comment by hennevogel** [comment]
hey @kulmesa , thank you for this contribution! :bouquet:

Can you elaborate on the use case for this? Why do you need these filters? :-)

**Comment by kaltsi** [comment]
@hennevogel our use case for these filters is that we use obs as a CI build machine and a new review project is created for each commit. We are creating lots and lots of these projects and some of them have a long life time, others are deleted more quickly. The end result is that we have tens or hundreds of projects named Foo:review:12345:something.

It's handy to be able to hide these by default, like the users' home projects are hidden by default already.

**Comment by adrianschroeter** [comment]
@kaltsi the options.yml belong to the server admin, but not necessary to the OBS Admin. IMHO it would be a better solution to either

  make the configuration part of /configuration

and/or

 define some marker for a project (eg. an attribute) to opt-out of the default project list. Does this make sense to you?

**Comment by hennevogel** [comment]
The reasoning behind this is to not load thousands of objects from the database only to ignore them with javascript in rendering...

**Comment by kulmesa** [comment]
> make the configuration part of /configuration
Do you mean the configuration database, or what "/configuration" are you referring to?

> The reasoning behind this is to not load thousands of objects from the database only to ignore them with javascript in rendering...

Well, in our case there are not that many projects (we are using this also to filter home projects). So from end user point of view it is much faster to show/hide projects just by clicking checkboxes, and then in javascript to filter those projects out without reloading the page. So it's mainly a usability improvement.

**Comment by hennevogel** [comment]
> Do you mean the configuration database, or what "/configuration" are you referring to?

Yes. Configuration.

> Well, in our case there are not that many projects (we are using this also to filter home projects). 

I understand that this is crafted for your needs but we need to make this useful for everyone else in a generic way :-)

**Comment by kulmesa** [comment]
About the configuration: the idea was that admin could easily define multiple regexp style patterns (e.g. `"Home:*"`, `"Foo:review:*"` etc) to exclude projects from the default project list. Then there would be checkboxes for each configured project filter in the project list page, where user could check/uncheck which projects to show. If there are no filters configured, it doesn't affect to default project list in any way (also no checkboxes are visible).

So in that sense the options.yml provides quite easy way to configure project filters, but I suppose those could be configured in database also.

**Comment by hennevogel** [comment]
No matter where this is stored, I do understand what you have done and I also understand the reason. However I don't agree that this is a good implementation for the interface and I think there are better ways to achieve what you want. For instance to make the [Project scope](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/project.rb#L100) configurable

**Comment by adrianschroeter** [comment]
@kulmesa JFYI, we have discussed this internally and we will spend some time one this. But let's keep this request open until then :)

**Comment by adrianschroeter** [comment]
Moises is working on this here: https://github.com/openSUSE/open-build-service/pull/2543

So I close this request. Please review the pull request and check if it solve your needs (I think so;)

**Pull request closed without merging**
