### PR TITLE
Allow to specify commit messages when changing files

### LINKED ISSUE #3179: Allow to specify commit messages when changing files
As a user, I'd like to specify commit messages when I change any file. (like on GitHub)

### PR DESCRIPTION
**Pull request by rhabacker**
Fixes #3179  (for 2.9 branch)

- The commit input field is disabled by default or by pressing undo
image

- After changing any text in the edit field, the commit input field can be edited
image

- After pressing **Save** the message is added to the revision
image

### CODE REVIEW

**Comment by rhabacker** [comment]
> Hakiri — Security warnings were found. 

This result is not related to this patch

**Comment by rhabacker** [comment]
> The Travis CI build failed 
> Failures:
> 1) Projects creating packages in projects not owned by user, eg. global namespace as non-admin user

This error message does not seem to be related to this patch either.

**Comment by hennevogel** [comment]
Sorry but we do not backport features...

**Comment by hennevogel** [comment]
Can you please submit this to master?

**Comment by rhabacker** [comment]
> Thank you for your contribution! bouquet
> 
> But sorry but we do not backport features, can you submit this to master instead? TIA!

Which is then ported back to 2.10 ? How long will it take for the public obs to update to 2.10 before this annoying problem is fixed?

**Comment by hennevogel** [comment]
Let's see if we will back-port this to 2.10

**Pull request closed without merging**
