### PR TITLE
[api] Fix structure.sql file

### PR DESCRIPTION
**Pull request by eduardoj**
Adds a needed new empty line at the end of the file for our test
environment for testing migrations.

Pair programming with @bgeuken

### CODE REVIEW

**Comment by adrianschroeter** [comment]
hm, we could also strip empty lines in the test to be a bit more  robust here ...

**Comment by evanrolfe** [comment]
Can you explain more about why we need this new line here? Was it added manually?

**Comment by bgeuken** [comment]
We need it to pass the test that diffs the structure.sql from git with the one we generate during the rpm build.

The whitespace probably comes from automatic merge resolution when merging a PR that was based on an older version than master.

**Comment by bgeuken** [comment]
@adrianschroeter Since I am about to change this, I wouldn't update worry to much about updating the migration test

**Pull request merged**
