### PR TITLE
Replace status traffic lights with colored shapes

### PR DESCRIPTION
**Pull request by mdeniz**
Replace the old traffic light with something more visible.

**Before**:

Screenshot Before

**After**:

Screenshot After

EDITED:

**Final version**

Screenshot Option2

### CODE REVIEW

**Comment by ChrisBr** [comment]
LGTM 👍 
However, as it is a design change I would also wait for others to approve!

**Comment by hennevogel** [comment]
@mdeniz where do those icons come from? :-)

**Comment by adrianschroeter** [comment]
I like it:) Errors will be indeed way more visible

**Comment by Ana06** [comment]
I like it too! :+1:

**Comment by mdeniz** [comment]
@hennevogel I took the green one from http://www.wpclipart.com/blanks/shapes/color_labels/circle/color_label_circle_green.png.html and edited for the other colors plus resizing.

It says that us a public domain image... but I'm unsure if we can use/edit it freely (that's why I labeled this PR with DO NOT MERGE).

**Comment by DavidKang** [comment]
LGTM 👍

**Comment by mdeniz** [comment]
@coolo is this just a complain in a comment or are you willing to propose something in particular?

Maybe not using only color but also different shapes, would work also for color blindness people?

**Comment by coolo** [comment]
the red one is actually much darker than the others, but your orange and green are basically the same. There are interesting chromium extensions to simulate how colour blind people see your page. Different shapes or different filling patterns are typical counter measures. I.e. point 3 of http://blog.usabilla.com/how-to-design-for-color-blindness/

**Comment by adrianschroeter** [comment]
On Mittwoch, 15. Februar 2017, 11:10:01 CET wrote Stephan Kulow:
> "Errors will be indeed way more visible" ... for those 84% not affected by colour blindness

Right, but the traffic lights were also not very good for them I think.

But different shapes would indeed be more helpful for them.
(Maybe CD player like, > for green, || for yellow and a box for red? just an idea.)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by bgeuken** [comment]
@adrianschroeter
Member
> adrianschroeter commented 25 minutes ago
> > On Mittwoch, 15. Februar 2017, 11:10:01 CET wrote Stephan Kulow:
> >  "Errors will be indeed way more visible" ... for those 84% not affected by colour blindness
>
> Right, but the traffic lights were also not very good for them I think.
>
> But different shapes would indeed be more helpful for them.
> (Maybe CD player like, > for green, || for yellow and a box for red? just an idea.)

Or we add a tooltip to them. Not the most convenient solution, but at least something. Emoticons might also work, or thumbs up / down.

Anyway, I like the change :+1:

**Comment by bgeuken** [comment]
One minor thing is that the distance of the icon could be harmonized

**Comment by Ana06** [comment]
This is also interested to read: http://webaim.org/articles/visual/colorblind. The most important part is this one:

> When designing web content for people who are color-blind you do NOT have to convert all of your images to black and white or get rid of your images entirely. In fact, you may not have to change any of your images at all. **Make sure that colors are not your only method of conveying important information.**

The color circles are much better than the traffic lights, as the traffic lights were difficult to see even for me. However we could select different shapes for every colour if we want to make it more accesible. They should be simple shapes, like an square, a triangule and a circle; because If we use something more complex like emoticons then it won't be useful for people with low vision and other visual disabilities. But more important than the colour is the fact that the images are not correctly tagged. If they had a proper _title_ and _alt_ everybody could read them.

**Comment by mdeniz** [comment]
Ok, so, I will change orange color to yellow, also the shape (square for red, triangle for yellow, and circle for green). And I will add title/alt too.

@bgeuken what do you mean with "the distance of the icon could be harmonized"? that each group of icon and text should have the same width or the should share the total width?

BTW, @coolo now I'm curious... Can you explain us how you did that in openQA? 😈

**Comment by bgeuken** [comment]
@mdeniz I mean the space between neighbouring icons. It varies right now. In your first screenshot is was more visible than in the second. In general I find it a bit distracting.

Would be great if you could set it to a fixed, consistent space.

**Comment by mdeniz** [comment]
That space is because the names of the daemons... icons have fixed width. I will try to handle that...

**Comment by coolo** [comment]
openQA has either text next to traffic light or a tooltip. But we also made sure the colours can be differentiated in user testing with an colour blind colleague :)

**Comment by mdeniz** [comment]
Also when a failed needle have a red frame among other with green?

**Comment by coolo** [comment]
but I like your solution - on first look it looks a bit like a toddler game, but as red and yellow are exceptions, I don't think there is a problem - people appreciate green bubbles :)

**Comment by mdeniz** [comment]
BTW can you point me to the extension for chromium that simulates color blindness?

**Comment by coolo** [comment]
the red border is a lot darker than the green one - colour blind people learn to look for such things (as I learned)

**Comment by coolo** [comment]
so what matters is sticking to a palette - and not use different shades of red all around. Sass can be quite helpful with that - and so our icons are css/fontawesome

**Comment by mdeniz** [comment]
Yes true, I hope we will at that point not that far away, I mean, using a CSS framework to do it easily...

BTW, I used icons instead of those new shapes... what do you think?


Screenshot Option2

**Comment by coolo** [comment]
Hurray for conistency!

**Comment by mdeniz** [comment]
The icons are smaller... that's maybe why I don't like them that much... but, what do you think @openSUSE/open-build-service guys?

**Comment by DavidKang** [comment]
I like it 👍

**Comment by Ana06** [comment]
I prefer the simple shapes, but the icons are more consistent with the rest of OBS, so fine with both options. :+1:

**Comment by mdeniz** [comment]
Ok, now Icons, fixed width, word-break for long names, gray background to "see" it better... Take a look at the new screenshot @openSUSE/open-build-service 


Screenshot Option2

**Comment by Ana06** [comment]
> gray background to "see" it better

I am not sure that this is true, as it decreases the contrast. But it is fine, this grey is not that different from white anyway. And It looks way better than before :tada: 

What I don't understand is why we are using a `div` with the icon as background, instead of `img`. :confused:

**Comment by hennevogel** [comment]
I like it

**Pull request merged**
