### PR TITLE
[webui] Start work on webui2

### PR DESCRIPTION
**Pull request by hellcp**
What's done:
* Show user
* Search (whole)
* Repositories for package and project
* Users and groups for projects and package (whole)
* Project:
  * Show project
  * subprojects
  * prjconf
  * project pulse
  * project requests
  * project monitor (actually still will look bad with OBS:Server:Stable repo, haven't made changes that would fix it)
  * new project
  * new_package
  * project meta
  * edit project
  * project lists
  * buildstatus
* Package: 
  * add file, 
  * branch dialog 
  * buildstatus
  * commits
  * revisions
  * edit
* Config:
  * index
  * interconnect
  * architectures
* Comments

Apparent bugs:
* Bootstrap collides with current styling and js for codemirror, working on that
* Adding distros into projects fails with wrong auth message (no idea)
* Links from monitor's workers view link only from progress part of the progress bar
* Switching to rpmlint in buildstatus doesn't work

### CODE REVIEW

**Comment by ChrisBr** [comment]
@hellcp is it supposed to work?

I get an

> Sprockets::FileNotFound in Webui::Main#index

error!

Review app is here: https://obs-reviewlab.opensuse.org/hellcp-master

**Comment by hennevogel** [comment]
@hellcp awesome stuff, thank you for your contribution!

But can you please split this up into smaller pull-requests and commits? Reviewing this is impossible...

**Comment by hellcp** [comment]
@ChrisBr fixed!

@hennevogel will do

**Comment by hellcp** [comment]
Working on smaller PRs

**Comment by ChrisBr** [comment]
Reopening for now as I want to see the review app :smile: Ignore for reviewing...

**Comment by hellcp** [comment]
@ChrisBr yeah, none controllers were modified to support webui2, I will do that for next prs

**Comment by hennevogel** [comment]
[Bootstrap: main#index](https://trello.com/c/VqPCDuTh/1451-bootstrap-mainindex)

**Comment by hennevogel** [comment]
[Bootstrap: package#show](https://trello.com/c/VpGsVhbL/1450-bootstrap-packageshow)

**Comment by hennevogel** [comment]
[Bootstrap: package#revisions](https://trello.com/c/M8As7Mvs/1442-bootstrap-packagerevisions)

**Comment by hennevogel** [comment]
@hellcp did you get around to split this up into smaller PRs yet?

**Comment by hennevogel** [comment]
@hellcp see #5415 for what we are looking for

**Comment by hellcp** [comment]
Yeah, I was preparing some stuff, so PRs will come shortly

**Pull request closed without merging**
