### PR TITLE
Image templates icon

### PR DESCRIPTION
**Pull request by Ana06**
Find better icon for image templates and then fix styling of the icon on main page. :bowtie:

I have also removed the width and height as they are overwritten in the `css`.

I have change the `resprite` task to not add `.css` to the generated `.scss` style file as it  deprecated and unnecessary. Related to https://github.com/openSUSE/open-build-service/pull/2391.

## Main page
image

## Image templates page

image

### CODE REVIEW

**Comment by Ana06** [comment]
[(8) Present kiwi templates](https://trello.com/c/0JyzpRkk/112-8-present-kiwi-templates)

**Comment by Ana06** [comment]
Not sure of what tag applies to 929c57049665fa059817ae2b00df3248b2d3cdec

**Comment by bgeuken** [comment]
@Ana06 I would say webui, since it only affects the ui.

**Comment by bgeuken** [comment]
I like the icon

LGTM overall

**Comment by mdeniz** [comment]
I also like the icon 👍

**Pull request merged**
