### PR TITLE
Bugfix/fix user helper

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@coolo ^Just in case you were working on this

**Comment by coolo** [comment]
nope. this is about the errbit crash on owner search? Why isn't this caught in the feature tests?

**Comment by bgeuken** [comment]
> @coolo 
> nope. this is about the errbit crash on owner search? Why isn't this caught in the feature tests?

This method has like 10+ different scenarios that would have to be tested to cover everything. That wouldn't be feasible in a feature test (don't know if we have feature tests at all that cover this helper).

**Comment by coolo** [comment]
I'm not saying we should test all scenarios of the helper in the feature test. I'm wondering what makes the actual crash special - and if it makes sense to have *that* case as feature test. Not looking at the crash, but at the user story behind it.

**Comment by bgeuken** [comment]
@coolo I understood. But I think it's enough to test this in the helper. To reproduce the bug one would need a user without realname and a role, or the :short option and a role .

**Comment by coolo** [comment]
I see

**Pull request merged**
