### PR TITLE
[api] fix crash on parsing bugzilla time stamps

### PR DESCRIPTION
**Pull request by adrianschroeter**
don't trust rubocop ...

### CODE REVIEW

**Comment by bgeuken** [comment]
Could you explain what crashes and how?

**Comment by bgeuken** [comment]
Looks like (to_time_in_current_zone is)[http://apidock.com/rails/Date/to_time_in_current_zone] deprecated. Did you (in_time_zone)[try http://api.rubyonrails.org/classes/DateAndTime/Zones.html#method-i-in_time_zone]?

**Comment by adrianschroeter** [comment]
It is crashing with

NoMethodError: undefined method `to_time_in_current_zone' for #<XMLRPC::DateTime:0x007f8af57aba48>

here. Note that this is the XMLRPC::DateTime and not the ruby default one.

app/models/issue_tracker.rb:222→ parse_single_bugzilla_issue
app/models/issue_tracker.rb:193→ block in fetch_bugzilla_issues
app/models/issue_tracker.rb:193→ each
app/models/issue_tracker.rb:193→ fetch_bugzilla_issues
app/models/issue_tracker.rb:269→ private_fetch_issues
app/models/issue_tracker.rb:168→ fetch_issues
app/models/issue.rb:67→ fetch_updates
app/models/issue.rb:34→ find_by_name_and_tracker
app/models/issue.rb:16→ find_or_create_by_name_and_tracker
app/controllers/issues_controller.rb:8→ show

**Comment by bgeuken** [comment]
If bugzilla provides timestamps in utc, we should convert them to the timezone of the system.

**Comment by adrianschroeter** [comment]
On Mittwoch, 15. März 2017, 05:27:39 CET wrote Björn Geuken:
> If bugzilla provides timestamps in utc, we should convert them to the timezone of the system.

well, only if this would not break the data when we move the server to a different timezone.
(I know we have this problem also in other places).

However, we need to get code in a working state in first place. Let's discuss the way how 
we store data independent of this please.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Pull request merged**
