### PR TITLE
[frontend] Update README.UPDATERS

### PR DESCRIPTION
**Pull request by bgeuken**
Update README.UPDATERS according to recent feedback from users that
tested our RC 1 release.

### CODE REVIEW

**Comment by bgeuken** [comment]
@openSUSE/open-build-service Please review

@adrianschroeter JFYI

**Comment by Conan-Kudo** [comment]
@bgeuken You also need to edit the passenger configuration to use ruby2.5, or otherwise it throws an unhelpful error about being unable to start the application.

**Comment by bgeuken** [comment]
:thinking: That should already been done. At least for the appliance... Will check

**Comment by bgeuken** [comment]
So it wasn't done in our packages. We usually document this and let user do that. So that we don't unintentionally break other user's systems.

@Conan-Kudo Thanks for the pointer :smile:

**Comment by Conan-Kudo** [comment]
👍

**Pull request merged**
