### PR TITLE
Do not expand sources by default on Package#file_exists? method

### LINKED ISSUE #12152: [production][image_templates#index] undefined method `[]' for nil:NilClass
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/61f9107784bf460540e2cea8)
# undefined method `[]&#39; for nil:NilClass #
### URL ###
[https://build.opensuse.org/image_templates](https://build.opensuse.org/image_templates)"
### Where ###
image_templates#index

### Occured ###
Feb 01 10:50am

### Similar ###
0

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;controller&quot; =&gt; &quot;webui/image_templates&quot;
}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
1334:  app/models/package.rb -> **block in file_exists?**
1334:  app/models/package.rb -> **any?**
1334:  app/models/package.rb -> **file_exists?**
1338:  app/models/package.rb -> **has_icon?**
97:  app/helpers/webui/webui_helper.rb -> **image_template_icon**
25:  app/views/webui/image_templates/index.html.haml -> **block (2 levels) in _app_views_webui_image_templates_index_html_haml___1255963092566186187_46972601555720**
88:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/relation/delegation.rb -> **each**
88:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/relation/delegation.rb -> **each**
16:  app/views/webui/image_templates/index.html.haml -> **each_with_index**
16:  app/views/webui/image_templates/index.html.haml -> **block in _app_views_webui_image_templates_index_html_haml___1255963092566186187_46972601555720**
9:  app/views/webui/image_templates/index.html.haml -> **each**
9:  app/views/webui/image_templates/index.html.haml -> **_app_views_webui_image_templates_index_html_haml___1255963092566186187_46972601555720**
247:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/base.rb -> **public_send**
247:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/base.rb -> **_run**
154:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/template.rb -> **block in render**
205:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **instrument**
345:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/template.rb -> **instrument_render_template**
152:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/template.rb -> **render**
61:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/template_renderer.rb -> **block (2 levels) in render_template**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **instrument**
56:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/template_renderer.rb -> **block in render_template**
71:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/template_renderer.rb -> **block in render_with_layout**
205:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **instrument**
70:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/template_renderer.rb -> **render_with_layout**
55:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/template_renderer.rb -> **render_template**
11:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/template_renderer.rb -> **render**
61:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/renderer.rb -> **render_template_to_object**
29:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/renderer/renderer.rb -> **render_to_object**
117:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/rendering.rb -> **block in _render_template**
273:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/base.rb -> **in_rendering_context**
116:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/rendering.rb -> **_render_template**
218:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/streaming.rb -> **_render_template**
103:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/rendering.rb -> **render_to_body**
52:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rendering.rb -> **render_to_body**
142:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/renderers.rb -> **render_to_body**
25:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/rendering.rb -> **render**
36:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rendering.rb -> **render**
46:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
308:  /usr/lib64/ruby/2.5.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/core_ext/benchmark.rb -> **ms**
46:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **block in render**
86:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
45:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **render**
35:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/implicit_render.rb -> **default_render**
6:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/basic_implicit_render.rb -> **block in send_action**
6:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/basic_implicit_render.rb -> **tap**
6:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **call**
77:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **memoized_call**
42:  /GEM_ROOT/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/permissions_policy.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
15:  /GEM_ROOT/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/sendfile.rb -> **call**
92:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
416:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots) |

### PR DESCRIPTION
**Pull request by danidoni**
Only expand sources when asking for multibuild packages

Fixes #12152

### CODE REVIEW

**Review by dmarcoux — APPROVED** [review]

**Comment by dmarcoux** [comment]
Oh, I just noticed it's in draft. Something else will be added?

**Comment by danidoni** [comment]
> Oh, I just noticed it's in draft. Something else will be added?

I would like to write some specs for this, but IDK how to do it yet.

**Comment by dmarcoux** [comment]
While testing something in the OBS workflows locally, I hit this issue too. I applied the changes from this PR and this is still breaking.

**Comment by vpereira** [comment]
> I would like to write some specs for this, but IDK how to do it yet.

it is a P2...

**Comment by vpereira** [comment]
> While testing something in the OBS workflows locally, I hit this issue too. I applied the changes from this PR and it is still breaking.

could you please provide us more information about it @dmarcoux ?

**Comment by danidoni** [comment]
> > I would like to write some specs for this, but IDK how to do it yet.
> 
> it is a P2...

I'll try to come up with the specs in a follow-up PR

**Comment by dmarcoux** [comment]
This is how I reproduced the error:
1. Create a package (like `home:Admin/something`)
2. Branch the `home:Admin/something` package to `home:Admin/something2`.
3. Change the revision inside `_link` of `home:Admin/something2` by removing a few characters (this will break the link).
4. In a Rails console, run this to get the error: ` Package.get_by_project_and_name('home:Admin', 'something2').multibuild?`.

**Comment by dmarcoux** [comment]
This is an issue in the workflow since we fetch the multibuild flavors of a package by calling `multibuild_flavors` https://github.com/openSUSE/open-build-service/blob/5ed5d007442bb9d7491f08474e4aff9a0586fdec/src/api/app/models/concerns/multibuild_package.rb#L30-L37

in https://github.com/openSUSE/open-build-service/blob/5ed5d007442bb9d7491f08474e4aff9a0586fdec/src/api/app/models/workflow/step.rb#L75

This is how I reproduced the issue while testing something for a SCM/CI integration PR. I then applied the changes included in this PR and it still happened. The steps provided in my previous comment are just simplified to show how this happens.

**Comment by vpereira** [comment]
> This is how I reproduced the issue while testing something for a SCM/CI integration PR. I then applied the changes included in this PR and it still happened. The steps provided in my previous comment are just simplified to show how this happens.

Ok, but If I'm not wrong, similar issue was happening in the same place before the patch too, when using "link package"

**Comment by danidoni** [comment]
> > This is how I reproduced the issue while testing something for a SCM/CI integration PR. I then applied the changes included in this PR and it still happened. The steps provided in my previous comment are just simplified to show how this happens.
> 
> Ok, but If I'm not wrong, similar issue was happening in the same place before the patch too, when using "link package"



> This is how I reproduced the error with the current changes:
> 
>     1. Create a package (like `home:Admin/something`)
> 
>     2. Branch the `home:Admin/something` package to `home:Admin/something2`.
> 
>     3. Change the revision inside `_link` of `home:Admin/something2` by removing a few characters (this will break the link).
> 
>     4. In a Rails console, run this to get the error: ` Package.get_by_project_and_name('home:Admin', 'something2').multibuild?`.

I think this is a corner case and can be tackled later. Do you agree @dmarcoux ?

**Comment by dmarcoux** [comment]
> I think this is a corner case and can be tackled later. Do you agree @dmarcoux ?

No, the SCM/CI integration won't work.

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
