### PR TITLE
[api] added fix and test for build flag inheritance project to package

### PR DESCRIPTION
**Pull request by mmohring**
This tests some of the cases which will fail with the current git master. The inheritance of flags from project to package in the API and thus in the WebUI is currently borked. There is a separate patch to fix the API.

### CODE REVIEW

**Comment by mmohring** [comment]
@adrianschroeter @mdeniz Please review.

**Comment by adrianschroeter** [comment]
thanks, but I like to ask henne to review it, since he refactored the code.

**Comment by mmohring** [comment]
OK, will wait for your feedback.

**Comment by hennevogel** [comment]
Looks good to me. But you have to add `Flag#default_status` to `BLACK_LIST` in [test/unit/code_quality_test.rb](https://github.com/openSUSE/open-build-service/blob/master/src/api/test/unit/code_quality_test.rb#L58) please

**Comment by mmohring** [comment]
@hennevogel Sure, I fix the Code Quality Issue.

**Pull request merged**
