### PR TITLE
[api] fix missing token-rebuild-multibuild case

### PR DESCRIPTION
**Pull request by adrianschroeter**
forgot to add this chunk in 45bb4dd7b8b6c515b161b8cecbf03bac4f8de40e

We need to transfer multibuild container name for rebuild operations

_Replace this line with a description of your changes. Please follow the suggestions in the comment below._

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Comment by hennevogel** [comment]
You need help with rspec?

**Comment by danidoni** [comment]
I'll try to address the rspec failures and make this green

**Comment by danidoni** [comment]
Okay, specs fixed. I'll squash the commits

**Review by vpereira — APPROVED** [review]

**Review by hennevogel — CHANGES_REQUESTED** [review]
Hm it looks to me as if you just recorded new requests with VCR without getting rid of the old ones.

**Comment by danidoni** [comment]
> Hm it looks to me as if you just recorded new requests with VCR without getting rid of the old ones.

Fixed

**Comment by vpereira** [comment]
@hennevogel your request was addressed, therefore i will merge it.

**Pull request merged**
