### PR TITLE
Patchinfo controller

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@adrianschroeter And this one?

**Comment by bgeuken** [comment]
@openSUSE/open-build-service Anyone mind to review?

**Comment by ChrisBr** [comment]
@bgeuken Otherwise LGTM :+1:

**Comment by hennevogel** [comment]
Alright this one is good to :rocket:?

**Comment by ChrisBr** [comment]
@hennevogel Jup, form my side it's fine

**Comment by bgeuken** [comment]
from mine as well. Thanks for reviewing:) Next one will be shorter

**Pull request merged**
