### PR TITLE
Fix branching while service running

### PR DESCRIPTION
**Pull request by tuminoid**
Don't fail with 400 remote error, if service is running while branching it.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
We can not merge this because it will harm situations where the source is a link. The new created branch will contain a not expanded link.

(the lsrev_expanded is mainly there to expand source links, it's a side-effect that it will also expand source services)

However, we keep this pull request open for further analyses and finding a different solution.

**Comment by tuminoid** [comment]
Thanks @adrianschroeter, good catch, will rethink this too.

**Comment by mdeniz** [comment]
@tuminoid @adrianschroeter can we close this PR for now... and reopen it when you rethink this?

**Comment by hennevogel** [comment]
Please open again if you have thought this through.

**Comment by adrianschroeter** [comment]
please reopen if this is still critical for you.

However, the api is always setting noservice on branching. So we wonder how this patch makes a difference for you?

**Pull request closed without merging**
