### PR TITLE
Fix how we access Event::Base.payload hash

### LINKED ISSUE #16165: Notification emails about maintainership changes no longer have the name of the change author and the project in the Subject line
# Issue Description

The subject line of maintainership changes sent out by OBS changed around 12 UTC today. It was previously "Build Service Notification", but now it says "added you as on" instead. It looks like there should be some variable substitution going on, but it's not taking place or all the values are `Nil`.

Email from today:
image

Previous message:
image

The message body is still rendered correctly.

### PR DESCRIPTION
**Pull request by hennevogel**
In this hash keys have been strings not symbols.
Fix how we access those and make this hash indifferent.

Fixes #16165

### CODE REVIEW

**Comment by hennevogel** [comment]
The `.with_indifferent_access` bit is monkey patched...

**Review by ncounter — APPROVED** [review]

**Comment by hennevogel** [comment]
The lack of specs for this showed...

**Comment by hennevogel** [comment]
I removed the `.with_indifferent_access` part it's too deep down and needs too many changes. Especially for storing the YAML has into the database...

**Comment by eduardoj** [comment]
> I removed the `.with_indifferent_access` part. It's too deep down and needs too many changes. Especially for storing the YAML hash into the database...

In such case, we should also modify this line: https://github.com/openSUSE/open-build-service/blob/5bf1abb70cd02f89ae3492188fe06607716ba6fd/src/api/app/models/event/request.rb#L108

**Comment by hennevogel** [comment]
> In such case, we should also modify this line: ...

probably yes

**Comment by hennevogel** [comment]
@eduardoj pushed

**Pull request merged**
