### PR TITLE
Switch to webui2 in test environment in request show

### PR DESCRIPTION
**Pull request by krauselukas**
We need to enable bootstrap in the test environment to
catch failing feature tests.

### CODE REVIEW

**Comment by dmarcoux** [comment]
It's not to prevent failing specs, but to catch failing specs early instead of just before finishing the deliverable.

The issue now is that since the page is not completely migrated to webui2, some specs will fail until we are done with the migration. Skipping them would bring us back to what we had before this PR, so it's not a viable solution. Someone has an idea?

**Comment by DavidKang** [comment]
@dmarcoux, we can skip it only for Bootstrap using `skip_if_bootstrap` and in this case, we know that should add new tests for bootstrap.

**Comment by krauselukas** [comment]
@dmarcoux allright, i changed the commit message and skiped the failing feature tests

**Comment by dmarcoux** [comment]
[Enable skipped tests for Bootstrap](https://trello.com/c/wghw0C5E/1040-enable-skipped-tests-for-bootstrap)

**Comment by dmarcoux** [comment]
As you can see with the link above, I created a card in our backlog to enable the skipped tests before we finish the deliverable.

**Comment by DavidKang** [comment]
@coolo, thanks :smile_cat:

**Comment by hennevogel** [comment]
I don't get it. We keep showing the old UI in production (fine) but then we delay fixing the tests/writing new ones with `skip_if_bootstrap` until the end of the deliverable again? Which was the horrible situation we wanted to get out of. I think you need to rethink this...

**Pull request merged**
