### PR TITLE
hot fix to get basic functionality back for now

### PR DESCRIPTION
**Pull request by adrianschroeter**
seems there is more, but no time right now.

many clases plus methods plus global variables are not really
easy to debug

### CODE REVIEW

**Comment by bugfinder** [comment]
IBS added as api-15-owner_hotfix.patch

**Comment by coolo** [comment]
it would be cool to understand the problem you're trying to fix - because as you can see on the red marks here, you broke tests.

**Comment by coolo** [comment]
This is about the empty result of `iosc bugowner -v bash`, do I guess right?

**Comment by bugfinder** [comment]
looks like the patch broken more than it fixed, reverted for now.

**Comment by coolo** [comment]
@adrianschroeter your "hot fixed regressions" patched 10 minutes before you leave the office are pretty annoying. Especially for things that aren't regressions at all.

211b125291d201636425d88441c9c43220c02655 is your commit from 2014 and added a filter to only return confirmed accounts. While it seems your whole stunt was about subaccounts not returned.

So if the requirements changed meanwhile, the code should change too - that's not exactly the definition of regression. I'll create a PR for what you seem to be after - returning subaccounts.

**Comment by coolo** [comment]
-> https://github.com/openSUSE/open-build-service/pull/7642

**Comment by hennevogel** [comment]
Love is in the air...

**Pull request closed without merging**
