### PR TITLE
Travis speedup

### PR DESCRIPTION
**Pull request by hennevogel**
* Fails fast: All test suites (api, webui, rubocop) run in parallel, the first failing one let's the complete CI 
  build fail
* Prepare bundler caching so we can use it once travis-ci/apt-source-whitelist/pull/14 is done
* Do not introduce the coveralls gem inside the CI Build, include it by default
* Simplify the scripts used to setup the CI build
* Simplify the SimpleCov setup

CI builds now look like this:

<a href="https://travis-ci.org/hennevogel/open-build-service/builds/76086466">
screenshot from 2015-08-18 13-45-11
</a>

### CODE REVIEW

**Comment by hennevogel** [comment]
One nasty thing is that coveralls will report premature coverage here even if only one testsuite ran. So the coveralls reporting is useless unless travis has run through completely

**Comment by hennevogel** [comment]
Also please note that travis sums up the time of the individual test runs in it's indexes. Which means that they now say around ~45 minutes (5 for rubocop, 20 for api&webui) when in reality the CI build only took as long as the longes running test suite (20 minutes).

**Comment by bgeuken** [comment]
Looks awesome.

Though someone else should have a second look at it.

**Comment by mdeniz** [comment]
LGTM +1

**Comment by marcus-h** [comment]
Hmm in commit 282fd203063717a73719b3c0183b360ce890df88 there seems
to be a missing redirection. It should probably look like this:

diff --git a/dist/ci/obs_testsuite_travis.sh b/dist/ci/obs_testsuite_travis.sh
index 00e0a00..a5b1a3e 100755
--- a/dist/ci/obs_testsuite_travis.sh
+++ b/dist/ci/obs_testsuite_travis.sh
@@ -37,8 +37,8 @@ fi
 cd ../..
  
   echo "Killing backend processes"
   -if fuser -v $PWD | egrep 'perl|ruby'; then
   -  list=`fuser -v $PWD 2>&1 | egrep 'perl|ruby' | sed -e "s,^ *$USER *,,;"  | cut '-d ' -f1`
   +if fuser -v $PWD 2>&1 | egrep 'perl|ruby'; then
   +  list=`fuser -v $PWD 2>&1 | egrep 'perl|ruby' | sed -e "s,^.*$USER *,,;"  | cut '-d ' -f1`
      for p in $list; do
           echo "Kill $p"
                # the process might have gone away on its own, so use || true

Maybe omit the if-statement and always execute the its body? In case you
want to keep it, we could also pass "--quiet" to the first egrep call.

**Comment by hennevogel** [comment]
@marcus-h this is just copy&paste from how it was before, are you sure?

**Comment by hennevogel** [comment]
BTW when everything works this shaves off 8-10 minutes from the travis run

**Comment by marcus-h** [comment]
On 2015-08-18 07:37:04 -0700, Henne Vogelsang wrote:
> @marcus-h this is just copy&paste from how it was before, are you sure?
> 
fuser writes everything except the PIDs to stderr (man fuser). Hence,
the egrep doesn't match and exits with status "1". Thus, the if condition
fails and nothing is killed.
If I'm not completely mistaken, the current code is a NOP:)

(Note: I'm referring to fuser from psmisc-22.21-6.2.x86_64)

**Comment by hennevogel** [comment]
Awesome, then we can even remove it as it's obviously not needed ;-)

**Comment by hennevogel** [comment]
Alright. Here we go! :ship:

**Pull request merged**
