### PR TITLE
[frontend] Use nested module syntax for Kiwi classes

### PR DESCRIPTION
**Pull request by hennevogel**
simplecov has problems to calculate coverage otherwise...

### CODE REVIEW

**Comment by hennevogel** [comment]
I guess it's easier to review if you look at the [diff without whitespace](https://github.com/openSUSE/open-build-service/pull/4080/files?w=1)

**Comment by hennevogel** [comment]
Coverage report still does not include the files...

**Comment by hennevogel** [comment]
Now the only difference is that `event.rb` uses `require_relative` for all the other files...

**Comment by hennevogel** [comment]
Don't know what to do with this now. Close it?

**Comment by evanrolfe** [comment]
> Don't know what to do with this now. Close it?

Its up to you what to with this PR! I've been using nested syntax just because I'm already in the habit of using it, maybe we should agree on which on to use?

**Comment by mdeniz** [comment]
Let's merge it... at least is more consistent, isn't it?

**Pull request merged**
