### PR TITLE
Move staging excluded requests view to webui namespace

### PR DESCRIPTION
**Pull request by krauselukas**

### CODE REVIEW

**Comment by krauselukas** [comment]
[Webui::Staging::ExcludedRequestsController](https://trello.com/c/T6b1Il1C/1280-webuistagingexcludedrequestscontroller)

**Comment by coolo** [comment]
Let me guess: your request is not in backlog and as such the code doesn't want to exclude it. 

A very similiar case is https://github.com/openSUSE/open-build-service/issues/7355 - just file it as an issue and attach the label. We're collecting issues

**Comment by dmarcoux** [comment]
[It's in the review app.](https://obs-reviewlab.opensuse.org/krauselukas-rm_bento_staging_excluded_req/staging_workflows/1) The request is ready, so it should be possible to exclude it.

**Comment by coolo** [comment]
'it should be possible' => https://github.com/openSUSE/open-build-service/issues/new?template=Bug_report.md - that's what I'm saying. 
spec/controllers/staging/excluded_requests_controller_spec.rb only covers excluding backlog requests.

**Comment by krauselukas** [comment]
@dmarcoux I excluded one request here https://obs-reviewlab.opensuse.org/krauselukas-rm_bento_staging_excluded_req/staging_workflows/1/excluded_requests

**Pull request merged**
