### PR TITLE
Update migration test

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
I am 98% sure we don't need the BSTREE hack in the migration test. We just would have had to update the structure.sql back then. Same is true for the '`' chars around schema_migrations string.
The get since rails 5.1 when db:migrate is called.

**Comment by adrianschroeter** [comment]
The BTREE stuff just appeared in last weeks after some change (in git master or due to some updated package), so this was needed to avoid the new failure

**Comment by bgeuken** [comment]
Let's try it. If my theory is correct, the correct way to fix it would have been to run rake db:migrate to update the structure.sql (to add the BTREEs there).

**Comment by mmohring** [comment]
I had setup the new rubygem packages and run the testsuites with your above patch. It passed. LGTM 👍

**Comment by bgeuken** [comment]
Thanks for the feedback:-)

**Comment by mmohring** [comment]
Hi, sorry I forgot to mention that I had to fix the obs-server.spec file, because:

[ 1893s] error: Installed (but unpackaged) file(s) found:
[ 1893s]    /srv/www/obs/api/config/environments/migration.rb

**Comment by bgeuken** [comment]
Just noticed^^
 -> https://github.com/openSUSE/open-build-service/pull/3290

**Pull request merged**
