### PR TITLE
[frontend] Add docker-compose file for HAProxy

### PR DESCRIPTION
**Pull request by ChrisBr**
when starting the development environment with

`docker-compose -f docker-compose.yml -f docker-compose.haproxy.yml up`

another frontend server is started and HAProxy will distribute
the load between the two frontend containers.

### CODE REVIEW

**Comment by hennevogel** [comment]
Hm. Why?

**Comment by ChrisBr** [comment]
> Hm. Why?

Why not? As this is how we want to deploy in the future I want to be able to try it out and play with it in development ....

**Comment by adrianschroeter** [comment]
On Freitag, 27. April 2018, 10:01:34 CEST wrote Christian Bruckmayer:
> > Hm. Why?
> 
> Why not? As this is how we want to deploy in the future I want to be able to try it out and play with it in development .... 

docker-compose is not supported and HA proxy is very specific setup we run in our
infrastructure.

may indeed make more sense to have these infrastructure specific pieces in some other
git repo and keep this one clean from unofficial stuff.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by ChrisBr** [comment]
> docker-compose is not supported and HA proxy is very specific setup we run in our
infrastructure.

docker-compose is not supported? We use it since a year in development? 

This is ONLY for development, I want to play locally around what breaks / happens if I have two instances running (e.g. memcache, delayed job etc etc) before I start setting up real machines. Maybe it is not even worth to setup two machines because it would be too much work to get everything running? We just don't know ....

But well, close it then if there is so much rejection ....

**Comment by ChrisBr** [comment]
> may indeed make more sense to have these infrastructure specific pieces in some other
git repo and keep this one clean from unofficial stuff.

btw we also have docker-compose files for the application health monitoring setup and as well for CI....

**Comment by hennevogel** [comment]
>> Hm. Why?

> Why not? As this is how we want to deploy in the future I want to be able to try it out and play with it in development ....

But we are not going to deploy instance specific config files. I find this too intrusive.

**Comment by hennevogel** [comment]
I'm all for having something HA-proxy like, I just don't want the intrusive config changes. My little drama :princess:

**Comment by hennevogel** [comment]
> Which one? The thinking_sphinx and Procfile?

Sure and I understand how it works. What I would like to see is a solution without touching the current thinking sphinx config file.

**Comment by ChrisBr** [comment]
@hennevogel added what we discussed:
* Created dedicated contrib/thinking_sphinx.yml.ha file which gets mounted
* Created dedicated Procfile which gets mounted

Additionally I added the hostname to the peek status bar, see screenshot:
image

I also enabled the HAProxy statistics page:
image

**Comment by ChrisBr** [comment]
> Please add the "why" to 2f6a2bb

Ups, added

**Comment by ChrisBr** [comment]
SR is here https://build.opensuse.org/request/show/614980

**Comment by ChrisBr** [comment]
https://build.opensuse.org/request/show/615182

**Pull request merged**
