### PR TITLE
Updating gems

### PR DESCRIPTION
**Pull request by DavidKang**

### CODE REVIEW

**Comment by DavidKang** [comment]
Before merge we need to updated the packages in O:S:U

**Comment by DavidKang** [comment]
I will handle the last Hakiri warning in another PR

**Comment by greysteil** [comment]
Hey @DavidKang, slightly cheeky, but I saw you're using Depfu on this repo and wondered if you'd evaluated [Dependabot](https://dependabot.com) when you chose it? I built it and it's a bit more conscientious about open source than Depfu (our core is open source [here](https://github.com/dependabot/dependabot-core) and I'm a core contributor to Bundler after doing a lot of work with them over the last year, particularly on the resolution engine). We're also a bit bigger (about 10x).

**Comment by DavidKang** [comment]
@greysteil, thanks for the information :smile_cat:

**Comment by DavidKang** [comment]
Dependantbot is enabled, this PR is not needed

**Pull request closed without merging**
