### PR TITLE
Remove a lot of unused code in test_helper

### PR DESCRIPTION
**Pull request by coolo**
As in minitest we only have the spider test left, there is
a lot of code unnecessary

### CODE REVIEW

**Comment by hennevogel** [comment]
> As in minitest we only have the spider test left

Erm what?

**Comment by coolo** [comment]
What is unclear here?

**Comment by hennevogel** [comment]
> What is unclear here?

`login_dmayr` is used in `CommentsControllerTest` which is in `test:api:group1`. We don't execute them anymore?

**Comment by coolo** [comment]
there are 2 login_dmayr. One in Webui::IntegrationTest and one in  ActionDispatch::IntegrationTest

**Comment by hennevogel** [comment]
> there are 2 login_dmayr

Sorry for the noise, guess I need glasses 🤓

**Pull request merged**
