### PR TITLE
[ci] Update simplecov gem to 0.15.1

### PR DESCRIPTION
**Pull request by DavidKang**
d:l:r:e is not updated to this version of simplecov

### CODE REVIEW

**Comment by DavidKang** [comment]
Submit Requested: https://build.opensuse.org/request/show/526025

**Comment by mschnitzer** [comment]
Request was accepted.

**Comment by DavidKang** [comment]
DO NOT MERGE IT until coverage is increased

**Comment by hennevogel** [comment]
@DavidKang when is this going to be the case? :-)

**Comment by DavidKang** [comment]
@hennevogel, I'm going to see why in some cases is not taking an account the `end` for the coverage.

**Comment by PragTob** [comment]
Small excerp from the simplecov thread for visibility:

> Another thing I noticed is that it appears that you might start simplecov 2 times (both from rails_helper and test_helper) which might lead to some missing coverage as mentioned in the README. You could use the `support/coverage` you already have in place and also use it from `test_helper.rb`.
>
> Alternatively the suggested way is to use [`.simplecov`](https://github.com/colszowka/simplecov#using-simplecov-for-centralized-config) :)

Cheers!

**Comment by hennevogel** [comment]
@PragTob those two test_helper(minitest)/rails_helper(rspec) are completely separated test suites...

**Pull request closed without merging**
