### PR TITLE
Move Add Maintenance Incidents actions next to the Maintenance Incidents Header

### PR DESCRIPTION
**Pull request by danidoni**
## How it looks like now?
image

### CODE REVIEW

**Comment by danidoni** [comment]
[Revisit and move pending actions (generic VS contextual)](https://trello.com/c/wtYKbgJm/1572-revisit-and-move-pending-actions-generic-vs-contextual)

**Review by krauselukas — COMMENTED** [review]
Shouldn't be the action in the sidebar in this case? Since the add action is related to the maintenance incident and the the view context are the incidents itself?

**Review by krauselukas — APPROVED** [review]
Sorry, I thought again, I think its correct looking at other examples

**Review by krauselukas — CHANGES_REQUESTED** [review]
as discussed with @danidoni my original concern was correct, so the action belongs to the sidebar

**Comment by DavidKang** [comment]
Not sure,  but this PR https://github.com/openSUSE/open-build-service/pull/10453, should also be reworked to be consistent, right?
I mean, if you are going to move it to the sidebar.

**Comment by danidoni** [comment]
> Not sure, but this PR #10453, should also be reworked to be consistent, right?
> I mean, if you are going to move it to the sidebar.

Yes, that's the next step

**Comment by danidoni** [comment]
> Not sure, but this PR #10453, should also be reworked to be consistent, right?
> I mean, if you are going to move it to the sidebar.

Taken care of here #10458

**Review by krauselukas — APPROVED** [review]

**Pull request merged**
