### PR TITLE
Move status_controller#history to its own controller

### PR DESCRIPTION
**Pull request by vpereira**
Following the single responsibility pattern,
we move the history action from ```Status_Controller```
to its own controller ```StatusController``` and rename
the action to ```show```. Keeping the old routes

### CODE REVIEW

**Comment by coolo** [comment]
FYI: this route isn't used since e39a9a7b7563aa063700d15da876da2df10db531

**Comment by vpereira** [comment]
that means i can drop it completely @coolo ?

**Comment by coolo** [comment]
damn, I should finish my sentenses - it was an internal route to be consumed by the webui.

**Comment by Ana06** [comment]
@coolo does project action by chance also stopped being used? to avoid moving it out and then removing it... :unamused: 

Are you also sure anybody else is relying in those rutes? :thinking:

**Comment by vpereira** [comment]
closing after talk with @hennevogel and @coolo. the history related actions are going to be removed in a follow-up PR

**Comment by coolo** [comment]
status/project is used a lot - e.g. by the infamous bot to update rubygems

**Pull request closed without merging**
