### PR TITLE
[webui] Allow to use 'filelimit' parameter for package source diffs

### PR DESCRIPTION
**Pull request by mschnitzer**
There is the 'filelimit' parameter which is supported by the backend.

### CODE REVIEW

**Comment by mschnitzer** [comment]
[(3) UI request diff truncate hint missing](https://trello.com/c/TKN1NJEC/1210-3-ui-request-diff-truncate-hint-missing)

**Comment by mschnitzer** [comment]
@Ana06 it will be required by the card I linked. I just wanted to split code.

**Comment by Ana06** [comment]
@mschnitzer 

> @Ana06 it will be required by the card I linked. I just wanted to split code.

why do you want to split the code?

**Comment by mschnitzer** [comment]
@Ana06 I meant the PR's. We can also have this commit in the upcoming PR - I don't care. It doesn't make a difference.

**Comment by Ana06** [comment]
@mschnitzer 

> @Ana06 I meant the PR's. We can also have this commit in the upcoming PR - I don't care. It doesn't make a difference.

It makes a difference, in that moment it would be needed... now it is not. I would prefer to add this together with the rest of the changes. As said, it is just a really small part of it.

**Comment by mschnitzer** [comment]
Alright then

**Pull request closed without merging**
