### PR TITLE
Get rid of frontend compat patchinfo

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@ChrisBr @adrianschroeter @mdeniz @hennevogel Please review!

I am adding some tests for the remove action soon

**Comment by bgeuken** [comment]
I rebased. Unfortunately this conversation got lost:/ : https://github.com/bgeuken/open-build-service/commit/5d3911f7069596833227eefe059eb749a8027269#commitcomment-13310347

**Comment by hennevogel** [comment]
Looks good to me :-)

**Comment by bgeuken** [comment]
I rebased on current master and added additional tests (1a6469b). Since this already got approved, I am merging it now.

**Pull request merged**
