### PR TITLE
[backend] allow to get buildinfo for linked projects #10751

### LINKED ISSUE #10751: Package meta not work when link project
# Issue Description
When I link project using option
```xml
  <link project="PRJNAME"/>
```
to other project, package from this project in `Inherited packages` tab  building with ignoring package meta configuration.

Expected Result
============
Packages in the `Inherited packages` tab are built in the same way as in the original project

How to Reproduce
===============
1. Create project PROJECT1
2. Create package PACKAGE
3. Add repository.
3. Configure package meta. Disable build for `i586`
4. Create project PROJECT2
5. Edit meta of PROJECT2
    ```xml
    <project name="PROJECT2">
      <link project="PROJECT1"/>
      <repository name="CentOS_6">
         <path project="PROJECT1" repository="CentOS_6"/>
         <arch>x86_64</arch>
         <arch>i586</arch>
      </repository>
    </project>
    ```
6. See result in `Inherited packages`

Further Information
===============
* Source project: https://build.opensuse.org/project/show/home:k.velichko
* Linked project: https://build.opensuse.org/project/show/home:k.velichko:branches:home:k.velichko
* Reproduced in local OBS 2.10.8

### PR DESCRIPTION
**Pull request by kvelichko-omp**
Hey Friends,

This PR allow control package build  when link project. Fixes #10751

To verify this feature

- Enable interconnect with openSUSE.org
- Create the project `donor` with meta:
```
<project name="donor">
  <title/>
  <description/>
  <person userid="Admin" role="maintainer"/>
  <repository name="openSUSE_Leap_15.2">
    <path project="openSUSE.org:openSUSE:Leap:15.2" repository="standard"/>
    <arch>x86_64</arch>
  </repository>
  <repository name="disabled_repo">
    <path project="openSUSE.org:openSUSE:Leap:15.2" repository="standard"/>
    <arch>x86_64</arch>
  </repository>
</project>
```
- Create package `simple_enabled` into donor project with meta:
```
<package name="simple_enabled" project="donor">
  <title/>
  <description/>
  <build>
    <disable/>
    <enable arch="x86_64" repository="openSUSE_Leap_15.2"/>
  </build>
</package>
```
- Add file `some.spec` into package `simple_enabled` with content:
```
Name:           simple_enabled
License:        GPLv2+
Group:          Development/Tools/Building
AutoReqProv:    on
Summary:        Test Package
Version:        1.0
Release:        1
Requires:       bash
Conflicts:      something
Provides:       myself

%description

%prep

%build

%install
mkdir -p $RPM_BUILD_ROOT
echo "CONTENT" > $RPM_BUILD_ROOT/my_packaged_file

%files
%defattr(-,root,root)
/my_packaged_file

%changelog
```
- Create home:Admin project with meta:
```
<project name="home:Admin">
  <title/>
  <description/>
  <link project="donor"/>
  <person userid="Admin" role="maintainer"/>
  <repository name="openSUSE_Leap_15.2" block="all" linkedbuild="all">
    <path project="donor" repository="openSUSE_Leap_15.2"/>
    <arch>x86_64</arch>
  </repository>
  <repository name="disabled_repo" block="all" linkedbuild="all">
    <path project="donor" repository="disabled_repo"/>
    <arch>x86_64</arch>
  </repository>
</project>
```
**Monitor page of donor project:**
donor monitor before

**Monitor page of home:Admin Before:**
home monitor before

**Monitor page of home:Admin After:**
home monitor after

### CODE REVIEW

**Comment by kvelichko-omp** [comment]
Hi. You have any news about this?

**Comment by dmarcoux** [comment]
@mls @adrianschroeter @M0ses: Please have a look at this PR.

**Comment by kvelichko-omp** [comment]
@mlschroe @adrianschroeter @M0ses: any news?

**Comment by adrianschroeter** [comment]
package meta is supposed to be ignored when the package comes from another project.

The repository names are do necessarly match and this woudl be also a deeply incompatible change.

If the flag is supposed to stick to the sources, define it in the sources. For example with Exclude/ExclusiveArch definitions.

**Pull request closed without merging**
