### PR TITLE
Fix validation of IssueTracker and its Factory

### LINKED ISSUE #5439: Cassettes hide yet another problem
master:
```
Issue
  #fetch_issues
    fetches the issues

Finished in 1.88 seconds (files took 4.51 seconds to load)
```

Now enable global_write_through in spec/support/vcr.rb and run again:
```
Issue
  #fetch_issues
    fetches the issues (FAILED - 1)

Failures:

  1) Issue#fetch_issues fetches the issues
     Failure/Error: raise ActiveXML::Transport::Error, message.force_encoding('UTF-8')
     
     ActiveXML::Transport::Error:
       <status code="400">
         <summary>element 'description' contains attributes nil</summary>
       </status>
     # ./lib/backend/connection.rb:126:in `handle_response'
     # ./lib/backend/connection.rb:112:in `put_or_post'
     # ./lib/backend/connection.rb:35:in `put'
     # ./lib/backend/connection_helper.rb:60:in `http_put'
     # ./lib/backend/api/issue_trackers.rb:9:in `write_list'
     # ./app/jobs/issue_tracker_write_to_backend_job.rb:8:in `perform'
     # ./app/models/issue_tracker.rb:24:in `delayed_write_to_backend'
     # ./spec/models/issue_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

Finished in 1.86 seconds (files took 4.67 seconds to load)

### PR DESCRIPTION
**Pull request by coolo**
The syntax of a class shouldn't depend on Config options

Fixes #5439

### CODE REVIEW

**Comment by coolo** [comment]
the minitest suite fails now

**Comment by bgeuken** [comment]
Interesting. Could you check whether global_write_through is set to true or not when the test starts / ` app/models/issue_tracker.rb` get's parsed first time?

**Comment by coolo** [comment]
minitest only sets global_write_through on first process call (get,post,put). If the model has been parsed at that point or not depends on test order (as usual  :cry: )

The change I did now is that the save hook is actually called and as such the backend knows now about the issue_trackers once some new issue tracker is created. If that's the case or not - again - depends on the test order. 

If I run the failing tests individually, they work - which kind of proves they expect the backend *not* to know the issue trackers from fixtures/seeds

test/unit/issue_test.rb has 2 tests that create new issue trackers. Those delete the others and then save into backend. This does not happen in master. And I think this is what they see.

**Comment by coolo** [comment]
If my theory is right, dcea9eb1f should help

**Comment by hennevogel** [comment]
```
 _____________________
/                     \
| global write through |
|    needs to die      |
\_____________________/
         !  !
         !  !
         L_ !
        / _)!
       / /__L
 _____/ (____)
        (____)
 _____  (____)
      \_(____)
         !  !
         !  !
         \__/
```

**Comment by coolo** [comment]
I'm all for it - and actually the main reason the cassettes have to die, as they are only kept alive due to global_write_through=false

**Comment by coolo** [comment]
tests pass - on to find all the other failures in rspec with global_write_through

**Pull request merged**
