### PR TITLE
[ci] Run our new rpsec test suite in travis

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
This currently fails because of rspec tests. So **please don't merge**

**Comment by hennevogel** [comment]
Why already?

**Comment by adrianschroeter** [comment]
IMHO we should not open pull requests when they can not get merged ....

**Comment by mdeniz** [comment]
Can we just close this PR, the new from out meeting includes these changes too

**Comment by hennevogel** [comment]
We can. Duplicate of #1501

**Comment by bgeuken** [comment]
@adrianschroeter That's how I discovered that the rspec tests currently fail;-) And I didn't expect we would take that long to fix them...

Glad that we could agree to run rspec tests in our travis test suite too...

**Comment by bgeuken** [comment]
Glad that we could agree to run rspec tests in our travis test suite too...

**Pull request closed without merging**
