### PR TITLE
[doc] use asciidoc format for ReleaseNotes

### PR DESCRIPTION
**Pull request by lethliel**
This is an idea and start to switch the documentation of
obs to asciidoc files which can then easily translated in
any format (like HTML, PDF, EPUB, man pages)

I started with the ReleaseNotes files and tried to keep
them "as they were".

http://asciidoc.org/

### CODE REVIEW

**Comment by hennevogel** [comment]
Can you elaborate what you mean with ` the documentation of obs`?

**Comment by lethliel** [comment]
The books for an example. But this is just the first step.

**Comment by lethliel** [comment]
@hennevogel I know. But this is also for the ReleaseNotes which look nicer using Asciidoc when they are viewed directly in Github...

**Comment by hennevogel** [comment]
> which look nicer using Asciidoc when they are viewed directly in Github

Then I would vote for markdown as we use it everywhere else (READMEs, issues, wiki, blog etc.) already and it's also [easily translated](https://pandoc.org/) to other formats...

**Comment by hennevogel** [comment]
@lethliel now what? :-)

**Comment by dmarcoux** [comment]
Closing this due to inactivity for almost a month now. Feel free to open it again if needed.

**Pull request closed without merging**
