### PR TITLE
Support closed, merged and reopened pull/merge requests in ConfigureRepositories step

### PR DESCRIPTION
**Pull request by dmarcoux**

### CODE REVIEW

**Comment by dmarcoux** [comment]
[Support closing/merging/reopening actions for PRs/MRs](https://trello.com/c/nlIsH1Wp/1737-support-closing-merging-reopening-actions-for-prs-mrs)

**Comment by hennevogel** [comment]
I'm not sure rolling back step by step makes much sense. How about you just delete the project?

**Comment by vpereira** [comment]
> I'm not sure rolling back step by step makes much sense. How about you just delete the project and the subscriber?

that's what I'm doing here https://github.com/openSUSE/open-build-service/pull/11595

**Comment by dmarcoux** [comment]
Superseded by #11596

**Pull request closed without merging**
