### PR TITLE
Fix issue#1699 - plotters on /monitor page exchanged

### PR DESCRIPTION
**Pull request by bgeuken**
Updating the jquery flot version required to explicitly add jquery.flot.stack.js
to the application.js file.
This caused the active workers monitor graph not being stacked anymore.

### CODE REVIEW

**Comment by mmohring** [comment]
Are you sure that you don't have to change src/api/app/views/webui/monitor/_events.html.erb. There is only spacing changed in this file.

**Comment by coolo** [comment]
the stack: true is already part of the file - just toothless without the =include

**Comment by mmohring** [comment]
@coolo enlight us, which =include where, I have got my wires crossed :)

**Comment by coolo** [comment]
the javascript asset. the correct key word is =require, but it's actually including :)

**Comment by coolo** [comment]
basically: LGTM

**Comment by bgeuken** [comment]
@mmohring The actual fix was to add the jquery.flot.stack.js lib to the application.js. The changes in _events.html.erb are just small cleanups I made while debugging.

**Comment by mmohring** [comment]
@bgeuken I just wanted to say that it does not change the graphs when I apply this patch.

**Comment by bgeuken** [comment]
Your OBS probably runs in production mode. Try this:
RAILS_ENV=production bundle exec rake.ruby2.3 assets:precompile

**Comment by mmohring** [comment]
LGTM. Works. You are right I got fooled by the `bundle exec rake.ruby2.3 assets:precompile` to be done for some content files.

**Pull request merged**
