### PR TITLE
[docu] Introduces a commit message template

### PR DESCRIPTION
**Pull request by hennevogel**
A bunch of us have talked about what the content of good commit meesages should
look like and came up with this template. Here is how you can make use of it:

cp .gitmessage ~/.gitmessage

Add this to your ~/.gitconfig

[commit]
  template = ~/.gitmessage

Everyboy following this template will help people to understand the changes in
the future. Addtionally it will make it easier for us to use commit messages in
documentation like our Changelog, books or our blog.

Co-authored-by: Manuel Schnitzer <github@mschnitzer.de>
Co-authored-by: Björn Geuken <bgeuken@suse.de>
Co-authored-by: Henne Vogelsang <hvogel@opensuse.org>
Co-authored-by: Moises Deniz Aleman <mdeniz@suse.com>
Co-authored-by: Eduardo Navarro <enavarro@suse.com>

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2018-02-09 14:40:23 +0000, Henne Vogelsang wrote:
> diff --git a/.gitmessage b/.gitmessage
> new file mode 100644
> index 0000000000..563bcb70dd
> --- /dev/null
> +++ b/.gitmessage

<SNIP>

> +# Explain **why** you have changed this instead of the *how*.
> +# This is the most important content of the message.
> +
Hmm I probably got this wrong, but why is the "why" interesting?
Examples for "why":
- fix bug xyz
- avoid crash in abc

IMHO, the "how" is the interesting part. Especially, because
you can verify if the textual "how" description is correctly
translated into the code (and maybe vice versa).

(Personally, I like "2) Describe your changes" in [1].)

> +# If this commit fixes an issue you need to mention it like
> +# Fixes #1234
> +
Maybe an optional nice to have: include the summary line (if
useful...) of the bug. For instance,
Fixes #1234 ("Exception when doing xyz")

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst

**Comment by hennevogel** [comment]
> Hmm I probably got this wrong, but why is the "why" interesting?

Because we think it's important to understand **why** someone has done something and because we love small commits with self-explanatory code. Your examples of **why** would IMHO translate to

```
Subject: Make Glass.gauge return "half-full" instead of "half-empty" if it's filled 50%

People complained about the negative mood this spread in the interface.

Fixes #xyz
```

```
Subject: Make Glass.gauge return always a string 

Returning an array ['half-full', 'half-empty'] in the case of 50%
made the abc controller crash.
```

**Comment by hennevogel** [comment]
@marcus-h is that definition okay with you? :-)

**Comment by marcus-h** [comment]
On 2018-02-12 10:03:59 +0000, Henne Vogelsang wrote:
> @marcus-h is that definition okay with you? :-)
> 
Maybe... But anyway just merge it. I'm sure people will
automatically/intuitively choose the right amount of "why", "how"
etc. in their commit messages:)

From your other mail:
> Because we think it's important to understand **why** someone has done something

That is, "why" in terms of "why does the commit fix the problem?"?
If so, this, in some sense, coincides with my interpretation of "how".

> and because we love small commits with self-explanatory code.

Who doesn't?;)

**Pull request merged**
