### PR TITLE
Fix hanging consistency check jobs

### PR DESCRIPTION
**Pull request by adrianschroeter**

### CODE REVIEW

**Comment by hennevogel** [comment]
AdminMailer. Nice.

**Comment by adrianschroeter** [comment]
@hennevogel not 100% sure, using a special Event type would make it more configurable and flexiable.

But it won't work when there is a problem with event or delayed job processing like we had in the last days....

**Comment by hennevogel** [comment]
Well, this way better than raising an exception :-)

**Comment by adrianschroeter** [comment]
hm, and we could also send notifications from the backend .... maybe I should really change this and use AdminMailer only direct when we detect problems in the event or job queuing ...

Or we create an own table to record such issues. They could be displayed then also.

But that would be a new feature and I just want to solve the hanging jobs for now. So this is just a temporary solution IMHO.

**Pull request merged**
