### PR TITLE
Link to the Commit Style wiki page in the 'Proper Commit Messages' section

### PR DESCRIPTION
**Pull request by dmarcoux**
Having a single source of truth is better than having duplicated information.

### CODE REVIEW

**Comment by dmarcoux** [comment]
We either link to the Commit Style wiki page or pull its content in the CONTRIBUTING.md. I prefer the approach taken in this PR.

What do you think?

**Review by danidoni — APPROVED** [review]

**Comment by hennevogel** [comment]
I don't like throwing heaps and heaps of rules at people. It's a big contribution hurdle. Remember how you felt with your first open source contribution. I was shitting my pants that I would do something wrong and that people would be mean or that something would break. If you would have shown me a 20 item list to follow I would just not do it.

**Comment by dmarcoux** [comment]
@hennevogel True, a big list of things to do can be scary for no contributors. So you prefer to keep it as it is?

**Comment by dmarcoux** [comment]
@danidoni is for the change, @hennevogel is against it. I didn't get other feedback, so I'll close this PR since it's not unanimous.

**Pull request closed without merging**
