### PR TITLE
[backend] add 'cacheonly' option for diffing sources

### PR DESCRIPTION
**Pull request by mlschroe**
We'll use this in the API to defer source diffing to a delay job,
so that the WebUI does not clog up all source server slots.

### CODE REVIEW

**Comment by vpereira** [comment]
@mlschroe ```undefined method `is_nobody?' for nil:NilClass```

**Comment by adrianschroeter** [comment]
@vpereira my bug, hopefully fixed now.

**Comment by mlschroe** [comment]
@adrianschroeter you need to add the `cachonly` option to the list of accepted options in the source_diff method (`lib/backend/api/sources/package.rb`)

**Comment by vpereira** [comment]
> @vpereira my bug, hopefully fixed now.

Ok, but the spider is failing @adrianschroeter normally it means that some route is raising an exception..

**Pull request merged**
