### PR TITLE
Replace Bento by Bootstrap for configuration

### PR DESCRIPTION
**Pull request by eduardoj**

### CODE REVIEW

**Comment by eduardoj** [comment]
[Webui::ConfigurationController](https://trello.com/c/lo9vQTLL/1247-webuiconfigurationcontroller)

**Comment by dmarcoux** [comment]
`Remove not used (...) methods` is a bit weird in the first commit message. It could be `Remove unused (...) methods` or `Remove unneeded (...) methods`.

**Comment by eduardoj** [comment]
> `Remove not used (...) methods` is a bit weird in the first commit message. It could be `Remove unused (...) methods` or `Remove unneeded (...) methods`.

Changed. Thanks!

**Comment by eduardoj** [comment]
I rebased on master due to merge conflicts.

**Pull request merged**
