### PR TITLE
[webui] Modified submit package request from revisions view.

### PR DESCRIPTION
**Pull request by alllexandr**
[webui] Modified submit package request from revisions view. For submit viewed revision.
Added revision parameter to submitPackage button ('package_go', 'Submit package')

### CODE REVIEW

**Comment by hennevogel** [comment]
hey @alllexandr, thank you for your contribution 💐  If you need help with resolving the test failures let us know, we are here to help :neckbeard:

**Comment by ChrisBr** [comment]
I restarted the tests, looked unrelated!

But anyway, a test for this change would be nice :smile:

**Comment by alllexandr** [comment]
can some one help me with test? I don understand why my commit don't pass it.

**Comment by ChrisBr** [comment]
@alllexandr can you please run the failing test locally on your machine with
``
bundle exec rake test TEST=test/functional/webui/package_branch_test.rb:90
``

and paste the output somewhere. I could imagine that you get a 500 because ``@revision`` is ``nil`` and then the link generation does not work...

**Comment by bgeuken** [comment]
@alllexandr What happened here is that the test was [adding a new revision](https://github.com/openSUSE/open-build-service/blob/master/src/api/test/functional/webui/package_branch_test.rb#L84) after loading the page. Since with your changes the revision suddenly matters, this caused the test to fail.

#2878 fixes this by reloading the page after creating the revision.

**Comment by hennevogel** [comment]
@alllexandr can you [rebase](https://help.github.com/articles/about-git-rebase/) your pull request on master? Then @bgeuken's fix is picked up :-)

**Comment by bgeuken** [comment]
@alllexandr I've cherry-picked your commit now and created a pull request (#2917). Hope that's okay with you.

Thanks again for your contribution:-)

And it seems I've overlooked another test failure before-.-

**Comment by alllexandr** [comment]
thanks for help

**Pull request closed without merging**
