### PR TITLE
WIP Refactor request show controller

### PR DESCRIPTION
**Pull request by vpereira**
Working progress attempt to extract code from the ```RequestController#show``` action, using some service to do it

TODO:

- [ ] check what is really needed from ```BsRequest#webui_infos```
- [ ] extend specs from ```RequestWebuiInfo``` class

### CODE REVIEW

**Comment by hennevogel** [comment]
I guess you have a fundamental flaw in your architecture: You think  `.webui_infos` makes any sense. It doesn't. Do not bury it deeper, rip it out. :boom: :rofl:

**Comment by coolo** [comment]
this is 100% the wrong thing to do.

**Comment by coolo** [comment]
the whole purpose of webui_infos was to get *one* route for the webui to access in the api - when both were different projects. But this is long gone and the function doesn't make any sense any longer. 

In #6225 I even don't use any of the show code - but it's my understanding that such refactoring is for later time and you want to finish migrating all of OBS to bootstrap first.

**Comment by hennevogel** [comment]
> but it's my understanding that such refactoring is for later time and you want to finish migrating all of OBS to bootstrap first.

This is 100% the wrong understanding :cowboy_hat_face:

**Comment by vpereira** [comment]
> I guess you have a fundamental flaw in your architecture: You think `.webui_infos` makes any sense. It doesn't. Do not bury it deeper, rip it out.

that's why I have it as first task in the TODO :)

**Comment by vpereira** [comment]
> but it's my understanding that such refactoring is for later time and you want to finish migrating all of > OBS to bootstrap first.

I don't remember to see you in the last planing meetings :smile: :smile:

**Comment by coolo** [comment]
> I don't remember to see you in the last planing meetings

I don't remember an invitation, so I take my understanding of what is said in public.

**Comment by hennevogel** [comment]
> I don't remember an invitation, so I take my understanding of what is said in public.

Feel free to stop by my desk and/or IRC query if you want to improve your understanding. I'm here for you :kiss:

**Comment by vpereira** [comment]
close it for now

**Comment by bgeuken** [comment]
> this is 100% the wrong thing to do.

Well, I would say the same about some of the additional layers of hashing code that someone added recently:wink: For me it depends in the end on whether we reach the goal (replacing webui_info with active record relations) or not. If it helps to wrap the code first some object or service that's fine for me.
(IIRC, I already mentioned that I didn't yet see any good usecase in OBS for the services pattern:smiley:)

**Pull request closed without merging**
