### PR TITLE
[api] Encapsulate the code related to project#update_from_xml into its own service class

### PR DESCRIPTION
**Pull request by evanrolfe**
There are many public methods in the `Project` class which are only ever used by the `update_from_xml` method so these should be made private and can be encapsulated into a [service class](https://blog.engineyard.com/2014/keeping-your-rails-controllers-dry-with-services) in order to try and get a tiny bit closer to following the single responsibility principle and to reduce the size of the `Project` class.

### CODE REVIEW

**Comment by DavidKang** [comment]
@evanrolfe, nice 👍

**Comment by hennevogel** [comment]
@openSUSE/open-build-service we should discuss if we want to use service classes :-)

**Comment by evanrolfe** [comment]
Here is the mailing list discussion about service objects:
https://lists.opensuse.org/opensuse-buildservice/2017-03/msg00055.html

**Comment by DavidKang** [comment]
@evanrolfe, rebase please 😸

**Comment by evanrolfe** [comment]
thanks @DavidKang this is rebased now

**Comment by bgeuken** [comment]
LGTM

Some description in the commit message would be nice though. Could even be the one you added to the PR.

**Pull request merged**
