### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by ChrisBr** [comment]
@hennevogel Please review!

Do we run Rubocop at the moment for new submitted PRs? I'm just wondering because we had a few offences in master ...

Should I prefix the commits with [CI] (or which prefix would be appropriated here?)?

**Comment by bgeuken** [comment]
@ChrisBr This one should fix our test suite: https://github.com/openSUSE/open-build-service/pull/1076

**Comment by ChrisBr** [comment]
@bgeuken Sure! I use now a heredoc...

**Comment by bgeuken** [comment]
LGTM. Feel free to merge with or without the heredoc change:)

**Comment by hennevogel** [comment]
Please prefix the commits with [ci]

**Comment by ChrisBr** [comment]
@hennevogel done

**Pull request merged**
