### PR TITLE
[webui] fix error message on branch package

### PR DESCRIPTION
**Pull request by adrianschroeter**
some minor  bits during reviewing Package/Project find method usages in webui

### CODE REVIEW

**Comment by ChrisBr** [comment]
Hm, I'd prefer to split it in two commits:
- the bugfix 
- the cosmetic stuff
because it was hard while reviewing to find the actual bugfix ...

And for the cosmetic stuff I'd prefer to use the new ruby hash syntax (I wonder that rubocop does not complain ...)!
``redirect_to :controller => :project, :action => 'new_package_branch', :project => params[:project]``
vs.
``redirect_to controller: :project, action: 'new_package_branch', project: params[:project]``

**Comment by adrianschroeter** [comment]
hm, missed the new hash syntax style comment ... will deal with that one ...

**Comment by adrianschroeter** [comment]
ne1 interessted in reviewing the last commit or just merging?

**Comment by bgeuken** [comment]
LGTM

**Pull request merged**
