### PR TITLE
Rubocop is your friend part 7

### PR DESCRIPTION
**Pull request by DavidKang**
@openSUSE/open-build-service Please review

The affected cops are:
* http://rubocop.readthedocs.io/en/latest/cops_layout/#layoutmultilineoperationindentation
* http://rubocop.readthedocs.io/en/latest/cops_layout/#layoutmultilinemethodcallbracelayout
* http://rubocop.readthedocs.io/en/latest/cops_layout/#layoutindenthash

### CODE REVIEW

**Comment by DavidKang** [comment]
@eduardoj, done

**Comment by DavidKang** [comment]
@bgeuken, right!, I will remove the commit for not block this PR. 😸

**Comment by DavidKang** [comment]
@ChrisBr, could review it please 😸

**Comment by bgeuken** [comment]
He already agreed via mail^^

**Pull request merged**
