### PR TITLE
Remove rspec-retry, not used since July

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by ChrisBr** [comment]
Really :thinking:

**Comment by coolo** [comment]
So can we remove that variable assignment to see how bad it is? Because I believe there is no real problem solved

**Comment by coolo** [comment]
(as in: the tests failing in package builds also flicker in circleci)

**Comment by ChrisBr** [comment]
If you drop https://github.com/openSUSE/open-build-service/blob/master/src/api/script/prepare_spec_tests.sh#L10
we can merge.

**Pull request merged**
