### PR TITLE
Factory dashboard: remove ring2 

### PR DESCRIPTION
**Pull request by coolo**
Was merged into ring1

### CODE REVIEW

**Comment by coolo** [comment]
I'll rebase, once the test case is in

**Comment by ChrisBr** [comment]
Fixes https://github.com/openSUSE/open-build-service/issues/5249

**Comment by ChrisBr** [comment]
It is labeled with do not merge as we wait for more tests!

**Comment by coolo** [comment]
rebased on the tests and fixed them too - so please review, so we can deploy the proper fix for ring2 removal

**Comment by coolo** [comment]
what is the usual timeframe for codeclimate? It seems to hang often

**Comment by ChrisBr** [comment]
> what is the usual timeframe for codeclimate? It seems to hang often
 
Seems to be broken... ignore it!

**Pull request merged**
