### PR TITLE
[api] support request pre-approval

### PR DESCRIPTION
**Pull request by adrianschroeter**
add option to pre-approve a request in review state. It will be accepted
when last review gets accepted.

former way could not work since requests in review state already get
accepted by time.

Also fixed inconsistent behaviour of autoaccept depending on which of the duplicate
autoaccept handling was used.

belongs to Fate 316775

### CODE REVIEW

**Comment by adrianschroeter** [comment]
The failure in rspec BsRequest.delayed_auto_accept reads like it is testing that a request without auto_accept is actually calling BsRequest.delayed_auto_accept . This makes no sense to me or do I read it wrong?

**Comment by adrianschroeter** [comment]
Björn, it is not your test, but you touched it:) Do you have an opinion if it could be a valid test?

**Comment by hennevogel** [comment]
rebased...

**Comment by hennevogel** [comment]
coveralls hands. coverage is okay, see [ci job](https://circleci.com/gh/openSUSE/open-build-service/12187?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). merging.

**Pull request merged**
