### PR TITLE
send package status to a redis server if configured

### PR DESCRIPTION
**Pull request by mlschroe**

### CODE REVIEW

**Comment by vpereira** [comment]
hi @mlschroe does it need any change in the UI, or can we take advantage of that in the frontend?

**Comment by hennevogel** [comment]
Sounds like an awesome opportunity to start documentation! :smile:

**Comment by mlschroe** [comment]
Not so fast, lets first see if it works or not.

**Comment by coolo** [comment]
shall we add a redis container to the ci?

**Pull request merged**
