### PR TITLE
[webui] Make login form clearly distinguishable from search form.

### PR DESCRIPTION
**Pull request by srivatsav1998**
Co-authored-by: Stefan Knorr <sknorr@suse.de>

### CODE REVIEW

**Comment by Ana06** [comment]
@coolo do you have any concern with this? can it be merged? :thinking:

**Comment by coolo** [comment]
well, according to #4608 you don't want bento changes here - but just a copy of it.

**Comment by Ana06** [comment]
@hennevogel can we merge this? :thinking:

**Comment by srivatsav1998** [comment]
If I do git fetch upstream, all the commits are getting added to my pull request with me as an author. What should I do? :(

**Comment by bgeuken** [comment]
@srivatsav1998 commented 16 hours ago
> If I do git fetch upstream, all the commits are getting added to my pull request with me as an author. What should I do? :(

Could you post the command you were running, and where you were running it?

**Comment by srivatsav1998** [comment]
Why is this still not merged? Is there an issue with my request?

**Comment by srivatsav1998** [comment]
@bgeuken, I figured out my mistake. I committed to my master branch instead of creating a new branch. This created the issue with my pull request whenever I tried to update my master branch. Thanks for your response.

**Comment by bgeuken** [comment]
> srivatsav1998 commented 15 minutes ago
> @bgeuken, I figured out my mistake.

okay

> Ana06 commented 2 days ago
> @hennevogel can we merge this?

Given that we already deviate from [upstream bento](https://github.com/openSUSE/opensuse-themes) I don't see any good reason to block this PR now.
So let's merge this and then decide how we want to handle bento in our project in future, eg. syncing with upstream, moving it to vendor/assets/, etc.

**Comment by bgeuken** [comment]
Thanks for your contribution :bouquet:

**Pull request merged**
