### PR TITLE
Create ./sysvinit/ folder for system V init

### PR DESCRIPTION
**Pull request by leemgs**
There are 1) systemd-based unit files for up-to-date Linux distributions and 2) system V init based run-level scripts out-of-date Linux distributions. For readability and consistency, Let's create an appropriate folder.

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

\CC: @myungjoo

### CODE REVIEW

**Comment by leemgs** [comment]
@hennevogel . Thank you for your comment. Updated. And,  I have applied "squash".

**Comment by bgeuken** [comment]
Nice! Thank you:+1:

**Comment by mmohring** [comment]
This patch makes:

make -C dist test
and
rpm packaging fail

Please take a look into the interface for make install and make test in dist/Makefile

**Comment by adrianschroeter** [comment]
We need indeed to fix at least the package build.

Either by fixing Makefiles or by reverting this request.

**Comment by leemgs** [comment]
> Either by fixing Makefiles or by reverting this request.
Please, revert the request insead of fixing Makefiles.
I will re-submit a PR after applying the comment of @mmohring without modifying global Makefile. :)

**Pull request merged**
