### PR TITLE
db: don't use 0 as default datetime value. workaround for #2222

### PR DESCRIPTION
**Pull request by Artox**
The SQL Server might be running with NO_ZERO_DATE set. Use the earliest
valid date as a workaround.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
This is not an issue in our builds, so I wonder why it is in your case. Do you use a different rails stack?
In any case it seems to break stuff according to the test suite.

**Comment by Artox** [comment]
This is with opensuse 42.1 in a docker container, but mysql(not mariadb) living in a debian stable container:

Server version          5.7.15
Protocol version        10
Connection              172.17.0.2 via TCP/IP
TCP port                3306
Uptime:                 1 min 10 sec

that failing test could use a review, however the fix would ideally be to rpovide a proper default value, sth. like NOW(), right?

**Comment by Artox** [comment]
apparently providing CURRENT_TIMESTAMP as default adds a hard dependency on mysql >= 5.6.
This, how about setting default NULL?
Apparently that way it passes all test-cases, but idk if it has any functional implications.

**Comment by bgeuken** [comment]
Looks fine to me. I wouldn't know a reason why the timestamps for projects and packages couldn't be NULL by default. We do that for many other attributes already.

**Comment by bgeuken** [comment]
Adding the do not merge label for now, since the last commit seems to be WIP.

**Comment by Artox** [comment]
I will be pushing a single commit to this PR using default null.
The WIP commit was jsut to see if NULL would fail the testcases or not.

**Comment by bgeuken** [comment]
Change LGTM.

@adrianschroeter are you ok with merging this?

**Comment by adrianschroeter** [comment]
Don't patch this file, but write a migration or this will get reverted on next migration.

Please add also the [api] prefix to your commit message.

**Comment by hennevogel** [comment]
@Artox can you please add the requested changes?

**Comment by hennevogel** [comment]
@Artox?

**Comment by Artox** [comment]
Sorry, I have been extremely busy in the last 2 weeks. I will see about changing the commit to Adrians liking soon(TM)

**Comment by bgeuken** [comment]
@artox This will fix the test failures: https://github.com/bgeuken/open-build-service/commit/4560a27b887d1642a6425974b10185791e7e2695

I didn't want to edit your commit, feel free to add the changes to your commit.

Also please add the [api] tag at the front of your commit message.

And apologies for the late reply 💐

**Comment by Artox** [comment]
@bgeuken Thanks for pointing me at the relation of migration class name and file name!

Fingers crossed that tests pass this time

**Comment by Artox** [comment]
Previous push missed the updated_at field in migration, but 0116d805ae6bc1154c6553ab02e160eecb4d8dfb should be fine now.

**Comment by bgeuken** [comment]
cool :+1:

**Pull request merged**
