### PR TITLE
Ruby 2.5 for 2.9 branch

### PR DESCRIPTION
**Pull request by ChrisBr**
Just cherry-picked from master....

### CODE REVIEW

**Comment by bgeuken** [comment]
you might want to add https://github.com/openSUSE/open-build-service/pull/4460 as well. It's only a docker change. So not necessarily needed for OBS 2.9. But maybe for the sake of completness^^

**Comment by adrianschroeter** [comment]
I like to wait for e few more days running in production on ruby2.9 before really doing the merge into 2.9 branch ....

**Comment by ChrisBr** [comment]
[P9: (8) ruby 2.5 switch](https://trello.com/c/GYUJ3lEj/672-p9-8-ruby-25-switch)

**Comment by hennevogel** [comment]
I think we have waited enough. Merging...

**Pull request merged**
