### PR TITLE
Anonymous access for orderkiwirepos API call

### PR DESCRIPTION
**Pull request by bgeuken**
Per discussion with Adrian we should allow anonymous access to this API point. This will allow external tools, like osc and obs-services, to use this API call without handling credentials.

### CODE REVIEW

**Comment by bgeuken** [comment]
@adrianschroeter Thinking about it, this shouldn't be a POST bug GET request. Since we are not changing any state, but querying data.

**Comment by adrianschroeter** [comment]
It is conform to other operations, where we calculate something, but not just deliver existing data. Also we do modify the send body, this won't work with a GET.

**Comment by bgeuken** [comment]
What do you mean with modify the send body?

**Comment by adrianschroeter** [comment]
You send a kiwi file as part of your request and you get the modified version back.

**Comment by bgeuken** [comment]
Okay, let's keep it consistent with the rest of the code and use POST here.

**Comment by mdeniz** [comment]
[(8) Automatic fix repository ordering of distribution repositories in kiwi import files](https://trello.com/c/rLy1dUVG/38-8-automatic-fix-repository-ordering-of-distribution-repositories-in-kiwi-import-files)

**Comment by ChrisBr** [comment]
LGTM

**Pull request merged**
