### PR TITLE
[ci] Add rubocop cache and also in Travis CI

### PR DESCRIPTION
**Pull request by mdeniz**

### CODE REVIEW

**Comment by mdeniz** [comment]
[(3) Enhance Travis CI configuration [1]](https://trello.com/c/kw5YPySM/9-3-enhance-travis-ci-configuration-1)

**Comment by mschnitzer** [comment]
What exactly will be cached?

**Comment by mdeniz** [comment]
http://rubocop.readthedocs.io/en/latest/caching/

**Comment by mschnitzer** [comment]
LGTM 👍

**Comment by bgeuken** [comment]
:+1:

**Pull request merged**
