### PR TITLE
[webui] Show full humanized time

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by krauselukas** [comment]
Hey @andreas-schwab
Thanks for the PR. Could you please reference the corresponding issue in the commit message,
like: ```Fixes #7382``` (https://github.com/openSUSE/open-build-service/issues/7382)
And maybe provide a little description of what has changed and why.

**Comment by hennevogel** [comment]
@andreas-schwab can you rebase? then I can merge this as false-positive.

**Comment by danidoni** [comment]
Created a new PR rebased against master to fix the Code Climate issue [here](https://github.com/openSUSE/open-build-service/pull/9319)

**Comment by danidoni** [comment]
Closing

**Comment by danidoni** [comment]
Thanks for your effort @andreas-schwab !

**Pull request closed without merging**
