### PR TITLE
[dist] enable obs-api-support.target on update 

### PR DESCRIPTION
**Pull request by M0ses**

### CODE REVIEW

**Comment by hennevogel** [comment]
@M0ses why shouldn't we merge?

**Comment by M0ses** [comment]
It doesn`t work ATM WIP

**Comment by M0ses** [comment]
Doing last check in kanku before ready to merge

**Comment by M0ses** [comment]
IMHO ready to merge

**Comment by hennevogel** [comment]
Sounds like something you want to push to 2.10 too, right?

**Comment by M0ses** [comment]
@hennevogel : Correct, I will prepare a PR for 2.10 and add you as reviewer

**Pull request merged**
