### PR TITLE
[backend] Fix dod handling in getbinary_repository

### LINKED ISSUE #2061: Repository binarylist is broken for repository using DoD
Getting a binarylist of `Ubuntu:16.04` from build.opensuse.org:

```
$ osc -A https://api.opensuse.org/ -X GET /build/Ubuntu:16.04/standard/x86_64/_repository
...
  <binary filename="zsh-common.deb" size="3170342" mtime="1469569341" />
  <binary filename="pool/main/z/zsh/zsh-dbg_5.1.1-1ubuntu2_amd64.deb" size="" mtime="" />
```

First entry is correct (all entries from `Ubuntu:14.04` look like that and they are downloadable), but the latter entry is just broken, and cannot be downloaded using the full path given, nor just the filename. Size and mtime entries are broken as well, so the backend is not handling them correctly either.

```
$ osc -A https://api.opensuse.org api -X GET /build/Ubuntu:16.04/standard/x86_64/_repository/pool/main/z/zsh/zsh-doc_5.1.1-1ubuntu2_all.deb
Server returned an error: HTTP Error 404: Not Found

$ osc -A https://api.opensuse.org api -X GET /build/Ubuntu:16.04/standard/x86_64/_repository/zsh-doc_5.1.1-1ubuntu2_all.deb
Server returned an error: HTTP Error 404: no such binary 'zsh-doc_5.1.1-1ubuntu2_all.deb'
no such binary 'zsh-doc_5.1.1-1ubuntu2_all.deb'
```

Ubuntu 16.04 is served over DoD, so either DoD or API is handling some paths incorrectly.

This is easy to reproduce by trying to mirror the Ubuntu:16.04/standard/x86_64 with `obs_mirror_project` tool.

### PR DESCRIPTION
**Pull request by marcus-h**
Fixes #2061.

### CODE REVIEW

**Comment by mlschroe** [comment]
I don't mind merging this, but the original plan was just to allow fetching the binaries by name without the type suffix.

**Comment by marcus-h** [comment]
On 2016-08-30 04:31:31 -0700, Michael Schroeder wrote:
> I don't mind merging this, but the original plan was just to allow fetching the binaries by name without the type suffix.
> 
Hmm why do you want to treat a dod package as a "special" case? Since
we can fetch a "normal" package via <name>.<suffix>, I would expect
that this also works for a dod package.

**Comment by mlschroe** [comment]
But you can"t fetch a normal package as name.suffix, at least not in general. It will work in most of the cases, because the built packages are stored that way, but it won't work for imported (non-DoD) distributions like RedHat:RHEL-7.

But as said, I'm willing to make an exception for DoD and also allow the filename the package will get after download.

**Comment by marcus-h** [comment]
On 2016-08-30 07:23:15 -0700, Michael Schroeder wrote:
> But you can"t fetch a normal package as name.suffix, at least not in general. It will work in most of the cases, because the built packages are stored that way, but it won't work for imported (non-DoD) distributions like RedHat:RHEL-7.
> 
Ah right... I haven't thought about this. But the patch "fixes" this case as
well;)

> But as said, I'm willing to make an exception for DoD and also allow the filename the package will get after download.
> 
Hmm we should either keep the status quo or allow this for all packages (IMHO).

**Comment by DavidKang** [comment]
@marcus-h, @mlschroe, @M0ses and @lethliel, ping

**Comment by Ana06** [comment]
@marcus-h, @mlschroe, @M0ses and @lethliel what is the state of this? are you still working on it? :confused:

**Comment by adrianschroeter** [comment]
still needs improvement, but michael will handle this without this request

**Pull request closed without merging**
