### PR TITLE
[backend] handle multi-stage dockerfile builds (OBS-68)

### PR DESCRIPTION
**Pull request by dirkmueller**
There can be more than one containerfile: as dependency in dockerfile builds. this is when there is multi-stage
builds in use.

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Comment by adrianschroeter** [comment]
hey, cool, thanks a lot.

But could you avoid all the reformating and white space changes to make it easier reviewable?

**Comment by coolo** [comment]
Most of these white space changes are due to the for loop added. If you look at the diff with -w (and ignore the move of the comment to the right function) you get

```
@@ -97,23 +98,22 @@ sub check {
 
   my @deps = @{$info->{'dep'} || []};
 
-  my $cdep;    # container dependency
+  my $expanddebug = $ctx->{'expanddebug'};
+
   my $cprp;     # container prp
   my $cbdep;   # container bdep for job
   my $cmeta;   # container meta entry
-  my $expanddebug = $ctx->{'expanddebug'};
 
   my @containerdeps = grep {/^container:/} @deps;
   if (@containerdeps) {
-    return ('broken', 'multiple containers') if @containerdeps != 1;
-    $cdep = $containerdeps[0];
     @deps = grep {!/^container:/} @deps;
 
     # setup container pool
     my $cpool = $ctx->{'pool'};
-
-    # expand to container package name
     my $xp = BSSolv::expander->new($cpool, $ctx->{'conf'});
+
+    foreach my $cdep (@containerdeps) {
+      # expand to container package names
       my ($cok, @cdeps) = $xp->expand($cdep);
       BSSched::BuildJob::add_expanddebug($ctx, 'container expansion', $xp, $cpool) if $expanddebug;
       return ('unresolvable', join(', ', @cdeps)) unless $cok;
@@ -183,6 +183,7 @@ sub check {
       my $r = $ctx->append_info_path($info, \@newpath);
       return ('delayed', 'remotemap entry missing') unless $r;
     }
+  }
 
 
   my %aprpprios;
@@ -303,6 +304,7 @@ sub check {
     }
     return ('blocked', join(', ', @blocked));
   }
+  ### TODO: Check all specified container dependencies
   push @new_meta, $cmeta if $cmeta;
   @new_meta = sort {substr($a, 34) cmp substr($b, 34)} @new_meta;
   unshift @new_meta, map {"$_->{'srcmd5'}  $_->{'project'}/$_->{'package'}"} @{$info->{'extrasource'} || []};
```

**Comment by adrianschroeter** [comment]
On Dienstag, 11. Mai 2021, 08:17:12 CEST Stephan Kulow wrote:
> Most of these white space changes are due to the for loop added. If you look at the diff with -w (and ignore the move of the comment to the right function) you get

I know that, but want to merge commits where this is not needed.

> ```
> @@ -97,23 +98,22 @@ sub check {
>  
>    my @deps = @{$info->{'dep'} || []};
>  
> -  my $cdep;    # container dependency
> +  my $expanddebug = $ctx->{'expanddebug'};
> +
>    my $cprp;     # container prp
>    my $cbdep;   # container bdep for job
>    my $cmeta;   # container meta entry
> -  my $expanddebug = $ctx->{'expanddebug'};
>  
>    my @containerdeps = grep {/^container:/} @deps;
>    if ***@***.***) {
> -    return ('broken', 'multiple containers') if @containerdeps != 1;
> -    $cdep = $containerdeps[0];
>      @deps = grep {!/^container:/} @deps;
>  
>      # setup container pool
>      my $cpool = $ctx->{'pool'};
> -
> -    # expand to container package name
>      my $xp = BSSolv::expander->new($cpool, $ctx->{'conf'});
> +
> +    foreach my $cdep ***@***.***) {
> +      # expand to container package names
>        my ($cok, @cdeps) = $xp->expand($cdep);
>        BSSched::BuildJob::add_expanddebug($ctx, 'container expansion', $xp, $cpool) if $expanddebug;
>        return ('unresolvable', join(', ', @cdeps)) unless $cok;
> @@ -183,6 +183,7 @@ sub check {
>        my $r = $ctx->append_info_path($info, ***@***.***);
>        return ('delayed', 'remotemap entry missing') unless $r;
>      }
> +  }
>  
>  
>    my %aprpprios;
> @@ -303,6 +304,7 @@ sub check {
>      }
>      return ('blocked', join(', ', @blocked));
>    }
> +  ### TODO: Check all specified container dependencies
>    push @new_meta, $cmeta if $cmeta;
>    @new_meta = sort {substr($a, 34) cmp substr($b, 34)} @new_meta;
>    unshift @new_meta, map {"$_->{'srcmd5'}  $_->{'project'}/$_->{'package'}"} @{$info->{'extrasource'} || []};
> ```
> 
> 


-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by coolo** [comment]
No indenting for for loops?

**Comment by dirkmueller** [comment]
> it was not limited to the loop indention

you can't create PRs without the whitespace fixes due to: 

```
<stdin>:17: trailing whitespace.
  my ($proj, $projid, $repoid) = @_; 
<stdin>:38: trailing whitespace.
  
<stdin>:39: trailing whitespace.
  
warning: 3 Zeilen fügen Whitespace-Fehler hinzu.
```

sort of expected if the maintainers don't follow the rules themseles they set up for contributors.

**Comment by dirkmueller** [comment]
this will not work - mls is working on an alternative patch.

**Comment by adrianschroeter** [comment]
let's close this one

**Pull request closed without merging**
