### PR TITLE
Move repositories actions to Actions menu

### PR DESCRIPTION
**Pull request by saraycp**
Under beta program, the general actions related to repositories are
moved to the Actions menu.

When not in beta, the actions are displayed in the same place, however
the code has been moved to a partial for simplicity.

### CODE REVIEW

**Comment by saraycp** [comment]
@DavidKang, thanks. Fixed. Could you have another look?

**Comment by saraycp** [comment]
@dmarcoux, partial renamed!

**Comment by dmarcoux** [comment]
The top card (with the tabs) is now quite empty with the actions moved in the `Actions` menu. I suggest combining the first card with the second. So the repositories defined in the second card would be in the first card.

suggestion

**Comment by saraycp** [comment]
> The top card (with the tabs) is now quite empty with the actions moved in the `Actions` menu. I suggest combining the first card with the second. So the repositories defined in the second card would be in the first card. It would also remove the repetition of `Repositories for my_project`, which doesn't bring any value.

@dmarcoux now the two sections/cards are combined, as you suggested. I decided to modify this only for beta users.

Since this changes increased the code complexity I finally refactored the view code. There is a new commit for that, which can be squashed once it is approved.

**Pull request merged**
