### PR TITLE
No more fun while waiting for Rspec to finish

### PR DESCRIPTION
**Pull request by Ana06**
Remove the :unicorn: as it conflicts with the property tests.

If we keep both the :unicorn: and the output of the property tests it looks ugly:

screenshot_20170119_092330
screenshot_20170119_092441

And if we disable the output of the property tests when the :unicorn: is present (that is what I had already done), we miss important information when a test fails. As we only know that a test has failed but not with what example. So, I think that it is much better to remove the :unicorn: than to hide the output of the property tests, as it will be useful while the :unicorn: is not.

### CODE REVIEW

**Comment by Ana06** [comment]
[(3) Add property tests to OBS](https://trello.com/c/VVho8Rf2/191-3-add-property-tests-to-obs)

**Comment by mdeniz** [comment]
Nothing to do with the unicorn formatter, I think you are breaking the output of the RSpec, also the default one, so no matter what formatter do you have. We have to figure out why do you need more output than the failing test.

👎

**Comment by Ana06** [comment]
@mdeniz 

> I think you are breaking the output of the RSpec, also the default one, so no matter what formatter do you have

Yes, but it doesn't look that ugly with the default one

image

>  We have to figure out why do you need more output than the failing test.

Because property tests are running several random examples so if one tests fails you need to know with what random example fails (and maybe if it was the first one or in what number of test it failed).

The :unicorn: is not practical at all, I would like to remove it even without the property tests. And if you don't want to remove it, what is the alternative to avoid that it conflict with the :unicorn:?

@openSUSE/open-build-service opinions?

**Comment by hennevogel** [comment]
Where is the code that produces the output?

**Comment by Ana06** [comment]
@hennevogel 

> Where is the code that produces the output?
It comes from the Rantly gem

**Comment by hennevogel** [comment]
This stinks, I don't like it. Please set `RANTLY_VERBOSE=0` please in the support file, then you can enable it if the tests fail. You could also conditionally disable the nyan-cat formatter then

**Comment by Ana06** [comment]
@hennevogel 

>  Please set RANTLY_VERBOSE=0 in the support file, then you can enable it if the tests fail

But it is random data. So if the test fails and then you enable it, it may not fail when running it again and you won't be able to know what was the case that failed before. So this is not a solution.

Anyway, I think I found a better solution so we don't have to remove the unicorn because of that. Although I would still want to remove it, it is just annoying when you want to debug something.

**Pull request closed without merging**
