### PR TITLE
[api] extendkey: make days parameter accessable

### PR DESCRIPTION
**Pull request by adrianschroeter**
Allowing the user to specify the number of days until expiry

### CODE REVIEW

**Comment by bmwiedemann** [comment]
The related backend commits were 1d94f8ebd6cea56d2aabb28cbd7bab4ef250606f and ce815cac6e4f6aa6e213c9cf1dbc71beae15963d

**Review by bmwiedemann — APPROVED** [review]

**Comment by ManuelSchneid3r** [comment]
may i ask where I can set the date?

**Comment by hennevogel** [comment]
`osc signkey --help`

**Comment by ManuelSchneid3r** [comment]
Some more info on this parameter would be nice. I cant set a date or interval. 

```
$ osc signkey --extend
<status code="ok" />
```

**Pull request merged**
