### PR TITLE
Avoid double release 

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by ChrisBr** [comment]
@bgeuken very nice! :ship: it when you fix the test.

**Comment by bgeuken** [comment]
\*updated\*

**Comment by adrianschroeter** [comment]
Nice stuff. Just the action kind needs to get taken also into account (eg. submit & change_devel for same target is a usecase).

**Comment by adrianschroeter** [comment]
Can you also add a test case which shows the api answer? esp. error code and message.

**Comment by bgeuken** [comment]
> adrianschroeter commented an hour ago
>
> Nice stuff. Just the action kind needs to get taken also into account (eg. submit & change_devel for same target is a usecase).

You mean that the uniqueness should also apply if one action has type 'submit' and the other 'change_devel'?

**Comment by adrianschroeter** [comment]
On Montag, 3. April 2017, 04:53:50 CEST wrote Björn Geuken:
> > adrianschroeter commented an hour ago
> >
> > Nice stuff. Just the action kind needs to get taken also into account (eg. submit & change_devel for same target is a usecase).
> 
> You mean that the uniqueness should also apply if one action has type 'submit' and the other 'change_devel'?

If the kinds a different in general. The submit and change_devel was just an example where it can make sense to
have multiple for the same target.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by adrianschroeter** [comment]
forget my kind comment, the type is already checked as discussed 1:1

**Comment by hennevogel** [comment]
Let's go then...

**Pull request merged**
