### PR TITLE
[api][webui] set cache_lines.key limit to 4096

### PR DESCRIPTION
**Pull request by evanrolfe**
Fixes a change introduced by PR https://github.com/openSUSE/open-build-service/pull/2652

### CODE REVIEW

**Comment by ChrisBr** [comment]
LGTM :+1:

**Comment by Ana06** [comment]
[(5) P4: Review changes made by PR#2652](https://trello.com/c/UryVv6Jf/298-5-p4-review-changes-made-by-pr-2652)

**Comment by coolo** [comment]
what is the point? memcached doesn't support that long keys anyway.

**Comment by bgeuken** [comment]
Actually I would like to drop that model completely -> #2893

**Pull request merged**
