### PR TITLE
bootstrap enabled globally in development

### PR DESCRIPTION
**Pull request by vpereira**
In the development environment we have Bootstrap feature globally enabled.

### CODE REVIEW

**Comment by vpereira** [comment]
https://github.com/jnunemaker/flipper/issues/420

**Comment by vpereira** [comment]
> The second time we restart the server it raises this error:

I will research further on that

**Comment by vpereira** [comment]
could you try it again @saraycp ?

**Comment by saraycp** [comment]
@vpereira Approved . I also re-triggered the OBS Package Build that was failing. Let's see...

**Comment by vpereira** [comment]
@saraycp I changed the approach. now I'm doing it on the rake task `dev:bootstrap` so after we build the containers with `rake docker:build`, the `Flipper[:bootstrap]` will be enabled.

**Pull request merged**
