### PR TITLE
Ignore airbrake in migration env

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@adrianschroeter Just in case you currently look into this... This should avoid the current package build failure.

btw, this doesn't seem to cause problems, but might want to have a environment conf for migrate env. Or extend the default environment.rb...

```
[  378s] Created database 'api_25'
[  383s] config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:
[  383s] 
[  383s]   * development - set it to false
[  383s]   * test - set it to false (unless you use a tool that preloads your test environment)
[  383s]   * production - set it to true
[  383s] 
```

**Comment by adrianschroeter** [comment]
Good morning @bgeuken I would merge 7fcf0e6 right away, but I am not sure about the other one... I would name it "migratetest" at least, since the migrations happen in all environments. But we want to move the migration test anyway, so maybe you could just push the 7fcf0e6 one for now and we follow up with the other one later?

**Comment by bgeuken** [comment]
Sure, I update the PR. For the record, the migration env already [exists](https://github.com/openSUSE/open-build-service/blob/master/src/api/script/api_test_in_spec.sh#L66).

**Comment by adrianschroeter** [comment]
The migration env exits there only very briefly while running the test, but not in the installation anymore

**Comment by bgeuken** [comment]
> adrianschroeter commented 5 hours ago
> The migration env exits there only very briefly while running the test, but not in the installation anymore

But it exists. You can see in the buildlog output [I posted before](https://github.com/openSUSE/open-build-service/pull/3278#issuecomment-310852500) that it requires a minimal configuration.

**Pull request merged**
