### PR TITLE
Start basic developer documentation for the Backend library using YARD

### PR DESCRIPTION
**Pull request by mdeniz**

### CODE REVIEW

**Comment by DavidKang** [comment]
@mschnitzer, IMHO I found very useful and It will generate an awesome documentation.

> I would even say your classes don't need documentation at all because they are really clear. It's not comparable to something like for e.g. the Project model.

IMHO even if the method is really clear, something happens that the parameters are not so clear.

In summary, I like it 😸

**Comment by mdeniz** [comment]
@mschnitzer, YARD is widely used... do you think it is unuseful? 

How do you expect to know which type of params you can use?

**Comment by mschnitzer** [comment]
@mdeniz well for these classes you're using `YARD` it's pretty obvious. It's just an overkill in my opinion because it blows up the whole file for something what is not really necessary. We never used `YARD` before (did we?). If we want to start documenting classes like that, we should discuss this a bit more. Methods should be written that they are easy to be understandable and you already achieved that in your implementation.

**Comment by mdeniz** [comment]
I don't know why but github is not updating this PR with my new commit... I will close it and superseed it with a new one.

**Pull request closed without merging**
