### PR TITLE
fix spider test again

### PR DESCRIPTION
**Pull request by bugfinder**

### CODE REVIEW

**Comment by dmarcoux** [comment]
I'm a bit lost here... The spider specs are passing on master. Why is this change needed?

**Comment by bugfinder** [comment]
all these fixes along these lines are spurious fails, packages and projects already deleted and still found in the spider crawl probably because of some caching. It also depends on timing and number of threads/cpus you have during the test. this one reproducibly failed today in IBS SLE-15-SP3 builds

**Comment by dmarcoux** [comment]
What is the error message? It seems like the package is not branched correctly.

**Comment by hennevogel** [comment]
closing, we are way past SLE-15-SP3 and it still works on master...

**Pull request closed without merging**
