### PR TITLE
Add rubocop-rspec

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by bgeuken** [comment]
@openSUSE/open-build-service please review

**Comment by bgeuken** [comment]
@Ana06 The bug is that the auto-gen configuration was not disabling the cop for that file. So the cop kept reporting an offense. I am going to file an issue once I managed to reproduce this.

**Comment by bgeuken** [comment]
@openSUSE/open-build-service btw. Given that we introduce quite some new cops, it would be good if you  check if there is any cop you disagree with. Unfortunately there doesn't seem to be any documentation for the rspec cops.

**Comment by Ana06** [comment]
Documentation: http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec    😉

**Comment by bgeuken** [comment]
Ah, thanks!

**Pull request merged**
