### PR TITLE
Add initial support for authenticating users via Kerberos.

### PR DESCRIPTION
**Pull request by trhd**
Here's an implementation for Kerberos support in OBS in case that is something that you might want to include in OBS.

Some notes about this implementation:
 - Mainly tested on 2.6 and then ported to master.
 - These changes should have no affect on OBS's behaviour when Kerberos is not configured.
 - Expects users to initially log in/register without Kerberos (to create the user account on the server).
 - Doesn't include Kerberos support for the Web UI (only the API i.e. osc).

Corresponding PR for osc: https://github.com/openSUSE/osc/pull/254

### CODE REVIEW

**Comment by hennevogel** [comment]
Hey @trhd, thank you for this contirbution 💐 

Can you please add tests for this? If you need help with [our spec](https://github.com/openSUSE/open-build-service/blob/master/src/api/spec/README.md) let us know.

**Comment by adrianschroeter** [comment]
Could you make the dependency to rubygem-gssapi optional?

Similar how it is done in extract_ldap_user for the ldap module

**Comment by trhd** [comment]
Fixed some rubocop errors and marked gssapi gem as an optional dependency (hopefully I did this right).

Unfortunately I don't think I have the time to implement any tests for this right now.

In case somebody else wants to take a stab at it, this is more or less how I tested this manually:

 - Set up a Kerberos server.
 - Genereate a Kerberos principal for the test OBS server in the Kerberos server.
 - Create a keytab for the OBS server and copy it in place.
 - Generate a Kerberos principal for a test user.
 - Configure OBS's Kerberos options (at least the keytab and principal name).
 - Configure your test Kerberos server for the OBS server.
 - Log in to the test OBS server via web UI as the test user..
 - Use osc with Kerberos support to do stuff on the OBS server.

**Comment by trhd** [comment]
Unfortunately I didn't have time to write any better tests but perhaps these ones can serve as inspiration for more development if nothing else.

**Comment by bgeuken** [comment]
@adrianschroeter Mind to review again?

**Comment by adrianschroeter** [comment]
well, the code is fine, but I agree with henne that we want test cases for this before merging. Esp. the constant broken LDAP support tells us that we need it :/

**Comment by k0da** [comment]
@adrianschroeter isn't https://github.com/openSUSE/open-build-service/pull/2467/commits/b5b54e68c0910fa0e8c47a2f4defc9494bed628c supposed to address this?

**Comment by adrianschroeter** [comment]
ups, missed the CI indeed .. will take care on merging it as excuse

**Comment by adrianschroeter** [comment]
Done here https://github.com/openSUSE/open-build-service/pull/2776

will merge when travis was successful

**Pull request closed without merging**
