### PR TITLE
Revert package webui fix

### LINKED ISSUE #1438: "Revert to revision" ignores revision
https://build.opensuse.org/package/submit_request_dialog/project/package?revision=42&target_project=project will submit the latest version which completely defeats the purpose of reverting.

### PR DESCRIPTION
**Pull request by tuminoid**
Fixes #1438.

### CODE REVIEW

**Comment by hennevogel** [comment]
What exactly is this reverting?

**Comment by kulmesa** [comment]
> What exactly is this reverting?

Well, it's not really reverting anything. It's a bug fix for the "Revert to revision" issue #1438. It was missing the revision parameter from the submit request, so it wasn't really reverting anything after the request was accepted.

> Can you please add a test for this?

Sure, we will update it soon. Do you want test case also for the pull request for 2.6 branch #2267 

BTW, are those two failing CI rspec tests some test environment issues? I was checking this manually in vagrant box, and I think it was working fine there. For some reason the "Requests superseed other requests" rpec test got error from backend 
`Errno::ECONNREFUSED (Failed to open TCP connection to localhost:3200 (Connection refused - connect(2) for "localhost" port 3200)):`

**Comment by bgeuken** [comment]
What Henne meant was a test that would fail without your changes. No need to update the VCR cassette. That one just http records requests to the backend, which then will be played when running our test suite without a backend.

**Comment by hennevogel** [comment]
@tuminoid yeah what I meant is that this, obviously, isn't tested at all. Please add a test that makes sure this never happens again.

**Comment by kulmesa** [comment]
That previous test cassette commit (37fada8) was just to get the CI tests passing for this pull request, but I guess that commit can be discarded if it was ok previously?

> If you need help with writing tests, let us know.

I'm not so familiar how testing works in master, but I can create a test case for 2.6 branch request #2267 (if you are interested to merge that in the first place).

**Comment by hennevogel** [comment]
I like the test. Thanks for this contribution @tuminoid :bouquet:  :-)

**Pull request merged**
