### PR TITLE
Add new way to identify spider bots

### PR DESCRIPTION
**Pull request by mschnitzer**
This identifies spider bots more effectively and removes the old way to identify spiders (apache configuration).

### CODE REVIEW

**Comment by bgeuken** [comment]
LGTM

**Comment by hennevogel** [comment]
Cool. Please also package the gem and submit it do OBS:Server:Unstable

**Comment by hennevogel** [comment]
@mschnitzer are you going to do this?

**Comment by mschnitzer** [comment]
@hennevogel sure

**Comment by mschnitzer** [comment]
@hennevogel @mdeniz @bgeuken please see the new commit: https://github.com/openSUSE/open-build-service/pull/2320/commits/eb9b8cbedc78e00db47da7c3ee346b9584790374

It will get rebased after you guys are fine with the release notes entry.

**Comment by hennevogel** [comment]
Please use the proper tag for the last commit: [dist]

**Comment by mschnitzer** [comment]
@hennevogel done

**Comment by bgeuken** [comment]
Currently blocked by missing rpms for that gem. We'll have a look at this later

**Comment by hennevogel** [comment]
The gem package is there now (although it fails to build ;-). But let's go anyway.

**Pull request merged**
