### PR TITLE
Precompile assets before running feature specs in CircleCI

### LINKED ISSUE #10170: Styles are broken when running feature specs with the capybara mobile driver
# Styles are broken when running feature specs with capybara
Our CircleCI runs some of the beta feature specs under mobile emulation. To do so, it sets the `CAPYBARA_DRIVER=mobile` environment variable before running the feature specs.

While troubleshooting [some errors in our specs](https://app.circleci.com/pipelines/github/saraycp/open-build-service/688/workflows/52fc22bf-b364-4c2a-919b-8f37866c96cb/jobs/4065/parallel-runs/1) we found out that capybara was unable to click on some elements from a page because they where below an oversized Open Build Service logo:

capybara-screenshot

The logo size is clearly wrong. It is set via CSS rules, and by looking at the rest of the elements in that page, looks like some other CSS rules are broken too. 

The broken styles are interfering with the proper execution of the feature specs. On mobile environments the oversized logo covers the half of the screen, hiding elements to the Capybara runner.

Note that Using the `:desktop` capybara driver also breaks the styles. Note the oversized logo and the search box in the capture below.

Screenshot from 2020-09-18 14-25-16

Expected Result
============
The capybara driver should not break the styles of the application.

How to Reproduce
===============
1. Put a `docker-compose.selenium.yml` in the root of the project. You can find the contents for the file below.
2. Use this command line to open a session inside the dockerized project: `docker-compose -f docker-compose.yml -f docker-compose.selenium.yml run --service-ports --use-aliases --rm frontend bash -l`
3. Open a Vnc viewer (I used TigerVNC Viewer) pointing to localhost.
3. Run `export CAPYBARA_DRIVER=mobile` inside the dockerized session.
3. Run `rspec spec/features/beta/webui/projects/status_spec.rb` inside the dockerized session.
4. The application under test shows broken styles.

Further Information
===============

Use this `docker-compose.selenium.yml` to reproduce the issue.

```docker
version: "2.1"
services:
  frontend:
    depends_on:
      - selenium
    environment:
      RSPEC_HOST: frontend
  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      VNC_NO_PASSWORD: 1
    ports:
      - 5900:5900
```

### PR DESCRIPTION
**Pull request by danidoni**
Sometimes feature specs in CirclecCI fail due to html elements missing.
Those elements are missing because assets cover them and the capybara driver
can't click on them. The assets cover some elements because they have the wrong
size and they have the wrong size because we use an outdated version of the
assets.

This PR cleans old assets and precompiles them before running the feature specs.

Fixes #10170

### CODE REVIEW

**Comment by coolo** [comment]
you basically discard the assets generated in the `checkout` job - why are they outdated to begin with?

**Comment by danidoni** [comment]
> you basically discard the assets generated in the `checkout_code` job - why are they outdated to begin with?

I have no idea yet. This PR is just an experiment to test my assumptions, but you are right, the problem is having outdated assets in the first place.

Thanks for the tip about the `checkout_code` job! I was missing that piece.

**Comment by dmarcoux** [comment]
@danidoni This PR should be closed since it's not an issue with the assets. See [my latest comment on the issue](https://github.com/openSUSE/open-build-service/issues/10170#issuecomment-796812962) for details.

**Comment by danidoni** [comment]
I know. Closing

**Pull request closed without merging**
