### PR TITLE
[ci] Enable IfUnlessModifier Rubocop cop

### PR DESCRIPTION
**Pull request by Ana06**
Enable `IfUnlessModifier` Rubocop cop and autocorrect offenses. :bowtie: 

This cop checks for `if` and `unless` statements that would fit on one line if written as a modifier `if`/`unless`. The maximum line length is configurable.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Do we want to have this rule @openSUSE/open-build-service ?

**Comment by bgeuken** [comment]
> ChrisBr commented 15 hours ago
>
> Do we want to have this rule @openSUSE/open-build-service ?

I don't think so. Having conditions in one line is ok in some cases, but often doing so the code get's very busy. Which makes it hard to read. And that doesn't only depend on the length of the line.

**Comment by hennevogel** [comment]
I don't think this cop is complaining about 

```ruby
if true
  true
  true
end
```

so I don't see how this makes things more busy :-) I like this cop.

**Comment by Ana06** [comment]
@bgeuken 

> I don't think so. Having conditions in one line is ok in some cases, but often doing so the code get's very busy. Which makes it hard to read. And that doesn't only depend on the length of the line.

_Very busy_? if it is not too long to read it, what is the problem on having it in one line? Can you give a concrete example of _busy code_? :confused: 

And again, this is in the Ruby style guide: https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier This is pretend to be a community-driven style guide, so I think we should follow it.  :weary:

FYI The default line length is 80 characters including the `if/else` clause.

**Comment by hennevogel** [comment]
@Ana06 we don't have to follow this religiously, it's okay to deviate from this guide if we as the people that have to live with it want to. That is why it's called guide and not law... :-)

**Comment by Ana06** [comment]
@hennevogel but if we have arguments to don't like it, why don we try to change the style guide then? That is what community-driven means right? Anyway, I like the cop. So, what do we want to do?

**Comment by bgeuken** [comment]
First of all, yes I also like to write conditions in one line, like [here](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/helpers/maintenance_helper.rb#L364):
```ruby
next if lpkg_name == p.name
```
I can look at this and on first glance know what is going on.

But in the very same file you also find [this](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/helpers/maintenance_helper.rb#L175):
```ruby
sourcePackage.project.repositories.each do |sourceRepo|
  next if filterSourceRepository && filterSourceRepository != sourceRepo
```

To me this is already borderline, since it's crouched together and contains a lot of information, which makes it harder to read / understand than it should.

I also don't see why something like [this](https://github.com/openSUSE/open-build-service/pull/2399/files#diff-071e78ffb951a733b9c91d875747338aL385) is supposed to be bad coding style, while [this](https://github.com/openSUSE/open-build-service/pull/2399/files#diff-071e78ffb951a733b9c91d875747338aR381)

```ruby
     unless xml.has_attribute? 'origin'
       xml.set_attribute "origin", "backend"
     end
```
vs.
```ruby
  xml.set_attribute "origin", "backend" unless xml.has_attribute? 'origin'
```

Personally I find the if x do y much more natural to read. The indentation already tells you that the following code is a condition and does not always apply. In contrast to the trailing if style, where you read the whole line just learn at the end that the code isn't interesting for you, because it's some specific case.

And we already have many of these trailing ifs, like [here](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/bs_request.rb#L199) and [here](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/bs_request_action.rb#L118).
I don't know about you, but I find them very ugly. Often enough they actually rule each other out and could (should?) be written as if / else.

btw the default line length is [150](https://github.com/openSUSE/open-build-service/blob/master/src/api/.rubocop.yml#L116) not 80.

**Comment by bgeuken** [comment]
> And again, this is in the Ruby style guide: https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier
> This is pretend to be a community-driven style guide, so I think we should follow it

The thing with rubocop is that it tries to create hard rules for things that often are not that strict and specificly defined. It's just a bot.
Like "Favor modifier if/unless usage when you have a single-line body." doesn't mean  "by all means".

Beside, not everyone follows that styleguide that strictly. And not everyone who does, goes that hardcore to use each and every rubocop rule. There is even http://relaxed.ruby.style/

**Comment by coolo** [comment]
80% of the changes propsed look good, but I agree with @bgeuken (for what it's worth): if the code becomes easier or harder to read is too much to ask from a cop rule.

**Comment by Ana06** [comment]
@bgeuken 

> btw the default line length is 150 not 80

That is not true. Your link is pointed to another cop, for this one the default line length is 80 and it can be independently change. I mean that Rubocop only force `if/else` statements to be written in one line if they fit in 80 (or other number) characters and the rest of the line can still be 150 characters.

> There is even http://relaxed.ruby.style/

They even disable the LineLength rule :scream:


Anyway, it is clear that most of you don't like the cop so I'll close this.

**Pull request closed without merging**
