### PR TITLE
Git cop

### PR DESCRIPTION
**Pull request by Ana06**
Adding `git-cop` gem to improve our commits.

### Enabled cops with error severity

- `commit_author_email`: Ensures author email address exists.

- `commit_body_leading_line`: Ensures there is blank line between the commit subject and body.

- `commit_subject_prefix`: Ensure that the commit has one or more tags (*api*, *app*, *backend*, *ci*, *dist*, *doc*, *webui*) alphabetically ordered.

### Enabled cops with warning severity (a message is render when executing git-cop but it doesn't fail)

- `commit_body_bullet`: enforce `-` for lists.

- `commit_body_line_length`:  Ensures each line of the commit body is not longer than 72 characters.

- `commit_body_phrase`: Avoid meaningless words/phrases.

- `commit_body_presence`: Ensures the commit has a description.

- `commit_subject_length`: Ensures the commit subject length is not more than 50 characters.

I also added a *How to write proper commit messages* section to the our contributing file which include the git-cop current configuration. :bowtie:

### CODE REVIEW

**Comment by Ana06** [comment]
Review but do not merge until git-cop is in build.opensuse.org :wink:

**Comment by hennevogel** [comment]
@Ana06 are you going to submit it?

**Comment by Ana06** [comment]
@hennevogel 

> @Ana06 are you going to submit it?

Doing it :running_man:

**Comment by Ana06** [comment]
@hennevogel my package is broken an I don't know why :sob: :sob: 
https://build.opensuse.org/package/show/home:ammartinez/rubygem-git-cop

**Comment by Ana06** [comment]
@openSUSE/open-build-service I didn't have time to fix the package. This is ready to merge once that is done. If someone has time fell free to submit the gem and merge this :wink: 

image

**Comment by hennevogel** [comment]
OBS submit requests pending: [#514925](https://build.opensuse.org/request/show/514925), [#514931](https://build.opensuse.org/request/show/514931), [514927](https://build.opensuse.org/request/show/514927), [#514928](https://build.opensuse.org/request/show/514928), [#514929](https://build.opensuse.org/request/show/514929) and [#514930](https://build.opensuse.org/request/show/514930)

**Comment by bgeuken** [comment]
Submit requests accepted, packages branched to our project, and revisions are locked.

=> Ready for merging

**Comment by ChrisBr** [comment]
@Ana06 @hennevogel the depfu PR's are failing now because the don't follow our commit schema...

**Comment by bgeuken** [comment]
Solved in #3525

**Pull request merged**
