### PR TITLE
add research notice to readme

### PR DESCRIPTION
**Pull request by yochannah**
... so participants are aware this repo is participating in a study adn metrics will be gathered :)

let me know if there are any issues or questions.

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Comment by dmarcoux** [comment]
Sorry, but I don't see the point in having this in the README. I'll wait on a second opinion before taking action on this.

@openSUSE/obs-frontend: What do you think? Do you agree with me?

**Comment by vpereira** [comment]
Looking the description on https://sustainable-open-science-and-software.github.io/, I don't see how could we be in the scope of this research. Could you please provide more information @yochannah ?

**Comment by hennevogel** [comment]
hey @yochannah I don't see the point in adding this. We are a public open source project with [public data on github](https://docs.github.com/en/github/site-policy/github-privacy-statement#public-repositories) that you can request at will.

**Comment by yochannah** [comment]
Hey folks - the scope of this research project covers any open source project - whilst many are science or research projects it's fine for non-research projects to participate too. 

The reason for the readme notification is to try and avoid being a "spooky" researcher who is gathering info without making people aware (github permits open use of github data, but it is still politer to make people aware). 

Would there be a better way to help people know about this than the readme?

**Comment by dmarcoux** [comment]
I would list the open source projects on the research project website. It's much less time consuming for both parties, the open source contributors and you. There's no need to review a PR for contributors and you can directly list projects on the website without having to submit a PR on all projects involved in your research. I find this important because a lot of open source projects are quite overloaded with work... not every project has a team of paid software engineers like the Open Build Service.

**Pull request closed without merging**
