### PR TITLE
[ci] Enable Rails/Exit Rubocop cop

### PR DESCRIPTION
**Pull request by Ana06**

### CODE REVIEW

**Comment by Ana06** [comment]
[Enable the Rails/Exit Rubocop cop](https://trello.com/c/vgLKXBCf/264-enable-the-rails-exit-rubocop-cop)

**Comment by marcus-h** [comment]
> diff --git a/src/api/config/deploy.rb b/src/api/config/deploy.rb
> index fda1d4f..020edb4 100644
> --- a/src/api/config/deploy.rb
> +++ b/src/api/config/deploy.rb
> @@ -118,12 +118,11 @@
>      Dir.glob('**/*.rb').each do |f|
>        unless system("ruby -c -d #{f} > /dev/null")
>          puts "syntax error in #{f} - will not deploy"
> -        exit 1
> +        return
>        end
>      end
>      unless system("rails test")
>        puts "Error on rails test - will not deploy"
> -      exit 1
>      end
>    end
>  end

Hmm this might break existing deploy scripts, if they rely on $?.
(silent assumption: capistrano correctly propagates the SystemExit...)

Btw., is this script still in use at all?

**Comment by hennevogel** [comment]
> Btw., is this script still in use at all?

No it is not and you can just delete it :-)

**Comment by Ana06** [comment]
@hennevogel 

What it is not used is the `test_suite` task?

**Comment by hennevogel** [comment]
config/deploy.rb is not used

**Comment by Ana06** [comment]
@hennevogel 

> config/deploy.rb is not used

Then I guess that _Capfile_ is not used neither as it is loading _config/deploy_

**Comment by hennevogel** [comment]
you guess right

**Pull request merged**
