### PR TITLE
[api][webui] Enable the Style/RedundantSelf cop

### PR DESCRIPTION
**Pull request by Ana06**
Enable the `Style/RedundantSelf` cop in Rubocop and let Rubocop to autocorrect the offenses. :bowtie:

### CODE REVIEW

**Comment by bgeuken** [comment]
Hm, I actually liked the explicit self. It makes it clearer that a method of that object got called.

**Comment by Ana06** [comment]
But if it is not needed is because there is no doubt that is a method of that object what we are calling. The [Ruby Style guide](https://github.com/bbatsov/ruby-style-guide#no-self-unless-required) recommends not to use it. :bowtie:  

I would like to enable this cops, it is an extra word that we have to read and that add useless information. So, taking into account that there are more than 1200 redundant selfs in the project we are wasting a considerable amount of time reading the word self. Also, it makes the code more difficult to read.  :clock1:

**Comment by bgeuken** [comment]
I can live with this change. Though I like to explicitly write self. when we call an attribute.

And I doubt reading self wastes so much time. Can I have a benchmark please?:P

**Comment by mdeniz** [comment]
I also prefer not to use the `self` everywhere, we should keep an eye on it to not use it in the left part of an assignation.

**Comment by bgeuken** [comment]
As said, I can live with it -> merged

**Comment by Ana06** [comment]
[Enable the Style/RedundantSelf cop in Rubocop](https://trello.com/c/H9yFtgOw/74-enable-the-style-redundantself-cop-in-rubocop)

**Pull request merged**
