### PR TITLE
Fix sorting

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by bgeuken** [comment]
NIce! Could you add a test for it so this does not happen again?

**Comment by ChrisBr** [comment]
@bgeuken yes good point but also we face here some limitations with the missing controller tests. Maybe we should really discuss introducing some light weight controller tests? I don't think testing this in a feature tests makes much sense...

**Comment by bgeuken** [comment]
@ChrisBr as we just discussed in person;-)

**Comment by bgeuken** [comment]
Let's merge this. I'll provide a test

**Comment by ChrisBr** [comment]
@bgeuken do you want to introduce controller tests or how do you plan to test it?

**Comment by bgeuken** [comment]
With this 8f8737fe80d98c5b7ba31a64de0f8:) I wouldn't introduce functional tests without proposing it first

**Pull request merged**
