### PR TITLE
Attempt to fix flaky user feature spec

### PR DESCRIPTION
**Pull request by ChrisBr**
not 100% sure if this will the issue though #6457.

### CODE REVIEW

**Comment by coolo** [comment]
Impossible, sorry.

If you expect 'John Doe' on https://15834-2046192-gh.circle-artifacts.com/3/capybara/User_s_home_project_creation_edit_account_information.png, it doesn't matter in which order you do it.

**Comment by coolo** [comment]
From the test.log of the failure:

```
[fdfa4187-4cd2-4478-8aaf-f7a51c231d50] [695:9.67]   User Update (0.4ms)  UPDATE `users` SET `realname` = '', `email` = 'john.doe@opensuse.org', `updated_at` = '2018-12-04 12:46:38.793787' WHERE `users`.`id` = 1
[fdfa4187-4cd2-4478-8aaf-f7a51c231d50] [695:9.67]    (0.2ms)  COMMIT
```

So your problem is before the post

**Comment by coolo** [comment]
I assume the modal dialog isn't yet open for input at the fill_in

**Comment by ChrisBr** [comment]
Ok, I will try to disable the css transitions as well ...

https://github.com/openSUSE/open-build-service/pull/6090/files
https://github.com/openSUSE/open-build-service/pull/5885/files

**Comment by coolo** [comment]
yes. Tell henne that there is no good way :)

**Pull request closed without merging**
