### PR TITLE
[ci] Move Rubocop config files to base directory

### PR DESCRIPTION
**Pull request by eduardoj**
Move `.rubocop.yml` and `.rubocop_todo.yml` files to base directory to be able to apply Rubocop also to the Ruby files outside of the Rails project. Add also exceptions for `dist` directory to .rubocop_todo.yml for every cop, so it will be easy to enable them afterwards.

Add `rubocop` target to main Makefile. Now you can call Rubocop from the base directory with this command: `make rubocop`. Modify `travis_script.sh` to call this target. Modify `.travis.yml` to install rubocop gem system wide. Now it is possible to execute it from base directory.

Pair programmed with @Ana06.

### CODE REVIEW

**Comment by DavidKang** [comment]
@eduardoj, why were some cops removed?

**Comment by Ana06** [comment]
@DavidKang 

> @eduardoj, why were some cops removed?

They are not removed. All those cops are enabled by default, so we added the new files as exception but it keeps working for the cases it worked before. And we moved them to `rubocop_todo.yml` again as they are not done anymore, as the new offences have to be corrected.

**Comment by DavidKang** [comment]
Nice 👍

**Comment by bgeuken** [comment]
Cool

**Comment by eduardoj** [comment]
[Move rubocop config files two subdirectories up and make it valid for the whole project](https://trello.com/c/QmX8pye8/318-move-rubocop-config-files-two-subdirectories-up-and-make-it-valid-for-the-whole-project)

**Pull request merged**
