### PR TITLE
[doc] Remove documentation of schema from models

### PR DESCRIPTION
**Pull request by bgeuken**
For unknown reasons we used to have "Schema Information" for each model.
Since this is neither used nor maintained and thus outdated, it's not
worth to keep this around.
If it turns out that we want to have a schema, we should use Rails's
schema.rb anyway.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
Henne just introduced that using the annotate gem...

**Comment by DavidKang** [comment]
@bgeuken, this was added by annotate gem in #2817, so maybe you also want remove this gem from Gemfile and lib/task

**Comment by DavidKang** [comment]
By the way, I like this gem 😸

**Comment by coolo** [comment]
but if it's outdated in 4 days, there is a problem :)

**Comment by bgeuken** [comment]
I see. Not sure I get the point of this, but ok^^

**Comment by mdeniz** [comment]
In order to not have outdated annotations... Why don't we ensure that in each running of the migrations in development environment the regeneration of the annotations are run?

**Comment by bgeuken** [comment]
To me this sounds like we actually want (need?) the rails schema.rb. Instead we create workarounds that noone will use.

**Comment by mdeniz** [comment]
We don't use the schema at all, do we? So, is just a "easy" way of knowing the structure of the model without having to deal with the structure.sql file.... I don't see it as a workaround 😮

**Pull request closed without merging**
