### PR TITLE
Remove authentication requirement from POST /person/register documentation endpoint

### PR DESCRIPTION
**Pull request by danidoni**
It's not needed, following the source code:
https://github.com/openSUSE/open-build-service/blob/436ce907fd7d6e2abc201410922d1aa87444883f/src/api/app/controllers/person_controller.rb#L11

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

### CODE REVIEW

**Comment by dmarcoux** [comment]
The failure in the `checkout_code` check is already addressed on _master_. So rebasing the branch will solve the issue.

**Comment by danidoni** [comment]
> The failure in the `checkout_code` check is already addressed on _master_. So rebasing the branch will solve the issue.

Oh, nice! Rebasing!

**Review by krauselukas — APPROVED** [review]

**Review by krauselukas — CHANGES_REQUESTED** [review]
Ah sorry @danidoni please just mention its about the endpoint documentation, not the endpoint it self in the commit message. :D I could imagine people getting nervous by just reading the commit message

**Comment by danidoni** [comment]
> Ah sorry @danidoni please just mention its about the endpoint documentation, not the endpoint it self in the commit message. :D I could imagine people getting nervous by just reading the commit message

Good point! Updated!

**Comment by krauselukas** [comment]
@danidoni would be awesome if you could change the commit message itself, its just a little bit missleading

**Comment by danidoni** [comment]
> @danidoni would be awesome if you could change the commit message itself, its just a little bit missleading

Done!

**Review by krauselukas — APPROVED** [review]
Gracias

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
