### PR TITLE
Bugfix/backend file

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by DavidKang** [comment]
Nitpick: In the description of the first commit message you have a typo in: method called to_s(**st**ring)

**Comment by coolo** [comment]
I think he intentend this to merge to_s and string

**Comment by bgeuken** [comment]
I rephrased it

**Comment by bgeuken** [comment]
@DavidKang Had to adjust some of the code. Please have a second look

**Comment by bgeuken** [comment]
This is to deeply nested into our code to fix it easily.  So I went for the simple solution -> #5183

**Pull request closed without merging**
