### PR TITLE
Merge depfu PRs

### PR DESCRIPTION
**Pull request by coolo**
All the gems are uptodate in dlre

### CODE REVIEW

**Comment by coolo** [comment]
@bgeuken as you moved that private to class. If I make the function really private, we break the spec calling it:

https://circleci.com/gh/coolo/open-build-service/1090 - shall we just make it public or move it somewhere else?

**Comment by coolo** [comment]
@bgeuken - as discussed

**Comment by ChrisBr** [comment]
@coolo you know that you can directly push into the depfu pull requests with 
```
git push upstream depfu/update/srcapi/rubocop-0.58.1
```

This way we do not lose the information from depfu and the obs-bot.
I merged all other depfu PRs now except the rubocop! Either rebase or push your fix into the depfu PR :pray: :smile: Thanks!

**Comment by coolo** [comment]
I have no upstream repo :)

**Comment by coolo** [comment]
na dann

**Pull request closed without merging**
