### PR TITLE
Use brakeman in circleci instead of relying on dead hakiri

### PR DESCRIPTION
**Pull request by coolo**
Background: https://brakemanscanner.org/blog/2018/06/28/brakeman-has-been-acquired-by-synopsys/

### CODE REVIEW

**Comment by coolo** [comment]
(one more prerequire for rails 6)

**Comment by coolo** [comment]
brakeman complains here that we allow checks to have urls. And there is indeed a potential problem as we don't do any verification on these urls. Shall we?

**Comment by Conan-Kudo** [comment]
I don't think you guys can pull Brakeman in as a dependency. It's been licensed CC-BY-NC-SA since June 2018. At least, this will make things ugly for packaging OBS in Fedora, where this license is banned.

**Comment by coolo** [comment]
There interest to use a real and uptodate security scanner is small anyway - as you can see in the lack of any comments in the last 2 months.

**Comment by krauselukas** [comment]
@coolo sorry that this didn't got more attention, there is definitely interest in getting something that is more up-to-date and works with Rails 6. One solution regarding the licence problem, could be to not ship the gem and only integrate it to our circle ci setup (we only need it available in this repo right?). Otherwise we could also think about using another application, maybe from the GitHub Marketplace, which also gets the job done, or even uses brakeman in the background. I will also do some research, since I continued with the rails 6 upgrade last week.

**Comment by krauselukas** [comment]
I added a little chapter to our wiki to show how to handle false positives with brakeman for now :)
https://github.com/openSUSE/open-build-service/wiki/Development-Environment-Tips-&-Tricks#brakeman

**Pull request merged**
