### PR TITLE
rubocop fix for Layout/AlignHash

### PR DESCRIPTION
**Pull request by vpereira**
I had to run rubocop again, fixing the ```Layout/AlignHash```, otherwise the checkout pipeline would fail.. Am I missing something @coolo, @Ana06 ?

### CODE REVIEW

**Comment by coolo** [comment]
hmm, looks like AlignHash behaves different in 0.60 than in 0.59 - we merged the PRs independently

**Comment by vpereira** [comment]
github integration not working again. The tests are green https://circleci.com/workflow-run/9139189b-95e2-4d1d-a1aa-3827202bf5f6

**Comment by coolo** [comment]
But I don't consider this an improvement and I don't think I would have proposed the cop based on this output. But there are tons of options to it - I'll play around them to get the 0.59 behaviour. Stay tuned

**Comment by vpereira** [comment]
> But I don't consider this an improvement and I don't think I would have proposed the cop based on this output. But there are tons of options to it - I'll play around them to get the 0.59 behaviour. Stay tuned

I'm not sure. I'm ok with the output generated by the 0.6 and I would prefer if we either disable it or keep it as it is. No coolo magics to "fix it" :)

**Comment by coolo** [comment]
Here the 3 options in comparision: https://gist.github.com/coolo/1a08fe487e57d357f962ebef07052552

I don't know what bug caused 0.59 not to apply either, but I'm proposing table. I'll create a full PR to compare the full output

**Comment by coolo** [comment]
I'm not ok with the output - and the vote wasn't on this output either. So disabling it to keep master rolling is the best option for now IMO (we can leave the one time auto correct in, it doesn't harm)

**Comment by vpereira** [comment]
the circleci passed https://github.com/openSUSE/open-build-service/pull/6184/commits/ab31d0cba4ec7febb8360b6b0da496ac063824a7

however looks like its not notifying github back :/

**Comment by coolo** [comment]
it doesn't if you follow your own project. it's a super annoying glitch

**Pull request merged**
