### PR TITLE
Add token id to tokens index and remove quotes from last trigger on paragraph

### PR DESCRIPTION
**Pull request by krauselukas**
Screenshot_2021-11-10 Open Build Service

### CODE REVIEW

**Comment by krauselukas** [comment]
[Include the ID of the token in the token index/show card](https://trello.com/c/Ukaco428/1791-include-the-id-of-the-token-in-the-token-index-show-card)

**Review by rubhanazeem — APPROVED** [review]

**Comment by dmarcoux** [comment]
@krauselukas There's a flickering spec, you'll have to restart the `rspec` check since this is your fork.

**Comment by krauselukas** [comment]
Hmm, backend_test stuck again, going to merge since there are no backend changes involved

**Comment by dmarcoux** [comment]
> Shouldn't we show also se the id of the token after creating it?

I agree.

**Pull request merged**
