### PR TITLE
[webui] fix crash when trying to access navigation list

### PR DESCRIPTION
**Pull request by adrianschroeter**
causing crashes in staging dashboard

### CODE REVIEW

**Comment by adrianschroeter** [comment]
incomplete, user_tasks_path needs also fixed, just workarounded for my lunch for now:)

**Comment by hennevogel** [comment]
You can change this but I would rather find out why is this crashing...

**Comment by hennevogel** [comment]
The routes are there.

```shell
run_in_api bundle.ruby2.5 exec bin/rake routes|grep -w "user_tasks\|home"
home GET                 /home(.:format)                                                               webui/user#home
user_tasks GET                 /user/tasks(.:format)                                                         webui/users/tasks#index
```

**Comment by ChrisBr** [comment]
@adrianschroeter the error is from the dashboard
https://github.com/openSUSE/obs_factory/pull/133/files

**Comment by adrianschroeter** [comment]
@ChrisBr  cool thanks

**Pull request closed without merging**
