### PR TITLE
Update the list of crawlers

### PR DESCRIPTION
**Pull request by hennevogel**
This was never done after the initial commit. Should be done periodically somehow...

### CODE REVIEW

**Review by danidoni — APPROVED** [review]

**Comment by danidoni** [comment]
I guess the test failures are something unrelated to the changes, can you re-run them?

**Comment by dmarcoux** [comment]
Where is the list coming from? I'm just curious... :slightly_smiling_face:

**Comment by hennevogel** [comment]
`rake voight_kampff:import_user_agents`

**Comment by vpereira** [comment]
could you re-run the feature specs @hennevogel ? Unfortunately I couldn't do it myself.

**Comment by hennevogel** [comment]
Seems like this has an effect on the feature spec.

**Comment by hennevogel** [comment]
@danidoni @dmarcoux I think you want to re-review this

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
