### PR TITLE
Fix project comment spec for Bootstrap

### PR DESCRIPTION
**Pull request by Ana06**
This test needs to be fixed before the Bootstrap migration of the project page is enabled to all beta users. :bowtie:

### CODE REVIEW

**Comment by dmarcoux** [comment]
I am already working on this here: https://github.com/openSUSE/open-build-service/pull/6502

**Comment by Ana06** [comment]
@dmarcoux you could have closed the other PR or write a comment there.... :unamused:

**Comment by dmarcoux** [comment]
I'm sorry, I didn't know they even existed. I don't know why, but we had like 4 PRs doing the same thing.

**Comment by hennevogel** [comment]
# Headless Chicken Mode

Headless Chicken Mode

**Pull request closed without merging**
