### PR TITLE
[webui] Added a tab with the last requests at user's home

### LINKED ISSUE #928: In the OBS web GUI, where do I click to show my involved SR's when none are currently open?
If you don't have any current SR's, then there is no way to navigate to the list. Add a link to the web GUI for showing involved SR's even when there are none open.

### PR DESCRIPTION
**Pull request by mdeniz**
Added a list with the last requests at user's home (upto 100, paginated if needed).
Fixes #928.

### CODE REVIEW

**Comment by hennevogel** [comment]
Screenshot?

**Comment by mdeniz** [comment]
last_requests_snapshot

**Comment by hennevogel** [comment]
How do I get all?

**Comment by mdeniz** [comment]
Done.
Now you can search in all fields except creation date. And you can sort by creation, requester and type. All server-side processing.

**Comment by hennevogel** [comment]
Awesome. Let's go :balloon:

**Comment by hennevogel** [comment]
Or not, what about squashing the commits?

**Comment by mdeniz** [comment]
Done ;)

**Comment by hennevogel** [comment]
:rocket:

**Pull request merged**
