### PR TITLE
Enables UnusedBlockArgument rubocop rule

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by adrianschroeter** [comment]
f5e50e0
 is changing api backend interface code ... please use [api] tag in such cases.

**Comment by Ana06** [comment]
And why 2 commits? For me fixing the Rubocop cop offenses is part of enabling the cop. :confused:

**Comment by ChrisBr** [comment]
For me these are two different tasks, but actually I don't mind to squash ... @hennevogel / @bgeuken what do you think?

**Comment by hennevogel** [comment]
One is about enabling the cop. The other one about changes in the code. Both should use the propoer tag right? :-)

**Comment by ChrisBr** [comment]
Yep!
So [ci] is not the proper tag (because we used [ci] in the past for rubocop commits ...)?

**Comment by hennevogel** [comment]
[ci] for the first [api] for the second @ChrisBr

**Comment by bgeuken** [comment]
@ChrisBr \*ping\* Can you change the commit tag please?

**Comment by ChrisBr** [comment]
@adrianschroeter @hennevogel @bgeuken done!

**Comment by bgeuken** [comment]
Thanks!

**Pull request merged**
