### PR TITLE
Workaround after_destroy_commit loosing Thread variables

### LINKED ISSUE #12797: [production][] Requiring user, but found nobody
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/62cd2a5384bf460539e6615a)
# Requiring user, but found nobody #
### Occured ###
Jul 12  8:01am

### Similar ###
17

## Params ##
~~~
{}
~~~

## Session ##
~~~
{}
~~~

## Backtrace ##
~~~
240:  app/models/user.rb -> **session!**
1455:  app/models/project.rb -> **delete_on_backend**
427:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in make_lambda**
260:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in conditional**
516:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in invoke_after**
516:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **each**
516:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **invoke_after**
107:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
25:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
824:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **_run_commit_callbacks**
321:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb -> **committed!**
155:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **commit_records**
304:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in commit_transaction**
26:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
294:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **commit_transaction**
351:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in within_new_transaction**
26:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
317:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **within_new_transaction**
320:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
209:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb -> **transaction**
290:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb -> **transaction**
86:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/locking/pessimistic.rb -> **with_lock**
883:  app/models/bs_request.rb -> **auto_accept**
4:  app/jobs/bs_request_auto_accept_job.rb -> **perform**
48:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/execution.rb -> **block in perform_now**
117:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
328:  /GEM_ROOT/gems/i18n-1.10.0/lib/i18n.rb -> **with_locale**
9:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/translation.rb -> **block (2 levels) in &lt;module:Translation&gt;**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **instance_exec**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
66:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/core_ext/time/zones.rb -> **use_zone**
9:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/timezones.rb -> **block (2 levels) in &lt;module:Timezones&gt;**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **instance_exec**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
21:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/instrumentation.rb -> **block in instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **instrument**
31:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/instrumentation.rb -> **instrument**
14:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/instrumentation.rb -> **block (2 levels) in &lt;module:Instrumentation&gt;**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **instance_exec**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
22:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/logging.rb -> **block in tag_logger**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
22:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/logging.rb -> **tag_logger**
15:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/logging.rb -> **block (2 levels) in &lt;module:Logging&gt;**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **instance_exec**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
137:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
47:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/execution.rb -> **perform_now**
25:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/execution.rb -> **block in execute**
117:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
47:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/railtie.rb -> **block (4 levels) in &lt;class:Railtie&gt;**
91:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/execution_wrapper.rb -> **wrap**
72:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/reloader.rb -> **block in wrap**
91:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/execution_wrapper.rb -> **wrap**
71:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/reloader.rb -> **wrap**
46:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/railtie.rb -> **block (3 levels) in &lt;class:Railtie&gt;**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **instance_exec**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
137:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
23:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/execution.rb -> **execute**
42:  /GEM_ROOT/gems/activejob-6.1.5.1/lib/active_job/queue_adapters/delayed_job_adapter.rb -> **perform**
81:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/backend/base.rb -> **block in invoke_job**
10:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/delayed_job.rb -> **block (2 levels) in &lt;class:Airbrake&gt;**
79:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block (2 levels) in add**
61:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block in initialize**
79:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block in add**
66:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **run_callbacks**
78:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/backend/base.rb -> **invoke_job**
230:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block (2 levels) in run**
179:  /GEM_ROOT/gems/timeout-0.3.0/lib/timeout.rb -> **block in timeout**
186:  /GEM_ROOT/gems/timeout-0.3.0/lib/timeout.rb -> **timeout**
230:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block in run**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
229:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **run**
312:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block in reserve_and_run_one_job**
61:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block in initialize**
66:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **run_callbacks**
312:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **reserve_and_run_one_job**
213:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block in work_off**
212:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **times**
212:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **work_off**
175:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block (4 levels) in start**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
174:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block (3 levels) in start**
61:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block in initialize**
66:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **run_callbacks**
173:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block (2 levels) in start**
172:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **loop**
172:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **block in start**
7:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/plugins/clear_locks.rb -> **block (2 levels) in &lt;class:ClearLocks&gt;**
79:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block (2 levels) in add**
61:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block in initialize**
79:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **block in add**
66:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **execute**
40:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/lifecycle.rb -> **run_callbacks**
171:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/worker.rb -> **start**
137:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/command.rb -> **run**
125:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/command.rb -> **block in run_process**
277:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **block in start_proc**
84:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/daemonize.rb -> **call_as_daemon**
281:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **start_proc**
307:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/application.rb -> **start**
56:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/controller.rb -> **run**
199:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons.rb -> **block in run_proc**
124:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons/cmdline.rb -> **catch_exceptions**
198:  /GEM_ROOT/gems/daemons-1.4.1/lib/daemons.rb -> **run_proc**
123:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/command.rb -> **run_process**
98:  /GEM_ROOT/gems/delayed_job-4.1.10/lib/delayed/command.rb -> **daemonize**
5:  script/delayed_job.api.rb -> **&lt;top (required)&gt;**
58:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **load**
58:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **kernel_load**
23:  /usr/lib64/ruby/3.1.0/bundler/cli/exec.rb -> **run**
484:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **exec**
27:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb -> **run**
127:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb -> **invoke_command**
392:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb -> **dispatch**
31:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **dispatch**
485:  /usr/lib64/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb -> **start**
25:  /usr/lib64/ruby/3.1.0/bundler/cli.rb -> **start**
48:  /usr/lib64/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle -> **block in &lt;top (required)&gt;**
103:  /usr/lib64/ruby/3.1.0/bundler/friendly_errors.rb -> **with_friendly_errors**
36:  /usr/lib64/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle -> **&lt;top (required)&gt;**
25:  /usr/bin/bundle.ruby3.1 -> **load**
25:  /usr/bin/bundle.ruby3.1 -> **&lt;main&gt;**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | delayed_job.1030 |
| HTTP_USER_AGENT |  |

### PR DESCRIPTION
**Pull request by hennevogel**
Fixes #12797

### CODE REVIEW

**Comment by dmarcoux** [comment]
Small typo: lo<strike>o</strike>sing

**Comment by hennevogel** [comment]
> How can we test this?

What do you want to test?

**Comment by dmarcoux** [comment]
> > How can we test this?
> 
> What do you want to test?

With the latest changes, it's all clear. There's nothing fancy happening :slightly_smiling_face:

**Comment by jduff** [comment]
Feel free to ignore me since I'm not a part of this project, but you should be able to add a test for the case that was failing ie. Accessing the user from an after commit callback and ensure that works after the patch. This would help to prevent a regression in the future if someone deletes the `user_id` line.

This is probably a case where I would also add a comment on each of those methods explaining why `user_id` is also being set/used because it isn't obvious why that is needed in addition to setting `user`.

Glad I was able to help out!

**Comment by hennevogel** [comment]
> Feel free to ignore me since I'm not a part of this project

Never! We are all one big project no? 😃 

> This would help to prevent a regression in the future if someone deletes the user_id line.

We don't guard for code removal with specs, we trust our code-review to check things. Things like...

> add a comment on each of those methods explaining

...commit messages to transfer why something was done.

**Review by danidoni — APPROVED** [review]

**Pull request merged**
