### PR TITLE
Project suspend reason

### PR DESCRIPTION
**Pull request by adrianschroeter**
Stuff you find in old unsubmitted commits while debugging breakages ....

Some code cleanup and more transparency for suspended projects.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
the checkout_code/codeclimate complains about exactly that what has been solved in second commit.

The rspec failure is most likely problems with vcr records, which I can not really fix. Would be nice if someone else could do.

**Comment by DavidKang** [comment]
@adrianschroeter, I fixed the complains of the checkout_code.

**Comment by adrianschroeter** [comment]
thanks!

**Comment by vpereira** [comment]
no approval was needed here? :-1:

**Comment by hennevogel** [comment]
We agreed to only merge if there is a positive github review -> https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-contribute-code

Please stick to what we agreed upon!

**Comment by adrianschroeter** [comment]
On Montag, 25. Mai 2020, 15:26:20 CEST wrote Henne Vogelsang:
> We agreed to only merge if there is a positive github review -> https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-contribute-code

It was reworked by david and was just hanging around. No one from frontend team 
does anyway review build flow topics.

if you are bored, there is #9453, solving a serious issue leading to 
missing updates and is just hanging around since a month due to not
agreed code style checks.

not breaking OBS content is more important than just blocking people
to have fun.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by hennevogel** [comment]
> It was reworked by david and was just hanging around

That doesn't mean he gave you a positive review, that just means he tried to help you to pass the automated checks.

> No one from frontend team does anyway review build flow topics

We review as much as we can.

> if you are bored

Au contraire. We are as busy, as anyone I suppose.

>  there is #9453, solving a serious issue leading to missing updates and is just hanging around since a month due to not agreed code style checks.

If you don't agree to code style checks you should maybe talk to the other developers that you want to change/ignore them.  @ people in the PR with `@openSUSE/obs-frontend` or send a mail, or IRC, or Rocket...

**Comment by vpereira** [comment]
Hey @adrianschroeter, please interact with us. Nobody blocks people for fun. Ping us, tell us what you are doing, here or privately. In the #9453 , we weren't sure if you are working to fix the codeclimate issue or not.

**Pull request merged**
