### PR TITLE
Document `/search/project` endpoint with OpenAPI

### PR DESCRIPTION
**Pull request by eduardoj**

### CODE REVIEW

**Comment by dmarcoux** [comment]
I tried with the match parameter `@name='home:Admin'`, so it should match the `home:Admin` project, but it returns an empty collection, even if it says `matches="1"`:
```
<collection matches="1">
</collection>
```

Is this expected?

**Comment by dmarcoux** [comment]
This PR should also include the deprecated POST endpoint for the same route, so similar to what has been done in #12963.

**Comment by dmarcoux** [comment]
> This PR should also include the deprecated POST endpoint for the same route, so similar to what has been done in #12963.

We can handle this in a follow-up PR.

**Comment by dmarcoux** [comment]
> I tried with the match parameter `@name='home:Admin'`, so it should match the `home:Admin` project, but it returns an empty collection, even if it says `matches="1"`:
> 
> ```
> <collection matches="1">
> </collection>
> ```
> 
> Is this expected?

After talking with @eduardoj, we are going to track this issue in our backlog. It is not related to the API documentation.

**Comment by eduardoj** [comment]
> This PR should also include the deprecated POST endpoint for the same route, so similar to what has been done in #12963.

Yes, done. Please have another look.

**Review by dmarcoux — APPROVED** [review]

**Comment by dmarcoux** [comment]
> I tried to reproduce this issue but I couldn't. Could you confirm this still happens to you?

It's fine after rebuilding my development environment.

**Pull request merged**
