### PR TITLE
Migrate live build log to Bootstrap

### PR DESCRIPTION
**Pull request by DavidKang**
We migrate package#live_build_log to bootstrap.

### Without dependencies

screenshot_2018-09-25 build log for package perl-citrix project home admin - open build service 4

### With Dependencies

screenshot_2018-09-25 build log for package perl-citrix project home admin - open build service 7

### Small Screen
untitled

The original screenshot is [here](http://paste.opensuse.org/15277277)

### CODE REVIEW

**Comment by hennevogel** [comment]
I think you should adopt the font size one mobile :-)

**Comment by ChrisBr** [comment]
Here is a build log:
https://obs-reviewlab.opensuse.org/davidkang-sprint48package-live-build-log/package/live_build_log/home:Admin/ctris/openSUSE_Tumbleweed/i586

**Comment by ChrisBr** [comment]
> is for the whole page or only for the content of the log?

I would say only for the log as it breaks the line "strangely" :thinking: 

selection_016

Top of page is fine from my POV.

**Comment by ChrisBr** [comment]
[nitpick] The inner container with the log content is almost not visible:

selection_017

**Comment by hennevogel** [comment]
> @hennevogel, is for the whole page or only for the content of the log?

For the content of the log would be enough for me :)

**Comment by hennevogel** [comment]
>  if we put it smaller the log will be harder to read.

How did you 'test' this? I suggest you look at this on your mobile and decide. It's not only screen estate, it's also how close you hold the device to your body for instance.

**Comment by DavidKang** [comment]
I use firefox development tool for that, but tomorrow I will try it on my mobile.

**Comment by bgeuken** [comment]
I would propose that we review what we did beginning of next week and collect issues we found. Including how the bootstrap pages look for smaller screen devices

**Comment by hennevogel** [comment]
>  Including how the bootstrap pages look for smaller screen devices

Sure we can postpone this. It works as it is.

**Comment by hennevogel** [comment]
@DavidKang merging or you do still want to do something?

**Comment by DavidKang** [comment]
@hennevogel, we can merge it

**Comment by DavidKang** [comment]
Rebased with bootstrap-master to resolve the conflicts.

**Pull request merged**
